export const AUTH_ANONYMOUS_USER_ID = 'anonymous';
export const AUTH_GUEST_ROLE = 'guest';
export const AUTH_SYSTEM_ROLE = 'system';
export const AUTH_GLOBAL_TENANT_ID = 'global';
export const ACCESS_TOKEN_TYPE = 'access';
export const REFRESH_TOKEN_TYPE = 'refresh';
export const AUTH_SESSION_PREFIX = 'auth:session';
export const IS_PUBLIC_KEY = 'isPublic';
export const ROLES_KEY = 'roles';
export const PERMISSIONS_KEY = 'permissions';
export const POLICY_KEY = 'policy';
export const DEFAULT_ROLE_OWNER = 'owner';
export const DEFAULT_ROLE_ADMIN = 'admin';
export const DEFAULT_ROLE_MEMBER = 'member';
export const DEFAULT_ROLE_STOREKEEPER = 'storekeeper';
export const DEFAULT_ROLE_TEACHER = 'teacher';
export const DEFAULT_ROLE_DEAN_ACADEMICS = 'dean_academics';
export const DEFAULT_ROLE_EXAMS_MANAGER = 'exams_manager';
export const DEFAULT_ROLE_HOD = 'hod';
export const DEFAULT_ROLE_CLASS_TEACHER = 'class_teacher';
export const DEFAULT_ROLE_GRADE_MASTER = 'grade_master';
export const DEFAULT_ROLE_ACCOUNTANT = 'accountant';
export const DEFAULT_ROLE_STAFF = 'staff';
export const DEFAULT_ROLE_PRINCIPAL = 'principal';
export const DEFAULT_ROLE_DEPUTY_PRINCIPAL = 'deputy_principal';
export const DEFAULT_ROLE_SECRETARY = 'secretary';
export const DEFAULT_ROLE_BURSAR = 'bursar';
export const DEFAULT_ROLE_PARENT = 'parent';
export const DEFAULT_ROLE_STUDENT = 'student';
export const DEFAULT_ROLE_LIBRARIAN = 'librarian';
export const DEFAULT_ROLE_NURSE = 'nurse';
export const DEFAULT_ROLE_CLINIC_STAFF = 'clinic_staff';
export const DEFAULT_ROLE_COUNSELLOR = 'school_counsellor';
export const DEFAULT_ROLE_DISCIPLINE_MASTER = 'discipline_master';
export const DEFAULT_ROLE_BOARDING_MASTER = 'boarding_master';
export const DEFAULT_ROLE_SECURITY_OFFICER = 'security_officer';
export const DEFAULT_ROLE_TRANSPORT_MANAGER = 'transport_manager';
export const DEFAULT_ROLE_LAB_TECHNICIAN = 'lab_technician';
export const DEFAULT_ROLE_ADMISSIONS_OFFICER = 'admissions_officer';
export const DEFAULT_ROLE_ICT_MANAGER = 'ict_manager';
export const DEFAULT_ROLE_SUPPORT_AGENT = 'support_agent';
export const DEFAULT_ROLE_SUPPORT_LEAD = 'support_lead';
export const SUPERADMIN_ROLE_OWNER = 'platform_owner';

export const DEFAULT_PERMISSION_CATALOG = [
  { resource: '*', action: '*', description: 'Full tenant access' },
  { resource: 'auth', action: 'read', description: 'Read authenticated identity context' },
  { resource: 'users', action: 'read', description: 'View tenant users' },
  { resource: 'users', action: 'write', description: 'Manage tenant users' },
  { resource: 'roles', action: 'read', description: 'View tenant roles' },
  { resource: 'roles', action: 'write', description: 'Manage tenant roles' },
  { resource: 'permissions', action: 'read', description: 'View tenant permissions' },
  { resource: 'permissions', action: 'write', description: 'Manage tenant permissions' },
  { resource: 'platform', action: 'auto-repair', description: 'Run platform dashboard auto-repair diagnostics and repair snapshots' },
  { resource: 'tenant_memberships', action: 'read', description: 'View tenant memberships' },
  { resource: 'tenant_memberships', action: 'write', description: 'Manage tenant memberships' },
  { resource: 'finance', action: 'read', description: 'View financial operations' },
  { resource: 'finance', action: 'write', description: 'Manage financial operations' },
  { resource: 'reports', action: 'read', description: 'View generated report export jobs and snapshots' },
  { resource: 'library', action: 'read', description: 'View library operations' },
  { resource: 'library', action: 'write', description: 'Manage library operations' },
  { resource: 'students', action: 'read', description: 'View student records' },
  { resource: 'students', action: 'write', description: 'Manage student records' },
  { resource: 'inventory', action: 'read', description: 'View inventory records' },
  { resource: 'inventory', action: 'write', description: 'Manage inventory records' },
  { resource: 'assets', action: 'read', description: 'View asset and apparatus tracking records' },
  { resource: 'academics', action: 'read', description: 'View academic years, terms, classes, subjects, and assignments' },
  { resource: 'academics', action: 'write', description: 'Manage academic setup records' },
  { resource: 'academics', action: 'assign-teachers', description: 'Manage teacher subject and class assignments' },
  { resource: 'exams', action: 'read', description: 'View exam series, marks, and report cards' },
  { resource: 'exams', action: 'write', description: 'Manage exam setup and assessments' },
  { resource: 'exams', action: 'enter-marks', description: 'Enter marks for assigned subject and class scopes' },
  { resource: 'exams', action: 'review', description: 'Review exam progress across subjects' },
  { resource: 'exams', action: 'approve', description: 'Lock, correct, and publish exam results' },
  { resource: 'hr', action: 'read', description: 'View staff management records' },
  { resource: 'hr', action: 'write', description: 'Manage staff profiles, contracts, leave, and documents' },
  { resource: 'timetable', action: 'read', description: 'View timetable planning and published schedules' },
  { resource: 'timetable', action: 'write', description: 'Manage timetable drafts and published versions' },
  { resource: 'procurement', action: 'read', description: 'View procurement workflows' },
  { resource: 'procurement', action: 'write', description: 'Manage procurement workflows' },
  { resource: 'payments', action: 'create', description: 'Initiate tenant payment requests' },
  { resource: 'school_sms', action: 'read', description: 'View tenant SMS balance, quota, and logs' },
  { resource: 'school_sms', action: 'send', description: 'Send SMS through the tenant SMS wallet' },
  { resource: 'school_sms', action: 'purchase', description: 'Request additional tenant SMS credits' },
  { resource: 'daraja', action: 'read', description: 'View masked school M-PESA Daraja settings' },
  { resource: 'daraja', action: 'write', description: 'Manage school-owned M-PESA Daraja credentials' },
  { resource: 'daraja', action: 'test', description: 'Test school-owned M-PESA Daraja credentials' },
  { resource: 'portal', action: 'read_own_children', description: 'View linked parent/student portal data' },
  { resource: 'portal', action: 'message_school', description: 'Send portal messages to the school' },
  { resource: 'student-portal', action: 'read', description: 'View the authenticated learner portal workspace' },
  { resource: 'student-portal', action: 'write', description: 'Submit authenticated learner portal actions' },
  { resource: 'admissions', action: 'read', description: 'View admissions workflows' },
  { resource: 'admissions', action: 'write', description: 'Manage admissions workflows' },
  { resource: 'documents', action: 'read', description: 'View document records' },
  { resource: 'documents', action: 'write', description: 'Manage document records' },
  { resource: 'transfers', action: 'read', description: 'View transfer workflows' },
  { resource: 'transfers', action: 'write', description: 'Manage transfer workflows' },
  { resource: 'billing', action: 'read', description: 'View SaaS billing state' },
  { resource: 'billing', action: 'write', description: 'Manage SaaS billing state' },
  { resource: 'compliance', action: 'read', description: 'View data protection, DSR, breach, and retention evidence' },
  { resource: 'compliance', action: 'write', description: 'Manage data subject request and breach response workflows' },
  { resource: 'support', action: 'view', description: 'View tenant support tickets and support resources' },
  { resource: 'support', action: 'create', description: 'Create tenant support tickets' },
  { resource: 'support', action: 'reply', description: 'Reply to support ticket conversations and upload support attachments' },
  { resource: 'support', action: 'manage', description: 'Manage, assign, escalate, resolve, and analyze support tickets' },
  { resource: 'discipline', action: 'read', description: 'View permitted discipline incidents, actions, and behavior summaries' },
  { resource: 'discipline', action: 'write', description: 'Report discipline incidents, add evidence, and record permitted discipline updates' },
  { resource: 'discipline', action: 'manage', description: 'Manage discipline cases, workflows, settings, escalations, and parent notices' },
  { resource: 'discipline', action: 'approve', description: 'Approve high-severity disciplinary actions such as suspension or expulsion' },
  { resource: 'discipline', action: 'reports', description: 'Export discipline reports and analytics' },
  { resource: 'counselling', action: 'read', description: 'View permitted counselling referrals, sessions, and improvement plans' },
  { resource: 'counselling', action: 'write', description: 'Create counselling referrals, sessions, notes, and improvement plan updates' },
  { resource: 'counselling', action: 'manage', description: 'Manage confidential counselling workflows and follow-up plans' },
  { resource: 'labs', action: 'read', description: 'View laboratory departments, labs, sessions, inventory, and safety reports' },
  { resource: 'labs', action: 'write', description: 'Manage laboratory departments, labs, and sessions' },
  { resource: 'labs', action: 'attendance', description: 'Record mandatory laboratory attendance' },
  { resource: 'labs', action: 'inventory', description: 'Manage laboratory equipment and chemicals' },
  { resource: 'labs', action: 'approve-disposal', description: 'Approve chemical disposal requests' },
  { resource: 'principal', action: 'read', description: 'View strategic school command center and audit summaries' },
  { resource: 'principal', action: 'write', description: 'Approve policy actions and manual teacher attendance overrides' },
  { resource: 'deputy', action: 'read', description: 'View operations command center, attendance, discipline, and timetable execution' },
  { resource: 'deputy', action: 'write', description: 'Manage operations incidents, discipline workflow, and duty rosters' },
  { resource: 'secretary', action: 'read', description: 'View admissions, records, communications, meetings, and reports workspace' },
  { resource: 'secretary', action: 'write', description: 'Manage records, announcements, meeting minutes, and report exports' },
  { resource: 'teacher_attendance', action: 'read', description: 'View biometric teacher attendance logs' },
  { resource: 'teacher_attendance', action: 'devices', description: 'Register and manage biometric devices and identities' },
  { resource: 'teacher_attendance', action: 'override', description: 'Create audited manual teacher attendance overrides' },
  { resource: 'teacher_attendance', action: 'reports', description: 'View biometric teacher attendance reports' },
  { resource: 'clinic', action: 'read', description: 'View clinic visits, inventory summaries, and allowed health records' },
  { resource: 'clinic', action: 'write', description: 'Record clinic visits, treatment notes, and non-confidential health workflows' },
  { resource: 'clinic', action: 'inventory', description: 'Manage clinic medicine inventory, batches, stock entries, and disposal records' },
  { resource: 'clinic', action: 'dispense', description: 'Dispense medicine and update clinic stock automatically' },
  { resource: 'clinic', action: 'reports', description: 'View summary clinic analytics without confidential diagnosis notes' },
  { resource: 'clinic', action: 'confidential', description: 'View confidential clinical notes where explicitly authorized' },
  { resource: 'transport', action: 'read', description: 'View transport routes, manifests, and operational summaries' },
  { resource: 'transport', action: 'write', description: 'Manage transport operations' },
  { resource: 'hostel', action: 'read', description: 'View hostel occupancy, incidents, and boarding summaries' },
  { resource: 'hostel', action: 'write', description: 'Manage hostel operations' },
  { resource: 'boarding', action: 'read', description: 'View boarding operations, meals, and welfare summaries' },
  { resource: 'boarding', action: 'write', description: 'Manage boarding operations' },
  { resource: 'lms', action: 'read', description: 'View eLearning and LMS resources' },
  { resource: 'lms', action: 'write', description: 'Manage eLearning and LMS resources' },
  { resource: 'visitors', action: 'read', description: 'View visitor logs and gate summaries' },
  { resource: 'visitors', action: 'write', description: 'Manage visitor records and gate check-ins' },
] as const;

export const DEFAULT_ROLE_CATALOG = [
  {
    code: DEFAULT_ROLE_OWNER,
    name: 'Owner',
    description: 'Full access to tenant resources',
    permissions: ['*:*'],
  },
  {
    code: DEFAULT_ROLE_ADMIN,
    name: 'Administrator',
    description: 'Operational access for tenant administration',
    permissions: [
      'auth:read',
      'users:read',
      'users:write',
      'roles:read',
      'roles:write',
      'permissions:read',
      'permissions:write',
      'tenant_memberships:read',
      'tenant_memberships:write',
      'students:read',
      'students:write',
      'reports:read',
      'inventory:read',
      'inventory:write',
      'academics:read',
      'academics:write',
      'academics:assign-teachers',
      'exams:read',
      'exams:write',
      'exams:enter-marks',
      'exams:review',
      'exams:approve',
      'library:read',
      'library:write',
      'hr:read',
      'hr:write',
      'timetable:read',
      'timetable:write',
      'procurement:read',
      'procurement:write',
      'payments:create',
      'school_sms:read',
      'school_sms:send',
      'school_sms:purchase',
      'daraja:read',
      'daraja:write',
      'daraja:test',
      'admissions:read',
      'admissions:write',
      'documents:read',
      'documents:write',
      'transfers:read',
      'transfers:write',
      'billing:read',
      'billing:write',
      'compliance:read',
      'compliance:write',
      'support:view',
      'support:create',
      'support:reply',
      'discipline:read',
      'discipline:write',
      'discipline:manage',
      'discipline:approve',
      'discipline:reports',
      'counselling:read',
      'counselling:write',
      'counselling:manage',
      'labs:read',
      'labs:write',
      'labs:attendance',
      'labs:inventory',
      'labs:approve-disposal',
      'clinic:read',
      'clinic:write',
      'clinic:inventory',
      'clinic:dispense',
      'clinic:reports',
      'clinic:confidential',
      'transport:read',
      'transport:write',
      'hostel:read',
      'hostel:write',
      'boarding:read',
      'boarding:write',
      'lms:read',
      'lms:write',
      'visitors:read',
      'visitors:write',
    ],
  },
  {
    code: DEFAULT_ROLE_MEMBER,
    name: 'Member',
    description: 'Standard tenant access',
    permissions: [
      'auth:read',
      'users:read',
      'students:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_TEACHER,
    name: 'Teacher',
    description: 'Academic classroom access for teachers',
    permissions: [
      'auth:read',
      'students:read',
      'academics:read',
      'exams:read',
      'exams:enter-marks',
      'school_sms:send',
      'discipline:read',
      'discipline:write',
      'labs:read',
      'labs:attendance',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_DEAN_ACADEMICS,
    name: 'Dean of Academics',
    description: 'Academic quality assurance, exam moderation, report card review, grading integrity checks, and curriculum compliance approval',
    permissions: [
      'auth:read',
      'students:read',
      'academics:read',
      'exams:read',
      'exams:review',
      'exams:approve',
      'reports:read',
      'school_sms:send',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_EXAMS_MANAGER,
    name: 'Exams Manager',
    description: 'Academic data production, exam setup, timetable scheduling, marks entry coordination, grade processing, and draft report card generation',
    permissions: [
      'auth:read',
      'students:read',
      'academics:read',
      'exams:read',
      'exams:write',
      'exams:enter-marks',
      'exams:review',
      'reports:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_HOD,
    name: 'Head of Department',
    description: 'Department-level academic oversight for teachers, subjects, syllabus coverage, exams, lesson plans, and curriculum compliance',
    permissions: [
      'auth:read',
      'students:read',
      'academics:read',
      'academics:assign-teachers',
      'exams:read',
      'exams:review',
      'discipline:read',
      'timetable:read',
      'reports:read',
      'school_sms:send',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_CLASS_TEACHER,
    name: 'Class Teacher',
    description: 'Class-level attendance, welfare, parent communication, and academic oversight',
    permissions: [
      'auth:read',
      'students:read',
      'academics:read',
      'exams:read',
      'exams:enter-marks',
      'school_sms:send',
      'discipline:read',
      'discipline:write',
      'clinic:read',
      'reports:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_GRADE_MASTER,
    name: 'Grade/Form Master',
    description: 'Multi-stream grade oversight for attendance, discipline, academics, class teachers, welfare, and parent escalations',
    permissions: [
      'auth:read',
      'students:read',
      'academics:read',
      'academics:assign-teachers',
      'exams:read',
      'exams:review',
      'discipline:read',
      'discipline:write',
      'discipline:reports',
      'clinic:reports',
      'school_sms:send',
      'reports:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_ACCOUNTANT,
    name: 'Accountant',
    description: 'Finance and billing operations access',
    permissions: [
      'auth:read',
      'finance:read',
      'finance:write',
      'billing:read',
      'billing:write',
      'payments:create',
      'school_sms:read',
      'school_sms:send',
      'school_sms:purchase',
      'daraja:read',
      'daraja:write',
      'daraja:test',
      'discipline:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_STAFF,
    name: 'Staff',
    description: 'General school staff access',
    permissions: [
      'auth:read',
      'students:read',
      'discipline:read',
      'discipline:write',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_PRINCIPAL,
    name: 'Principal',
    description: 'Strategic school leadership access with governance and read-only finance oversight',
    permissions: [
      'auth:read',
      'users:read',
      'users:write',
      'tenant_memberships:read',
      'tenant_memberships:write',
      'roles:read',
      'principal:read',
      'principal:write',
      'deputy:read',
      'secretary:read',
      'students:read',
      'finance:read',
      'billing:read',
      'compliance:read',
      'compliance:write',
      'academics:read',
      'academics:write',
      'academics:assign-teachers',
      'exams:read',
      'discipline:read',
      'discipline:approve',
      'discipline:reports',
      'hr:read',
      'timetable:read',
      'reports:read',
      'labs:read',
      'labs:approve-disposal',
      'clinic:reports',
      'inventory:read',
      'procurement:read',
      'school_sms:read',
      'school_sms:send',
      'transport:read',
      'hostel:read',
      'boarding:read',
      'library:read',
      'lms:read',
      'teacher_attendance:read',
      'teacher_attendance:override',
      'teacher_attendance:reports',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_DEPUTY_PRINCIPAL,
    name: 'Deputy Principal',
    description: 'Daily operations, discipline, duty roster, and timetable execution access',
    permissions: [
      'auth:read',
      'deputy:read',
      'deputy:write',
      'students:read',
      'academics:read',
      'academics:write',
      'academics:assign-teachers',
      'discipline:read',
      'discipline:write',
      'discipline:manage',
      'timetable:read',
      'timetable:write',
      'labs:read',
      'labs:attendance',
      'clinic:reports',
      'transport:read',
      'transport:write',
      'hostel:read',
      'hostel:write',
      'boarding:read',
      'boarding:write',
      'teacher_attendance:read',
      'teacher_attendance:reports',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_SECRETARY,
    name: 'Secretary',
    description: 'Administration, admissions, communications, records, meetings, and report exports',
    permissions: [
      'auth:read',
      'secretary:read',
      'secretary:write',
      'admissions:read',
      'admissions:write',
      'students:read',
      'documents:read',
      'documents:write',
      'reports:read',
      'school_sms:read',
      'school_sms:send',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_BURSAR,
    name: 'Bursar',
    description: 'School finance, fee reconciliation, payments, billing, and SMS balance oversight',
    permissions: [
      'auth:read',
      'students:read',
      'finance:read',
      'finance:write',
      'billing:read',
      'billing:write',
      'payments:create',
      'school_sms:read',
      'school_sms:send',
      'school_sms:purchase',
      'daraja:read',
      'daraja:write',
      'daraja:test',
      'reports:read',
      'procurement:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_PARENT,
    name: 'Parent',
    description: 'Parent portal access for invited guardians',
    permissions: [
      'auth:read',
      'payments:create',
      'portal:read_own_children',
      'portal:message_school',
      'discipline:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_STUDENT,
    name: 'Student',
    description: 'Student portal access for invited learners',
    permissions: [
      'auth:read',
      'student-portal:read',
      'student-portal:write',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_LIBRARIAN,
    name: 'Librarian',
    description: 'Library operations access',
    permissions: [
      'auth:read',
      'library:read',
      'library:write',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_NURSE,
    name: 'Nurse',
    description: 'School clinic, student health notes, medicine dispensing, and health follow-up access',
    permissions: [
      'auth:read',
      'students:read',
      'clinic:read',
      'clinic:write',
      'clinic:inventory',
      'clinic:dispense',
      'clinic:reports',
      'clinic:confidential',
      'procurement:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_CLINIC_STAFF,
    name: 'Clinic Staff',
    description: 'School clinic medicine inventory, visits, dispensing, and confidential health operations',
    permissions: [
      'auth:read',
      'students:read',
      'clinic:read',
      'clinic:write',
      'clinic:inventory',
      'clinic:dispense',
      'clinic:reports',
      'clinic:confidential',
      'procurement:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_DISCIPLINE_MASTER,
    name: 'Discipline Master',
    description: 'Dean of students access for discipline case management and parent workflows',
    permissions: [
      'auth:read',
      'students:read',
      'discipline:read',
      'discipline:write',
      'discipline:manage',
      'discipline:reports',
      'counselling:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_COUNSELLOR,
    name: 'School Counsellor',
    description: 'Confidential counselling, referrals, sessions, and behavior improvement planning',
    permissions: [
      'auth:read',
      'students:read',
      'discipline:read',
      'counselling:read',
      'counselling:write',
      'counselling:manage',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_STOREKEEPER,
    name: 'Storekeeper',
    description: 'Inventory-only stock receiving, issuing, transfers, and reports',
    permissions: [
      'auth:read',
      'inventory:read',
      'inventory:write',
      'procurement:read',
      'procurement:write',
      'transfers:read',
      'transfers:write',
      'labs:read',
      'labs:inventory',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_BOARDING_MASTER,
    name: 'Boarding Master',
    description: 'Boarding, hostel, welfare, evening movement, and dorm incident operations access',
    permissions: [
      'auth:read',
      'students:read',
      'discipline:read',
      'discipline:write',
      'hostel:read',
      'hostel:write',
      'boarding:read',
      'boarding:write',
      'school_sms:send',
      'reports:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_SECURITY_OFFICER,
    name: 'Security Officer',
    description: 'Visitor logs, gate records, movement visibility, and incident reporting access',
    permissions: [
      'auth:read',
      'students:read',
      'visitors:read',
      'visitors:write',
      'transport:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_TRANSPORT_MANAGER,
    name: 'Transport Manager',
    description: 'Fleet, routes, drivers, student allocation, GPS, fuel, and transport compliance access',
    permissions: [
      'auth:read',
      'students:read',
      'transport:read',
      'transport:write',
      'school_sms:send',
      'reports:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_LAB_TECHNICIAN,
    name: 'Laboratory Technician',
    description: 'Laboratory safety, chemical control, equipment tracking, practical preparation, and audit logs access',
    permissions: [
      'auth:read',
      'labs:read',
      'labs:write',
      'labs:inventory',
      'inventory:read',
      'procurement:read',
      'assets:read',
      'reports:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_ADMISSIONS_OFFICER,
    name: 'Admissions Officer',
    description: 'Admissions inquiries, applications, document checks, onboarding, and parent handoff access',
    permissions: [
      'auth:read',
      'admissions:read',
      'admissions:write',
      'students:read',
      'students:write',
      'documents:read',
      'documents:write',
      'school_sms:send',
      'reports:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_ICT_MANAGER,
    name: 'ICT / Computer Lab Manager',
    description: 'ICT assets, lab devices, repairs, software licenses, and device support access',
    permissions: [
      'auth:read',
      'assets:read',
      'inventory:read',
      'procurement:read',
      'labs:read',
      'reports:read',
      'support:view',
      'support:create',
      'support:reply',
    ],
  },
  {
    code: DEFAULT_ROLE_SUPPORT_AGENT,
    name: 'Support Agent',
    description: 'Platform support operator who manages school tickets and customer conversations',
    permissions: [
      'auth:read',
      'support:view',
      'support:create',
      'support:reply',
      'support:manage',
      'billing:read',
      'reports:read',
    ],
  },
  {
    code: DEFAULT_ROLE_SUPPORT_LEAD,
    name: 'Support Lead',
    description: 'Platform support lead with queue, SLA, assignment, and analytics control',
    permissions: [
      'auth:read',
      'support:view',
      'support:create',
      'support:reply',
      'support:manage',
      'users:read',
      'billing:read',
      'reports:read',
    ],
  },
] as const;
