import type { PrincipalInsightProviderConfig } from './principal-insights.types';

export const PRINCIPAL_INSIGHT_PROVIDERS: readonly PrincipalInsightProviderConfig[] = [
  {
    module_code: 'students',
    id: 'school_overview',
    title: 'School Overview',
    category: 'overview',
    permission_required: 'students:read',
    widgets: [
      { id: 'students_total', title: 'Total Students', metric_key: 'total_students' },
      { id: 'classes_active', title: 'Active Classes', metric_key: 'active_classes_streams' },
      { id: 'parent_engagement', title: 'Parent Engagement', metric_key: 'parent_engagement_rate', unit: '%' },
    ],
    drilldowns: ['students.gender', 'students.population_trend', 'students.guardian_engagement'],
    reports: ['school-overview', 'population-trend'],
  },
  {
    module_code: 'academics',
    id: 'academics',
    title: 'Academics Insights',
    category: 'academics',
    permission_required: 'academics:read',
    widgets: [
      { id: 'levels', title: 'Academic Levels', metric_key: 'academic_levels' },
      { id: 'active_subjects', title: 'Active Subjects', metric_key: 'active_subjects' },
      { id: 'unassigned_students', title: 'Unassigned Students', metric_key: 'unassigned_students' },
      { id: 'cbe_progress', title: 'CBC/CBE Progress', metric_key: 'competency_progress_rate', unit: '%' },
    ],
    drilldowns: ['academics.department-performance', 'academics.class-ranking', 'academics.risk-alerts'],
    reports: ['academic-summary', 'cbc-cbe-competency-progress'],
  },
  {
    module_code: 'exams',
    id: 'exams',
    title: 'Exams and Results',
    category: 'academics',
    permission_required: 'exams:read',
    widgets: [
      { id: 'mean_score', title: 'Mean Score', metric_key: 'mean_score' },
      { id: 'completion', title: 'Exam Completion', metric_key: 'exam_completion_rate', unit: '%' },
      { id: 'draft_marks', title: 'Draft Marks', metric_key: 'draft_marks' },
    ],
    drilldowns: ['exams.subject-ranking', 'exams.teacher-distribution', 'exams.cohort-trends'],
    reports: ['exam-performance', 'class-ranking'],
  },
  {
    module_code: 'finance',
    id: 'finance',
    title: 'Finance Insights',
    category: 'finance',
    permission_required: 'finance:read',
    confidentiality: 'summary_only',
    widgets: [
      { id: 'collections', title: 'Fee Collection', metric_key: 'fee_collection_rate', unit: '%' },
      { id: 'outstanding', title: 'Outstanding Balances', metric_key: 'outstanding_balance_minor', unit: 'KES cents' },
      { id: 'daily_collections', title: 'Daily Collections', metric_key: 'daily_collections_minor', unit: 'KES cents' },
      { id: 'pending_approvals', title: 'Pending Approvals', metric_key: 'pending_finance_approvals' },
    ],
    drilldowns: ['finance.arrears-aging', 'finance.expected-vs-actual', 'finance.budget-utilization'],
    reports: ['fee-collection', 'arrears-aging', 'budget-utilization'],
  },
  {
    module_code: 'staff',
    id: 'staff_hr',
    title: 'Staff and HR Insights',
    category: 'staff',
    permission_required: 'hr:read',
    confidentiality: 'summary_only',
    widgets: [
      { id: 'active_staff', title: 'Active Staff', metric_key: 'active_staff' },
      { id: 'leave_requests', title: 'Leave Requests', metric_key: 'pending_leave_requests' },
      { id: 'contract_expiry', title: 'Contracts Expiring', metric_key: 'contracts_expiring_soon' },
      { id: 'workload_alerts', title: 'Workload Alerts', metric_key: 'workload_alerts' },
    ],
    drilldowns: ['hr.attendance-trends', 'hr.leave-utilization', 'hr.department-workload'],
    reports: ['staff-summary', 'leave-utilization'],
  },
  {
    module_code: 'teacher_biometric_attendance',
    id: 'biometric_attendance',
    title: 'Biometric Attendance Insights',
    category: 'attendance',
    permission_required: 'teacher_attendance:read',
    widgets: [
      { id: 'teacher_present', title: 'Teachers Present Today', metric_key: 'teacher_present_today' },
      { id: 'late_arrivals', title: 'Late Arrivals', metric_key: 'teacher_late_today' },
      { id: 'absentee_alerts', title: 'Absentee Alerts', metric_key: 'teacher_absent_today' },
      { id: 'offline_devices', title: 'Offline Devices', metric_key: 'offline_biometric_devices' },
    ],
    drilldowns: ['attendance.live-feed', 'attendance.department-trends', 'attendance.device-health'],
    reports: ['teacher-attendance-daily', 'punctuality-ranking'],
  },
  {
    module_code: 'clinic_health',
    id: 'clinic_health',
    title: 'Clinic and Health Insights',
    category: 'health',
    permission_required: 'clinic:reports',
    confidentiality: 'summary_only',
    widgets: [
      { id: 'clinic_visits_today', title: "Today's Clinic Visits", metric_key: 'clinic_visits_today' },
      { id: 'low_stock_meds', title: 'Low-Stock Medicines', metric_key: 'medicine_low_stock' },
      { id: 'out_of_stock_meds', title: 'Out-of-Stock Medicines', metric_key: 'out_of_stock_medicines' },
      { id: 'expiring_meds', title: 'Expiring Medicines', metric_key: 'medicine_expiring_soon' },
      { id: 'critical_meds', title: 'Critical Medicine Shortages', metric_key: 'critical_medicine_shortages' },
      { id: 'clinic_costs', title: 'Clinic Costs This Month', metric_key: 'medicine_consumption_cost_minor', unit: 'KES cents' },
      { id: 'expiry_wastage', title: 'Expiry Wastage Value', metric_key: 'wastage_due_to_expiry_minor', unit: 'KES cents' },
      { id: 'emergency_readiness', title: 'Emergency Supply Readiness', metric_key: 'emergency_supply_ready_rate', unit: '%' },
      { id: 'most_used_medicine', title: 'Most Used Medicine', metric_key: 'most_used_medicine' },
    ],
    drilldowns: ['clinic.medicine-availability', 'clinic.visit-trends', 'clinic.emergency-readiness'],
    reports: ['clinic-operations', 'medicine-inventory', 'medicine-expiry'],
  },
  {
    module_code: 'inventory',
    id: 'inventory',
    title: 'Inventory Insights',
    category: 'operations',
    permission_required: 'inventory:read',
    widgets: [
      { id: 'low_stock', title: 'Low Stock Alerts', metric_key: 'inventory_low_stock' },
      { id: 'out_stock', title: 'Out of Stock', metric_key: 'inventory_out_of_stock' },
      { id: 'damaged_assets', title: 'Damaged Assets', metric_key: 'damaged_assets' },
      { id: 'inventory_value', title: 'Inventory Valuation', metric_key: 'inventory_value_minor', unit: 'KES cents' },
    ],
    drilldowns: ['inventory.low-stock', 'inventory.asset-utilization', 'inventory.department-consumption'],
    reports: ['inventory-valuation', 'stock-movement'],
  },
  {
    module_code: 'procurement',
    id: 'procurement',
    title: 'Procurement Insights',
    category: 'operations',
    permission_required: 'procurement:read',
    widgets: [
      { id: 'pending_requests', title: 'Pending Requests', metric_key: 'pending_procurement_requests' },
      { id: 'open_pos', title: 'Open Purchase Orders', metric_key: 'open_purchase_orders' },
      { id: 'overdue_pos', title: 'Overdue Deliveries', metric_key: 'overdue_purchase_orders' },
    ],
    drilldowns: ['procurement.pending-approvals', 'procurement.supplier-performance'],
    reports: ['procurement-history', 'supplier-summary'],
  },
  {
    module_code: 'lab_management',
    id: 'laboratory',
    title: 'Laboratory Insights',
    category: 'academics',
    permission_required: 'labs:read',
    widgets: [
      { id: 'lab_attendance', title: 'Lab Attendance Compliance', metric_key: 'lab_attendance_compliance_rate', unit: '%' },
      { id: 'missed_practicals', title: 'Missed Practicals', metric_key: 'missed_practical_sessions' },
      { id: 'chemical_expiry', title: 'Chemical Expiry Alerts', metric_key: 'chemical_expiry_alerts' },
      { id: 'maintenance', title: 'Equipment Maintenance Alerts', metric_key: 'lab_equipment_maintenance_alerts' },
    ],
    drilldowns: ['labs.attendance-compliance', 'labs.chemical-safety', 'labs.booking-conflicts'],
    reports: ['lab-safety', 'lab-attendance', 'chemical-expiry'],
  },
  {
    module_code: 'discipline',
    id: 'discipline_welfare',
    title: 'Discipline and Welfare',
    category: 'student_welfare',
    permission_required: 'discipline:reports',
    confidentiality: 'summary_only',
    widgets: [
      { id: 'open_cases', title: 'Open Cases', metric_key: 'open_discipline_cases' },
      { id: 'critical_cases', title: 'Critical Cases', metric_key: 'critical_discipline_cases' },
      { id: 'repeat_offenders', title: 'Repeat Offender Alerts', metric_key: 'repeat_offender_alerts' },
      { id: 'welfare_concerns', title: 'Welfare Concerns', metric_key: 'welfare_concerns' },
    ],
    drilldowns: ['discipline.trends', 'discipline.repeat-offenders', 'discipline.counselling-referrals'],
    reports: ['discipline-summary', 'welfare-risk'],
  },
  {
    module_code: 'transport',
    id: 'transport',
    title: 'Transport Insights',
    category: 'operations',
    permission_required: 'transport:read',
    widgets: [
      { id: 'route_delays', title: 'Route Delays', metric_key: 'transport_route_delays' },
      { id: 'bus_attendance', title: 'Bus Attendance', metric_key: 'bus_attendance_rate', unit: '%' },
      { id: 'vehicle_alerts', title: 'Vehicle Alerts', metric_key: 'vehicle_alerts' },
    ],
    drilldowns: ['transport.routes', 'transport.bus-attendance'],
    reports: ['transport-operations'],
  },
  {
    module_code: 'hostel',
    id: 'hostel',
    title: 'Hostel Insights',
    category: 'boarding',
    permission_required: 'hostel:read',
    widgets: [
      { id: 'occupancy', title: 'Hostel Occupancy', metric_key: 'hostel_occupancy_rate', unit: '%' },
      { id: 'boarding_incidents', title: 'Boarding Incidents', metric_key: 'boarding_incidents' },
      { id: 'dormitory_issues', title: 'Dormitory Issues', metric_key: 'dormitory_issues' },
    ],
    drilldowns: ['hostel.occupancy', 'hostel.incidents'],
    reports: ['hostel-summary'],
  },
  {
    module_code: 'boarding',
    id: 'boarding',
    title: 'Boarding Insights',
    category: 'boarding',
    permission_required: 'boarding:read',
    widgets: [
      { id: 'meal_consumption', title: 'Meal Consumption', metric_key: 'meal_consumption_rate', unit: '%' },
      { id: 'boarding_welfare', title: 'Boarding Welfare Alerts', metric_key: 'boarding_welfare_alerts' },
    ],
    drilldowns: ['boarding.meals', 'boarding.welfare'],
    reports: ['boarding-operations'],
  },
  {
    module_code: 'communication_sms',
    id: 'communication',
    title: 'Communication Insights',
    category: 'communication',
    permission_required: 'school_sms:read',
    widgets: [
      { id: 'delivery_rate', title: 'SMS Delivery Rate', metric_key: 'sms_delivery_rate', unit: '%' },
      { id: 'failed_sms', title: 'Failed SMS', metric_key: 'failed_sms' },
      { id: 'sms_balance', title: 'SMS Balance', metric_key: 'sms_balance' },
      { id: 'announcement_reads', title: 'Circular Readership', metric_key: 'circular_readership_rate', unit: '%' },
    ],
    drilldowns: ['communication.delivery-logs', 'communication.parent-engagement'],
    reports: ['communication-effectiveness', 'sms-delivery'],
  },
  {
    module_code: 'timetable',
    id: 'timetable',
    title: 'Timetabling Insights',
    category: 'academics',
    permission_required: 'timetable:read',
    widgets: [
      { id: 'coverage', title: 'Lesson Coverage', metric_key: 'lesson_coverage_rate', unit: '%' },
      { id: 'conflicts', title: 'Timetable Conflicts', metric_key: 'timetable_conflicts' },
      { id: 'missing_lessons', title: 'Missing Lessons', metric_key: 'missing_lessons' },
    ],
    drilldowns: ['timetable.coverage', 'timetable.conflicts'],
    reports: ['timetable-execution'],
  },
  {
    module_code: 'library',
    id: 'library',
    title: 'Library Insights',
    category: 'academics',
    permission_required: 'library:read',
    widgets: [
      { id: 'borrowed_books', title: 'Borrowed Books', metric_key: 'borrowed_books' },
      { id: 'overdue_books', title: 'Overdue Books', metric_key: 'overdue_books' },
      { id: 'library_visits', title: 'Library Visits', metric_key: 'library_visits_today' },
    ],
    drilldowns: ['library.borrowing', 'library.overdue'],
    reports: ['library-operations'],
  },
  {
    module_code: 'ai_insights',
    id: 'ai_smart_alerts',
    title: 'AI and Smart Alerts',
    category: 'analytics',
    permission_required: 'principal:read',
    widgets: [
      { id: 'fee_default_risk', title: 'Fee Default Risk', metric_key: 'fee_default_risk_alerts' },
      { id: 'medicine_shortage', title: 'Medicine Shortage Forecasts', metric_key: 'medicine_shortage_predictions' },
      { id: 'attendance_irregularities', title: 'Attendance Irregularities', metric_key: 'attendance_irregularities' },
      { id: 'budget_overrun', title: 'Budget Overrun Alerts', metric_key: 'budget_overrun_alerts' },
      { id: 'performance_decline', title: 'Performance Decline Warnings', metric_key: 'performance_decline_warnings' },
      { id: 'risk_alerts', title: 'Total Smart Risk Alerts', metric_key: 'smart_risk_alerts' },
    ],
    drilldowns: ['ai.risk-alerts', 'ai.anomalies', 'ai.forecasts'],
    reports: ['smart-alerts'],
  },
] as const;
