// GENERATED BY scaffold_boarding_master.js
"use client";

import { useState, useEffect, type FormEvent, type ReactNode } from "react";
import {
  AlertTriangle,
  BedDouble,
  Building,
  Calendar,
  CheckCircle,
  CheckSquare,
  ClipboardList,
  Clock,
  DoorOpen,
  FileText,
  HeartPulse,
  LayoutDashboard,
  MessageSquare,
  Package,
  Search,
  Settings,
  ShieldAlert,
  UserPlus,
  Users,
  Utensils,
  Wrench,
  type LucideIcon,
} from "lucide-react";

import { useSchoolQuery } from "@/lib/data/school-hooks";
import { getCurrentSchoolId, publishSchoolOperationalEvent } from "@/lib/school/school-operational-store";
import { requestDashboardApi } from "@/lib/dashboard/api-client";
import { toast } from "sonner";
import { ApprovalInbox } from "@/components/shared/approval-inbox";
import { NotificationBell } from "@/components/shared/notification-bell";
import { TaskQueue } from "@/components/shared/task-queue";
import { downloadCsvFile, openPrintDocument } from "@/lib/dashboard/export";
import { buildSchoolSectionHref } from "./school-pages";
import { LeaveExitWorkspace as RoutedLeaveExitWorkspace } from "./boarding-master/leave-exit-workspace";

type RouteMode = "hosted" | "public";
type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type ViewId = "overview" | "register" | "dorms" | "beds" | "roll-call" | "leave" | "late-returns" | "duty" | "incidents" | "welfare" | "meals" | "inspections" | "maintenance" | "inventory" | "visitors" | "communication" | "approvals" | "reports" | "settings";
type BoardingActionTone = "success" | "info" | "warning" | "danger";

type NavItem = {
  id: ViewId;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard, group: "Command Center" },
  { id: "register", label: "Boarder Register", icon: Users, group: "Boarders" },
  { id: "dorms", label: "Dormitories & Rooms", icon: Building, group: "Facilities" },
  { id: "beds", label: "Bed Allocation", icon: BedDouble, group: "Facilities" },
  { id: "roll-call", label: "Daily Roll Call", icon: ClipboardList, group: "Daily Operations" },
  { id: "leave", label: "Leave / Exeat Requests", icon: DoorOpen, group: "Daily Operations" },
  { id: "late-returns", label: "Late Returns & Absences", icon: Clock, group: "Daily Operations" },
  { id: "duty", label: "Duty Roster", icon: Calendar, group: "Daily Operations" },
  { id: "incidents", label: "Dorm Incidents", icon: ShieldAlert, group: "Welfare & Discipline" },
  { id: "welfare", label: "Health & Welfare", icon: HeartPulse, group: "Welfare & Discipline" },
  { id: "meals", label: "Meals & Dining", icon: Utensils, group: "Welfare & Discipline" },
  { id: "inspections", label: "Dorm Inspections", icon: CheckSquare, group: "Maintenance & Stores" },
  { id: "maintenance", label: "Maintenance Requests", icon: Wrench, group: "Maintenance & Stores" },
  { id: "inventory", label: "Boarding Inventory", icon: Package, group: "Maintenance & Stores" },
  { id: "visitors", label: "Visitors & Gate Passes", icon: UserPlus, group: "Communication" },
  { id: "communication", label: "Parent Communication", icon: MessageSquare, group: "Communication" },
  { id: "approvals", label: "Approvals", icon: CheckCircle, group: "Management" },
  { id: "reports", label: "Reports & Downloads", icon: FileText, group: "Management" },
  { id: "settings", label: "Boarding Settings", icon: Settings, group: "Management" },
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

type SearchRecord = { id: string; label: string; detail: string; view: ViewId };

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function asRows<T>(value: unknown): T[] {
  if (Array.isArray(value)) return value as T[];
  if (value && typeof value === "object" && Array.isArray((value as any).data)) return (value as any).data;
  if (value && typeof value === "object" && Array.isArray((value as any).items)) return (value as any).items;
  return [];
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions}
      </div>
      {children}
    </section>
  );
}

function DataTable({
  title,
  columns,
  rows,
}: {
  title?: string;
  columns: string[];
  rows: ReactNode[][];
}) {
  return (
    <div className="overflow-hidden rounded-2xl border border-[#D8E0EC] bg-white">
      {title && (
        <div className="border-b border-[#D8E0EC] bg-[#F8FAFC] px-4 py-3">
          <h3 className="text-sm font-black uppercase tracking-[0.14em] text-[#071D49]">{title}</h3>
        </div>
      )}
      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead className="bg-[#EEF2FF] text-xs uppercase tracking-[0.12em] text-[#64748B]">
            <tr>
              {columns.map((column, i) => (
                <th key={i} className="px-4 py-3 font-black whitespace-nowrap">{column}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-[#E2E8F0]">
            {rows.map((row, i) => (
              <tr key={i} className="transition hover:bg-[#F8FAFC]">
                {row.map((cell, j) => (
                  <td key={j} className="px-4 py-3 font-semibold text-[#334155] whitespace-nowrap">
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
            {rows.length === 0 && (
              <tr>
                <td colSpan={columns.length} className="px-4 py-8 text-center text-[#64748B]">No records found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function boardingActionSlug(title: string) {
  return title.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "").slice(0, 80) || "boarding_action";
}

async function persistBoardingWorkflowAction(title: string, body: string, tone: BoardingActionTone) {
  return requestDashboardApi("/api/admin-command/boarding-master/actions", {
    method: "POST",
    body: {
      action: boardingActionSlug(title),
      title,
      message: body,
      priority: tone === "danger" || tone === "warning" ? "high" : "normal",
      targetRoles: tone === "danger" || tone === "warning"
        ? ["boarding_master", "principal", "deputy_principal"]
        : ["boarding_master", "principal"],
      payload: { tone },
    },
  });
}

async function recordBoardingAction(title: string, body: string, tone: BoardingActionTone = "info") {
  try {
    await persistBoardingWorkflowAction(title, body, tone);
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : "Boarding action could not be recorded";
    toast.error(message);
    return false;
  }

  const notify = tone === "danger" ? toast.error : tone === "success" ? toast.success : toast.info;
  notify(title, { description: body });
  publishSchoolOperationalEvent({
    type: "boarding.workflow_action",
    module: "boarding",
    actorRole: "boarding_master",
    title,
    body,
  });
  return true;
}

async function openBoardingActionRecord(title: string, rows: Array<[string, string]>) {
  const persisted = await recordBoardingAction("Boarding record opened", `${title} is available for preview, print, or PDF download.`, "success");
  if (!persisted) {
    return;
  }

  openPrintDocument({
    eyebrow: "MyShule Boarding Master",
    title,
    subtitle: `School: ${getCurrentSchoolId() || "current tenant"} | Generated ${new Date().toLocaleString()}`,
    rows: rows.map(([label, value]) => ({ label, value })),
    footer: "Boarding records and reports are tenant-scoped and should be reviewed before parent or staff communication.",
  });
}

async function exportBoardingCsv(filename: string, headers: string[], rows: string[][], title: string) {
  const persisted = await recordBoardingAction("Boarding export created", `${title} was downloaded from the current boarding workspace.`, "success");
  if (!persisted) {
    return;
  }

  downloadCsvFile({ filename, headers, rows });
}

async function generateBoardingReport(reportType: string) {
  try {
    await requestDashboardApi("/admin-command/boarding-master/reports/generate", {
      method: "POST",
      body: { report_type: reportType, generated_from: "boarding-master-command-center" },
    });
    openBoardingActionRecord(reportType, [
      ["Report", reportType],
      ["Scope", "Current school tenant"],
      ["Generated from", "Boarding Master command center"],
      ["Status", "Generation requested and print preview generated"],
    ]);
  } catch (error: any) {
    recordBoardingAction("Boarding report failed", error?.message || "The report could not be generated. Check backend readiness and tenant context.", "danger");
  }
}

// Workspaces Implementations

function OverviewWorkspace({ onNavigate }: { onNavigate: (view: ViewId) => void }) {
  const { data: dashboard, isLoading } = useSchoolQuery<any>("/api/boarding/dashboard");

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-4">
         <button type="button" onClick={() => onNavigate('register')} className="text-left rounded-xl border border-[#D8E0EC] bg-white p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-[#64748B] uppercase tracking-wider">Total Boarders</p>
           <p className="text-3xl font-black text-[#071D49] mt-2">{isLoading ? "-" : dashboard?.total_boarders ?? dashboard?.total_records ?? 0}</p>
         </button>
         <button type="button" onClick={() => onNavigate('roll-call')} className="text-left rounded-xl border border-[#D8E0EC] bg-white p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-[#64748B] uppercase tracking-wider">Present Tonight</p>
           <p className="text-3xl font-black text-[#071D49] mt-2">{isLoading ? "-" : dashboard?.open_records ?? 0}</p>
         </button>
         <button type="button" onClick={() => onNavigate('roll-call')} className="text-left rounded-xl border border-rose-200 bg-rose-50 p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-rose-700 uppercase tracking-wider">Missing Roll Call</p>
           <p className="text-3xl font-black text-rose-900 mt-2">{isLoading ? "-" : dashboard?.action_due ?? 0}</p>
         </button>
         <button type="button" onClick={() => onNavigate('leave')} className="text-left rounded-xl border border-blue-200 bg-blue-50 p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-blue-700 uppercase tracking-wider">Approved Leave-Outs</p>
           <p className="text-3xl font-black text-blue-900 mt-2">{isLoading ? "-" : dashboard?.approved_leave ?? 0}</p>
         </button>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Panel title="Tonight's Roll Call" icon={ClipboardList}>
          <DataTable 
            columns={["Student", "Status", "Action"]}
            rows={(dashboard?.records || []).slice(0, 5).map((r: any) => [
              r.title,
              <StatusChip key="s1" label={r.status} tone={r.status === 'active' ? 'success' : 'warning'}/>,
              <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('roll-call')}>View</button>
            ])}
          />
        </Panel>

        <Panel title="Urgent Follow-ups" icon={AlertTriangle}>
          <DataTable 
            columns={["Concern", "Student", "Action"]}
            rows={(dashboard?.activity || []).slice(0, 5).map((a: any) => [
              a.action,
              a.actor_role,
              <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Urgent boarding follow-up", [["Concern", String(a.action ?? "-")], ["Student/role", String(a.actor_role ?? "-")], ["Next action", "Review in boarding incidents or welfare queue"]])}>View</button>
            ])}
          />
        </Panel>
      </div>
      
      <Panel title="Dorm Status" icon={Building}>
        <DataTable 
          columns={["Dormitory", "Capacity", "Occupied", "Available", "Roll Call %", "Action"]}
          rows={(dashboard?.records || []).filter((r: any) => r.category === 'dorm').slice(0, 5).map((r: any) => [
            r.title, r.metric_count || "0", r.metric_count || "0", "0", "100%", <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('dorms')}>Open Dorm</button>
          ])}
        />
      </Panel>
    </div>
  );
}

function RegisterWorkspace() {
  const { data: dashboard, refetch } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);

  async function handleAddBoarder(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const studentName = String(form.get("student_name") || "").trim();
    const admissionNumber = String(form.get("admission_number") || "").trim();
    const house = String(form.get("house") || "").trim();
    const room = String(form.get("room") || "").trim();
    const bedLabel = String(form.get("bed_label") || "").trim();

    if (!studentName || !admissionNumber || !house || !bedLabel) {
      toast.error("Student name, admission number, house, and bed label are required.");
      return;
    }

    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/boarding/records", {
        method: "POST",
        body: {
          title: studentName,
          category: "student",
          owner_name: house,
          status: "active",
          priority: "normal",
          notes: `Boarder ${admissionNumber} assigned to ${house}${room ? ` room ${room}` : ""} bed ${bedLabel}.`,
          metadata: {
            admission_number: admissionNumber,
            house,
            room,
            bed_label: bedLabel,
            boarding_category: "boarder",
          },
        },
      });
      toast.success("Boarder added to register");
      publishSchoolOperationalEvent({
        type: "boarding.boarder_registered",
        module: "boarding",
        actorRole: "boarding_master",
        title: "Boarder registered",
        body: `${studentName} was added to the boarding register.`,
      });
      event.currentTarget.reset();
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Boarder could not be added");
    } finally {
      setIsSubmitting(false);
    }
  }

  const boarders = (dashboard?.records || []).filter((record: any) => record.category === "student");

  return (
    <Panel 
      title="Boarder Register" 
      description="Master list of all learners in boarding." 
      icon={Users}
      actions={
        <div className="flex gap-2">
           <button type="button" className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-black text-[#071D49]" onClick={() => exportBoardingCsv("boarding-register-import-template.csv", ["student_admission_number", "boarding_category", "house", "room", "bed_label"], [], "Boarding register import template")}>Import</button>
        </div>
      }
    >
      <form onSubmit={handleAddBoarder} className="mb-5 grid gap-3 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 md:grid-cols-2 xl:grid-cols-5">
        <input name="student_name" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Student name" />
        <input name="admission_number" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Admission number" />
        <input name="house" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="House / dormitory" />
        <input name="room" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Room" />
        <input name="bed_label" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Bed label" />
        <button type="submit" disabled={isSubmitting} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white disabled:opacity-50 md:col-span-2 xl:col-span-1">
          {isSubmitting ? "Adding..." : "Add Boarder"}
        </button>
      </form>
      <DataTable 
        columns={["Student", "ADM", "House", "Room", "Bed", "Status", "Actions"]}
        rows={boarders.map((r: any) => [
          r.title,
          r.metadata?.admission_number || r.metadata?.adm || "-",
          r.metadata?.house || r.owner_name || "-",
          r.metadata?.room || "-",
          r.metadata?.bed_label || r.metadata?.bed || "-",
          <StatusChip key="s1" label={r.status} tone={r.status === 'active' ? 'success' : 'neutral'}/>,
          <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Boarder profile", [["Student", String(r.title ?? "-")], ["Admission", String(r.metadata?.admission_number ?? "-")], ["House", String(r.metadata?.house ?? r.owner_name ?? "-")], ["Room", String(r.metadata?.room ?? "-")], ["Bed", String(r.metadata?.bed_label ?? "-")], ["Status", String(r.status ?? "-")]])}>View Profile</button>
        ])}
      />
    </Panel>
  );
}

function DormsWorkspace() {
  const { data: dashboard } = useSchoolQuery<any>("/api/boarding/dashboard");

  return (
    <Panel title="Dormitories & Rooms" description="Manage physical boarding structure and capacity." icon={Building}>
      <DataTable 
        columns={["Dormitory", "Type", "Capacity", "Status", "Actions"]}
        rows={(dashboard?.records || []).filter((r: any) => r.category === 'dorm').map((r: any) => [
          r.title, "Dormitory", r.metric_count || "0", <StatusChip key="s1" label={r.status} tone={r.status === 'active' ? 'success' : 'neutral'}/>, <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Dormitory rooms", [["Dormitory", String(r.title ?? "-")], ["Capacity", String(r.metric_count ?? "0")], ["Status", String(r.status ?? "-")]])}>View Rooms</button>
        ])}
      />
    </Panel>
  );
}

function BedsWorkspace() {
  const { data: dashboard } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleAssignBed = async (studentId?: string, bedId?: string) => {
    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/admin-command/boarding-master/allocation", {
        method: "POST",
        body: { student_id: studentId || "auto", bed_id: bedId || "auto" },
      });
      toast.success("Bed assigned successfully");
      publishSchoolOperationalEvent({
        type: "boarding.bed_assigned",
        module: "boarding",
        actorRole: "boarding_master",
        title: "Bed Assigned",
        body: "A bed has been assigned to a student.",
      });
    } catch (e: any) {
      toast.error(e.message || "Failed to assign bed");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Panel title="Bed Allocation" description="Assign, change, transfer, and release beds." icon={BedDouble}>
      <div className="grid grid-cols-2 gap-4">
        <div>
           <h3 className="text-sm font-black uppercase text-[#071D49] mb-4">Students Needing Beds</h3>
           <DataTable 
             columns={["Student", "Status", "Action"]}
             rows={(dashboard?.records || []).filter((r: any) => r.status !== 'active').map((r: any) => [
               r.title, r.status, <button key="a1" type="button" onClick={() => handleAssignBed(r.id, undefined)} disabled={isSubmitting} className="text-[#1D4ED8] font-bold text-xs disabled:opacity-50">Allocate</button>
             ])}
           />
        </div>
        <div>
           <h3 className="text-sm font-black uppercase text-[#071D49] mb-4">Available Beds</h3>
           <DataTable 
             columns={["Dorm", "Room", "Bed No.", "Action"]}
             rows={(dashboard?.records || []).filter((r: any) => r.category === 'bed').map((r: any) => [
               r.owner_name || "-", "-", r.title, <button key="a1" type="button" onClick={() => handleAssignBed(undefined, r.id)} disabled={isSubmitting} className="text-[#1D4ED8] font-bold text-xs disabled:opacity-50">Assign Bed</button>
             ])}
           />
        </div>
      </div>
    </Panel>
  );
}

function RollCallWorkspace() {
  const { data: dashboard } = useSchoolQuery<any>("/api/boarding/dashboard");
  const { data: attendanceData } = useSchoolQuery<any>("/api/admin-command/boarding-master/boarding-attendance");
  const { data: allocationData } = useSchoolQuery<any>("/api/admin-command/boarding-master/allocation");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const attendanceRows = asRows<any>(attendanceData?.attendanceList ?? attendanceData);
  const allocationRows = asRows<any>(allocationData?.allocationList ?? allocationData);
  const boarderRows = attendanceRows.length > 0
    ? attendanceRows
    : allocationRows.length > 0
      ? allocationRows
      : (dashboard?.records || []).filter((r: any) => r.category === 'student');

  const handleRollCall = async (studentId?: string) => {
    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/admin-command/boarding-master/boarding-attendance", {
        method: "POST",
        body: studentId ? { student_id: studentId, status: "present" } : { action: "start_roll_call" },
      });
      toast.success(studentId ? "Roll call marked" : "Roll call started");
      publishSchoolOperationalEvent({
        type: "boarding.roll_call",
        module: "boarding",
        actorRole: "boarding_master",
        title: "Roll Call Processed",
        body: studentId ? "Roll call marked for student." : "Roll call started.",
      });
    } catch (e: any) {
      toast.error(e.message || "Failed to process roll call");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Panel title="Daily Roll Call" description="Confirm that every boarder is accounted for." icon={ClipboardList}>
      <div className="mb-4 flex gap-2">
           <button type="button" onClick={() => handleRollCall()} disabled={isSubmitting} className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white disabled:opacity-50">
             {isSubmitting ? "Starting..." : "Start Roll Call"}
           </button>
           <button type="button" className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-black text-[#071D49]" onClick={() => openBoardingActionRecord("Missing roll-call list", [["Date", "Today"], ["Scope", "Current school boarders"], ["Action", "Print or download missing list"], ["Follow-up", "Notify deputy and parent for unresolved absences"]])}>Print Missing List</button>
      </div>
      <DataTable 
        columns={["Student", "ADM", "Dorm", "Room", "Bed", "Status", "Actions"]}
        rows={boarderRows.map((r: any) => [
          r.student_name || r.title || r.student_id?.substring?.(0, 8) || "Boarder record",
          r.admission_number || r.metadata?.adm || "-",
          r.hostel || r.metadata?.dorm || r.hostel_name || "-",
          r.room_number || r.metadata?.room || "-",
          r.bed_number || r.metadata?.bed || r.bed_id?.substring?.(0, 8) || "-",
          <StatusChip key={`s-${r.id || r.student_id}`} label={r.status === 'active' || r.status === 'present' ? "Present" : r.status || "Not marked"} tone={r.status === 'active' || r.status === 'present' ? "success" : "warning"}/>,
          <button key={`a-${r.id || r.student_id}`} type="button" onClick={() => handleRollCall(r.student_id || r.id)} disabled={isSubmitting} className="text-[#1D4ED8] font-bold text-xs disabled:opacity-50">Edit Status</button>
        ])}
      />
    </Panel>
  );
}

function LeaveWorkspace() {
  return <RoutedLeaveExitWorkspace />;
}

function LateReturnsWorkspace() {
  const { data: dashboard, refetch } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const lateReturns = (dashboard?.records || []).filter((record: any) => record.category === "late_return");

  async function handleAddLateReturn(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const studentName = String(form.get("student_name") || "").trim();
    const dorm = String(form.get("dorm") || "").trim();
    const expectedTime = String(form.get("expected_time") || "").trim();
    const actualTime = String(form.get("actual_time") || "").trim();
    const notes = String(form.get("notes") || "").trim();

    if (!studentName || !dorm || !expectedTime || !actualTime || !notes) {
      toast.error("Student, dorm, expected time, actual time, and notes are required.");
      return;
    }

    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/boarding/records", {
        method: "POST",
        body: {
          title: studentName,
          category: "late_return",
          owner_name: dorm,
          status: "unresolved",
          priority: "high",
          notes,
          metadata: {
            dorm,
            expected_time: expectedTime,
            actual_time: actualTime,
          },
        },
      });
      toast.success("Late return recorded");
      publishSchoolOperationalEvent({
        type: "boarding.late_return",
        module: "boarding",
        actorRole: "boarding_master",
        title: "Late return recorded",
        body: `${studentName} returned late to ${dorm}.`,
      });
      event.currentTarget.reset();
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Late return could not be recorded");
    } finally {
      setIsSubmitting(false);
    }
  }

  async function handleResolveLateReturn(record: any) {
    const explanation = window.prompt(`Explanation or action taken for ${record.title}`);
    if (!explanation?.trim()) return;

    setIsSubmitting(true);
    try {
      await requestDashboardApi(`/api/boarding/records/${record.id}/status`, {
        method: "PATCH",
        body: {
          status: "resolved",
          notes: explanation.trim(),
        },
      });
      toast.success("Late return explanation saved");
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Late return explanation could not be saved");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Panel title="Late Returns & Absences" description="Track students who return late from leave or miss roll call." icon={Clock}>
      <form onSubmit={handleAddLateReturn} className="mb-5 grid gap-3 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 md:grid-cols-2 xl:grid-cols-5">
        <input name="student_name" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Student name" />
        <input name="dorm" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Dormitory" />
        <input name="expected_time" required type="time" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" aria-label="Expected return time" />
        <input name="actual_time" required type="time" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" aria-label="Actual return time" />
        <textarea name="notes" required rows={2} className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm md:col-span-2 xl:col-span-4" placeholder="Initial observation and parent/deputy follow-up notes" />
        <button type="submit" disabled={isSubmitting} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white disabled:opacity-50">
          {isSubmitting ? "Recording..." : "Record Late Return"}
        </button>
      </form>
      <DataTable 
        columns={["Student", "Dorm", "Expected Time", "Actual Time", "Delay", "Status", "Actions"]}
        rows={lateReturns.map((record: any) => [
          record.title,
          record.metadata?.dorm || record.owner_name || "-",
          record.metadata?.expected_time || "-",
          record.metadata?.actual_time || "-",
          record.metadata?.delay || "-",
          <StatusChip key="s1" label={record.status} tone={record.status === "resolved" ? "success" : "danger"}/>,
          record.status === "resolved"
            ? <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Late return explanation", [["Student", String(record.title ?? "-")], ["Dorm", String(record.metadata?.dorm ?? record.owner_name ?? "-")], ["Explanation", String(record.notes ?? "-")], ["Status", String(record.status ?? "-")]])}>View Explanation</button>
            : <button key="a1" type="button" disabled={isSubmitting} className="text-[#1D4ED8] font-bold text-xs disabled:opacity-50" onClick={() => handleResolveLateReturn(record)}>Add Explanation</button>,
        ])}
      />
    </Panel>
  );
}

function DutyWorkspace() {
  const { data: dashboard, refetch } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const dutyReports = (dashboard?.records || []).filter((record: any) => record.category === "duty_report");

  async function handleAddDutyReport(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const dutyDate = String(form.get("duty_date") || "").trim();
    const dormitory = String(form.get("dormitory") || "").trim();
    const staffOnDuty = String(form.get("staff_on_duty") || "").trim();
    const prefect = String(form.get("prefect") || "").trim();
    const notes = String(form.get("notes") || "").trim();

    if (!dutyDate || !dormitory || !staffOnDuty || !notes) {
      toast.error("Date, dormitory, staff on duty, and report notes are required.");
      return;
    }

    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/boarding/records", {
        method: "POST",
        body: {
          title: `${dormitory} duty report`,
          category: "duty_report",
          owner_name: staffOnDuty,
          status: "active",
          priority: "normal",
          due_date: dutyDate,
          notes,
          metadata: {
            duty_date: dutyDate,
            dormitory,
            staff_on_duty: staffOnDuty,
            prefect,
          },
        },
      });
      toast.success("Duty report saved");
      publishSchoolOperationalEvent({
        type: "boarding.duty_report_created",
        module: "boarding",
        actorRole: "boarding_master",
        title: "Duty report saved",
        body: `${staffOnDuty} saved a duty report for ${dormitory}.`,
      });
      event.currentTarget.reset();
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Duty report could not be saved");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Panel title="Duty Roster" description="Manage boarding duty staff, dorm captains, and prefects." icon={Calendar}>
      <form onSubmit={handleAddDutyReport} className="mb-5 grid gap-3 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 md:grid-cols-2 xl:grid-cols-5">
        <input name="duty_date" required type="date" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" aria-label="Duty date" />
        <input name="dormitory" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Dormitory" />
        <input name="staff_on_duty" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Staff on duty" />
        <input name="prefect" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Prefect / captain" />
        <textarea name="notes" required rows={2} className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm md:col-span-2 xl:col-span-4" placeholder="Dorm patrol notes, issues, and handover actions" />
        <button type="submit" disabled={isSubmitting} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white disabled:opacity-50">
          {isSubmitting ? "Saving..." : "Add Report"}
        </button>
      </form>
      <DataTable 
        columns={["Date", "Dormitory", "Staff on Duty", "Prefect/Captain", "Status", "Actions"]}
        rows={dutyReports.map((record: any) => [
          record.metadata?.duty_date || record.due_date || "-",
          record.metadata?.dormitory || record.title || "-",
          record.metadata?.staff_on_duty || record.owner_name || "-",
          record.metadata?.prefect || "-",
          <StatusChip key="s1" label={record.status} tone={record.status === "active" ? "info" : "success"}/>,
          <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Duty report", [["Date", String(record.metadata?.duty_date ?? record.due_date ?? "-")], ["Dormitory", String(record.metadata?.dormitory ?? "-")], ["Staff", String(record.metadata?.staff_on_duty ?? record.owner_name ?? "-")], ["Prefect", String(record.metadata?.prefect ?? "-")], ["Notes", String(record.notes ?? "-")]])}>View Report</button>,
        ])}
      />
    </Panel>
  );
}

function IncidentsWorkspace() {
  const { data: dashboard } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);

  const handleLogIncident = async (incidentId?: string) => {
    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/admin-command/boarding-master/incidents", {
        method: "POST",
        body: incidentId ? { action: "escalate", incident_id: incidentId } : { action: "log_incident", type: "noise" },
      });
      toast.success(incidentId ? "Incident escalated" : "Incident logged");
      publishSchoolOperationalEvent({
        type: "boarding.incident_logged",
        module: "boarding",
        actorRole: "boarding_master",
        title: incidentId ? "Incident Escalated" : "Incident Logged",
        body: incidentId ? "A boarding incident was escalated." : "A new boarding incident was logged.",
      });
    } catch (e: any) {
      toast.error(e.message || "Failed to process incident");
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Panel title="Dorm Incidents" description="Log boarding-related incidents in hostels or dormitories." icon={ShieldAlert}>
       <div className="mb-4 flex gap-2">
           <button type="button" onClick={() => handleLogIncident()} disabled={isSubmitting} className="rounded-xl bg-rose-50 text-rose-700 border border-rose-200 px-3 py-2 text-sm font-black disabled:opacity-50">
             {isSubmitting ? "Logging..." : "Log Incident"}
           </button>
       </div>
       <DataTable 
        columns={["Ref", "Student(s)", "Dorm", "Type", "Severity", "Status", "Actions"]}
        rows={
          (dashboard?.records || []).filter((r: any) => r.category === 'incident').length > 0
          ? (dashboard?.records || []).filter((r: any) => r.category === 'incident').map((r: any) => [
              `#${r.id.substring(0, 4)}`, r.title, r.owner_name || "-", r.metadata?.type || "-",
              <StatusChip key="s1" label={r.priority} tone={r.priority === 'critical' ? 'danger' : 'warning'}/>,
              r.status,
              <button key="a1" type="button" onClick={() => handleLogIncident(r.id)} disabled={isSubmitting} className="text-[#1D4ED8] font-bold text-xs disabled:opacity-50">Escalate</button>
            ])
          : [
            ["#1042", "Peter Otieno", "St. Joseph", "Noise", <StatusChip key="s1" label="Medium" tone="warning"/>, "Open", <button key="a1" type="button" onClick={() => handleLogIncident("1042")} disabled={isSubmitting} className="text-[#1D4ED8] font-bold text-xs disabled:opacity-50">Escalate</button>],
          ]
        }
      />
    </Panel>
  );
}

function WelfareWorkspace() {
  const { data: dashboard, refetch } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const welfareNotes = (dashboard?.records || []).filter((record: any) => record.category === "welfare_note");

  async function handleAddWelfareNote(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const studentName = String(form.get("student_name") || "").trim();
    const dorm = String(form.get("dorm") || "").trim();
    const concernType = String(form.get("concern_type") || "").trim();
    const referredTo = String(form.get("referred_to") || "").trim();
    const notes = String(form.get("notes") || "").trim();

    if (!studentName || !dorm || !concernType || !notes) {
      toast.error("Student, dorm, concern type, and note are required.");
      return;
    }

    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/boarding/records", {
        method: "POST",
        body: {
          title: studentName,
          category: "welfare_note",
          owner_name: dorm,
          status: referredTo ? "referred" : "open",
          priority: concernType.toLowerCase().includes("sick") || concernType.toLowerCase().includes("medical") ? "high" : "normal",
          notes,
          metadata: {
            dorm,
            concern_type: concernType,
            referred_to: referredTo,
          },
        },
      });
      toast.success("Welfare note saved");
      publishSchoolOperationalEvent({
        type: "boarding.welfare_note_created",
        module: "boarding",
        actorRole: "boarding_master",
        title: "Welfare note saved",
        body: `${studentName} welfare note was saved for ${dorm}.`,
      });
      event.currentTarget.reset();
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Welfare note could not be saved");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Panel title="Health & Welfare" description="Track boarding welfare concerns and sick bay coordination." icon={HeartPulse}>
       <form onSubmit={handleAddWelfareNote} className="mb-5 grid gap-3 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 md:grid-cols-2 xl:grid-cols-5">
        <input name="student_name" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Student name" />
        <input name="dorm" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Dormitory" />
        <input name="concern_type" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Concern type" />
        <input name="referred_to" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Referred to" />
        <textarea name="notes" required rows={2} className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm md:col-span-2 xl:col-span-4" placeholder="Welfare note and follow-up action" />
        <button type="submit" disabled={isSubmitting} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white disabled:opacity-50">
          {isSubmitting ? "Saving..." : "Add Note"}
        </button>
       </form>
       <DataTable 
        columns={["Student", "Dorm", "Concern Type", "Last Note", "Referred To", "Status", "Actions"]}
        rows={welfareNotes.map((record: any) => [
          record.title,
          record.metadata?.dorm || record.owner_name || "-",
          record.metadata?.concern_type || "-",
          record.notes || "-",
          record.metadata?.referred_to || "-",
          <StatusChip key="s1" label={record.status} tone={record.status === "referred" ? "info" : "warning"}/>,
          <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Welfare note", [["Student", String(record.title ?? "-")], ["Dorm", String(record.metadata?.dorm ?? record.owner_name ?? "-")], ["Concern", String(record.metadata?.concern_type ?? "-")], ["Referred to", String(record.metadata?.referred_to ?? "-")], ["Note", String(record.notes ?? "-")]])}>View Note</button>,
        ])}
      />
    </Panel>
  );
}

function MealsWorkspace() {
  return (
    <Panel title="Meals & Dining" description="Tracks boarding meal attendance and special diets." icon={Utensils}>
       <DataTable 
        columns={["Meal", "Date", "Expected", "Present", "On Leave", "Issues", "Actions"]}
        rows={[
          ["Breakfast", "Today", "1,240", "1,190", "45", "0", <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Breakfast dining issue review", [["Meal", "Breakfast"], ["Date", "Today"], ["Expected", "1,240"], ["Present", "1,190"], ["On Leave", "45"], ["Issues", "0"]])}>View Issue</button>],
        ]}
      />
    </Panel>
  );
}

function InspectionsWorkspace() {
  const { data: dashboard, refetch } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const inspections = (dashboard?.records || []).filter((record: any) => record.category === "dorm_inspection");

  async function handleStartInspection(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const inspectionDate = String(form.get("inspection_date") || "").trim();
    const dorm = String(form.get("dorm") || "").trim();
    const room = String(form.get("room") || "").trim();
    const inspector = String(form.get("inspector") || "").trim();
    const score = Number(form.get("score") || 0);
    const issues = String(form.get("issues") || "").trim();

    if (!inspectionDate || !dorm || !room || !inspector || !score) {
      toast.error("Date, dorm, room, inspector, and score are required.");
      return;
    }

    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/boarding/records", {
        method: "POST",
        body: {
          title: `${dorm} ${room} inspection`,
          category: "dorm_inspection",
          owner_name: inspector,
          status: issues ? "requires_follow_up" : "completed",
          priority: issues ? "high" : "normal",
          due_date: inspectionDate,
          metric_count: score,
          notes: issues || "Inspection completed with no reported issue.",
          metadata: {
            inspection_date: inspectionDate,
            dorm,
            room,
            inspector,
            score,
            issues,
          },
        },
      });
      toast.success("Dorm inspection saved");
      event.currentTarget.reset();
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Dorm inspection could not be saved");
    } finally {
      setIsSubmitting(false);
    }
  }

  async function handleCreateRepairRequest(record: any) {
    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/boarding/records", {
        method: "POST",
        body: {
          title: `${record.metadata?.dorm || record.title} repair request`,
          category: "maintenance_request",
          owner_name: record.metadata?.dorm || record.owner_name || null,
          status: "open",
          priority: record.priority === "high" ? "high" : "normal",
          notes: record.metadata?.issues || record.notes || "Repair request raised from dorm inspection.",
          metadata: {
            dorm: record.metadata?.dorm,
            room: record.metadata?.room,
            issue: record.metadata?.issues || record.notes,
            source_inspection_id: record.id,
          },
        },
      });
      toast.success("Repair request created");
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Repair request could not be created");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Panel title="Dorm Inspections" description="Cleanliness checks, room inspections, and hygiene." icon={CheckSquare}>
       <form onSubmit={handleStartInspection} className="mb-5 grid gap-3 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 md:grid-cols-2 xl:grid-cols-6">
        <input name="inspection_date" required type="date" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" aria-label="Inspection date" />
        <input name="dorm" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Dormitory" />
        <input name="room" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Room" />
        <input name="inspector" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Inspector" />
        <input name="score" required type="number" min={0} max={100} className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Score %" />
        <textarea name="issues" rows={2} className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm md:col-span-2 xl:col-span-5" placeholder="Issues or follow-up actions" />
        <button type="submit" disabled={isSubmitting} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white disabled:opacity-50">
          {isSubmitting ? "Saving..." : "Start Inspection"}
        </button>
       </form>
       <DataTable 
        columns={["Date", "Dorm", "Room", "Inspector", "Score", "Issues", "Status", "Actions"]}
        rows={inspections.map((record: any) => [
          record.metadata?.inspection_date || record.due_date || "-",
          record.metadata?.dorm || "-",
          record.metadata?.room || "-",
          record.metadata?.inspector || record.owner_name || "-",
          `${record.metadata?.score || record.metric_count || 0}%`,
          record.metadata?.issues || record.notes || "None",
          <StatusChip key="s1" label={record.status} tone={record.status === "completed" ? "success" : "warning"}/>,
          record.status === "requires_follow_up"
            ? <button key="a1" type="button" disabled={isSubmitting} className="text-[#1D4ED8] font-bold text-xs disabled:opacity-50" onClick={() => handleCreateRepairRequest(record)}>Create Repair</button>
            : <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Dorm inspection", [["Dorm", String(record.metadata?.dorm ?? "-")], ["Room", String(record.metadata?.room ?? "-")], ["Score", String(record.metadata?.score ?? record.metric_count ?? "-")], ["Issues", String(record.metadata?.issues ?? record.notes ?? "None")]])}>View</button>,
        ])}
      />
    </Panel>
  );
}

function MaintenanceWorkspace() {
  const { data: dashboard, refetch } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const repairs = (dashboard?.records || []).filter((record: any) => record.category === "maintenance_request");

  async function handleCreateRepairRequest(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const dorm = String(form.get("dorm") || "").trim();
    const room = String(form.get("room") || "").trim();
    const issue = String(form.get("issue") || "").trim();
    const priority = String(form.get("priority") || "normal").trim();
    const assignedTo = String(form.get("assigned_to") || "").trim();

    if (!dorm || !room || !issue) {
      toast.error("Dorm, room, and issue are required.");
      return;
    }

    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/boarding/records", {
        method: "POST",
        body: {
          title: `${dorm} ${room} repair`,
          category: "maintenance_request",
          owner_name: dorm,
          status: "open",
          priority: priority === "critical" || priority === "high" ? "high" : "normal",
          notes: issue,
          metadata: {
            dorm,
            room,
            issue,
            assigned_to: assignedTo,
          },
        },
      });
      toast.success("Repair request created");
      event.currentTarget.reset();
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Repair request could not be created");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Panel title="Maintenance Requests" description="Report broken beds, doors, windows, lights, etc." icon={Wrench}>
       <form onSubmit={handleCreateRepairRequest} className="mb-5 grid gap-3 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 md:grid-cols-2 xl:grid-cols-5">
        <input name="dorm" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Dormitory" />
        <input name="room" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Room" />
        <input name="issue" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Issue" />
        <select name="priority" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" defaultValue="normal" aria-label="Repair priority">
          <option value="normal">Normal</option>
          <option value="high">High</option>
          <option value="critical">Critical</option>
        </select>
        <input name="assigned_to" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Assigned to" />
        <button type="submit" disabled={isSubmitting} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white disabled:opacity-50 md:col-span-2 xl:col-span-1">
          {isSubmitting ? "Creating..." : "Create Repair Request"}
        </button>
       </form>
       <DataTable 
        columns={["Ref", "Dorm", "Room", "Issue", "Priority", "Assigned To", "Status", "Actions"]}
        rows={repairs.map((record: any) => [
          `REP-${String(record.id || "").slice(0, 4)}`,
          record.metadata?.dorm || record.owner_name || "-",
          record.metadata?.room || "-",
          record.metadata?.issue || record.notes || "-",
          <StatusChip key="p1" label={record.priority === "high" ? "Urgent" : "Normal"} tone={record.priority === "high" ? "danger" : "neutral"}/>,
          record.metadata?.assigned_to || "-",
          record.status,
          <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Repair request", [["Dorm", String(record.metadata?.dorm ?? record.owner_name ?? "-")], ["Room", String(record.metadata?.room ?? "-")], ["Issue", String(record.metadata?.issue ?? record.notes ?? "-")], ["Priority", String(record.priority ?? "-")], ["Assigned To", String(record.metadata?.assigned_to ?? "-")], ["Status", String(record.status ?? "-")]])}>View</button>,
        ])}
      />
    </Panel>
  );
}

function InventoryWorkspace() {
  const { data: dashboard, refetch } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const requests = (dashboard?.records || []).filter((record: any) => record.category === "inventory_request");

  async function handleRequestInventoryItems(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const item = String(form.get("item") || "").trim();
    const quantity = Number(form.get("quantity") || 0);
    const dorm = String(form.get("dorm") || "").trim();
    const reason = String(form.get("reason") || "").trim();

    if (!item || !quantity || !dorm || !reason) {
      toast.error("Item, quantity, dorm, and reason are required.");
      return;
    }

    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/boarding/records", {
        method: "POST",
        body: {
          title: item,
          category: "inventory_request",
          owner_name: dorm,
          status: "requested",
          priority: "normal",
          metric_count: quantity,
          notes: reason,
          metadata: {
            item,
            quantity,
            dorm,
            reason,
          },
        },
      });
      toast.success("Inventory request saved");
      event.currentTarget.reset();
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Inventory request could not be saved");
    } finally {
      setIsSubmitting(false);
    }
  }

  async function handleConfirmInventoryReceipt(record: any) {
    setIsSubmitting(true);
    try {
      await requestDashboardApi(`/api/boarding/records/${record.id}/status`, {
        method: "PATCH",
        body: {
          status: "received",
          notes: `Receipt confirmed for ${record.metadata?.quantity || record.metric_count || "-"} ${record.metadata?.item || record.title}.`,
        },
      });
      toast.success("Inventory receipt confirmed");
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Inventory receipt could not be confirmed");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Panel title="Boarding Inventory" description="Tracks boarding-related items issued to dorms." icon={Package}>
       <form onSubmit={handleRequestInventoryItems} className="mb-5 grid gap-3 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 md:grid-cols-2 xl:grid-cols-5">
        <input name="item" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Item" />
        <input name="quantity" required type="number" min={1} className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Quantity" />
        <input name="dorm" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Dormitory" />
        <input name="reason" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Reason" />
        <button type="submit" disabled={isSubmitting} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white disabled:opacity-50">
          {isSubmitting ? "Requesting..." : "Request Items"}
        </button>
       </form>
       <DataTable 
        columns={["Request Ref", "Item", "Qty", "Dorm", "Reason", "Status", "Actions"]}
        rows={requests.map((record: any) => [
          `INV-${String(record.id || "").slice(0, 4)}`,
          record.metadata?.item || record.title,
          record.metadata?.quantity || record.metric_count || "-",
          record.metadata?.dorm || record.owner_name || "-",
          record.metadata?.reason || record.notes || "-",
          <StatusChip key="s1" label={record.status} tone={record.status === "received" ? "success" : "warning"}/>,
          record.status === "received"
            ? <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Inventory receipt", [["Item", String(record.metadata?.item ?? record.title ?? "-")], ["Quantity", String(record.metadata?.quantity ?? record.metric_count ?? "-")], ["Dorm", String(record.metadata?.dorm ?? record.owner_name ?? "-")], ["Status", String(record.status ?? "-")]])}>View Receipt</button>
            : <button key="a1" type="button" disabled={isSubmitting} className="text-[#1D4ED8] font-bold text-xs disabled:opacity-50" onClick={() => handleConfirmInventoryReceipt(record)}>Confirm Receipt</button>,
        ])}
      />
    </Panel>
  );
}

function VisitorsWorkspace() {
  const { data: dashboard, refetch } = useSchoolQuery<any>("/api/boarding/dashboard");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const gatePasses = (dashboard?.records || []).filter((record: any) => record.category === "gate_pass");

  async function handleCreateGatePass(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const studentName = String(form.get("student_name") || "").trim();
    const guardian = String(form.get("guardian") || "").trim();
    const purpose = String(form.get("purpose") || "").trim();
    const validFrom = String(form.get("valid_from") || "").trim();
    const expectedReturn = String(form.get("expected_return") || "").trim();

    if (!studentName || !guardian || !purpose || !validFrom) {
      toast.error("Student, guardian, purpose, and valid-from time are required.");
      return;
    }

    setIsSubmitting(true);
    try {
      await requestDashboardApi("/api/boarding/records", {
        method: "POST",
        body: {
          title: studentName,
          category: "gate_pass",
          owner_name: guardian,
          status: "active",
          priority: "normal",
          notes: purpose,
          metadata: {
            student_name: studentName,
            guardian,
            purpose,
            valid_from: validFrom,
            expected_return: expectedReturn,
          },
        },
      });
      toast.success("Gate pass created");
      event.currentTarget.reset();
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Gate pass could not be created");
    } finally {
      setIsSubmitting(false);
    }
  }

  async function handleRecordGatePassCheckout(record: any) {
    setIsSubmitting(true);
    try {
      await requestDashboardApi(`/api/boarding/records/${record.id}/status`, {
        method: "PATCH",
        body: {
          status: "checked_out",
          notes: `Checkout recorded for ${record.metadata?.student_name || record.title} with ${record.metadata?.guardian || record.owner_name || "guardian"}.`,
        },
      });
      toast.success("Checkout recorded");
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Gate pass checkout could not be recorded");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Panel title="Visitors & Gate Passes" description="Coordinates parent/guardian boarding visits and student pickups." icon={UserPlus}>
       <form onSubmit={handleCreateGatePass} className="mb-5 grid gap-3 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 md:grid-cols-2 xl:grid-cols-5">
        <input name="student_name" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Student name" />
        <input name="guardian" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Guardian" />
        <input name="purpose" required className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" placeholder="Purpose" />
        <input name="valid_from" required type="datetime-local" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" aria-label="Valid from" />
        <input name="expected_return" type="datetime-local" className="rounded-lg border border-[#D8E0EC] bg-white px-3 py-2 text-sm" aria-label="Expected return" />
        <button type="submit" disabled={isSubmitting} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white disabled:opacity-50 md:col-span-2 xl:col-span-1">
          {isSubmitting ? "Creating..." : "Create Gate Pass"}
        </button>
       </form>
       <DataTable 
        columns={["Pass No.", "Student", "Guardian", "Purpose", "Valid From", "Status", "Actions"]}
        rows={gatePasses.map((record: any) => [
          `GP-${String(record.id || "").slice(0, 4)}`,
          record.metadata?.student_name || record.title,
          record.metadata?.guardian || record.owner_name || "-",
          record.metadata?.purpose || record.notes || "-",
          record.metadata?.valid_from || "-",
          <StatusChip key="s1" label={record.status} tone={record.status === "checked_out" ? "success" : "info"}/>,
          record.status === "checked_out"
            ? <button key="a1" type="button" className="text-[#1D4ED8] font-bold text-xs" onClick={() => openBoardingActionRecord("Gate pass checkout", [["Student", String(record.metadata?.student_name ?? record.title ?? "-")], ["Guardian", String(record.metadata?.guardian ?? record.owner_name ?? "-")], ["Purpose", String(record.metadata?.purpose ?? record.notes ?? "-")], ["Expected Return", String(record.metadata?.expected_return ?? "-")], ["Status", String(record.status ?? "-")]])}>View Checkout</button>
            : <button key="a1" type="button" disabled={isSubmitting} className="text-[#1D4ED8] font-bold text-xs disabled:opacity-50" onClick={() => handleRecordGatePassCheckout(record)}>Record Checkout</button>,
        ])}
      />
    </Panel>
  );
}

function CommunicationWorkspace() {
  return (
    <Panel title="Parent Communication" description="Communicate with parents about boarding matters." icon={MessageSquare}>
       <DataTable 
        columns={["Date", "Student", "Parent", "Channel", "Subject", "Status", "Actions"]}
        rows={[]}
      />
    </Panel>
  );
}

function ApprovalsWorkspace() {
  const { data, refetch } = useSchoolQuery<any>("/api/admin-command/boarding-master/leave-exit");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const requests = (data?.leaveexitList || []).filter((request: any) => request.status === "Pending");

  async function handleApproveBoardingRequest(request: any) {
    setIsSubmitting(true);
    try {
      await requestDashboardApi(`/api/admin-command/boarding-master/leave-exit/${request.id}/approve`, {
        method: "POST",
      });
      toast.success("Boarding approval completed");
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Boarding approval could not be completed");
    } finally {
      setIsSubmitting(false);
    }
  }

  async function handleRejectBoardingRequest(request: any) {
    const reason = window.prompt(`Reason for rejecting ${request.student_name || "this boarding request"}`);
    if (!reason?.trim()) return;

    setIsSubmitting(true);
    try {
      await requestDashboardApi(`/api/admin-command/boarding-master/leave-exit/${request.id}/reject`, {
        method: "POST",
        body: { reason: reason.trim() },
      });
      toast.success("Boarding request rejected");
      await refetch();
    } catch (error: unknown) {
      toast.error(error instanceof Error ? error.message : "Boarding request could not be rejected");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <Panel title="Approvals" description="Boarding approvals in one clean workspace." icon={CheckCircle}>
       <DataTable 
        columns={["Request", "Student/Dorm", "Type", "Required Approver", "Status", "Actions"]}
        rows={requests.map((request: any) => [
          "Leave Request",
          request.student_name || request.hostel || "-",
          request.leave_type || "Boarding leave",
          "Deputy Principal",
          <StatusChip key="s1" label={request.status} tone="warning"/>,
          <span key="a1" className="flex gap-2">
            <button type="button" disabled={isSubmitting} className="text-emerald-700 font-bold text-xs disabled:opacity-50" onClick={() => handleApproveBoardingRequest(request)}>Approve</button>
            <button type="button" disabled={isSubmitting} className="text-rose-700 font-bold text-xs disabled:opacity-50" onClick={() => handleRejectBoardingRequest(request)}>Reject</button>
          </span>,
        ])}
      />
    </Panel>
  );
}

function ReportsWorkspace() {
  const { data: reportsData } = useSchoolQuery<any>("/api/admin-command/boarding-master/reports");
  const reports = asRows<any>(reportsData);

  return (
    <Panel title="Reports & Downloads" description="Generates boarding reports for daily operations and audits." icon={FileText}>
       <div className="grid gap-4 md:grid-cols-3">
         {reports.map((report: any) => (
           <button key={report.id || report.snapshot_id || report.title} type="button" className="rounded-xl border border-[#D8E0EC] bg-white p-4 text-left font-bold text-[#071D49] hover:border-[#071D49] transition" onClick={() => openBoardingActionRecord(report.title || "Boarding report", [["Report", String(report.title ?? "-")], ["Status", String(report.status ?? "Ready")], ["Generated", String(report.created_at ?? "-")]])}>
             {report.title || "Boarding report"}
             <span className="mt-1 block text-xs font-semibold text-[#64748B]">{report.status || report.format || "Snapshot"}</span>
           </button>
         ))}
         {["Daily roll call report", "Missing students report", "Leave-out report", "Late return trend", "Dorm repairs report"].map(r => (
           <button key={r} type="button" className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-left font-bold text-[#071D49] hover:border-[#071D49] transition" onClick={() => generateBoardingReport(r)}>{r}</button>
         ))}
       </div>
    </Panel>
  );
}

function SettingsWorkspace() {
  return (
    <Panel title="Boarding Settings" description="Controls boarding-specific rules and notification rules." icon={Settings}>
       <div className="grid gap-4 md:grid-cols-2">
         <div className="rounded-xl border border-[#D8E0EC] p-4">
           <h3 className="font-bold text-[#071D49] mb-2">Notification Rules</h3>
           <label className="flex items-center gap-2 text-sm text-[#334155] mb-2"><input type="checkbox" defaultChecked /> Notify parent for late return</label>
           <label className="flex items-center gap-2 text-sm text-[#334155]"><input type="checkbox" defaultChecked /> Notify Deputy for missing roll call</label>
         </div>
       </div>
    </Panel>
  );
}

// Simple Layout Components

export function BoardingMasterCommandCenter({ routeMode, activeSection }: { routeMode: RouteMode; activeSection?: string }) {
  const [activeView, setActiveView] = useState<ViewId>(
    (activeSection && activeSection !== "dashboard" ? activeSection : "overview") as ViewId
  );
  const [searchTerm, setSearchTerm] = useState("");
  const { data: searchAllocationData } = useSchoolQuery<any>("/api/admin-command/boarding-master/allocation");
  const { data: searchIncidentsData } = useSchoolQuery<any>("/api/admin-command/boarding-master/incidents");
  const searchRecords: SearchRecord[] = [
    ...asRows<any>(searchAllocationData?.allocationList ?? searchAllocationData).slice(0, 8).map((record: any) => ({
      id: `allocation-${record.id || record.student_id}`,
      label: record.student_name || record.student_id?.substring?.(0, 8) || "Boarding allocation",
      detail: `${record.hostel || record.hostel_name || "Hostel not set"} | ${record.room_number || "room not set"} | ${record.status || "active"}`,
      view: "register" as ViewId,
    })),
    ...asRows<any>(searchIncidentsData?.incidentsList ?? searchIncidentsData).slice(0, 8).map((record: any) => ({
      id: `incident-${record.id}`,
      label: record.title || record.incident_type || "Boarding incident",
      detail: `${record.status || "open"} | ${record.severity || "normal"}`,
      view: "incidents" as ViewId,
    })),
  ];

  const searchResults = searchTerm.trim()
    ? searchRecords.filter((record) => `${record.label} ${record.detail}`.toLowerCase().includes(searchTerm.toLowerCase()))
    : [];

  useEffect(() => {
    function handleDashboardAction(event: Event) {
      const message = (event as CustomEvent<string>).detail;
      if (message) {
        toast.info(message);
      }
    }
    window.addEventListener("myshule-dashboard-action", handleDashboardAction);
    return () => window.removeEventListener("myshule-dashboard-action", handleDashboardAction);
  }, []);

  function openView(view: ViewId) {
    setActiveView(view);
    window.history.replaceState(null, "", buildSchoolSectionHref("boarding-master", view, routeMode ?? "hosted"));
  }

  function openSearchRecord(record: SearchRecord) {
    setActiveView(record.view);
    window.history.replaceState(null, "", buildSchoolSectionHref("boarding-master", record.view, routeMode ?? "hosted"));
    setSearchTerm("");
    toast.success(`Opened search result: ${record.label}`);
  }

  return (
    <div className="flex min-h-screen bg-[#F3F6FA]">
      {/* Sidebar */}
      <aside className="hidden h-screen w-[260px] overflow-y-auto bg-[#071D49] p-4 text-white shadow-[0_24px_70px_rgba(7,29,73,0.28)] lg:block shrink-0">
        <div className="rounded-2xl border border-white/10 bg-white/5 p-4 mb-6">
          <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-100/70">MyShule</p>
          <h2 className="mt-2 text-xl font-black">Boarding Master</h2>
          <p className="mt-2 text-sm leading-6 text-white/65">All Dormitories oversight.</p>
        </div>
        <nav className="space-y-1" aria-label="Boarding master navigation">
          {navItems.map((item, index) => {
            const showGroup = item.group !== navItems[index - 1]?.group;
            const Icon = item.icon;
            return (
              <div key={`${item.group}-${item.label}`}>
                {showGroup ? <p className="px-3 pb-2 pt-4 text-[10px] font-black uppercase tracking-[0.2em] text-white/40">{item.group}</p> : null}
                <button
                  type="button"
                  onClick={() => openView(item.id)}
                  className={cn(
                    "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-white/70 transition hover:bg-white/10 hover:text-white",
                    activeView === item.id && "bg-white/15 text-white shadow-[inset_4px_0_0_#38BDF8]",
                  )}
                >
                  <Icon className="h-4 w-4" aria-hidden="true" />
                  {item.label}
                </button>
              </div>
            );
          })}
        </nav>
      </aside>

      {/* Main Area */}
      <main className="flex-1 min-w-0 flex flex-col h-screen overflow-hidden">
        {/* Topbar */}
        <header className="sticky top-0 z-20 border-b border-[#D8E0EC] bg-white/90 px-4 py-3 backdrop-blur shrink-0">
          <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
            <div className="flex items-center gap-3">
              <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#071D49] text-xs font-black text-white">BM</div>
              <div>
                <h1 className="text-lg font-black text-[#071D49]">Good Evening, Mr. Otieno</h1>
                <p className="text-xs font-bold text-[#64748B]">Boarding Master Ã¢â‚¬Â¢ Term 2, 2026 Ã¢â‚¬Â¢ Week 6 Ã¢â‚¬Â¢ All Dormitories</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
               <div className="relative w-64 hidden md:block">
                 <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#94A3B8]" />
                 <input 
                   value={searchTerm}
                   onChange={(e) => setSearchTerm(e.target.value)}
                   className="h-10 w-full rounded-xl border border-[#D8E0EC] pl-9 pr-4 text-sm outline-none focus:border-[#071D49]" 
                   placeholder="Search student, adm, dorm, room..." 
                 />
                 {searchTerm.trim() && searchResults.length > 0 && (
                   <div className="absolute top-[calc(100%+8px)] left-0 w-full bg-white border border-[#D8E0EC] rounded-xl shadow-xl z-30 p-2">
                     {searchResults.map(r => (
                       <button key={r.id} type="button" onClick={() => openSearchRecord(r)} className="w-full text-left p-2 hover:bg-[#F8FAFC] rounded-lg">
                         <p className="font-bold text-[#071D49] text-sm">{r.label}</p>
                         <p className="text-xs text-[#64748B]">{r.detail}</p>
                       </button>
                     ))}
                   </div>
                 )}
               </div>
                   <StatusChip label="Current school" tone="info" />
               <div className="flex items-center gap-2">
                 <TaskQueue />
                 <ApprovalInbox currentUserId="school" />
                 <NotificationBell />
               </div>
               <button type="button" onClick={() => openView("roll-call")} className="inline-flex h-10 items-center justify-center rounded-xl bg-[#071D49] px-4 text-sm font-black text-white">Start Roll Call</button>
            </div>
          </div>
          {/* Mobile Nav Selector */}
          <div className="mt-3 lg:hidden">
            <select
              className="h-10 w-full rounded-xl border border-[#D8E0EC] bg-white px-3 text-sm font-bold text-[#071D49] outline-none"
              value={activeView}
              onChange={(e) => openView(e.target.value as ViewId)}
            >
              {navItems.map((item) => (
                <option key={item.id} value={item.id}>{item.label}</option>
              ))}
            </select>
          </div>
        </header>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-4 lg:p-6">
          {activeView === "overview" && <OverviewWorkspace onNavigate={openView} />}
          {activeView === "register" && <RegisterWorkspace />}
          {activeView === "dorms" && <DormsWorkspace />}
          {activeView === "beds" && <BedsWorkspace />}
          {activeView === "roll-call" && <RollCallWorkspace />}
          {activeView === "leave" && <LeaveWorkspace />}
          {activeView === "late-returns" && <LateReturnsWorkspace />}
          {activeView === "duty" && <DutyWorkspace />}
          {activeView === "incidents" && <IncidentsWorkspace />}
          {activeView === "welfare" && <WelfareWorkspace />}
          {activeView === "meals" && <MealsWorkspace />}
          {activeView === "inspections" && <InspectionsWorkspace />}
          {activeView === "maintenance" && <MaintenanceWorkspace />}
          {activeView === "inventory" && <InventoryWorkspace />}
          {activeView === "visitors" && <VisitorsWorkspace />}
          {activeView === "communication" && <CommunicationWorkspace />}
          {activeView === "approvals" && <ApprovalsWorkspace />}
          {activeView === "reports" && <ReportsWorkspace />}
          {activeView === "settings" && <SettingsWorkspace />}
        </div>
      </main>
      
    </div>
  );
}
