// GENERATED BY scaffold_grade_master.js
"use client";

import { useState, useEffect, type FormEvent, type ReactNode } from "react";
import {
  AlertTriangle,
  Banknote,
  Bell,
  BookMarked,
  BookOpenCheck,
  CalendarClock,
  CalendarDays,
  CheckSquare,
  ChevronDown,
  ClipboardCheck,
  FileText,
  HeartPulse,
  LayoutDashboard,
  MessageCircle,
  MoreHorizontal,
  Network,
  Search,
  Settings,
  ShieldAlert,
  TrendingUp,
  UserCheck,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

import { ApprovalInbox } from "@/components/shared/approval-inbox";
import { NotificationBell } from "@/components/shared/notification-bell";
import { TaskQueue } from "@/components/shared/task-queue";
import { WorkflowToast } from "@/components/shared/workflow-toast";
import { getCurrentSchoolId, publishSchoolOperationalEvent } from "@/lib/school/school-operational-store";

type GradeRouteMode = "hosted" | "public";
type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type GradeView = "overview" | "learners" | "streams" | "attendance" | "academics" | "exams" | "discipline" | "welfare" | "fees" | "communication" | "meetings" | "timetable" | "assignments" | "requests" | "reports" | "notifications" | "teaching" | "settings";

type NavItem = {
  id: GradeView;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard, group: "Command" },
  { id: "learners", label: "Learners", icon: Users, group: "Grade Operations" },
  { id: "streams", label: "Streams & Class Teachers", icon: Network, group: "Grade Operations" },
  { id: "attendance", label: "Attendance Monitor", icon: UserCheck, group: "Grade Operations" },
  { id: "academics", label: "Academic Progress", icon: TrendingUp, group: "Academics" },
  { id: "exams", label: "Exams & Report Readiness", icon: ClipboardCheck, group: "Academics" },
  { id: "discipline", label: "Discipline & Behaviour", icon: ShieldAlert, group: "Student Welfare" },
  { id: "welfare", label: "Welfare & Counselling", icon: HeartPulse, group: "Student Welfare" },
  { id: "fees", label: "Fees Watchlist", icon: Banknote, group: "Administration" },
  { id: "communication", label: "Parent Communication", icon: MessageCircle, group: "Communication" },
  { id: "meetings", label: "Meetings & Follow-ups", icon: CalendarDays, group: "Communication" },
  { id: "timetable", label: "Timetable & Lessons", icon: CalendarClock, group: "Planning" },
  { id: "assignments", label: "Assignments & Homework", icon: BookOpenCheck, group: "Planning" },
  { id: "requests", label: "Requests & Approvals", icon: CheckSquare, group: "Resources" },
  { id: "reports", label: "Reports & Downloads", icon: FileText, group: "Resources" },
  { id: "notifications", label: "Notifications", icon: Bell, group: "System" },
  { id: "teaching", label: "My Teaching Workspace", icon: BookMarked, group: "System" },
  { id: "settings", label: "Settings", icon: Settings, group: "System" },
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

const gradeSearchRecords = [
  { id: "student-brian", label: "Brian Otieno", detail: "ADM-2041 | Form 2 Blue | absent today", view: "learners" },
  { id: "guardian-wanjiku", label: "Mrs. Wanjiku", detail: "Guardian message about fees", view: "communication" },
] satisfies Array<{ id: string; label: string; detail: string; view: GradeView }>;

type GradeSearchRecord = (typeof gradeSearchRecords)[number];

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function ProgressBar({ value, tone = "info" }: { value: number; tone?: Tone }) {
  return (
    <div className="h-2 rounded-full bg-[#E2E8F0] overflow-hidden mt-2">
      <div className={cn("h-full rounded-full transition-all duration-500", toneClasses[tone].dot)} style={{ width: `${Math.max(0, Math.min(100, value))}%` }} />
    </div>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions}
      </div>
      {children}
    </section>
  );
}

function DataTable({
  title,
  columns,
  rows,
}: {
  title?: string;
  columns: string[];
  rows: ReactNode[][];
}) {
  return (
    <div className="overflow-hidden rounded-2xl border border-[#D8E0EC] bg-white">
      {title && (
        <div className="border-b border-[#D8E0EC] bg-[#F8FAFC] px-4 py-3">
          <h3 className="text-sm font-black uppercase tracking-[0.14em] text-[#071D49]">{title}</h3>
        </div>
      )}
      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead className="bg-[#EEF2FF] text-xs uppercase tracking-[0.12em] text-[#64748B]">
            <tr>
              {columns.map((column, i) => (
                <th key={i} className="px-4 py-3 font-black whitespace-nowrap">{column}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-[#E2E8F0]">
            {rows.map((row, i) => (
              <tr key={i} className="transition hover:bg-[#F8FAFC]">
                {row.map((cell, j) => (
                  <td key={j} className="px-4 py-3 font-semibold text-[#334155] whitespace-nowrap">
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
            {rows.length === 0 && (
              <tr>
                <td colSpan={columns.length} className="px-4 py-8 text-center text-[#64748B]">No records found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function EmptyState({ message, actionText, onAction }: { message: string, actionText: string, onAction: () => void }) {
  return (
    <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-[#D8E0EC] bg-[#F8FAFC] p-12 text-center">
      <AlertTriangle className="h-12 w-12 text-[#94A3B8] mb-4" />
      <p className="text-[#071D49] font-bold mb-4">{message}</p>
      <button onClick={onAction} className="rounded-xl bg-[#071D49] px-4 py-2 text-sm font-black text-white">{actionText}</button>
    </div>
  );
}

// Custom Drawers / Modals
function LearnerProfileDrawer({ learnerId, onClose }: { learnerId: string | null, onClose: () => void }) {
  if (!learnerId) return null;
  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-[#071D49]/20 backdrop-blur-sm">
      <div className="w-full max-w-xl bg-white h-full shadow-2xl flex flex-col border-l border-[#D8E0EC] overflow-y-auto">
        <header className="sticky top-0 bg-white/95 backdrop-blur z-10 border-b border-[#D8E0EC] p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
             <div className="h-12 w-12 rounded-full bg-[#071D49] text-white flex items-center justify-center font-black">
               {learnerId.substring(0,2).toUpperCase()}
             </div>
             <div>
               <h2 className="text-lg font-black text-[#071D49]">{learnerId}</h2>
               <p className="text-xs font-semibold text-[#64748B]">ADM: 2451 | Form 2 Blue</p>
             </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-[#F3F6FA] rounded-full transition text-[#64748B]">
            <X className="h-5 w-5" />
          </button>
        </header>
        <div className="p-4 space-y-6">
          <section className="flex flex-wrap gap-2">
            <button className="rounded-full bg-[#071D49] px-3 py-1.5 text-xs font-black text-white">Message Parent</button>
            <button className="rounded-full border border-[#D8E0EC] px-3 py-1.5 text-xs font-black text-[#071D49]">Record Concern</button>
            <button className="rounded-full border border-[#D8E0EC] px-3 py-1.5 text-xs font-black text-[#071D49]">Schedule Meeting</button>
            <button className="rounded-full border border-rose-200 text-rose-700 bg-rose-50 px-3 py-1.5 text-xs font-black">Escalate to Deputy</button>
          </section>
          <div className="grid grid-cols-2 gap-3">
             <div className="rounded-xl border border-[#D8E0EC] p-4 text-center bg-[#F8FAFC]">
               <p className="text-xs font-bold text-[#64748B] mb-1">Attendance</p>
               <p className="text-2xl font-black text-[#071D49]">78%</p>
               <StatusChip label="Risk" tone="danger" />
             </div>
             <div className="rounded-xl border border-[#D8E0EC] p-4 text-center bg-[#F8FAFC]">
               <p className="text-xs font-bold text-[#64748B] mb-1">Academic Average</p>
               <p className="text-2xl font-black text-[#071D49]">54%</p>
               <StatusChip label="Below Target" tone="warning" />
             </div>
          </div>
          {/* Mock tabs area */}
          <div className="border-b border-[#D8E0EC] flex gap-4 text-sm font-bold text-[#64748B]">
            <span className="border-b-2 border-[#071D49] text-[#071D49] pb-2">Overview</span>
            <span className="pb-2 cursor-pointer hover:text-[#071D49]">Attendance</span>
            <span className="pb-2 cursor-pointer hover:text-[#071D49]">Academics</span>
            <span className="pb-2 cursor-pointer hover:text-[#071D49]">Discipline</span>
            <span className="pb-2 cursor-pointer hover:text-[#071D49]">Welfare</span>
          </div>
          <div className="space-y-4">
             <p className="text-sm text-[#64748B]">This learner has been flagged for Academic + Attendance risk. The parent was contacted last Tuesday.</p>
          </div>
        </div>
      </div>
    </div>
  );
}

// Workspaces Implementations

function OverviewWorkspace({ onNavigate }: { onNavigate: (view: GradeView) => void }) {
  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-3 lg:grid-cols-4">
         <button onClick={() => onNavigate('learners')} className="text-left rounded-xl border border-[#D8E0EC] bg-white p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-[#64748B] uppercase tracking-wider">Total Learners</p>
           <p className="text-3xl font-black text-[#071D49] mt-2">420</p>
         </button>
         <button onClick={() => onNavigate('attendance')} className="text-left rounded-xl border border-[#D8E0EC] bg-white p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-[#64748B] uppercase tracking-wider">Present Today</p>
           <p className="text-3xl font-black text-[#071D49] mt-2">398</p>
         </button>
         <button onClick={() => onNavigate('attendance')} className="text-left rounded-xl border border-rose-200 bg-rose-50 p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-rose-700 uppercase tracking-wider">Absent Today</p>
           <p className="text-3xl font-black text-rose-900 mt-2">14</p>
         </button>
         <button onClick={() => onNavigate('academics')} className="text-left rounded-xl border border-amber-200 bg-amber-50 p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-amber-700 uppercase tracking-wider">Academic Risk</p>
           <p className="text-3xl font-black text-amber-900 mt-2">26</p>
         </button>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Panel title="Today's Form/Grade Health" icon={HeartPulse}>
          <DataTable 
            columns={["Metric", "Count", "Affected Streams", "Action"]}
            rows={[
              ["Absent Learners", "14", "Form 2 Blue, Form 2 Red", <button key="1" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('attendance')}>View Details</button>],
              ["New Incidents", "2", "Form 2 Green", <button key="2" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('discipline')}>Escalate</button>],
              ["Parent Meetings Due", "3", "Form 2 Blue", <button key="3" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('meetings')}>View Details</button>],
            ]}
          />
        </Panel>

        <Panel title="Urgent Learner Watchlist" icon={AlertTriangle}>
          <DataTable 
            columns={["Learner", "Reason", "Risk Level", "Action"]}
            rows={[
              ["Brian Otieno (2451)", "Repeated absence", <StatusChip key="c1" label="High" tone="danger"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Open Profile</button>],
              ["Mary Wanjiku (2211)", "Discipline concern", <StatusChip key="c2" label="Medium" tone="warning"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Record Follow-up</button>],
            ]}
          />
        </Panel>
      </div>

      <Panel title="Stream Comparison" icon={Network}>
        <DataTable 
          columns={["Stream", "Class Teacher", "Total", "Absent", "Avg Score", "Concerns", "Actions"]}
          rows={[
            ["Form 2 Blue", "Mr. Kamau", "140", "5", "68%", "2", <button key="v1" onClick={() => onNavigate('streams')} className="text-[#1D4ED8] font-bold text-xs">Open Stream</button>],
            ["Form 2 Green", "Mrs. Njeri", "142", "2", "72%", "0", <button key="v2" onClick={() => onNavigate('streams')} className="text-[#1D4ED8] font-bold text-xs">Open Stream</button>],
            ["Form 2 Red", "Mr. Otieno", "138", "7", "62%", "4", <button key="v3" onClick={() => onNavigate('streams')} className="text-[#1D4ED8] font-bold text-xs">Open Stream</button>],
          ]}
        />
      </Panel>
    </div>
  );
}

function LearnersWorkspace({ onSelectLearner }: { onSelectLearner: (id: string) => void }) {
  return (
    <Panel 
      title="Learners" 
      description="Manage and monitor all learners in the assigned grade/form." 
      icon={Users}
      actions={
        <div className="flex gap-2">
           <button className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-black text-[#071D49]">Export</button>
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white">Add Note</button>
        </div>
      }
    >
      <div className="mb-4 flex gap-2 overflow-x-auto pb-2">
         <select className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-semibold bg-white"><option>All Streams</option></select>
         <select className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-semibold bg-white"><option>Attendance Risk</option></select>
         <select className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-semibold bg-white"><option>Academic Risk</option></select>
      </div>
      <DataTable 
        columns={["ADM", "Learner", "Stream", "Attendance", "Average", "Risk", "Actions"]}
        rows={[
          ["2451", "Brian Otieno", "Form 2 Blue", "78%", "54%", <StatusChip key="r1" label="High" tone="danger" />, <button key="a1" onClick={() => onSelectLearner("Brian Otieno")} className="text-[#1D4ED8] font-bold text-xs">Open Profile</button>],
          ["2211", "Mary Wanjiku", "Form 2 Red", "95%", "88%", <StatusChip key="r2" label="Low" tone="success" />, <button key="a2" onClick={() => onSelectLearner("Mary Wanjiku")} className="text-[#1D4ED8] font-bold text-xs">Open Profile</button>],
          ["2399", "John Kamau", "Form 2 Green", "92%", "71%", <StatusChip key="r3" label="Medium" tone="warning" />, <button key="a3" onClick={() => onSelectLearner("John Kamau")} className="text-[#1D4ED8] font-bold text-xs">Open Profile</button>],
        ]}
      />
    </Panel>
  );
}

function StreamsWorkspace() {
  return (
    <Panel title="Streams & Class Teachers" description="Coordinate all class teachers under the form/grade." icon={Network}>
      <DataTable 
        columns={["Stream", "Class Teacher", "Learners", "Present", "Open Concerns", "Last Update", "Actions"]}
        rows={[
          ["Form 2 Blue", "Mr. Kamau", "140", "135", "2", "Today, 08:00 AM", <button key="m1" className="text-[#1D4ED8] font-bold text-xs">Message Teacher</button>],
          ["Form 2 Green", "Mrs. Njeri", "142", "140", "0", "Today, 08:15 AM", <button key="m2" className="text-[#1D4ED8] font-bold text-xs">Message Teacher</button>],
          ["Form 2 Red", "Mr. Otieno", "138", "131", "4", "Yesterday, 04:00 PM", <button key="m3" className="text-[#1D4ED8] font-bold text-xs">Request Update</button>],
        ]}
      />
    </Panel>
  );
}

function AttendanceWorkspace() {
  return (
    <Panel title="Attendance Monitor" description="Monitor completion and follow up on absenteeism across streams." icon={UserCheck}>
      <div className="grid gap-4 md:grid-cols-4 mb-6">
         <div className="rounded-xl bg-[#F8FAFC] border border-[#D8E0EC] p-4 text-center"><p className="text-2xl font-black text-[#071D49]">14</p><p className="text-xs font-bold text-[#64748B]">Absent Today</p></div>
         <div className="rounded-xl bg-[#F8FAFC] border border-[#D8E0EC] p-4 text-center"><p className="text-2xl font-black text-[#071D49]">6</p><p className="text-xs font-bold text-[#64748B]">Repeated Absentees</p></div>
         <div className="rounded-xl bg-rose-50 border border-rose-200 p-4 text-center"><p className="text-2xl font-black text-rose-700">1</p><p className="text-xs font-bold text-rose-700">Unmarked Streams</p></div>
      </div>
      <DataTable 
        columns={["Learner", "Stream", "Status", "Reason", "Absence Count", "Actions"]}
        rows={[
          ["Brian Otieno", "Form 2 Blue", <StatusChip key="s1" label="Absent" tone="danger"/>, "Unknown", "4 this term", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Message Parent</button>],
          ["Susan Njuguna", "Form 2 Red", <StatusChip key="s2" label="Late" tone="warning"/>, "Transport", "2 this term", <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Record Reason</button>],
        ]}
      />
    </Panel>
  );
}

function AcademicsWorkspace() {
  return (
    <Panel title="Academic Progress" description="Monitor academic performance trends across the entire form/grade." icon={TrendingUp}>
      <div className="grid gap-4 md:grid-cols-2 mb-6">
        <div className="rounded-xl border border-[#D8E0EC] p-4">
           <h3 className="font-bold text-[#071D49] mb-2">Form Average Trend</h3>
           <p className="text-3xl font-black text-[#071D49]">67.5%</p>
           <ProgressBar value={67.5} tone="success" />
        </div>
        <div className="rounded-xl border border-[#D8E0EC] p-4">
           <h3 className="font-bold text-[#071D49] mb-2">Subject With Highest Risk</h3>
           <p className="text-xl font-black text-rose-700">Mathematics</p>
           <p className="text-sm font-semibold text-[#64748B] mt-1">18 learners below target</p>
        </div>
      </div>
      <DataTable 
        columns={["Subject", "Teacher", "Average", "Missing Marks", "At-Risk", "Actions"]}
        rows={[
          ["Mathematics", "Mr. Kiplagat", "52%", "3", "18", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Request Intervention</button>],
          ["English", "Mrs. Wamaitha", "74%", "0", "4", <button key="a2" className="text-[#1D4ED8] font-bold text-xs">View Learners</button>],
        ]}
      />
    </Panel>
  );
}

function ExamsWorkspace() {
  return (
    <Panel title="Exams & Report Readiness" description="Monitor whether report cards are ready for their grade/form." icon={ClipboardCheck}>
      <DataTable 
        columns={["Stream", "Marks Status", "Teacher Comments", "Class Teacher", "Readiness", "Actions"]}
        rows={[
          ["Form 2 Blue", "100%", "95%", "100%", <StatusChip key="s1" label="Missing Comments" tone="warning"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Request Comments</button>],
          ["Form 2 Green", "100%", "100%", "100%", <StatusChip key="s2" label="Ready" tone="success"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Print Drafts</button>],
          ["Form 2 Red", "92%", "80%", "40%", <StatusChip key="s3" label="Missing Marks" tone="danger"/>, <button key="a3" className="text-[#1D4ED8] font-bold text-xs">Message Teacher</button>],
        ]}
      />
    </Panel>
  );
}

function DisciplineWorkspace() {
  return (
    <Panel title="Discipline & Behaviour" description="Monitors discipline issues within the form/grade." icon={ShieldAlert}>
       <div className="mb-4 flex gap-2">
           <button className="rounded-xl bg-rose-50 border border-rose-200 text-rose-700 px-3 py-2 text-sm font-black">Record Incident</button>
       </div>
       <DataTable 
        columns={["Case No.", "Learner", "Stream", "Severity", "Status", "Actions"]}
        rows={[
          ["#1042", "Peter Otieno", "Form 2 Red", <StatusChip key="s1" label="High" tone="danger"/>, "Open", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Escalate to Deputy</button>],
          ["#1041", "Sarah K", "Form 2 Blue", <StatusChip key="s2" label="Medium" tone="warning"/>, "Parent Notified", <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Mark Resolved</button>],
        ]}
      />
    </Panel>
  );
}

function WelfareWorkspace() {
  return (
    <Panel title="Welfare & Counselling" description="Tracks learner welfare concerns without exposing sensitive details." icon={HeartPulse}>
       <DataTable 
        columns={["Learner", "Stream", "Concern Type", "Priority", "Assigned To", "Status", "Actions"]}
        rows={[
          ["John Doe", "Form 2 Green", "Academic stress", <StatusChip key="p1" label="Medium" tone="warning"/>, "Counsellor", "Follow-up Due", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Notify Class Teacher</button>],
        ]}
      />
    </Panel>
  );
}

function FeesWorkspace() {
  return (
    <Panel title="Fees Watchlist" description="Read-only fee supervision view with parent follow-up tools." icon={Banknote}>
       <DataTable 
        columns={["Learner", "Stream", "Fee Balance", "Promise Date", "Report Block", "Actions"]}
        rows={[
          ["Brian Otieno", "Form 2 Blue", "KES 15,000", "2026-06-15", <StatusChip key="b1" label="Blocked" tone="danger"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Message Parent</button>],
        ]}
      />
    </Panel>
  );
}

function CommunicationWorkspace() {
  return (
    <Panel title="Parent Communication" description="Where the Grade/Form Master communicates with parents." icon={MessageCircle}>
       <div className="mb-4 flex gap-2">
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white">Send Bulk Notice</button>
           <button className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-black text-[#071D49]">Message Templates</button>
       </div>
       <DataTable 
        columns={["Learner", "Parent/Guardian", "Last Contacted", "Last Message Type", "Status", "Actions"]}
        rows={[
          ["Brian Otieno", "Mr. Otieno", "Today", "Attendance concern", <StatusChip key="s1" label="Delivered" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Send Message</button>],
        ]}
      />
    </Panel>
  );
}

function MeetingsWorkspace() {
  return (
    <Panel title="Meetings & Follow-ups" description="Follow-up command center for parent meetings, learner reviews." icon={CalendarDays}>
       <DataTable 
        columns={["Meeting Title", "Learner", "Date", "Time", "Status", "Actions"]}
        rows={[
          ["Attendance Review", "Brian Otieno", "2026-06-12", "10:00 AM", <StatusChip key="s1" label="Scheduled" tone="info"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Reschedule</button>],
        ]}
      />
    </Panel>
  );
}

function TimetableWorkspace() {
  return (
    <Panel title="Timetable & Lessons" description="Monitors whether learners are receiving lessons as planned." icon={CalendarClock}>
       <DataTable 
        columns={["Day", "Time", "Stream", "Subject", "Teacher", "Status", "Actions"]}
        rows={[
          ["Today", "08:00 AM", "Form 2 Blue", "Mathematics", "Mr. Kiplagat", <StatusChip key="s1" label="Completed" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">View Log</button>],
          ["Today", "09:20 AM", "Form 2 Red", "English", "Mrs. Wamaitha", <StatusChip key="s2" label="Missed" tone="danger"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Report Missed Lesson</button>],
        ]}
      />
    </Panel>
  );
}

function AssignmentsWorkspace() {
  return (
    <Panel title="Assignments & Homework" description="Monitors whether learners are receiving and submitting work." icon={BookOpenCheck}>
       <DataTable 
        columns={["Assignment", "Subject", "Stream", "Due Date", "Missing Count", "Actions"]}
        rows={[
          ["Algebra Ch 4", "Mathematics", "Form 2 Blue", "Yesterday", "12", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Export Missing List</button>],
        ]}
      />
    </Panel>
  );
}

function RequestsWorkspace() {
  return (
    <Panel title="Requests & Approvals" description="Handles requests that the Grade/Form Master can raise or review." icon={CheckSquare}>
       <DataTable 
        columns={["Request No.", "Type", "Learner/Stream", "Assigned To", "Status", "Actions"]}
        rows={[
          ["REQ-992", "Deputy intervention", "Peter Otieno", "Deputy Principal", <StatusChip key="s1" label="Pending" tone="warning"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Add Comment</button>],
        ]}
      />
    </Panel>
  );
}

function ReportsWorkspace() {
  return (
    <Panel title="Reports & Downloads" description="Printable and exportable grade/form reports." icon={FileText}>
       <div className="grid gap-4 md:grid-cols-3">
         {["Grade/Form learner list", "Daily attendance summary", "Report-card readiness", "Stream comparison", "Fee arrears watchlist"].map(r => (
           <button key={r} className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-left font-bold text-[#071D49] hover:border-[#071D49] transition">{r}</button>
         ))}
       </div>
    </Panel>
  );
}

function NotificationsWorkspace() {
  return (
    <Panel title="Notifications" description="Inbox for tasks and alerts related to the assigned form/grade." icon={Bell}>
       <DataTable 
        columns={["Type", "Message", "Priority", "Status", "Actions"]}
        rows={[
          ["System alert", "Form 2 Red unmarked attendance", <StatusChip key="p1" label="High" tone="danger"/>, "Unread", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Resolve</button>],
        ]}
      />
    </Panel>
  );
}

function TeachingWorkspace() {
  return (
    <Panel title="My Teaching Workspace" description="Teaching responsibilities for assigned subjects." icon={BookMarked}>
       <div className="flex flex-col items-center justify-center py-12 text-center border border-dashed border-[#D8E0EC] rounded-xl bg-[#F8FAFC]">
         <BookMarked className="h-12 w-12 text-[#94A3B8] mb-4" />
         <p className="text-lg font-bold text-[#071D49]">This is a shortcut to your Teacher Dashboard.</p>
         <p className="mt-2 text-sm text-[#64748B]">You will be taken to your teaching classes (e.g. Form 3 Blue Mathematics).</p>
         <button className="mt-4 rounded-xl bg-[#071D49] px-4 py-2 text-sm font-black text-white">Go to Teacher Dashboard</button>
       </div>
    </Panel>
  );
}

function SettingsWorkspace() {
  return (
    <Panel title="Settings" description="Dashboard preferences and limited form/grade workflow settings." icon={Settings}>
       <div className="grid gap-4 md:grid-cols-2">
         <div className="rounded-xl border border-[#D8E0EC] p-4">
           <h3 className="font-bold text-[#071D49] mb-2">Notification Preferences</h3>
           <label className="flex items-center gap-2 text-sm text-[#334155] mb-2"><input type="checkbox" defaultChecked /> Enable daily attendance digest</label>
           <label className="flex items-center gap-2 text-sm text-[#334155]"><input type="checkbox" defaultChecked /> Enable parent reply alerts</label>
         </div>
         <div className="rounded-xl border border-[#D8E0EC] p-4">
           <h3 className="font-bold text-[#071D49] mb-2">Default Filters</h3>
           <select className="w-full rounded-lg border border-[#D8E0EC] p-2 text-sm"><option>All Streams</option></select>
         </div>
       </div>
    </Panel>
  );
}

// Simple Layout Components

export function GradeMasterCommandCenter({ routeMode }: { routeMode: GradeRouteMode }) {
  const [activeView, setActiveView] = useState<GradeView>("overview");
  const [searchTerm, setSearchTerm] = useState("");
  const [notice, setNotice] = useState("");
  const [selectedLearner, setSelectedLearner] = useState<string | null>(null);

  const searchResults = searchTerm.trim()
    ? gradeSearchRecords.filter((record) => `${record.label} ${record.detail}`.toLowerCase().includes(searchTerm.toLowerCase()))
    : [];

  useEffect(() => {
    function handleDashboardAction(event: Event) {
      const message = (event as CustomEvent<string>).detail;
      if (message) {
        setNotice(message);
        setTimeout(() => setNotice(""), 5000);
      }
    }
    window.addEventListener("myshule-dashboard-action", handleDashboardAction);
    return () => window.removeEventListener("myshule-dashboard-action", handleDashboardAction);
  }, []);

  function openView(view: GradeView) {
    setActiveView(view);
  }

  function openSearchRecord(record: GradeSearchRecord) {
    setActiveView(record.view);
    setSearchTerm("");
    setNotice(`Opened search result: ${record.label}`);
    setTimeout(() => setNotice(""), 5000);
  }

  return (
    <div className="flex min-h-screen bg-[#F3F6FA]">
      {/* Sidebar */}
      <aside className="hidden h-screen w-[260px] overflow-y-auto bg-[#071D49] p-4 text-white shadow-[0_24px_70px_rgba(7,29,73,0.28)] lg:block shrink-0">
        <div className="rounded-2xl border border-white/10 bg-white/5 p-4 mb-6">
          <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-100/70">MyShule</p>
          <h2 className="mt-2 text-xl font-black">Grade/Form Master</h2>
          <p className="mt-2 text-sm leading-6 text-white/65">Form 2 Ã¢â‚¬â€ All Streams oversight.</p>
        </div>
        <nav className="space-y-1" aria-label="Grade form master navigation">
          {navItems.map((item, index) => {
            const showGroup = item.group !== navItems[index - 1]?.group;
            const Icon = item.icon;
            return (
              <div key={`${item.group}-${item.label}`}>
                {showGroup ? <p className="px-3 pb-2 pt-4 text-[10px] font-black uppercase tracking-[0.2em] text-white/40">{item.group}</p> : null}
                <button
                  type="button"
                  onClick={() => openView(item.id)}
                  className={cn(
                    "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-white/70 transition hover:bg-white/10 hover:text-white",
                    activeView === item.id && "bg-white/15 text-white shadow-[inset_4px_0_0_#38BDF8]",
                  )}
                >
                  <Icon className="h-4 w-4" aria-hidden="true" />
                  {item.label}
                </button>
              </div>
            );
          })}
        </nav>
      </aside>

      {/* Main Area */}
      <main className="flex-1 min-w-0 flex flex-col h-screen overflow-hidden">
        {/* Topbar */}
        <header className="sticky top-0 z-20 border-b border-[#D8E0EC] bg-white/90 px-4 py-3 backdrop-blur shrink-0">
          <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
            <div className="flex items-center gap-3">
              <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#071D49] text-xs font-black text-white">F2</div>
              <div>
                <h1 className="text-lg font-black text-[#071D49]">Good Morning, Mr. Otieno</h1>
                <p className="text-xs font-bold text-[#64748B]">Form 2 Master Ã¢â‚¬Â¢ Term 2, 2026 Ã¢â‚¬Â¢ Current Week: Week 5</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
               <div className="relative w-64 hidden md:block">
                 <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#94A3B8]" />
                 <input 
                   value={searchTerm}
                   onChange={(e) => setSearchTerm(e.target.value)}
                   className="h-10 w-full rounded-xl border border-[#D8E0EC] pl-9 pr-4 text-sm outline-none focus:border-[#071D49]" 
                   placeholder="Search learners..." 
                 />
                 {searchTerm.trim() && searchResults.length > 0 && (
                   <div className="absolute top-[calc(100%+8px)] left-0 w-full bg-white border border-[#D8E0EC] rounded-xl shadow-xl z-30 p-2">
                     {searchResults.map(r => (
                       <button key={r.id} onClick={() => openSearchRecord(r)} className="w-full text-left p-2 hover:bg-[#F8FAFC] rounded-lg">
                         <p className="font-bold text-[#071D49] text-sm">{r.label}</p>
                         <p className="text-xs text-[#64748B]">{r.detail}</p>
                       </button>
                     ))}
                   </div>
                 )}
               </div>
               <StatusChip label="Kisumu Boys" tone="info" />
               <button className="inline-flex h-10 items-center justify-center rounded-xl bg-[#071D49] px-4 text-sm font-black text-white hidden sm:flex">Take Quick Action</button>
               <TaskQueue />
               <ApprovalInbox currentUserId="school" />
               <NotificationBell />
            </div>
          </div>
          {/* Mobile Nav Selector */}
          <div className="mt-3 lg:hidden">
            <select
              className="h-10 w-full rounded-xl border border-[#D8E0EC] bg-white px-3 text-sm font-bold text-[#071D49] outline-none"
              value={activeView}
              onChange={(e) => openView(e.target.value as GradeView)}
            >
              {navItems.map((item) => (
                <option key={item.id} value={item.id}>{item.label}</option>
              ))}
            </select>
          </div>
        </header>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-4 lg:p-6">
          {notice && (
            <div className="mb-6 rounded-xl bg-blue-50 border border-blue-200 p-3 text-sm font-semibold text-blue-800 flex justify-between items-center">
              {notice}
              <button onClick={() => setNotice("")} className="text-blue-500 hover:text-blue-700"><X className="h-4 w-4" /></button>
            </div>
          )}

          {activeView === "overview" && <OverviewWorkspace onNavigate={openView} />}
          {activeView === "learners" && <LearnersWorkspace onSelectLearner={setSelectedLearner} />}
          {activeView === "streams" && <StreamsWorkspace />}
          {activeView === "attendance" && <AttendanceWorkspace />}
          {activeView === "academics" && <AcademicsWorkspace />}
          {activeView === "exams" && <ExamsWorkspace />}
          {activeView === "discipline" && <DisciplineWorkspace />}
          {activeView === "welfare" && <WelfareWorkspace />}
          {activeView === "fees" && <FeesWorkspace />}
          {activeView === "communication" && <CommunicationWorkspace />}
          {activeView === "meetings" && <MeetingsWorkspace />}
          {activeView === "timetable" && <TimetableWorkspace />}
          {activeView === "assignments" && <AssignmentsWorkspace />}
          {activeView === "requests" && <RequestsWorkspace />}
          {activeView === "reports" && <ReportsWorkspace />}
          {activeView === "notifications" && <NotificationsWorkspace />}
          {activeView === "teaching" && <TeachingWorkspace />}
          {activeView === "settings" && <SettingsWorkspace />}
        </div>
      </main>

      <LearnerProfileDrawer learnerId={selectedLearner} onClose={() => setSelectedLearner(null)} />
      
    </div>
  );
}
