// GENERATED BY scaffold_hod.js
"use client";

import { useState, type ReactNode } from "react";
import {
  AlertTriangle,
  Award,
  BarChart3,
  Bell,
  BookOpen,
  Calendar,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ClipboardList,
  DownloadCloud,
  Eye,
  FileCheck,
  FileText,
  Home,
  LayoutGrid,
  LifeBuoy,
  MessageSquare,
  MoreHorizontal,
  Package,
  Search,
  Settings,
  TrendingUp,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

import { ApprovalInbox } from "@/components/shared/approval-inbox";
import { NotificationBell } from "@/components/shared/notification-bell";
import { TaskQueue } from "@/components/shared/task-queue";
import { WorkflowToast } from "@/components/shared/workflow-toast";
import { useLiveTenantSession } from "@/hooks/use-live-tenant-session";
import { useSchoolQuery } from "@/lib/data/school-hooks";
import { usePermissions } from "@/components/providers/permission-context";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";

type HodRouteMode = "hosted" | "public";
type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type HodView = "overview" | "my-teaching" | "department-teachers" | "subject-allocation" | "schemes-of-work" | "lesson-plans" | "lesson-delivery" | "syllabus-coverage" | "assessments-cats" | "exams-marks-moderation" | "performance-analytics" | "learner-interventions" | "lesson-observation" | "resources-requests" | "department-meetings" | "communication" | "approvals" | "reports-downloads" | "department-settings";

type NavItem = {
  id: HodView;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
  { id: "overview", label: "Overview", icon: Home, group: "Command Center" },
  { id: "my-teaching", label: "My Teaching", icon: BookOpen, group: "Command Center" },
  { id: "department-teachers", label: "Department Teachers", icon: Users, group: "Department Admin" },
  { id: "subject-allocation", label: "Subject Allocation", icon: LayoutGrid, group: "Department Admin" },
  { id: "schemes-of-work", label: "Schemes of Work", icon: FileText, group: "Academics" },
  { id: "lesson-plans", label: "Lesson Plans", icon: FileCheck, group: "Academics" },
  { id: "lesson-delivery", label: "Lesson Delivery", icon: CheckCircle, group: "Academics" },
  { id: "syllabus-coverage", label: "Syllabus Coverage", icon: TrendingUp, group: "Academics" },
  { id: "assessments-cats", label: "Assessments & CATs", icon: ClipboardList, group: "Exams & Performance" },
  { id: "exams-marks-moderation", label: "Exams & Marks Moderation", icon: Award, group: "Exams & Performance" },
  { id: "performance-analytics", label: "Performance Analytics", icon: BarChart3, group: "Exams & Performance" },
  { id: "learner-interventions", label: "Learner Interventions", icon: LifeBuoy, group: "Support & Supervision" },
  { id: "lesson-observation", label: "Lesson Observation", icon: Eye, group: "Support & Supervision" },
  { id: "resources-requests", label: "Resources & Requests", icon: Package, group: "Operations" },
  { id: "department-meetings", label: "Department Meetings", icon: Calendar, group: "Operations" },
  { id: "communication", label: "Communication", icon: MessageSquare, group: "Operations" },
  { id: "approvals", label: "Approvals", icon: CheckSquare, group: "Operations" },
  { id: "reports-downloads", label: "Reports & Downloads", icon: DownloadCloud, group: "System" },
  { id: "department-settings", label: "Department Settings", icon: Settings, group: "System" },
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions}
      </div>
      {children}
    </section>
  );
}

function SimpleWorkspace({
  title,
  description,
  icon,
}: {
  title: string;
  description: string;
  icon: LucideIcon;
}) {
  return (
    <Panel title={title} description={description} icon={icon}>
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <AlertTriangle className="h-12 w-12 text-[#64748B]/30 mb-4" />
        <p className="text-lg font-semibold text-[#071D49]">Workspace Content Pending</p>
        <p className="mt-2 text-sm text-[#64748B]">This module is being connected to the new MyShule architecture.</p>
      </div>
    </Panel>
  );
}

function MyTeachingWorkspace() {
  const liveSession = useLiveTenantSession("school");
  const { data: assignments, isLoading: assignmentsLoading } = useSchoolQuery<any[]>("/api/academics/my-assignments", { enabled: !!liveSession.session });
  const { data: logs, isLoading: logsLoading } = useSchoolQuery<any[]>("/api/academics/my-lesson-logs", { enabled: !!liveSession.session });

  return (
    <Panel title="My Teaching" description="My classes, timetable, attendance, and marks." icon={BookOpen}>
      <div className="grid gap-6 md:grid-cols-2">
        <div>
          <h3 className="mb-3 text-sm font-bold text-[#071D49] uppercase tracking-wider">My Classes & Subjects</h3>
          {assignmentsLoading ? (
            <p className="text-sm text-slate-500">Loading assignments...</p>
          ) : !assignments?.length ? (
            <p className="text-sm text-slate-500">No active teaching assignments found.</p>
          ) : (
            <div className="space-y-3">
              {assignments.map((a: any, i) => (
                <div key={i} className="flex items-center justify-between rounded-lg border border-[#D8E0EC] bg-[#F8FAFC] p-3">
                  <div>
                    <span className="block font-bold text-[#071D49]">{a.subject?.name || 'Subject'}</span>
                    <span className="block text-xs text-[#64748B]">{a.class_section?.name || 'Class'}</span>
                  </div>
                  <button className="rounded bg-white px-3 py-1.5 text-xs font-bold text-[#071D49] border border-[#D8E0EC] hover:bg-gray-50">
                    View Roster
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
        <div>
          <h3 className="mb-3 text-sm font-bold text-[#071D49] uppercase tracking-wider">Recent Lesson Logs</h3>
          {logsLoading ? (
            <p className="text-sm text-slate-500">Loading logs...</p>
          ) : !logs?.length ? (
            <p className="text-sm text-slate-500">No recent lesson logs.</p>
          ) : (
            <div className="space-y-3">
              {logs.slice(0, 3).map((log: any, i) => (
                <div key={i} className="rounded-lg border border-[#D8E0EC] bg-white p-3">
                  <div className="flex items-start justify-between">
                    <div>
                      <span className="block font-bold text-[#071D49]">{log.topic}</span>
                      <span className="block text-xs text-[#64748B]">{new Date(log.created_at).toLocaleDateString()}</span>
                    </div>
                    <StatusChip label="Logged" tone="success" />
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </Panel>
  );
}

function DepartmentTeachersWorkspace() {
  const liveSession = useLiveTenantSession("school");
  const { data: staff, isLoading } = useSchoolQuery<any>("/api/hr/staff?department=academics", { enabled: !!liveSession.session });
  
  const teachers = staff?.items || staff || [];

  return (
    <Panel title="Department Teachers" description="Manage and supervise teachers in the department." icon={Users} actions={
      <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Add Teacher to Dept</button>
    }>
      {isLoading ? (
        <p className="text-sm text-slate-500">Loading teachers...</p>
      ) : !teachers.length ? (
        <div className="rounded-lg border border-dashed border-[#D8E0EC] p-8 text-center text-slate-500">
          No teachers assigned to this department.
        </div>
      ) : (
        <div className="overflow-hidden rounded-xl border border-[#D8E0EC]">
          <table className="w-full text-left text-sm">
            <thead className="bg-[#F8FAFC] text-xs uppercase text-[#64748B]">
              <tr>
                <th className="px-4 py-3 font-black">Teacher Name</th>
                <th className="px-4 py-3 font-black">Role / Title</th>
                <th className="px-4 py-3 font-black">Status</th>
                <th className="px-4 py-3 text-right font-black">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#D8E0EC]">
              {teachers.map((t: any, i: number) => (
                <tr key={i} className="hover:bg-slate-50">
                  <td className="px-4 py-3 font-semibold text-[#071D49]">
                    {t.first_name} {t.last_name}
                  </td>
                  <td className="px-4 py-3 text-[#64748B]">{t.job_title || 'Subject Teacher'}</td>
                  <td className="px-4 py-3">
                    <StatusChip label={t.status || 'Active'} tone={t.status === 'on_leave' ? 'warning' : 'success'} />
                  </td>
                  <td className="px-4 py-3 text-right">
                    <button className="text-[#1D4ED8] hover:underline text-xs font-bold">View Load</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Panel>
  );
}

function SubjectAllocationWorkspace() {
  const liveSession = useLiveTenantSession("school");
  const { data: assignments, isLoading } = useSchoolQuery<any[]>("/api/academics/teacher-assignments", { enabled: !!liveSession.session });
  const { hasPermission } = usePermissions();
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <>
      <Panel title="Subject Allocation" description="Assign department subjects to teachers and classes." icon={LayoutGrid} actions={
        hasPermission('academics:write') && (
          <button onClick={() => setIsModalOpen(true)} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">New Assignment</button>
        )
      }>
      {isLoading ? (
        <p className="text-sm text-slate-500">Loading assignments...</p>
      ) : !assignments?.length ? (
        <div className="rounded-lg border border-dashed border-[#D8E0EC] p-8 text-center text-slate-500">
          No subject allocations found. Click "New Assignment" to allocate subjects.
        </div>
      ) : (
        <div className="overflow-hidden rounded-xl border border-[#D8E0EC]">
          <table className="w-full text-left text-sm">
            <thead className="bg-[#F8FAFC] text-xs uppercase text-[#64748B]">
              <tr>
                <th className="px-4 py-3 font-black">Teacher</th>
                <th className="px-4 py-3 font-black">Subject</th>
                <th className="px-4 py-3 font-black">Class / Section</th>
                <th className="px-4 py-3 text-right font-black">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#D8E0EC]">
              {assignments.map((a: any, i) => (
                <tr key={i} className="hover:bg-slate-50">
                  <td className="px-4 py-3 font-semibold text-[#071D49]">
                    {a.teacher?.first_name} {a.teacher?.last_name}
                  </td>
                  <td className="px-4 py-3 text-[#64748B]">{a.subject?.name}</td>
                  <td className="px-4 py-3 text-[#64748B]">{a.class_section?.name}</td>
                  <td className="px-4 py-3 text-right">
                    <button className="text-rose-600 hover:underline text-xs font-bold">Revoke</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </Panel>
      <Modal open={isModalOpen} onClose={() => setIsModalOpen(false)} title="Assign Teacher Duties">
        <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); setIsModalOpen(false); }}>
          <div>
            <label className="text-sm font-bold text-[#071D49]">Teacher</label>
            <select className="w-full rounded-lg border border-[#D8E0EC] p-2">
              <option>Select teacher</option>
            </select>
          </div>
          <div>
            <label className="text-sm font-bold text-[#071D49]">Subject</label>
            <select className="w-full rounded-lg border border-[#D8E0EC] p-2">
              <option>Select subject</option>
            </select>
          </div>
          <div>
            <label className="text-sm font-bold text-[#071D49]">Class/Section</label>
            <select className="w-full rounded-lg border border-[#D8E0EC] p-2">
              <option>Select class</option>
            </select>
          </div>
          <div className="flex justify-end gap-2">
            <Button type="button" variant="outline" onClick={() => setIsModalOpen(false)}>Cancel</Button>
            <Button type="submit">Save Assignment</Button>
          </div>
        </form>
      </Modal>
    </>
  );
}

function DepartmentMeetingsWorkspace() {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const { hasPermission } = usePermissions();

  return (
    <>
      <Panel title="Department Meetings" description="Plan, record, and track department meetings." icon={Calendar} actions={
        hasPermission('academics:write') && (
          <button onClick={() => setIsModalOpen(true)} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Log Department Meeting</button>
        )
      }>
        <div className="flex flex-col items-center justify-center py-12 text-center">
          <Calendar className="h-12 w-12 text-[#64748B]/30 mb-4" />
          <p className="text-lg font-semibold text-[#071D49]">No Meetings Logged</p>
          <p className="mt-2 text-sm text-[#64748B]">Log meetings to keep track of departmental decisions.</p>
        </div>
      </Panel>
      <Modal open={isModalOpen} onClose={() => setIsModalOpen(false)} title="Log Department Meeting">
        <form className="space-y-4" onSubmit={(e) => { e.preventDefault(); setIsModalOpen(false); }}>
          <div>
            <label className="text-sm font-bold text-[#071D49]">Meeting Title</label>
            <input required type="text" className="w-full rounded-lg border border-[#D8E0EC] p-2" placeholder="e.g. End of Term Review" />
          </div>
          <div>
            <label className="text-sm font-bold text-[#071D49]">Date & Time</label>
            <input required type="datetime-local" className="w-full rounded-lg border border-[#D8E0EC] p-2" />
          </div>
          <div>
            <label className="text-sm font-bold text-[#071D49]">Minutes / Summary</label>
            <textarea required className="w-full rounded-lg border border-[#D8E0EC] p-2" rows={4}></textarea>
          </div>
          <div className="flex justify-end gap-2">
            <Button type="button" variant="outline" onClick={() => setIsModalOpen(false)}>Cancel</Button>
            <Button type="submit">Save Meeting</Button>
          </div>
        </form>
      </Modal>
    </>
  );
}

function OverviewWorkspace() {
  const liveSession = useLiveTenantSession("school");
  const { data: summary, isLoading } = useSchoolQuery<any>("/api/academics/summary", { enabled: !!liveSession.session });

  return (
    <Panel title="Overview" description="Live command center for department health." icon={Home} actions={
      <div className="flex gap-2">
        <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">New Department Report</button>
        <button className="rounded-lg border border-[#D8E0EC] px-4 py-2 text-sm font-black text-[#071D49]">Submit Weekly Update</button>
      </div>
    }>
      <div className="grid gap-4 md:grid-cols-4">
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <span className="block text-xs font-black uppercase text-[#64748B]">Dept Teachers</span>
          <span className="mt-1 block text-2xl font-black text-[#071D49]">{isLoading ? "..." : (summary?.total_teachers || 0)}</span>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <span className="block text-xs font-black uppercase text-[#64748B]">Syllabus Coverage</span>
          <span className="mt-1 block text-2xl font-black text-[#071D49]">{isLoading ? "..." : "64%"}</span>
        </div>
        <div className="rounded-xl border border-rose-200 bg-rose-50 p-4">
          <span className="block text-xs font-black uppercase text-rose-700">Pending Lesson Plans</span>
          <span className="mt-1 block text-2xl font-black text-rose-700">{isLoading ? "..." : "3 Missing"}</span>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <span className="block text-xs font-black uppercase text-[#64748B]">Marksheets Pending</span>
          <span className="mt-1 block text-2xl font-black text-[#071D49]">{isLoading ? "..." : "5"}</span>
        </div>
      </div>
    </Panel>
  );
}

export function HodCommandCenter({ routeMode = "hosted" }: { routeMode?: HodRouteMode }) {
  const [activeView, setActiveView] = useState<HodView>("overview");
  const [searchTerm, setSearchTerm] = useState("");
  const [notice, setNotice] = useState("");

  function openView(view: HodView) {
    setActiveView(view);
    setNotice("");
  }

  return (
    <div className="flex min-h-[calc(100vh-4rem)] bg-[#F3F6FA] -m-4 md:-m-5 lg:-m-8">
      <Sidebar activeView={activeView} onViewChange={openView} />
      <main className="flex-1 min-w-0 flex flex-col h-[calc(100vh-4rem)] overflow-hidden">
        <Topbar
          searchTerm={searchTerm}
          onSearchTermChange={setSearchTerm}
        />
        <div className="flex-1 overflow-y-auto p-4 lg:p-6 space-y-6">
          {notice && (
            <div className="rounded-xl bg-blue-50 border border-blue-200 p-3 text-sm font-semibold text-blue-800 flex justify-between items-center">
              {notice}
              <button onClick={() => setNotice("")} className="text-blue-500 hover:text-blue-700">
                <X className="h-4 w-4" />
              </button>
            </div>
          )}

          {activeView === "overview" && <OverviewWorkspace />}
          {activeView === "my-teaching" && <MyTeachingWorkspace />}
          {activeView === "department-teachers" && <DepartmentTeachersWorkspace />}
          {activeView === "subject-allocation" && <SubjectAllocationWorkspace />}
          {activeView === "schemes-of-work" && <SimpleWorkspace title="Schemes of Work" description="Track scheme of work submissions and approvals." icon={FileText} />}
          {activeView === "lesson-plans" && <SimpleWorkspace title="Lesson Plans" description="Review weekly/daily lesson plans from department teachers." icon={FileCheck} />}
          {activeView === "lesson-delivery" && <SimpleWorkspace title="Lesson Delivery" description="Track lesson delivery and make-up classes." icon={CheckCircle} />}
          {activeView === "syllabus-coverage" && <SimpleWorkspace title="Syllabus Coverage" description="Monitor syllabus progress by subject and teacher." icon={TrendingUp} />}
          {activeView === "assessments-cats" && <SimpleWorkspace title="Assessments & CATs" description="Manage department-level continuous assessments." icon={ClipboardList} />}
          {activeView === "exams-marks-moderation" && <SimpleWorkspace title="Exams & Marks Moderation" description="Review and moderate exam marks before submission." icon={Award} />}
          {activeView === "performance-analytics" && <SimpleWorkspace title="Performance Analytics" description="Analyze department performance trends." icon={BarChart3} />}
          {activeView === "learner-interventions" && <SimpleWorkspace title="Learner Interventions" description="Track learners needing academic support." icon={LifeBuoy} />}
          {activeView === "lesson-observation" && <SimpleWorkspace title="Lesson Observation" description="Observe lessons, record feedback, and support growth." icon={Eye} />}
          {activeView === "resources-requests" && <SimpleWorkspace title="Resources & Requests" description="Manage department academic resource needs." icon={Package} />}
          {activeView === "department-meetings" && <DepartmentMeetingsWorkspace />}
          {activeView === "communication" && <SimpleWorkspace title="Communication" description="Department-level messaging to teachers and parents." icon={MessageSquare} />}
          {activeView === "approvals" && <SimpleWorkspace title="Approvals" description="Handle department-level approvals." icon={CheckSquare} />}
          {activeView === "reports-downloads" && <SimpleWorkspace title="Reports & Downloads" description="Generate official department reports." icon={DownloadCloud} />}
          {activeView === "department-settings" && <SimpleWorkspace title="Department Settings" description="Configure department-specific academic settings." icon={Settings} />}
        </div>
      </main>
      
    </div>
  );
}

function Sidebar({
  activeView,
  onViewChange,
}: {
  activeView: HodView;
  onViewChange: (view: HodView) => void;
}) {
  return (
    <aside className="hidden w-[260px] overflow-y-auto bg-[#071D49] p-4 text-white shadow-[0_24px_70px_rgba(7,29,73,0.28)] lg:block shrink-0 h-full">
      <div className="rounded-2xl border border-white/10 bg-white/5 p-4 mb-6">
        <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-100/70">MyShule</p>
        <h2 className="mt-2 text-xl font-black">Head of Department</h2>
        <p className="mt-2 text-sm leading-6 text-white/65">Mathematics Department</p>
      </div>
      <nav className="space-y-1" aria-label="HOD navigation">
        {navItems.map((item, index) => {
          const showGroup = item.group !== navItems[index - 1]?.group;
          const Icon = item.icon;

          return (
            <div key={`${item.group}-${item.label}`}>
              {showGroup ? <p className="px-3 pb-2 pt-4 text-[10px] font-black uppercase tracking-[0.2em] text-white/40">{item.group}</p> : null}
              <button
                type="button"
                onClick={() => onViewChange(item.id)}
                className={cn(
                  "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-white/70 transition hover:bg-white/10 hover:text-white",
                  activeView === item.id && "bg-white/15 text-white shadow-[inset_4px_0_0_#38BDF8]",
                )}
              >
                <Icon className="h-4 w-4" aria-hidden="true" />
                {item.label}
              </button>
            </div>
          );
        })}
      </nav>
    </aside>
  );
}

function Topbar({
  searchTerm,
  onSearchTermChange,
}: {
  searchTerm: string;
  onSearchTermChange: (value: string) => void;
}) {
  return (
    <header className="sticky top-0 z-20 border-b border-[#D8E0EC] bg-white/90 px-4 py-3 backdrop-blur">
      <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
        <div className="flex items-center gap-3">
          <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#071D49] text-xs font-black text-white">HOD</div>
          <div>
            <h1 className="text-lg font-black text-[#071D49]">Good evening, Mr. Otieno</h1>
            <p className="text-sm font-medium text-[#64748B]">Mathematics Department Ã¢â‚¬Â¢ Academic Year 2026 Ã¢â‚¬Â¢ Term 2</p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#64748B]" />
            <input
              type="text"
              placeholder="Search department..."
              className="h-10 w-64 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] pl-9 pr-4 text-sm font-semibold text-[#071D49] placeholder-[#94A3B8] focus:border-[#38BDF8] focus:outline-none focus:ring-2 focus:ring-[#38BDF8]/20"
              value={searchTerm}
              onChange={(e) => onSearchTermChange(e.target.value)}
            />
          </div>
          <TaskQueue />
          <ApprovalInbox currentUserId="school" />
          <NotificationBell />
        </div>
      </div>
    </header>
  );
}
