// GENERATED BY scaffold_librarian.js
"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import {
  AlertTriangle,
  Banknote,
  Bell,
  BookDown,
  Bookmark,
  BookOpen,
  BookPlus,
  BookUp,
  Briefcase,
  Calendar,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  Clock,
  Download,
  FileText,
  Filter,
  Footprints,
  HeartCrack,
  Home,
  Layers,
  Library,
  MessageCircle,
  MoreHorizontal,
  Plus,
  Printer,
  ScanBarcode,
  Search,
  Settings,
  Users,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

import {
  getCurrentSchoolId,
  publishSchoolOperationalEvent,
} from "@/lib/school/school-operational-store";
import { ApprovalInbox } from "@/components/shared/approval-inbox";
import { NotificationBell } from "@/components/shared/notification-bell";
import { TaskQueue } from "@/components/shared/task-queue";
import { WorkflowToast } from "@/components/shared/workflow-toast";
import { useSchoolQuery } from "@/lib/data/school-hooks";

type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type LibrarianView = "overview" | "issue" | "return" | "catalogue" | "add_books" | "loans" | "lost_damaged" | "fines" | "borrowers" | "class_textbooks" | "reservations" | "stocktake" | "departments" | "visits" | "requests" | "reports" | "notices" | "settings";

type NavItem = {
  id: LibrarianView;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
  { id: "overview", label: "Overview", icon: Home, group: "Dashboard" },
  { id: "issue", label: "Issue Books", icon: BookUp, group: "Circulation" },
  { id: "return", label: "Return Books", icon: BookDown, group: "Circulation" },
  { id: "catalogue", label: "Book Catalogue", icon: Library, group: "Inventory" },
  { id: "add_books", label: "Add / Accession Books", icon: BookPlus, group: "Inventory" },
  { id: "loans", label: "Loans & Overdues", icon: Clock, group: "Monitoring" },
  { id: "lost_damaged", label: "Lost / Damaged Books", icon: HeartCrack, group: "Monitoring" },
  { id: "fines", label: "Fines & Payments", icon: Banknote, group: "Monitoring" },
  { id: "borrowers", label: "Students & Borrowers", icon: Users, group: "People" },
  { id: "class_textbooks", label: "Class Textbook Distribution", icon: Layers, group: "People" },
  { id: "reservations", label: "Reservations", icon: Bookmark, group: "Operations" },
  { id: "stocktake", label: "Library Stocktake", icon: ScanBarcode, group: "Operations" },
  { id: "departments", label: "Departments & Subject Resources", icon: Briefcase, group: "Operations" },
  { id: "visits", label: "Library Visits & Reading Logs", icon: Footprints, group: "Analytics" },
  { id: "requests", label: "Requests & Approvals", icon: CheckSquare, group: "System" },
  { id: "reports", label: "Reports & Downloads", icon: FileText, group: "System" },
  { id: "notices", label: "Notices & Communication", icon: MessageCircle, group: "System" },
  { id: "settings", label: "Library Settings", icon: Settings, group: "System" },
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold whitespace-nowrap", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full shrink-0", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions && <div className="shrink-0">{actions}</div>}
      </div>
      {children}
    </section>
  );
}

// ----------------------------------------------------------------------
// WORKSPACE COMPONENTS
// ----------------------------------------------------------------------

function OverviewWorkspace({ onNavigate }: { onNavigate: (v: LibrarianView) => void }) {
  const { data: summaryData, isLoading } = useSchoolQuery<any>("/api/library/summary");
  const { data: circulationResponse, isLoading: loadingCirc } = useSchoolQuery<any>("/api/library/circulation");
  const circulation = Array.isArray(circulationResponse) ? circulationResponse : [];

  const totalBooks = isLoading ? "..." : (summaryData?.total_catalog_items?.toLocaleString() || "0");
  const availableBooks = isLoading ? "..." : (summaryData?.available_copies?.toLocaleString() || "0");
  const issuedOut = isLoading ? "..." : (summaryData?.active_loans?.toLocaleString() || "0");
  const overdueBooks = isLoading ? "..." : (summaryData?.overdue_loans?.toLocaleString() || "0");
  const lostBooks = isLoading ? "..." : (summaryData?.lost_or_damaged_copies?.toLocaleString() || "0");
  const finesPending = isLoading ? "..." : `KES ${(summaryData?.total_fines_minor || 0).toLocaleString()}`;

  const recentActivity = isLoading || !summaryData?.recent_activities ? [] : summaryData.recent_activities;

  return (
    <Panel title="Library Overview" description="Manage books, loans, returns, overdue items, stock status, and borrower activity for the current term." icon={Home}>
      <div className="grid gap-4 md:grid-cols-4 lg:grid-cols-6 mb-6">
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("catalogue")}>
          <div className="text-sm font-semibold text-[#64748B]">Total Books</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">{totalBooks}</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("catalogue")}>
          <div className="text-sm font-semibold text-[#64748B]">Available</div>
          <div className="mt-1 text-2xl font-black text-emerald-600">{availableBooks}</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("loans")}>
          <div className="text-sm font-semibold text-[#64748B]">Issued Out</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">{issuedOut}</div>
        </div>
        <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 cursor-pointer hover:border-rose-300 transition" onClick={() => onNavigate("loans")}>
          <div className="text-sm font-semibold text-rose-700">Overdue Books</div>
          <div className="mt-1 text-2xl font-black text-rose-700">{overdueBooks}</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("lost_damaged")}>
          <div className="text-sm font-semibold text-[#64748B]">Lost / Damaged</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">{lostBooks}</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("fines")}>
          <div className="text-sm font-semibold text-[#64748B]">Fines Pending</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">{finesPending}</div>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          <div className="rounded-xl border border-[#D8E0EC] overflow-hidden">
            <div className="bg-[#F8FAFC] px-4 py-3 border-b border-[#D8E0EC] flex justify-between items-center">
              <h3 className="font-bold text-[#071D49]">TodayÃ¢â‚¬â„¢s Library Queue</h3>
              <button className="text-sm text-blue-600 font-semibold hover:underline">View All</button>
            </div>
            <div className="p-4">
              <table className="w-full text-sm text-left">
                <thead>
                  <tr className="text-[#64748B] border-b border-[#D8E0EC]">
                    <th className="pb-2 font-semibold">Borrower</th>
                    <th className="pb-2 font-semibold">Class</th>
                    <th className="pb-2 font-semibold">Book</th>
                    <th className="pb-2 font-semibold">Status</th>
                    <th className="pb-2 font-semibold text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#D8E0EC]">
                  {loadingCirc ? (
                    <tr><td colSpan={5} className="py-3 text-center text-[#64748B]">Loading...</td></tr>
                  ) : circulation.length === 0 ? (
                    <tr><td colSpan={5} className="py-3 text-center text-[#64748B]">No active library queue.</td></tr>
                  ) : (
                    circulation.slice(0, 5).map((item: any) => (
                      <tr key={item.id}>
                        <td className="py-3 font-medium text-[#071D49]">{item.borrower_id}</td>
                        <td className="py-3 text-[#64748B]">-</td>
                        <td className="py-3 text-[#071D49]">{item.copy_id}</td>
                        <td className="py-3"><StatusChip label={item.status || "Active"} tone={item.status === "Overdue" ? "danger" : "info"} /></td>
                        <td className="py-3 text-right">
                          <button className="text-blue-600 hover:underline font-semibold" onClick={() => onNavigate(item.action === "issue" ? "return" : "loans")}>Action</button>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
          </div>
          
          <div className="rounded-xl border border-[#D8E0EC] overflow-hidden">
            <div className="bg-[#F8FAFC] px-4 py-3 border-b border-[#D8E0EC]">
              <h3 className="font-bold text-[#071D49]">Recent Activity</h3>
            </div>
            <div className="p-4 space-y-4 text-sm">
              {recentActivity.length === 0 ? (
                <div className="text-[#64748B] italic">No recent activity.</div>
              ) : (
                recentActivity.map((activity: any) => (
                  <div key={activity.id} className="flex gap-3">
                    <div className={cn("w-2 h-2 rounded-full mt-1.5 shrink-0", activity.action === "issue" ? "bg-emerald-500" : activity.action === "return" ? "bg-blue-500" : "bg-rose-500")}></div>
                    <div>
                      <span className="font-semibold">{activity.action === "issue" ? "Book Issued:" : activity.action === "return" ? "Book Returned:" : "Status Changed:"}</span> 
                      <em> {activity.item_title}</em> {activity.action === "issue" ? "to" : activity.action === "return" ? "by" : "for"} {activity.borrower_id}.
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="rounded-xl border border-rose-200 bg-rose-50 overflow-hidden">
            <div className="px-4 py-3 border-b border-rose-200 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-rose-600" />
              <h3 className="font-bold text-rose-900">Urgent Alerts</h3>
            </div>
            <div className="p-4 space-y-3 text-sm text-rose-800">
              {summaryData?.overdue_loans > 0 ? (
                <div className="flex justify-between items-start">
                  <span><strong>{summaryData.overdue_loans} books</strong> are currently overdue.</span>
                  <button className="text-rose-900 underline font-semibold text-xs" onClick={() => onNavigate("loans")}>View</button>
                </div>
              ) : (
                <div className="flex justify-between items-start text-emerald-700">
                  <span>No overdue books.</span>
                </div>
              )}
            </div>
          </div>

          <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-center">
            <ScanBarcode className="h-10 w-10 text-[#071D49] mx-auto mb-2 opacity-80" />
            <p className="text-sm font-bold text-[#071D49] mb-4">Quick Issue / Return</p>
            <div className="flex flex-col gap-2">
              <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white" onClick={() => onNavigate("issue")}>Open Issue Desk</button>
              <button className="rounded-lg border border-[#071D49] px-4 py-2 text-sm font-black text-[#071D49]" onClick={() => onNavigate("return")}>Open Return Desk</button>
            </div>
          </div>
        </div>
      </div>
    </Panel>
  );
}

function IssueBooksWorkspace() {
  const [basket, setBasket] = useState<{title: string, barcode: string}[]>([]);
  const [barcodeInput, setBarcodeInput] = useState("");
  const [successMsg, setSuccessMsg] = useState("");

  const handleScan = (e: React.FormEvent) => {
    e.preventDefault();
    if (!barcodeInput) return;
    setBasket([...basket, { title: "Sample Book Scanned", barcode: barcodeInput }]);
    setBarcodeInput("");
  };

  const handleIssue = () => {
    if (basket.length === 0) return;
    setSuccessMsg(`${basket.length} books issued to Brian Otieno. Due date: 26 June 2026.`);
    setBasket([]);
  };

  return (
    <Panel title="Issue Books" description="Fast book issuing using barcode scan or manual search." icon={BookUp}>
      {successMsg && (
        <div className="mb-4 rounded-xl bg-emerald-50 border border-emerald-200 p-4 text-sm font-bold text-emerald-800 flex justify-between">
          <div className="flex items-center gap-2"><CheckCircle2 className="w-5 h-5" /> {successMsg}</div>
          <button className="underline">Print Issue Slip</button>
        </div>
      )}
      
      <div className="grid lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-bold text-[#071D49] mb-1">1. Select Borrower</label>
            <div className="relative">
              <Search className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" />
              <input type="text" placeholder="Search student by name, admission number, class..." className="w-full rounded-xl border border-[#D8E0EC] py-2 pl-9 pr-3 text-sm focus:border-[#071D49] focus:outline-none focus:ring-1 focus:ring-[#071D49]" />
            </div>
            {/* Mock selected borrower */}
            <div className="mt-2 rounded-xl border border-blue-200 bg-blue-50 p-3 flex justify-between items-center">
              <div>
                <div className="font-bold text-blue-900">Brian Otieno</div>
                <div className="text-xs text-blue-700">ADM-2041 Ã¢â‚¬Â¢ Form 3 Blue Ã¢â‚¬Â¢ <span className="font-bold">Clear Status</span></div>
              </div>
              <button className="text-blue-500 hover:bg-blue-100 p-1 rounded"><X className="w-4 h-4" /></button>
            </div>
          </div>

          <div>
            <label className="block text-sm font-bold text-[#071D49] mb-1">2. Scan or Search Book</label>
            <form onSubmit={handleScan} className="relative">
              <ScanBarcode className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" />
              <input autoFocus type="text" value={barcodeInput} onChange={e => setBarcodeInput(e.target.value)} placeholder="Scan barcode or search title, ISBN..." className="w-full rounded-xl border border-[#D8E0EC] py-2 pl-9 pr-3 text-sm focus:border-[#071D49] focus:outline-none focus:ring-1 focus:ring-[#071D49]" />
            </form>
          </div>
        </div>

        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] flex flex-col">
          <div className="px-4 py-3 border-b border-[#D8E0EC] font-bold text-[#071D49] flex justify-between">
            <span>Issue Basket ({basket.length})</span>
            {basket.length > 0 && <button className="text-xs text-rose-600 hover:underline" onClick={() => setBasket([])}>Clear</button>}
          </div>
          <div className="p-4 flex-1 overflow-auto min-h-[200px]">
            {basket.length === 0 ? (
              <div className="text-center text-[#64748B] text-sm py-8">Scan a book to add to basket</div>
            ) : (
              <ul className="space-y-2">
                {basket.map((item, idx) => (
                  <li key={idx} className="flex justify-between items-center bg-white p-2 border border-[#D8E0EC] rounded-lg text-sm">
                    <div>
                      <div className="font-semibold text-[#071D49]">{item.title}</div>
                      <div className="text-xs text-[#64748B]">Barcode: {item.barcode}</div>
                    </div>
                    <button className="text-rose-500"><XCircle className="w-4 h-4" /></button>
                  </li>
                ))}
              </ul>
            )}
          </div>
          <div className="p-4 border-t border-[#D8E0EC] bg-white rounded-b-xl">
            <button 
              disabled={basket.length === 0}
              onClick={handleIssue}
              className="w-full rounded-xl bg-[#071D49] py-3 text-sm font-black text-white disabled:opacity-50"
            >
              Issue {basket.length} Books
            </button>
          </div>
        </div>
      </div>
    </Panel>
  );
}

function ReturnBooksWorkspace() {
  const [barcodeInput, setBarcodeInput] = useState("");
  const [returned, setReturned] = useState<{title: string, borrower: string, fine: string} | null>(null);

  const handleScan = (e: React.FormEvent) => {
    e.preventDefault();
    if (!barcodeInput) return;
    setReturned({ title: "The River and the Source", borrower: "Amina Wanjiku", fine: "None" });
    setBarcodeInput("");
  };

  return (
    <Panel title="Return Books" description="Receive returned books, update condition, and clear loans." icon={BookDown}>
      <div className="max-w-2xl mx-auto">
        <form onSubmit={handleScan} className="mb-6 relative">
          <ScanBarcode className="absolute left-4 top-3.5 h-5 w-5 text-[#64748B]" />
          <input autoFocus type="text" value={barcodeInput} onChange={e => setBarcodeInput(e.target.value)} placeholder="Scan book barcode to return..." className="w-full rounded-2xl border-2 border-[#D8E0EC] py-3 pl-12 pr-4 text-base focus:border-[#071D49] focus:outline-none" />
          <button type="submit" className="absolute right-2 top-2 rounded-lg bg-[#071D49] px-4 py-1.5 text-sm font-black text-white">Return</button>
        </form>

        {returned && (
          <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center animate-in fade-in slide-in-from-bottom-4">
            <CheckCircle2 className="h-12 w-12 text-emerald-500 mx-auto mb-4" />
            <h3 className="text-xl font-black text-emerald-900 mb-1">Book Returned Successfully</h3>
            <p className="text-emerald-700 font-medium mb-4">{returned.title} returned by {returned.borrower}.</p>
            <div className="flex justify-center gap-3">
              <button className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-black text-white" onClick={() => setReturned(null)}>Scan Next Book</button>
              <button className="rounded-lg border border-emerald-300 px-4 py-2 text-sm font-black text-emerald-800">Print Return Slip</button>
            </div>
          </div>
        )}
      </div>
    </Panel>
  );
}

function BookCatalogueWorkspace() {
  const { data: catalog = [], isLoading } = useSchoolQuery<any>("/api/library/catalog");

  return (
    <Panel title="Book Catalogue" description="View, search, filter, edit, and manage all library books and copies." icon={Library} actions={
      <button className="flex items-center gap-2 rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">
        <Plus className="h-4 w-4" /> Add Book
      </button>
    }>
      <div className="flex flex-col sm:flex-row gap-3 mb-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" />
          <input type="text" placeholder="Search title, author, ISBN, barcode..." className="w-full rounded-xl border border-[#D8E0EC] py-2 pl-9 pr-3 text-sm focus:border-[#071D49] focus:outline-none focus:ring-1 focus:ring-[#071D49]" />
        </div>
        <button className="flex items-center gap-2 rounded-xl border border-[#D8E0EC] bg-white px-4 py-2 text-sm font-bold text-[#071D49]">
          <Filter className="h-4 w-4" /> Filters
        </button>
      </div>
      
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Author</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">ISBN</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Subject</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Total</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Available</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {isLoading ? (
              <tr><td colSpan={7} className="px-4 py-8 text-center text-[#64748B]">Loading...</td></tr>
            ) : catalog.length === 0 ? (
              <tr><td colSpan={7} className="px-4 py-8 text-center text-[#64748B]">No books found in catalogue.</td></tr>
            ) : catalog.map((b: any, i: number) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{b.title}</td>
                <td className="px-4 py-3 text-[#64748B]">{b.author || "-"}</td>
                <td className="px-4 py-3 text-[#64748B]">{b.isbn || "-"}</td>
                <td className="px-4 py-3 text-[#64748B]">{b.subject || "-"}</td>
                <td className="px-4 py-3 font-medium">{b.total || 0}</td>
                <td className="px-4 py-3 font-medium text-emerald-600">{b.available || 0}</td>
                <td className="px-4 py-3 text-right">
                  <button className="p-1 text-[#64748B] hover:bg-[#D8E0EC] rounded"><MoreHorizontal className="w-4 h-4" /></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}


function ReservationsWorkspace() {
  return (
    <Panel title="Reservations" description="Manage book reservations, waiting lists, availability alerts, and reservation expiry." icon={Bookmark} actions={
      <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Create Reservation</button>
    }>
      <div className="flex gap-4 mb-4 border-b border-[#D8E0EC]">
        <button className="pb-2 text-sm font-black text-[#071D49] border-b-2 border-[#071D49]">Active Reservations</button>
        <button className="pb-2 text-sm font-bold text-[#64748B]">Ready for Collection</button>
        <button className="pb-2 text-sm font-bold text-[#64748B]">Waiting List</button>
        <button className="pb-2 text-sm font-bold text-[#64748B]">Expired</button>
      </div>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Borrower</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Book Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Requested Date</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Expiry Date</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { borrower: "Amina Wanjiku", title: "A Doll's House", date: "09 Jun 2026", expiry: "12 Jun 2026", status: "Ready" },
              { borrower: "John Doe", title: "Secondary Math Bk 2", date: "10 Jun 2026", expiry: "-", status: "Waiting" },
            ].map((r, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{r.borrower}</td>
                <td className="px-4 py-3 text-[#071D49]">{r.title}</td>
                <td className="px-4 py-3 text-[#64748B]">{r.date}</td>
                <td className="px-4 py-3 text-[#64748B]">{r.expiry}</td>
                <td className="px-4 py-3"><StatusChip label={r.status} tone={r.status === 'Ready' ? 'success' : 'warning'} /></td>
                <td className="px-4 py-3 text-right">
                  <button className="text-blue-600 hover:underline font-semibold mr-3">Notify</button>
                  <button className="p-1 text-[#64748B] hover:bg-[#D8E0EC] rounded"><MoreHorizontal className="w-4 h-4" /></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function DepartmentsWorkspace() {
  return (
    <Panel title="Departments & Subject Resources" description="Manage resources assigned to subjects, departments, teachers, and learning areas." icon={Briefcase} actions={
      <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Issue to Department</button>
    }>
      <div className="flex flex-col sm:flex-row gap-3 mb-4">
        <select className="rounded-xl border border-[#D8E0EC] bg-white px-4 py-2 text-sm font-bold text-[#071D49]">
          <option>All Departments</option>
          <option>Science</option>
          <option>Languages</option>
          <option>Humanities</option>
          <option>Mathematics</option>
        </select>
        <select className="rounded-xl border border-[#D8E0EC] bg-white px-4 py-2 text-sm font-bold text-[#071D49]">
          <option>All Resource Types</option>
          <option>Teacher Guide</option>
          <option>Reference Book</option>
          <option>Dictionary / Atlas</option>
        </select>
      </div>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Resource Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Department</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Assigned To</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Total</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Available</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { title: "Advanced Chemistry Guide", dept: "Science", assigned: "Mr. Omondi", total: 3, available: 1 },
              { title: "Kamusi ya Kiswahili", dept: "Languages", assigned: "Dept Office", total: 10, available: 8 },
            ].map((d, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{d.title}</td>
                <td className="px-4 py-3 text-[#64748B]">{d.dept}</td>
                <td className="px-4 py-3 text-[#64748B]">{d.assigned}</td>
                <td className="px-4 py-3 font-medium">{d.total}</td>
                <td className="px-4 py-3 font-medium text-emerald-600">{d.available}</td>
                <td className="px-4 py-3 text-right">
                  <button className="text-blue-600 hover:underline font-semibold">View</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function VisitsWorkspace() {
  return (
    <Panel title="Library Visits & Reading Logs" description="Record student library visits, reading sessions, and reading program participation." icon={Footprints} actions={
      <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Log Visit</button>
    }>
      <div className="grid gap-4 md:grid-cols-3 mb-6">
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <div className="text-sm font-semibold text-[#64748B]">Visits Today</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">45</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <div className="text-sm font-semibold text-[#64748B]">Class Sessions</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">2</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <div className="text-sm font-semibold text-[#64748B]">Books Read (Term)</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">320</div>
        </div>
      </div>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Student/Class</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Time In</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Time Out</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Purpose</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { name: "Joy Kendi", in: "10:00 AM", out: "10:45 AM", purpose: "Reading", status: "Completed" },
              { name: "Form 1 East", in: "11:00 AM", out: "-", purpose: "Class Session", status: "Active" },
            ].map((v, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{v.name}</td>
                <td className="px-4 py-3 text-[#64748B]">{v.in}</td>
                <td className="px-4 py-3 text-[#64748B]">{v.out}</td>
                <td className="px-4 py-3 text-[#64748B]">{v.purpose}</td>
                <td className="px-4 py-3"><StatusChip label={v.status} tone={v.status === 'Active' ? 'success' : 'neutral'} /></td>
                <td className="px-4 py-3 text-right">
                  {v.status === "Active" && <button className="text-blue-600 hover:underline font-semibold mr-3">Check Out</button>}
                  <button className="p-1 text-[#64748B] hover:bg-[#D8E0EC] rounded"><MoreHorizontal className="w-4 h-4" /></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function RequestsApprovalsWorkspace() {
  return (
    <Panel title="Requests & Approvals" description="Handle book requests, stock purchase requests, write-off approvals, and waivers." icon={CheckSquare} actions={
      <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Create Request</button>
    }>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Request Type</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Target Role</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Details</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Date</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { type: "Write-off Approval", target: "Principal", details: "3 Books Damaged by Water", date: "10 Jun 2026", status: "Pending" },
              { type: "New Books Purchase", target: "Procurement", details: "CBC Grade 7 Science Books", date: "05 Jun 2026", status: "Approved" },
            ].map((r, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{r.type}</td>
                <td className="px-4 py-3 text-[#64748B]">{r.target}</td>
                <td className="px-4 py-3 text-[#64748B]">{r.details}</td>
                <td className="px-4 py-3 text-[#64748B]">{r.date}</td>
                <td className="px-4 py-3"><StatusChip label={r.status} tone={r.status === 'Approved' ? 'success' : 'warning'} /></td>
                <td className="px-4 py-3 text-right">
                  <button className="text-blue-600 hover:underline font-semibold">View</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function ReportsDownloadsWorkspace() {
  return (
    <Panel title="Reports & Downloads" description="Generate library reports for management, classes, departments, audits, and parents." icon={FileText}>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        {[
          "Full Library Catalogue",
          "Available Books List",
          "Active Loans Report",
          "Overdue Books by Class",
          "Lost & Damaged Books",
          "Library Fines & Payments",
          "Stocktake Summary",
          "Subject Resource Distribution"
        ].map((report, i) => (
          <div key={i} className="rounded-xl border border-[#D8E0EC] p-4 bg-white hover:border-blue-300 transition cursor-pointer flex justify-between items-center group">
            <span className="font-semibold text-[#071D49] text-sm">{report}</span>
            <Download className="w-4 h-4 text-[#64748B] group-hover:text-blue-600" />
          </div>
        ))}
      </div>
    </Panel>
  );
}

function NoticesCommunicationWorkspace() {
  return (
    <Panel title="Notices & Communication" description="Send library notices, overdue reminders, fine alerts, and lost book notices." icon={MessageCircle} actions={
      <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Compose Notice</button>
    }>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Message Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Recipient Type</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Method</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Sent Date</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { title: "Form 2 Overdue Reminder", target: "Students & Parents", method: "SMS, In-app", date: "10 Jun 2026", status: "Sent (45)" },
              { title: "New Set Books Arrival", target: "Language Dept", method: "In-app", date: "08 Jun 2026", status: "Sent (8)" },
            ].map((m, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{m.title}</td>
                <td className="px-4 py-3 text-[#64748B]">{m.target}</td>
                <td className="px-4 py-3 text-[#64748B]">{m.method}</td>
                <td className="px-4 py-3 text-[#64748B]">{m.date}</td>
                <td className="px-4 py-3"><StatusChip label={m.status} tone="success" /></td>
                <td className="px-4 py-3 text-right">
                  <button className="text-blue-600 hover:underline font-semibold">View</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}
// Minimal placeholder for the remaining 14 workspaces to maintain the structure
function SimpleWorkspace({ title, description, icon: Icon }: { title: string; description: string; icon: LucideIcon }) {
  return (
    <Panel title={title} description={description} icon={Icon}>
      <div className="flex flex-col items-center justify-center py-16 text-center bg-[#F8FAFC] rounded-xl border border-dashed border-[#D8E0EC]">
        <Icon className="h-12 w-12 text-[#64748B]/30 mb-4" />
        <p className="text-lg font-bold text-[#071D49]">{title} Workspace</p>
        <p className="mt-2 text-sm text-[#64748B] max-w-sm">{description}</p>
        <div className="mt-6 flex gap-3">
          <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Main Action</button>
          <button className="rounded-lg border border-[#D8E0EC] bg-white px-4 py-2 text-sm font-bold text-[#071D49]">Export</button>
        </div>
      </div>
    </Panel>
  );
}

export function LibrarianCommandCenter() {
  const [activeView, setActiveView] = useState<LibrarianView>("overview");

  return (
    <div className="flex min-h-screen bg-[#F3F6FA] font-sans">
      <Sidebar activeView={activeView} onViewChange={setActiveView} />
      <main className="flex-1 min-w-0 flex flex-col h-screen">
        <Topbar activeView={activeView} />
        <div className="flex-1 overflow-y-auto p-4 lg:p-6 space-y-6">
          {activeView === "overview" && <OverviewWorkspace onNavigate={setActiveView} />}
          {activeView === "issue" && <IssueBooksWorkspace />}
          {activeView === "return" && <ReturnBooksWorkspace />}
          {activeView === "catalogue" && <BookCatalogueWorkspace />}

          {activeView === "reservations" && <ReservationsWorkspace />}
          {activeView === "departments" && <DepartmentsWorkspace />}
          {activeView === "visits" && <VisitsWorkspace />}
          {activeView === "requests" && <RequestsApprovalsWorkspace />}
          {activeView === "reports" && <ReportsDownloadsWorkspace />}
          {activeView === "notices" && <NoticesCommunicationWorkspace />}
          {/* Dynamically render the rest with SimpleWorkspace */}
          {!["overview", "issue", "return", "catalogue", "reservations", "departments", "visits", "requests", "reports", "notices"].includes(activeView) && (
            <SimpleWorkspace 
              title={navItems.find(i => i.id === activeView)?.label || ""} 
              description="" 
              icon={navItems.find(i => i.id === activeView)?.icon || AlertTriangle} 
            />
          )}
        </div>
      </main>
      
    </div>
  );
}

function Sidebar({ activeView, onViewChange }: { activeView: LibrarianView; onViewChange: (view: LibrarianView) => void }) {
  return (
    <aside className="hidden h-screen w-[260px] overflow-y-auto bg-[#071D49] p-4 text-white shadow-[0_24px_70px_rgba(7,29,73,0.28)] lg:block shrink-0">
      <div className="rounded-2xl border border-white/10 bg-white/5 p-4 mb-6">
        <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-100/70">MyShule</p>
        <h2 className="mt-2 text-xl font-black">Librarian</h2>
        <p className="mt-2 text-sm leading-6 text-white/65">Main Library Operations</p>
      </div>
      <nav className="space-y-1" aria-label="Librarian navigation">
        {navItems.map((item, index) => {
          const showGroup = item.group !== navItems[index - 1]?.group;
          const Icon = item.icon;
          return (
            <div key={`${item.group}-${item.label}`}>
              {showGroup ? <p className="px-3 pb-2 pt-4 text-[10px] font-black uppercase tracking-[0.2em] text-white/40">{item.group}</p> : null}
              <button
                type="button"
                onClick={() => onViewChange(item.id)}
                className={cn(
                  "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-white/70 transition hover:bg-white/10 hover:text-white",
                  activeView === item.id && "bg-white/15 text-white shadow-[inset_4px_0_0_#38BDF8]"
                )}
              >
                <Icon className="h-4 w-4 shrink-0" aria-hidden="true" />
                <span className="truncate">{item.label}</span>
              </button>
            </div>
          );
        })}
      </nav>
    </aside>
  );
}

function Topbar({ activeView }: { activeView: LibrarianView }) {
  const label = navItems.find(i => i.id === activeView)?.label || "Dashboard";
  return (
    <header className="sticky top-0 z-20 border-b border-[#D8E0EC] bg-white/90 px-4 py-3 backdrop-blur shrink-0">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#071D49] text-xs font-black text-white shrink-0">LB</div>
          <h1 className="text-lg font-black text-[#071D49] truncate">{label}</h1>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <StatusChip label="Term 2 (2026)" tone="info" />
          <button className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#D8E0EC] hover:bg-[#F8FAFC] transition text-[#071D49]">
            <Search className="h-4 w-4" />
          </button>
          <div className="flex items-center gap-2">
            <TaskQueue />
            <ApprovalInbox currentUserId="school" />
            <NotificationBell />
          </div>
          <div className="relative group">
            <button className="flex h-10 items-center justify-center rounded-xl bg-[#071D49] px-4 text-sm font-black text-white gap-2">
              Quick Action <ChevronDown className="h-4 w-4" />
            </button>
            <div className="absolute right-0 mt-2 w-48 rounded-xl border border-[#D8E0EC] bg-white p-2 shadow-xl opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all">
              <button className="w-full text-left px-3 py-2 text-sm font-semibold text-[#071D49] hover:bg-[#F8FAFC] rounded-lg">Scan Book</button>
              <button className="w-full text-left px-3 py-2 text-sm font-semibold text-[#071D49] hover:bg-[#F8FAFC] rounded-lg">Issue Book</button>
              <button className="w-full text-left px-3 py-2 text-sm font-semibold text-[#071D49] hover:bg-[#F8FAFC] rounded-lg">Return Book</button>
              <div className="h-px bg-[#D8E0EC] my-1"></div>
              <button className="w-full text-left px-3 py-2 text-sm font-semibold text-rose-600 hover:bg-rose-50 rounded-lg">Record Lost Book</button>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}
