
// GENERATED BY scaffold_secretary_detailed.js
"use client";

import { useState, type ReactNode } from "react";
import {
  AlertTriangle,
  BarChart,
  Bell,
  Calendar,
  ClipboardList,
  Contact,
  FileText,
  HelpCircle,
  Home,
  MessageSquare,
  Package,
  Phone,
  Plus,
  Search,
  Settings,
  UserCircle,
  UserPlus,
  Users,
  X,
  type LucideIcon,
  Loader2,
} from "lucide-react";
import { toast } from "sonner";

uery } from "@/lib/data/school-hooks";
import { requestDashboardApi } from "@/lib/dashboard/api-client";
import { usePermissions } from "@/components/providers/permission-context";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { buildSchoolSectionHref } from "./school-pages";

// ==========================================
// TYPES AND CONSTANTS
// ==========================================

type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type SecretaryView = "overview" | "queue" | "parent_desk" | "student_lookup" | "visitor_register" | "calls_log" | "appointments" | "letters" | "admissions" | "communication" | "mail_parcels" | "staff_directory" | "lost_found" | "reports" | "settings";

type NavItem = {
  id: SecretaryView;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
  { id: "overview", label: "Overview", icon: Home, group: "Dashboard" },
  { id: "queue", label: "Front Office Queue", icon: Users, group: "Reception" },
  { id: "parent_desk", label: "Parent & Guardian Desk", icon: UserCircle, group: "Reception" },
  { id: "student_lookup", label: "Student Quick Lookup", icon: Search, group: "Reception" },
  { id: "visitor_register", label: "Visitor Register", icon: ClipboardList, group: "Reception" },
  { id: "calls_log", label: "Calls Log", icon: Phone, group: "Communication" },
  { id: "appointments", label: "Appointments", icon: Calendar, group: "Communication" },
  { id: "letters", label: "Letters & Documents", icon: FileText, group: "Office" },
  { id: "admissions", label: "Admissions Handoff", icon: UserPlus, group: "Office" },
  { id: "communication", label: "Communication Desk", icon: MessageSquare, group: "Communication" },
  { id: "mail_parcels", label: "Mail, Deliveries & Parcels", icon: Package, group: "Office" },
  { id: "staff_directory", label: "Staff Directory", icon: Contact, group: "Reference" },
  { id: "lost_found", label: "Lost & Found", icon: HelpCircle, group: "Office" },
  { id: "reports", label: "Reports", icon: BarChart, group: "System" },
  { id: "settings", label: "Settings", icon: Settings, group: "System" },
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

// ==========================================
// UTILITY COMPONENTS
// ==========================================

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold whitespace-nowrap", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full shrink-0", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions && <div className="shrink-0">{actions}</div>}
      </div>
      {children}
    </section>
  );
}

function RealDataTable({ 
  columns, 
  actions, 
  data, 
  loading, 
  error,
  emptyIcon: EmptyIcon = FileText,
  emptyMessage = "No records found"
}: { 
  columns: string[], 
  actions: string[], 
  data: any[], 
  loading: boolean, 
  error: string | null,
  emptyIcon?: LucideIcon,
  emptyMessage?: string
}) {
  if (columns.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-[#D8E0EC] bg-[#F8FAFC] py-16 text-center">
        <Settings className="h-12 w-12 text-[#94A3B8]" />
        <h3 className="mt-4 text-lg font-bold text-[#071D49]">Configuration View</h3>
        <p className="mt-2 text-sm text-[#64748B]">Manage settings here.</p>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-[#D8E0EC] bg-[#F8FAFC] py-16 text-center">
        <Loader2 className="h-8 w-8 text-[#1D4ED8] animate-spin" />
        <p className="mt-2 text-sm text-[#64748B]">Loading data...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-rose-200 bg-rose-50 py-16 text-center">
        <AlertTriangle className="h-8 w-8 text-rose-500" />
        <p className="mt-2 text-sm text-rose-700">{error}</p>
        <button className="mt-4 px-4 py-2 bg-white border border-rose-200 rounded-lg text-sm text-rose-700 hover:bg-rose-100 transition">Retry</button>
      </div>
    );
  }

  if (!data || data.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-[#D8E0EC] bg-[#F8FAFC] py-16 text-center">
        <EmptyIcon className="h-12 w-12 text-[#94A3B8]" />
        <h3 className="mt-4 text-lg font-bold text-[#071D49]">{emptyMessage}</h3>
        <p className="mt-2 text-sm text-[#64748B]">
          There are no items to display.
        </p>
      </div>
    );
  }

  return (
    <div className="overflow-x-auto rounded-xl border border-[#E2E8F0] mt-4">
      <table className="w-full text-left text-sm text-[#64748B]">
        <thead className="bg-[#F8FAFC] text-xs font-bold uppercase text-[#0F172A]">
          <tr>
            {columns.map((col, idx) => (
              <th key={idx} className="px-4 py-3 border-b border-[#E2E8F0] whitespace-nowrap">{col}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.map((row, rowIdx) => (
            <tr key={rowIdx} className="border-b border-[#E2E8F0] hover:bg-[#F8FAFC]">
              {columns.map((col, idx) => {
                if (col === 'Actions') {
                  return (
                    <td key={idx} className="px-4 py-3">
                      <div className="flex items-center gap-2">
                        {actions.slice(0, 3).map((act, i) => (
                          <button key={i} className="text-xs font-semibold text-[#1D4ED8] hover:underline whitespace-nowrap">
                            {act}
                          </button>
                        ))}
                      </div>
                    </td>
                  );
                }
                if (col === 'Status') {
                  return (
                    <td key={idx} className="px-4 py-3">
                      <StatusChip label={row.status || "WAITING"} tone="info" />
                    </td>
                  );
                }
                const fieldKey = col.toLowerCase().replace(/[^a-z0-9]/g, '_');
                return (
                  <td key={idx} className="px-4 py-3 whitespace-nowrap">
                    {row[fieldKey] || `${col} Data`}
                  </td>
                );
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ==========================================
// WORKSPACES
// ==========================================

function OverviewWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data, isLoading: loading, error } = useSchoolQuery<any>("/api/visitors/dashboard");

  return (
    <Panel title="Overview" description="Shows what needs attention today." icon={Home}>
      {error && (
        <div className="mb-6 rounded-xl border border-rose-200 bg-rose-50 p-4 flex justify-between items-center text-rose-700 text-sm">
          <div className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5" />
            {error instanceof Error ? error.message : String(error)}
          </div>
          <button className="bg-white border border-rose-200 px-3 py-1.5 rounded-lg font-semibold hover:bg-rose-100" onClick={() => window.location.reload()}>Retry</button>
        </div>
      )}
      <div className="grid gap-4 md:grid-cols-3 lg:grid-cols-5 mb-6">
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("queue")}>
          <div className="text-sm font-semibold text-[#64748B]">Parents Waiting</div>
          <div className="mt-1 text-2xl font-black text-rose-600">{loading ? "-" : (data?.parentsWaiting || 0)}</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("visitor_register")}>
          <div className="text-sm font-semibold text-[#64748B]">Visitors On Site</div>
          <div className="mt-1 text-2xl font-black text-blue-600">{loading ? "-" : (data?.active_visitors || 0)}</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("appointments")}>
          <div className="text-sm font-semibold text-[#64748B]">Today's Appts</div>
          <div className="mt-1 text-2xl font-black text-emerald-600">{loading ? "-" : (data?.today_appointments || 0)}</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("letters")}>
          <div className="text-sm font-semibold text-[#64748B]">Pending Letters</div>
          <div className="mt-1 text-2xl font-black text-amber-600">{loading ? "-" : (data?.pendingLetters || 0)}</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("calls_log")}>
          <div className="text-sm font-semibold text-[#64748B]">Missed Calls</div>
          <div className="mt-1 text-2xl font-black text-rose-600">{loading ? "-" : (data?.missedCalls || 0)}</div>
        </div>
      </div>
      <div className="grid gap-6 lg:grid-cols-2">
        <div className="rounded-xl border border-[#D8E0EC]">
          <div className="bg-[#F8FAFC] px-4 py-3 border-b border-[#D8E0EC] font-bold text-[#071D49]">
            Today's Front Desk Queue
          </div>
          <RealDataTable 
            columns={["Ticket No.", "Visitor", "Status", "Actions"]} 
            actions={["Call Next", "Escalate"]} 
            data={data?.records || []} 
            loading={loading}
            error={error?.message || null}
            emptyIcon={Users}
            emptyMessage="No one is waiting at reception."
          />
        </div>
        <div className="rounded-xl border border-[#D8E0EC]">
          <div className="bg-[#F8FAFC] px-4 py-3 border-b border-[#D8E0EC] font-bold text-[#071D49]">
            Urgent Follow-ups
          </div>
          <div className="p-4 text-sm text-[#64748B]">
            {loading ? "Loading..." : "No urgent items."}
          </div>
        </div>
      </div>
    </Panel>
  );
}

function QueueWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/visitors/logs");
  const data = rawData || [];

  return (
    <Panel title="Front Office Queue" description="Manages all people coming physically to the school office." icon={Users} actions={<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90"><Plus className="inline-block w-4 h-4 mr-1" /> Add Walk-in Ticket</button>}>
      <RealDataTable 
        columns={["Ticket No.","Time In","Name","Phone","Type","Purpose","Linked Student","Assigned To","Waiting Time","Status","Actions"]} 
        actions={["View","Call Next","Start Service","Assign Office","Mark Served","Escalate","Print Slip","Cancel"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={Users}
      />
    </Panel>
  );
}

function ParentDeskWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/communication/summary");
  const data = rawData || [];

  return (
    <Panel title="Parent & Guardian Desk" description="Handles parent-facing office requests." icon={UserCircle} actions={<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90"><Plus className="inline-block w-4 h-4 mr-1" /> Register Parent Request</button>}>
      <RealDataTable 
        columns={["Request No.","Parent Name","Phone","Student","Class","Request Type","Assigned To","Status","Date","Actions"]} 
        actions={["View","Assign","Reply","Mark Resolved","Create Appointment","Print Summary","Escalate"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={UserCircle}
      />
    </Panel>
  );
}

function StudentLookupWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/admissions");
  const data = rawData || [];

  return (
    <Panel title="Student Quick Lookup" description="Search and view student profiles." icon={Search} actions={
      <div className="relative w-64">
        <label className="flex min-h-10 items-center gap-3 rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] px-3 text-[#64748B] shadow-[inset_0_1px_2px_rgba(7,29,73,0.05)] focus-within:border-[#1D4ED8] focus-within:ring-1 focus-within:ring-[#1D4ED8] focus-within:bg-white transition">
          <Search className="h-4 w-4 shrink-0 text-[#94A3B8]" />
          <input
            className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none placeholder:text-[#94A3B8]"
            placeholder="Search by name, ID, class..."
          />
        </label>
      </div>
    }>
      <RealDataTable 
        columns={["Student Name","Admission No","Class","Status","Parent Name","Parent Phone","Actions"]} 
        actions={["View Profile","Print Clearance","Contact Parent"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={Search}
      />
    </Panel>
  );
}

function LogVisitorModal({ onClose, onSuccess }: { onClose: () => void, onSuccess?: () => void }) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  
  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);
    const formData = new FormData(e.currentTarget);
    try {
      await requestDashboardApi("/api/admin-command/frontoffice/visitors", {
        method: "POST",
        body: JSON.stringify({
          name: formData.get("name"),
          host: formData.get("host"),
          purpose: formData.get("purpose"),
        })
      });
      toast.success("Visitor logged successfully");
      if (onSuccess) onSuccess();
      onClose();
    } catch (err: any) {
      const msg = err.message || "Failed to log visitor";
      setError(msg);
      toast.error(msg);
    } finally {
      setIsSubmitting(false);
    }
  };
  return (
    <Modal title="New Visitor Sign-In" open={true} onClose={onClose} size="md">
      <form onSubmit={handleSubmit} className="p-6 space-y-4">
        {error && <div className="p-3 text-sm text-rose-700 bg-rose-50 rounded-xl">{error}</div>}
        <div>
          <label className="block text-sm font-bold text-[#071D49] mb-1">Visitor Name</label>
          <input name="name" required type="text" className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]" placeholder="Full name" />
        </div>
        <div>
          <label className="block text-sm font-bold text-[#071D49] mb-1">Host / Person to see</label>
          <input name="host" required type="text" className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]" placeholder="Staff name" />
        </div>
        <div>
          <label className="block text-sm font-bold text-[#071D49] mb-1">Purpose of Visit</label>
          <textarea name="purpose" required rows={3} className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]"></textarea>
        </div>
        <div className="mt-6 flex justify-end gap-3 pt-4 border-t border-[#D8E0EC]">
          <button type="button" onClick={onClose} className="rounded-xl px-4 py-2 text-sm font-bold text-[#64748B]">Cancel</button>
          <button disabled={isSubmitting} type="submit" className="rounded-xl bg-[#071D49] px-6 py-2 text-sm font-black text-white">
            {isSubmitting ? "Signing In..." : "Sign In"}
          </button>
        </div>
      </form>
    </Modal>
  );
}

function VisitorRegisterWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error, refetch } = useSchoolQuery<any[]>("/api/visitors/logs");
  const data = rawData || [];
  const { hasPermission } = usePermissions();
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <>
      <Panel title="Visitor Register" description="Digital logbook for all school visitors." icon={ClipboardList} actions={
        hasPermission('frontoffice:write') ? (
          <Button onClick={() => setIsModalOpen(true)}><Plus className="inline-block w-4 h-4 mr-1" /> New Visitor Sign-In</Button>
        ) : (
          <span className="text-xs font-bold text-[#64748B]">Restricted</span>
        )
      }>
        <RealDataTable 
          columns={["Time In","Visitor Name","Company/Org","Host","Purpose","Pass Number","Time Out","Status","Actions"]} 
          actions={["Sign Out","Print Pass","View Details"]} 
          data={data}
          loading={loading}
          error={error?.message || null}
          emptyIcon={ClipboardList}
        />
      </Panel>
      {isModalOpen && <LogVisitorModal onClose={() => setIsModalOpen(false)} onSuccess={() => refetch()} />}
    </>
  );
}

function CallsLogWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/communication/summary");
  const data = rawData || [];

  return (
    <Panel title="Calls Log" description="Record of incoming and outgoing calls." icon={Phone} actions={<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90"><Plus className="inline-block w-4 h-4 mr-1" /> Log New Call</button>}>
      <RealDataTable 
        columns={["Time","Direction","Caller/Recipient","Number","Subject","Duration","Action Required","Status","Actions"]} 
        actions={["View Notes","Mark Followed Up","Create Task"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={Phone}
      />
    </Panel>
  );
}

function ScheduleAppointmentModal({ onClose, onSuccess }: { onClose: () => void, onSuccess?: () => void }) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);
    const formData = new FormData(e.currentTarget);
    try {
      await requestDashboardApi("/api/admin-command/frontoffice/appointments", {
        method: "POST",
        body: JSON.stringify({
          visitorName: formData.get("visitorName"),
          date: formData.get("date"),
          time: formData.get("time"),
          host: formData.get("host"),
        })
      });
      toast.success("Appointment scheduled successfully");
      if (onSuccess) onSuccess();
      onClose();
    } catch (err: any) {
      const msg = err.message || "Failed to schedule appointment";
      setError(msg);
      toast.error(msg);
    } finally {
      setIsSubmitting(false);
    }
  };
  return (
    <Modal title="Schedule Appointment" open={true} onClose={onClose} size="md">
      <form onSubmit={handleSubmit} className="p-6 space-y-4">
        {error && <div className="p-3 text-sm text-rose-700 bg-rose-50 rounded-xl">{error}</div>}
        <div>
          <label className="block text-sm font-bold text-[#071D49] mb-1">Visitor/Parent Name</label>
          <input name="visitorName" required type="text" className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]" placeholder="Full name" />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-bold text-[#071D49] mb-1">Date</label>
            <input name="date" required type="date" className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]" />
          </div>
          <div>
            <label className="block text-sm font-bold text-[#071D49] mb-1">Time</label>
            <input name="time" required type="time" className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]" />
          </div>
        </div>
        <div>
          <label className="block text-sm font-bold text-[#071D49] mb-1">Host Staff</label>
          <input name="host" required type="text" className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]" placeholder="Staff name" />
        </div>
        <div className="mt-6 flex justify-end gap-3 pt-4 border-t border-[#D8E0EC]">
          <button type="button" onClick={onClose} className="rounded-xl px-4 py-2 text-sm font-bold text-[#64748B]">Cancel</button>
          <button disabled={isSubmitting} type="submit" className="rounded-xl bg-[#071D49] px-6 py-2 text-sm font-black text-white">
            {isSubmitting ? "Saving..." : "Schedule"}
          </button>
        </div>
      </form>
    </Modal>
  );
}

function AppointmentsWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error, refetch } = useSchoolQuery<any[]>("/api/visitors/appointments");
  const data = rawData || [];
  const { hasPermission } = usePermissions();
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <>
      <Panel title="Appointments" description="Manage scheduled visits and meetings." icon={Calendar} actions={
        hasPermission('frontoffice:write') ? (
          <Button onClick={() => setIsModalOpen(true)}><Plus className="inline-block w-4 h-4 mr-1" /> Schedule Appointment</Button>
        ) : (
          <span className="text-xs font-bold text-[#64748B]">Restricted</span>
        )
      }>
        <RealDataTable 
          columns={["Date","Time","Visitor Name","Host","Purpose","Status","Actions"]} 
          actions={["Check-In","Reschedule","Cancel"]} 
          data={data}
          loading={loading}
          error={error?.message || null}
          emptyIcon={Calendar}
        />
      </Panel>
      {isModalOpen && <ScheduleAppointmentModal onClose={() => setIsModalOpen(false)} onSuccess={() => refetch()} />}
    </>
  );
}

function LettersWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/communication/summary");
  const data = rawData || [];

  return (
    <Panel title="Letters & Documents" description="Manage official school correspondence." icon={FileText} actions={<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90"><Plus className="inline-block w-4 h-4 mr-1" /> Draft New Document</button>}>
      <RealDataTable 
        columns={["Date","Type","Reference","Recipient/Sender","Subject","Status","Actions"]} 
        actions={["View","Edit","Print","Archive"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={FileText}
      />
    </Panel>
  );
}

function AdmissionsWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/admissions/applications");
  const data = rawData || [];

  return (
    <Panel title="Admissions Handoff" description="Manage prospect inquiries and application handoffs." icon={UserPlus} actions={<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90"><Plus className="inline-block w-4 h-4 mr-1" /> New Inquiry</button>}>
      <RealDataTable 
        columns={["Date","Prospect Name","Grade Applied","Parent Phone","Channel","Status","Actions"]} 
        actions={["Send Forms","Follow Up","Hand off to Admissions"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={UserPlus}
      />
    </Panel>
  );
}

function CommunicationWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/communication/messages");
  const data = rawData || [];

  return (
    <Panel title="Communication Desk" description="Allows the Secretary to send approved office messages and announcements." icon={MessageSquare} actions={<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90"><Plus className="inline-block w-4 h-4 mr-1" /> New Message</button>}>
      <RealDataTable 
        columns={["Date","Recipient","Channel","Message Type","Status","Sent By","Actions"]} 
        actions={["View","Resend","Duplicate","Cancel","View Report"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={MessageSquare}
      />
    </Panel>
  );
}

function RecordDispatchModal({ onClose, onSuccess }: { onClose: () => void, onSuccess?: () => void }) {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError(null);
    const formData = new FormData(e.currentTarget);
    try {
      await requestDashboardApi("/api/admin-command/frontoffice/mail", {
        method: "POST",
        body: JSON.stringify({
          sender: formData.get("sender"),
          recipient: formData.get("recipient"),
          type: formData.get("type"),
        })
      });
      toast.success("Mail/Parcel recorded successfully");
      if (onSuccess) onSuccess();
      onClose();
    } catch (err: any) {
      const msg = err.message || "Failed to record mail/parcel";
      setError(msg);
      toast.error(msg);
    } finally {
      setIsSubmitting(false);
    }
  };
  return (
    <Modal title="Record Mail / Parcel" open={true} onClose={onClose} size="md">
      <form onSubmit={handleSubmit} className="p-6 space-y-4">
        {error && <div className="p-3 text-sm text-rose-700 bg-rose-50 rounded-xl">{error}</div>}
        <div>
          <label className="block text-sm font-bold text-[#071D49] mb-1">Sender</label>
          <input name="sender" required type="text" className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]" placeholder="Sender name or company" />
        </div>
        <div>
          <label className="block text-sm font-bold text-[#071D49] mb-1">Recipient</label>
          <input name="recipient" required type="text" className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]" placeholder="Staff or Department" />
        </div>
        <div>
          <label className="block text-sm font-bold text-[#071D49] mb-1">Item Type</label>
          <select name="type" required className="w-full rounded-xl border border-[#D8E0EC] p-3 text-sm outline-none focus:border-[#071D49]">
            <option value="">Select type...</option>
            <option value="letter">Official Letter</option>
            <option value="parcel">Parcel / Package</option>
            <option value="document">Document</option>
          </select>
        </div>
        <div className="mt-6 flex justify-end gap-3 pt-4 border-t border-[#D8E0EC]">
          <button type="button" onClick={onClose} className="rounded-xl px-4 py-2 text-sm font-bold text-[#64748B]">Cancel</button>
          <button disabled={isSubmitting} type="submit" className="rounded-xl bg-[#071D49] px-6 py-2 text-sm font-black text-white">
            {isSubmitting ? "Recording..." : "Record Item"}
          </button>
        </div>
      </form>
    </Modal>
  );
}

function MailParcelsWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error, refetch } = useSchoolQuery<any[]>("/api/operations/reports");
  const data = rawData || [];
  const { hasPermission } = usePermissions();
  const [isModalOpen, setIsModalOpen] = useState(false);

  return (
    <>
      <Panel title="Mail, Deliveries & Parcels" description="Tracks physical mail, deliveries, documents, and parcels entering or leaving school." icon={Package} actions={
        hasPermission('frontoffice:write') ? (
          <Button onClick={() => setIsModalOpen(true)}><Plus className="inline-block w-4 h-4 mr-1" /> Record Mail/Parcel</Button>
        ) : (
          <span className="text-xs font-bold text-[#64748B]">Restricted</span>
        )
      }>
        <RealDataTable 
          columns={["Ref No.","Date","Sender","Recipient","Type","Description","Status","Received By","Actions"]} 
          actions={["View","Assign Recipient","Notify Recipient","Mark Collected","Print Receipt","Mark Returned","Report Lost"]} 
          data={data}
          loading={loading}
          error={error?.message || null}
          emptyIcon={Package}
        />
      </Panel>
      {isModalOpen && <RecordDispatchModal onClose={() => setIsModalOpen(false)} onSuccess={() => refetch()} />}
    </>
  );
}

function StaffDirectoryWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any>("/api/hr/staff");
  const data = rawData?.items || rawData || [];

  return (
    <Panel title="Staff Directory" description="Staff contacts and office routing." icon={Contact} actions={null}>
      <RealDataTable 
        columns={["Staff Name","Role","Department","Phone","Email","Availability","Office","Actions"]} 
        actions={["View","Call","Send Message","Book Appointment","Assign Request"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={Contact}
      />
    </Panel>
  );
}

function LostFoundWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/operations/reports");
  const data = rawData || [];

  return (
    <Panel title="Lost & Found" description="Tracks items reported lost or found." icon={HelpCircle} actions={<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90"><Plus className="inline-block w-4 h-4 mr-1" /> Report Item</button>}>
      <RealDataTable 
        columns={["Item No.","Item Name","Category","Found/Reported By","Student Linked","Location","Date","Status","Actions"]} 
        actions={["View","Match","Contact Owner","Mark Claimed","Print Slip","Close"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={HelpCircle}
      />
    </Panel>
  );
}

function ReportsWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/dashboard/summary?role=secretary");
  const data = rawData || [];

  return (
    <Panel title="Reports" description="Generates front-office reports." icon={BarChart} actions={<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90"><Plus className="inline-block w-4 h-4 mr-1" /> Generate Report</button>}>
      <RealDataTable 
        columns={["Report Name","Date Range","Format","Status","Actions"]} 
        actions={["View","Download PDF","Download Excel","Print","Send to Principal"]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={BarChart}
      />
    </Panel>
  );
}

function SettingsWorkspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  const { data: rawData, isLoading: loading, error } = useSchoolQuery<any[]>("/api/school/settings");
  const data = rawData || [];

  return (
    <Panel title="Settings" description="Secretary-level preferences only." icon={Settings} actions={<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90"><Plus className="inline-block w-4 h-4 mr-1" /> Update Settings</button>}>
      <RealDataTable 
        columns={[]} 
        actions={[]} 
        data={data}
        loading={loading}
        error={error?.message || null}
        emptyIcon={Settings}
      />
    </Panel>
  );
}

// ==========================================
// MAIN SHELL
// ==========================================

export function SecretaryCommandCenterFull({ activeSection, routeMode }: { activeSection?: string; routeMode?: "hosted" | "public" }) {
  const [activeView, setActiveViewState] = useState<SecretaryView>((activeSection && activeSection !== "dashboard" ? activeSection : "overview") as SecretaryView);

  const setActiveView = (view: SecretaryView) => {
    setActiveViewState(view);
    const newPath = buildSchoolSectionHref("secretary", view, routeMode ?? "hosted");
    window.history.replaceState(null, "", newPath);
  };
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const activeNav = navItems.find((n) => n.id === activeView);

  const groups = Array.from(new Set(navItems.map((n) => n.group)));

  return (
    <div className="flex h-[calc(100vh-4rem)] bg-[#F1F5F9] font-sans text-[#0F172A] selection:bg-[#1D4ED8] selection:text-white rounded-xl overflow-hidden border border-[#D8E0EC]">
      {/* SIDEBAR (Desktop) */}
      <aside className="hidden w-72 shrink-0 flex-col border-r border-[#E2E8F0] bg-white lg:flex">
        <div className="flex h-16 shrink-0 items-center px-6 border-b border-[#E2E8F0]">
          <div className="flex items-center gap-3">
            <div className="grid h-8 w-8 place-items-center rounded-lg bg-[#1D4ED8] text-sm font-black text-white">S</div>
            <div>
              <p className="text-xs font-black uppercase tracking-wider text-[#1D4ED8]">MyShule</p>
              <h1 className="text-sm font-black text-[#0F172A]">Secretary Desk</h1>
            </div>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto px-4 py-6 custom-scrollbar">
          <div className="space-y-8">
            {groups.map((group) => (
              <div key={group}>
                <h3 className="px-2 text-xs font-black uppercase tracking-wider text-[#64748B] mb-2">{group}</h3>
                <nav className="space-y-1">
                  {navItems
                    .filter((n) => n.group === group)
                    .map((item) => {
                      const isActive = activeView === item.id;
                      const Icon = item.icon;
                      return (
                        <button
                          key={item.id}
                          onClick={() => setActiveView(item.id)}
                          className={cn(
                            "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold transition-all",
                            isActive
                              ? "bg-[#EEF5FF] text-[#1D4ED8]"
                              : "text-[#64748B] hover:bg-[#F8FAFC] hover:text-[#0F172A]"
                          )}
                        >
                          <Icon className={cn("h-5 w-5", isActive ? "text-[#1D4ED8]" : "text-[#94A3B8]")} />
                          {item.label}
                        </button>
                      );
                    })}
                </nav>
              </div>
            ))}
          </div>
        </div>
      </aside>

      {/* MAIN CONTENT */}
      <main className="flex min-w-0 flex-1 flex-col bg-[#F8FAFC]">
        {/* HEADER */}
        <header className="flex h-16 shrink-0 items-center justify-between border-b border-[#E2E8F0] bg-white px-4 sm:px-6">
          <div className="flex items-center gap-4">
            <button
              className="lg:hidden p-2 -ml-2 text-[#64748B] hover:bg-[#F8FAFC] rounded-lg"
              onClick={() => setIsMobileMenuOpen(true)}
            >
              <span className="sr-only">Open menu</span>
              <div className="space-y-1.5">
                <div className="h-0.5 w-6 bg-current rounded-full" />
                <div className="h-0.5 w-6 bg-current rounded-full" />
                <div className="h-0.5 w-6 bg-current rounded-full" />
              </div>
            </button>

            <div className="relative hidden sm:block">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-[#94A3B8]" />
              <input 
                type="text" 
                placeholder="Search students, parents, visitors..." 
                className="h-10 w-80 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] pl-10 pr-4 text-sm font-semibold text-[#0F172A] placeholder:text-[#94A3B8] focus:border-[#1D4ED8] focus:bg-white focus:outline-none focus:ring-1 focus:ring-[#1D4ED8]"
              />
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button className="relative rounded-full p-2 text-[#64748B] hover:bg-[#F8FAFC] transition">
              <Bell className="h-5 w-5" />
              <span className="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-rose-500 border-2 border-white" />
            </button>
          </div>
        </header>

        {/* WORKSPACE AREA */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8">
          <div className="mx-auto max-w-6xl">
            {activeView === "overview" && <OverviewWorkspace onNavigate={setActiveView} />}
            {activeView === "queue" && <QueueWorkspace onNavigate={setActiveView} />}
            {activeView === "parent_desk" && <ParentDeskWorkspace onNavigate={setActiveView} />}
            {activeView === "student_lookup" && <StudentLookupWorkspace onNavigate={setActiveView} />}
            {activeView === "visitor_register" && <VisitorRegisterWorkspace onNavigate={setActiveView} />}
            {activeView === "calls_log" && <CallsLogWorkspace onNavigate={setActiveView} />}
            {activeView === "appointments" && <AppointmentsWorkspace onNavigate={setActiveView} />}
            {activeView === "letters" && <LettersWorkspace onNavigate={setActiveView} />}
            {activeView === "admissions" && <AdmissionsWorkspace onNavigate={setActiveView} />}
            {activeView === "communication" && <CommunicationWorkspace onNavigate={setActiveView} />}
            {activeView === "mail_parcels" && <MailParcelsWorkspace onNavigate={setActiveView} />}
            {activeView === "staff_directory" && <StaffDirectoryWorkspace onNavigate={setActiveView} />}
            {activeView === "lost_found" && <LostFoundWorkspace onNavigate={setActiveView} />}
            {activeView === "reports" && <ReportsWorkspace onNavigate={setActiveView} />}
            {activeView === "settings" && <SettingsWorkspace onNavigate={setActiveView} />}
          </div>
        </div>
      </main>

      {/* MOBILE MENU OVERLAY */}
      {isMobileMenuOpen && (
        <div className="fixed inset-0 z-50 lg:hidden">
          <div className="fixed inset-0 bg-[#0F172A]/40 backdrop-blur-sm" onClick={() => setIsMobileMenuOpen(false)} />
          <div className="fixed inset-y-0 left-0 w-72 bg-white shadow-2xl flex flex-col">
            <div className="flex h-16 shrink-0 items-center justify-between px-6 border-b border-[#E2E8F0]">
              <div className="flex items-center gap-3">
                <div className="grid h-8 w-8 place-items-center rounded-lg bg-[#1D4ED8] text-sm font-black text-white">S</div>
                <div>
                  <h1 className="text-sm font-black text-[#0F172A]">Secretary Desk</h1>
                </div>
              </div>
              <button onClick={() => setIsMobileMenuOpen(false)} className="p-2 -mr-2 text-[#64748B]">
                <X className="h-5 w-5" />
              </button>
            </div>
            
            <div className="flex-1 overflow-y-auto px-4 py-6">
              <div className="space-y-8">
                {groups.map((group) => (
                  <div key={group}>
                    <h3 className="px-2 text-xs font-black uppercase tracking-wider text-[#64748B] mb-2">{group}</h3>
                    <nav className="space-y-1">
                      {navItems
                        .filter((n) => n.group === group)
                        .map((item) => {
                          const isActive = activeView === item.id;
                          const Icon = item.icon;
                          return (
                            <button
                              key={item.id}
                              onClick={() => {
                                setActiveView(item.id);
                                setIsMobileMenuOpen(false);
                              }}
                              className={cn(
                                "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold",
                                isActive
                                  ? "bg-[#EEF5FF] text-[#1D4ED8]"
                                  : "text-[#64748B]"
                              )}
                            >
                              <Icon className={cn("h-5 w-5", isActive ? "text-[#1D4ED8]" : "text-[#94A3B8]")} />
                              {item.label}
                            </button>
                          );
                        })}
                    </nav>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
