const schoolNavMap: Record<SchoolExperienceRole, ExperienceNavItem[]> = {
  "principal": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "setup-checklist", label: "Setup Checklist", href: toSchoolPath("setup-checklist"), icon: Settings },
    { id: "school-profile", label: "School Profile", href: toSchoolPath("school-profile"), icon: Building2 },
    { id: "academic-setup", label: "Academic Setup", href: toSchoolPath("academic-setup"), icon: GraduationCap },
    { id: "classes-streams", label: "Classes & Streams", href: toSchoolPath("classes-streams"), icon: Building2 },
    { id: "subjects-departments", label: "Subjects & Departments", href: toSchoolPath("subjects-departments"), icon: BookOpenCheck },
    { id: "staff-roles", label: "Staff & Roles", href: toSchoolPath("staff-roles"), icon: Users },
    { id: "students", label: "Students", href: toSchoolPath("students"), icon: Users },
    { id: "attendance", label: "Attendance", href: toSchoolPath("attendance"), icon: CalendarDays },
    { id: "academics", label: "Academics", href: toSchoolPath("academics"), icon: GraduationCap },
    { id: "exams-report-cards", label: "Exams & Report Cards", href: toSchoolPath("exams-report-cards"), icon: FileSpreadsheet },
    { id: "finance-overview", label: "Finance Overview", href: toSchoolPath("finance-overview"), icon: LayoutGrid },
    { id: "discipline", label: "Discipline", href: toSchoolPath("discipline"), icon: ShieldAlert },
    { id: "communication", label: "Communication", href: toSchoolPath("communication"), icon: MessageSquareText },
    { id: "approvals", label: "Approvals", href: toSchoolPath("approvals"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    { id: "settings", label: "Settings", href: toSchoolPath("settings"), icon: Settings },
    ...supportSidebarItems,
  ],
  "deputy-principal": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "daily-operations", label: "Daily Operations", href: toSchoolPath("daily-operations"), icon: ClipboardList },
    { id: "attendance-monitoring", label: "Attendance Monitoring", href: toSchoolPath("attendance-monitoring"), icon: CalendarDays },
    { id: "staff-duty-roster", label: "Staff Duty Roster", href: toSchoolPath("staff-duty-roster"), icon: Users },
    { id: "discipline-coordination", label: "Discipline Coordination", href: toSchoolPath("discipline-coordination"), icon: ShieldAlert },
    { id: "student-welfare", label: "Student Welfare", href: toSchoolPath("student-welfare"), icon: Users },
    { id: "approvals", label: "Approvals", href: toSchoolPath("approvals"), icon: ClipboardList },
    { id: "communication", label: "Communication", href: toSchoolPath("communication"), icon: MessageSquareText },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "admin": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "data-setup", label: "Data Setup", href: toSchoolPath("data-setup"), icon: Settings },
    { id: "students", label: "Students", href: toSchoolPath("students"), icon: Users },
    { id: "parents", label: "Parents", href: toSchoolPath("parents"), icon: Users },
    { id: "staff-records", label: "Staff Records", href: toSchoolPath("staff-records"), icon: Users },
    { id: "classes-streams", label: "Classes & Streams", href: toSchoolPath("classes-streams"), icon: Building2 },
    { id: "subjects", label: "Subjects", href: toSchoolPath("subjects"), icon: BookOpenCheck },
    { id: "imports", label: "Imports", href: toSchoolPath("imports"), icon: ClipboardList },
    { id: "data-quality", label: "Data Quality", href: toSchoolPath("data-quality"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    { id: "settings", label: "Settings", href: toSchoolPath("settings"), icon: Settings },
    ...supportSidebarItems,
  ],
  "dean-academics": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "curriculum-coverage", label: "Curriculum Coverage", href: toSchoolPath("curriculum-coverage"), icon: BookOpenCheck },
    { id: "lesson-plans", label: "Lesson Plans", href: toSchoolPath("lesson-plans"), icon: FileSpreadsheet },
    { id: "lesson-logs", label: "Lesson Logs", href: toSchoolPath("lesson-logs"), icon: FileSpreadsheet },
    { id: "teacher-workload", label: "Teacher Workload", href: toSchoolPath("teacher-workload"), icon: ClipboardList },
    { id: "department-performance", label: "Department Performance", href: toSchoolPath("department-performance"), icon: ClipboardList },
    { id: "assessments", label: "Assessments", href: toSchoolPath("assessments"), icon: GraduationCap },
    { id: "academic-interventions", label: "Academic Interventions", href: toSchoolPath("academic-interventions"), icon: GraduationCap },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "exams-manager": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "exam-setup", label: "Exam Setup", href: toSchoolPath("exam-setup"), icon: GraduationCap },
    { id: "exam-timetable", label: "Exam Timetable", href: toSchoolPath("exam-timetable"), icon: GraduationCap },
    { id: "marks-entry", label: "Marks Entry", href: toSchoolPath("marks-entry"), icon: GraduationCap },
    { id: "moderation", label: "Moderation", href: toSchoolPath("moderation"), icon: ClipboardList },
    { id: "report-cards", label: "Report Cards", href: toSchoolPath("report-cards"), icon: FileSpreadsheet },
    { id: "publishing", label: "Publishing", href: toSchoolPath("publishing"), icon: ClipboardList },
    { id: "analysis", label: "Analysis", href: toSchoolPath("analysis"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "hod": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "department-teachers", label: "Department Teachers", href: toSchoolPath("department-teachers"), icon: ClipboardList },
    { id: "subject-allocation", label: "Subject Allocation", href: toSchoolPath("subject-allocation"), icon: BookOpenCheck },
    { id: "coverage-review", label: "Coverage Review", href: toSchoolPath("coverage-review"), icon: ClipboardList },
    { id: "lesson-plans", label: "Lesson Plans", href: toSchoolPath("lesson-plans"), icon: FileSpreadsheet },
    { id: "marks-moderation", label: "Marks Moderation", href: toSchoolPath("marks-moderation"), icon: GraduationCap },
    { id: "resource-requests", label: "Resource Requests", href: toSchoolPath("resource-requests"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "teacher": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "my-timetable", label: "My Timetable", href: toSchoolPath("my-timetable"), icon: CalendarDays },
    { id: "attendance", label: "Attendance", href: toSchoolPath("attendance"), icon: CalendarDays },
    { id: "subjects-classes", label: "Subjects & Classes", href: toSchoolPath("subjects-classes"), icon: Building2 },
    { id: "lesson-plans", label: "Lesson Plans", href: toSchoolPath("lesson-plans"), icon: FileSpreadsheet },
    { id: "lesson-logs", label: "Lesson Logs", href: toSchoolPath("lesson-logs"), icon: FileSpreadsheet },
    { id: "assignments-homework", label: "Assignments/Homework", href: toSchoolPath("assignments-homework"), icon: ClipboardList },
    { id: "marks-entry", label: "Marks Entry", href: toSchoolPath("marks-entry"), icon: GraduationCap },
    { id: "student-notes", label: "Student Notes", href: toSchoolPath("student-notes"), icon: Users },
    { id: "resource-requests", label: "Resource Requests", href: toSchoolPath("resource-requests"), icon: ClipboardList },
    { id: "messages", label: "Messages", href: toSchoolPath("messages"), icon: MessageSquareText },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "class-teacher": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "my-class", label: "My Class", href: toSchoolPath("my-class"), icon: Building2 },
    { id: "attendance-follow-up", label: "Attendance Follow-up", href: toSchoolPath("attendance-follow-up"), icon: CalendarDays },
    { id: "learner-profiles", label: "Learner Profiles", href: toSchoolPath("learner-profiles"), icon: ClipboardList },
    { id: "parent-contacts", label: "Parent Contacts", href: toSchoolPath("parent-contacts"), icon: Users },
    { id: "class-academics", label: "Class Academics", href: toSchoolPath("class-academics"), icon: Building2 },
    { id: "report-comments", label: "Report Comments", href: toSchoolPath("report-comments"), icon: FileSpreadsheet },
    { id: "discipline-follow-up", label: "Discipline Follow-up", href: toSchoolPath("discipline-follow-up"), icon: ShieldAlert },
    { id: "welfare-notes", label: "Welfare Notes", href: toSchoolPath("welfare-notes"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "accountant": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "fee-structures", label: "Fee Structures", href: toSchoolPath("fee-structures"), icon: CircleDollarSign },
    { id: "invoices", label: "Invoices", href: toSchoolPath("invoices"), icon: CircleDollarSign },
    { id: "payments", label: "Payments", href: toSchoolPath("payments"), icon: CircleDollarSign },
    { id: "receipts", label: "Receipts", href: toSchoolPath("receipts"), icon: CircleDollarSign },
    { id: "m-pesa-reconciliation", label: "M-Pesa Reconciliation", href: toSchoolPath("m-pesa-reconciliation"), icon: ClipboardList },
    { id: "arrears", label: "Arrears", href: toSchoolPath("arrears"), icon: CircleDollarSign },
    { id: "waivers-discounts", label: "Waivers & Discounts", href: toSchoolPath("waivers-discounts"), icon: ClipboardList },
    { id: "expenses", label: "Expenses", href: toSchoolPath("expenses"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    { id: "settings", label: "Settings", href: toSchoolPath("settings"), icon: Settings },
    ...supportSidebarItems,
  ],
  "secretary": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "reception-queue", label: "Reception Queue", href: toSchoolPath("reception-queue"), icon: ClipboardList },
    { id: "visitors", label: "Visitors", href: toSchoolPath("visitors"), icon: ClipboardList },
    { id: "appointments", label: "Appointments", href: toSchoolPath("appointments"), icon: ClipboardList },
    { id: "calls-log", label: "Calls Log", href: toSchoolPath("calls-log"), icon: FileSpreadsheet },
    { id: "letters-documents", label: "Letters & Documents", href: toSchoolPath("letters-documents"), icon: ClipboardList },
    { id: "parent-messages", label: "Parent Messages", href: toSchoolPath("parent-messages"), icon: Users },
    { id: "student-clearance", label: "Student Clearance", href: toSchoolPath("student-clearance"), icon: Users },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "admissions": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "applications", label: "Applications", href: toSchoolPath("applications"), icon: ClipboardList },
    { id: "interviews", label: "Interviews", href: toSchoolPath("interviews"), icon: ClipboardList },
    { id: "admissions", label: "Admissions", href: toSchoolPath("admissions"), icon: ClipboardList },
    { id: "class-placement", label: "Class Placement", href: toSchoolPath("class-placement"), icon: Building2 },
    { id: "documents", label: "Documents", href: toSchoolPath("documents"), icon: ClipboardList },
    { id: "parent-linking", label: "Parent Linking", href: toSchoolPath("parent-linking"), icon: Users },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "discipline-master": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "incident-log", label: "Incident Log", href: toSchoolPath("incident-log"), icon: FileSpreadsheet },
    { id: "cases", label: "Cases", href: toSchoolPath("cases"), icon: ClipboardList },
    { id: "actions-sanctions", label: "Actions & Sanctions", href: toSchoolPath("actions-sanctions"), icon: ClipboardList },
    { id: "parent-summons", label: "Parent Summons", href: toSchoolPath("parent-summons"), icon: Users },
    { id: "counselling-referrals", label: "Counselling Referrals", href: toSchoolPath("counselling-referrals"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "guidance-counselling": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "referrals", label: "Referrals", href: toSchoolPath("referrals"), icon: ClipboardList },
    { id: "sessions", label: "Sessions", href: toSchoolPath("sessions"), icon: ClipboardList },
    { id: "follow-ups", label: "Follow-ups", href: toSchoolPath("follow-ups"), icon: ClipboardList },
    { id: "welfare-notes", label: "Welfare Notes", href: toSchoolPath("welfare-notes"), icon: ClipboardList },
    { id: "parent-engagement", label: "Parent Engagement", href: toSchoolPath("parent-engagement"), icon: Users },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "nurse": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "sick-bay-queue", label: "Sick Bay Queue", href: toSchoolPath("sick-bay-queue"), icon: ClipboardList },
    { id: "visits", label: "Visits", href: toSchoolPath("visits"), icon: ClipboardList },
    { id: "medicine-inventory", label: "Medicine Inventory", href: toSchoolPath("medicine-inventory"), icon: Boxes },
    { id: "dispensing-log", label: "Dispensing Log", href: toSchoolPath("dispensing-log"), icon: FileSpreadsheet },
    { id: "parent-notifications", label: "Parent Notifications", href: toSchoolPath("parent-notifications"), icon: Users },
    { id: "health-reports", label: "Health Reports", href: toSchoolPath("health-reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "librarian": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "books", label: "Books", href: toSchoolPath("books"), icon: Library },
    { id: "issue-book", label: "Issue Book", href: toSchoolPath("issue-book"), icon: Library },
    { id: "return-book", label: "Return Book", href: toSchoolPath("return-book"), icon: Library },
    { id: "borrowers", label: "Borrowers", href: toSchoolPath("borrowers"), icon: ClipboardList },
    { id: "overdue-books", label: "Overdue Books", href: toSchoolPath("overdue-books"), icon: Library },
    { id: "fines-lost-damaged", label: "Fines/Lost/Damaged", href: toSchoolPath("fines-lost-damaged"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "storekeeper": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "items", label: "Items", href: toSchoolPath("items"), icon: Boxes },
    { id: "stock-in", label: "Stock In", href: toSchoolPath("stock-in"), icon: Boxes },
    { id: "stock-issue", label: "Stock Issue", href: toSchoolPath("stock-issue"), icon: Boxes },
    { id: "requests", label: "Requests", href: toSchoolPath("requests"), icon: ClipboardList },
    { id: "low-stock", label: "Low Stock", href: toSchoolPath("low-stock"), icon: Boxes },
    { id: "stocktake", label: "Stocktake", href: toSchoolPath("stocktake"), icon: Boxes },
    { id: "damaged-missing", label: "Damaged/Missing", href: toSchoolPath("damaged-missing"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "procurement-officer": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "items", label: "Items", href: toSchoolPath("items"), icon: Boxes },
    { id: "stock-in", label: "Stock In", href: toSchoolPath("stock-in"), icon: Boxes },
    { id: "stock-issue", label: "Stock Issue", href: toSchoolPath("stock-issue"), icon: Boxes },
    { id: "requests", label: "Requests", href: toSchoolPath("requests"), icon: ClipboardList },
    { id: "low-stock", label: "Low Stock", href: toSchoolPath("low-stock"), icon: Boxes },
    { id: "stocktake", label: "Stocktake", href: toSchoolPath("stocktake"), icon: Boxes },
    { id: "damaged-missing", label: "Damaged/Missing", href: toSchoolPath("damaged-missing"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "boarding-master": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "hostels", label: "Hostels", href: toSchoolPath("hostels"), icon: ClipboardList },
    { id: "rooms-beds", label: "Rooms & Beds", href: toSchoolPath("rooms-beds"), icon: ClipboardList },
    { id: "allocation", label: "Allocation", href: toSchoolPath("allocation"), icon: ClipboardList },
    { id: "boarding-attendance", label: "Boarding Attendance", href: toSchoolPath("boarding-attendance"), icon: CalendarDays },
    { id: "leave-exit", label: "Leave/Exit", href: toSchoolPath("leave-exit"), icon: ClipboardList },
    { id: "incidents", label: "Incidents", href: toSchoolPath("incidents"), icon: ShieldAlert },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "security-officer": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "gate-register", label: "Gate Register", href: toSchoolPath("gate-register"), icon: ClipboardList },
    { id: "visitors", label: "Visitors", href: toSchoolPath("visitors"), icon: ClipboardList },
    { id: "student-exit-passes", label: "Student Exit Passes", href: toSchoolPath("student-exit-passes"), icon: Users },
    { id: "staff-movement", label: "Staff Movement", href: toSchoolPath("staff-movement"), icon: Users },
    { id: "incidents", label: "Incidents", href: toSchoolPath("incidents"), icon: ShieldAlert },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "transport-manager": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "routes", label: "Routes", href: toSchoolPath("routes"), icon: BusFront },
    { id: "vehicles", label: "Vehicles", href: toSchoolPath("vehicles"), icon: BusFront },
    { id: "drivers", label: "Drivers", href: toSchoolPath("drivers"), icon: ClipboardList },
    { id: "student-transport-list", label: "Student Transport List", href: toSchoolPath("student-transport-list"), icon: Users },
    { id: "trips", label: "Trips", href: toSchoolPath("trips"), icon: ClipboardList },
    { id: "fuel-maintenance", label: "Fuel & Maintenance", href: toSchoolPath("fuel-maintenance"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "laboratory-technician": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "lab-inventory", label: "Lab Inventory", href: toSchoolPath("lab-inventory"), icon: FlaskConical },
    { id: "apparatus-issue", label: "Apparatus Issue", href: toSchoolPath("apparatus-issue"), icon: FlaskConical },
    { id: "chemicals", label: "Chemicals", href: toSchoolPath("chemicals"), icon: FlaskConical },
    { id: "lab-timetable", label: "Lab Timetable", href: toSchoolPath("lab-timetable"), icon: CalendarDays },
    { id: "safety-incidents", label: "Safety Incidents", href: toSchoolPath("safety-incidents"), icon: ShieldAlert },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
  "ict-manager": [
    { id: "overview", label: "Overview", href: toSchoolPath("overview"), icon: LayoutGrid },
    { id: "assets", label: "Assets", href: toSchoolPath("assets"), icon: Boxes },
    { id: "asset-assignment", label: "Asset Assignment", href: toSchoolPath("asset-assignment"), icon: Boxes },
    { id: "maintenance", label: "Maintenance", href: toSchoolPath("maintenance"), icon: ClipboardList },
    { id: "loans-returns", label: "Loans & Returns", href: toSchoolPath("loans-returns"), icon: ClipboardList },
    { id: "facilities-issues", label: "Facilities Issues", href: toSchoolPath("facilities-issues"), icon: ClipboardList },
    { id: "reports", label: "Reports", href: toSchoolPath("reports"), icon: FileSpreadsheet },
    ...supportSidebarItems,
  ],
};