const fs = require('fs');

const workspaces = [
  { id: "overview", label: "Overview", icon: "Home", group: "Dashboard", desc: "Front office queue, active visitors, today's appointments, and pending follow-ups." },
  { id: "queue", label: "Front Office Queue", icon: "Users", group: "Reception", desc: "Manage walk-ins, parents, and visitor queues. Assign to offices." },
  { id: "parent_desk", label: "Parent & Guardian Desk", icon: "UserCircle", group: "Reception", desc: "Handle parent requests, fee statements, and contact updates." },
  { id: "student_lookup", label: "Student Quick Lookup", icon: "Search", group: "Reception", desc: "Quick read-only access to student class, parent contacts, and status." },
  { id: "visitor_register", label: "Visitor Register", icon: "ClipboardList", group: "Reception", desc: "Check-in visitors, print passes, and manage on-site non-parent visitors." },
  { id: "calls_log", label: "Calls Log", icon: "Phone", group: "Communication", desc: "Record incoming/outgoing office calls and set up follow-ups." },
  { id: "appointments", label: "Appointments", icon: "Calendar", group: "Communication", desc: "Schedule and track meetings between parents/visitors and school staff." },
  { id: "letters", label: "Letters & Documents", icon: "FileText", group: "Office", desc: "Generate, approve, and print official school letters and documents." },
  { id: "admissions", label: "Admissions Handoff", icon: "UserPlus", group: "Office", desc: "Record admission walk-ins, schedule interviews, and forward to admissions officer." },
  { id: "communication", label: "Communication Desk", icon: "MessageSquare", group: "Communication", desc: "Send approved SMS, email, and portal notices to parents and staff." },
  { id: "mail_parcels", label: "Mail, Deliveries & Parcels", icon: "Package", group: "Office", desc: "Track incoming and outgoing physical mail, deliveries, and parcels." },
  { id: "staff_directory", label: "Staff Directory", icon: "Contact", group: "Reference", desc: "Internal staff contacts, availability, and office routing." },
  { id: "lost_found", label: "Lost & Found", icon: "HelpCircle", group: "Office", desc: "Report and track lost items or items found within the school." },
  { id: "reports", label: "Reports", icon: "BarChart", group: "System", desc: "Generate daily queue, visitor, calls, and appointment reports." },
  { id: "settings", label: "Settings", icon: "Settings", group: "System", desc: "Configure queue defaults, letter templates, and front-office preferences." }
];

let tsx = `// GENERATED BY scaffold_secretary.js
"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import {
  AlertTriangle,
  BarChart,
  Bell,
  Calendar,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  ClipboardList,
  Contact,
  Download,
  FileText,
  Filter,
  HelpCircle,
  Home,
  MessageSquare,
  MoreHorizontal,
  Package,
  Phone,
  Plus,
  Printer,
  Search,
  Settings,
  UserCircle,
  UserPlus,
  Users,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

import {
  getCurrentSchoolId,
  publishSchoolOperationalEvent,
} from "@/lib/school/school-operational-store";

type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type SecretaryView = ${workspaces.map(w => `"${w.id}"`).join(" | ")};

type NavItem = {
  id: SecretaryView;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
${workspaces.map(w => `  { id: "${w.id}", label: "${w.label}", icon: ${w.icon}, group: "${w.group}" },`).join("\n")}
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold whitespace-nowrap", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full shrink-0", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions && <div className="shrink-0">{actions}</div>}
      </div>
      {children}
    </section>
  );
}

// ----------------------------------------------------------------------
// WORKSPACE COMPONENTS
// ----------------------------------------------------------------------
`;

workspaces.forEach(w => {
  let actions = '';
  if (w.id === 'queue') actions = '<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90">Add Walk-in</button>';
  if (w.id === 'parent_desk') actions = '<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90">Register Request</button>';
  if (w.id === 'visitor_register') actions = '<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90">Check In Visitor</button>';
  if (w.id === 'appointments') actions = '<button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-bold text-white transition hover:bg-[#071D49]/90">New Appointment</button>';

  const compName = w.id.split('_').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
  tsx += `
function ${compName}Workspace({ onNavigate }: { onNavigate: (v: SecretaryView) => void }) {
  return (
    <Panel title="${w.label}" description="${w.desc}" icon={${w.icon}} actions={${actions ? actions : 'null'}}>
      <div className="flex flex-col items-center justify-center rounded-xl border border-dashed border-[#D8E0EC] bg-[#F8FAFC] py-16 text-center">
        <${w.icon} className="h-12 w-12 text-[#94A3B8]" />
        <h3 className="mt-4 text-lg font-bold text-[#071D49]">No records found</h3>
        <p className="mt-2 text-sm text-[#64748B]">
          There are no items to display in the ${w.label.toLowerCase()} workspace yet.
        </p>
      </div>
    </Panel>
  );
}
`;
});

tsx += `
// ----------------------------------------------------------------------
// MAIN SHELL
// ----------------------------------------------------------------------

export function SecretaryCommandCenterFull({ routeMode }: { routeMode?: "hosted" | "public" }) {
  const [activeView, setActiveView] = useState<SecretaryView>("overview");
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);

  const activeNav = navItems.find((n) => n.id === activeView);

  const groups = Array.from(new Set(navItems.map((n) => n.group)));

  return (
    <div className="flex h-[calc(100vh-4rem)] bg-[#F1F5F9] font-sans text-[#0F172A] selection:bg-[#1D4ED8] selection:text-white rounded-xl overflow-hidden border border-[#D8E0EC]">
      {/* SIDEBAR (Desktop) */}
      <aside className="hidden w-72 shrink-0 flex-col border-r border-[#E2E8F0] bg-white lg:flex">
        <div className="flex h-16 shrink-0 items-center px-6 border-b border-[#E2E8F0]">
          <div className="flex items-center gap-3">
            <div className="grid h-8 w-8 place-items-center rounded-lg bg-[#1D4ED8] text-sm font-black text-white">S</div>
            <div>
              <p className="text-xs font-black uppercase tracking-wider text-[#1D4ED8]">MyShule</p>
              <h1 className="text-sm font-black text-[#0F172A]">Secretary Desk</h1>
            </div>
          </div>
        </div>

        <div className="flex-1 overflow-y-auto px-4 py-6 custom-scrollbar">
          <div className="space-y-8">
            {groups.map((group) => (
              <div key={group}>
                <h3 className="px-2 text-xs font-black uppercase tracking-wider text-[#64748B] mb-2">{group}</h3>
                <nav className="space-y-1">
                  {navItems
                    .filter((n) => n.group === group)
                    .map((item) => {
                      const isActive = activeView === item.id;
                      const Icon = item.icon;
                      return (
                        <button
                          key={item.id}
                          onClick={() => setActiveView(item.id)}
                          className={cn(
                            "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold transition-all",
                            isActive
                              ? "bg-[#EEF5FF] text-[#1D4ED8]"
                              : "text-[#64748B] hover:bg-[#F8FAFC] hover:text-[#0F172A]"
                          )}
                        >
                          <Icon className={cn("h-5 w-5", isActive ? "text-[#1D4ED8]" : "text-[#94A3B8]")} />
                          {item.label}
                        </button>
                      );
                    })}
                </nav>
              </div>
            ))}
          </div>
        </div>
      </aside>

      {/* MAIN CONTENT */}
      <main className="flex min-w-0 flex-1 flex-col bg-[#F8FAFC]">
        {/* HEADER */}
        <header className="flex h-16 shrink-0 items-center justify-between border-b border-[#E2E8F0] bg-white px-4 sm:px-6">
          <div className="flex items-center gap-4">
            <button
              className="lg:hidden p-2 -ml-2 text-[#64748B] hover:bg-[#F8FAFC] rounded-lg"
              onClick={() => setIsMobileMenuOpen(true)}
            >
              <span className="sr-only">Open menu</span>
              <div className="space-y-1.5">
                <div className="h-0.5 w-6 bg-current rounded-full" />
                <div className="h-0.5 w-6 bg-current rounded-full" />
                <div className="h-0.5 w-6 bg-current rounded-full" />
              </div>
            </button>

            <div className="relative hidden sm:block">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-[#94A3B8]" />
              <input 
                type="text" 
                placeholder="Search students, parents, visitors..." 
                className="h-10 w-80 rounded-xl border border-[#E2E8F0] bg-[#F8FAFC] pl-10 pr-4 text-sm font-semibold text-[#0F172A] placeholder:text-[#94A3B8] focus:border-[#1D4ED8] focus:bg-white focus:outline-none focus:ring-1 focus:ring-[#1D4ED8]"
              />
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button className="relative rounded-full p-2 text-[#64748B] hover:bg-[#F8FAFC] transition">
              <Bell className="h-5 w-5" />
              <span className="absolute right-1.5 top-1.5 h-2 w-2 rounded-full bg-rose-500 border-2 border-white" />
            </button>
          </div>
        </header>

        {/* WORKSPACE AREA */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-6 lg:p-8">
          <div className="mx-auto max-w-6xl">
            {activeView === "overview" && <OverviewWorkspace onNavigate={setActiveView} />}
            {activeView === "queue" && <QueueWorkspace onNavigate={setActiveView} />}
            {activeView === "parent_desk" && <ParentDeskWorkspace onNavigate={setActiveView} />}
            {activeView === "student_lookup" && <StudentLookupWorkspace onNavigate={setActiveView} />}
            {activeView === "visitor_register" && <VisitorRegisterWorkspace onNavigate={setActiveView} />}
            {activeView === "calls_log" && <CallsLogWorkspace onNavigate={setActiveView} />}
            {activeView === "appointments" && <AppointmentsWorkspace onNavigate={setActiveView} />}
            {activeView === "letters" && <LettersWorkspace onNavigate={setActiveView} />}
            {activeView === "admissions" && <AdmissionsWorkspace onNavigate={setActiveView} />}
            {activeView === "communication" && <CommunicationWorkspace onNavigate={setActiveView} />}
            {activeView === "mail_parcels" && <MailParcelsWorkspace onNavigate={setActiveView} />}
            {activeView === "staff_directory" && <StaffDirectoryWorkspace onNavigate={setActiveView} />}
            {activeView === "lost_found" && <LostFoundWorkspace onNavigate={setActiveView} />}
            {activeView === "reports" && <ReportsWorkspace onNavigate={setActiveView} />}
            {activeView === "settings" && <SettingsWorkspace onNavigate={setActiveView} />}
          </div>
        </div>
      </main>

      {/* MOBILE MENU OVERLAY */}
      {isMobileMenuOpen && (
        <div className="fixed inset-0 z-50 lg:hidden">
          <div className="fixed inset-0 bg-[#0F172A]/40 backdrop-blur-sm" onClick={() => setIsMobileMenuOpen(false)} />
          <div className="fixed inset-y-0 left-0 w-72 bg-white shadow-2xl flex flex-col">
            <div className="flex h-16 shrink-0 items-center justify-between px-6 border-b border-[#E2E8F0]">
              <div className="flex items-center gap-3">
                <div className="grid h-8 w-8 place-items-center rounded-lg bg-[#1D4ED8] text-sm font-black text-white">S</div>
                <div>
                  <h1 className="text-sm font-black text-[#0F172A]">Secretary Desk</h1>
                </div>
              </div>
              <button onClick={() => setIsMobileMenuOpen(false)} className="p-2 -mr-2 text-[#64748B]">
                <X className="h-5 w-5" />
              </button>
            </div>
            
            <div className="flex-1 overflow-y-auto px-4 py-6">
              <div className="space-y-8">
                {groups.map((group) => (
                  <div key={group}>
                    <h3 className="px-2 text-xs font-black uppercase tracking-wider text-[#64748B] mb-2">{group}</h3>
                    <nav className="space-y-1">
                      {navItems
                        .filter((n) => n.group === group)
                        .map((item) => {
                          const isActive = activeView === item.id;
                          const Icon = item.icon;
                          return (
                            <button
                              key={item.id}
                              onClick={() => {
                                setActiveView(item.id);
                                setIsMobileMenuOpen(false);
                              }}
                              className={cn(
                                "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-bold",
                                isActive
                                  ? "bg-[#EEF5FF] text-[#1D4ED8]"
                                  : "text-[#64748B]"
                              )}
                            >
                              <Icon className={cn("h-5 w-5", isActive ? "text-[#1D4ED8]" : "text-[#94A3B8]")} />
                              {item.label}
                            </button>
                          );
                        })}
                    </nav>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
`;

fs.writeFileSync('apps/web/src/components/school/secretary-command-center-full.tsx', tsx);
console.log('Successfully generated apps/web/src/components/school/secretary-command-center-full.tsx');
