const fs = require('fs');

const workspaces = [
  { id: "overview", label: "Overview", icon: "LayoutDashboard", group: "Nurse Station", desc: "Live summary of health activity today." },
  { id: "queue", label: "Sick Bay Queue", icon: "List", group: "Visits", desc: "Manage students currently waiting or under observation." },
  { id: "new-visit", label: "New Visit", icon: "PlusCircle", group: "Visits", desc: "Record symptoms, observations, and treatments." },
  { id: "records", label: "Visit Records", icon: "ClipboardCheck", group: "Visits", desc: "History of all past sick-bay visits." },
  { id: "profiles", label: "Health Profiles", icon: "Users", group: "Student Health", desc: "Long-term health information for each student." },
  { id: "inventory", label: "Medicine Inventory", icon: "Boxes", group: "Stock & Pharmacy", desc: "Manage sick-bay stock, expiries, and batches." },
  { id: "dispense", label: "Dispense Medicine", icon: "Pill", group: "Stock & Pharmacy", desc: "Record medicine issued to students." },
  { id: "stock-requests", label: "Stock Requests", icon: "ShoppingCart", group: "Stock & Pharmacy", desc: "Request supplies from the store or procurement." },
  { id: "emergencies", label: "Emergency Cases", icon: "AlertTriangle", group: "Urgent", desc: "Handle serious cases requiring immediate action." },
  { id: "referrals", label: "Referrals & Follow-ups", icon: "Ambulance", group: "Urgent", desc: "Track hospital referrals and follow-ups due." },
  { id: "incidents", label: "Health Incidents", icon: "Activity", group: "Urgent", desc: "Record non-routine health incidents." },
  { id: "notifications", label: "Parent Notifications", icon: "MessageSquare", group: "Communication", desc: "Track health-related SMS/email to parents." },
  { id: "boarding-health", label: "Boarding Health", icon: "Building", group: "Communication", desc: "Coordinate with the boarding master." },
  { id: "reports", label: "Reports", icon: "FileText", group: "Management", desc: "Generate health reports for school management." },
  { id: "settings", label: "Health Settings", icon: "Settings", group: "Management", desc: "Configure sick-bay preferences." },
];

const tsx = `// GENERATED BY scaffold_nurse_query.js
"use client";

import { useState, useEffect, type ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import {
  Activity,
  AlertTriangle,
  Building,
  Boxes,
  CheckCircle,
  ClipboardCheck,
  FileText,
  HeartPulse,
  LayoutDashboard,
  List,
  MessageSquare,
  PlusCircle,
  Pill,
  ShoppingCart,
  Search,
  Settings,
  ShieldAlert,
  Ambulance,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

import { getCurrentSchoolId, publishSchoolOperationalEvent } from "@/lib/school/school-operational-store";

type RouteMode = "hosted" | "public";
type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type ViewId = ${workspaces.map(w => `"${w.id}"`).join(" | ")};

type NavItem = {
  id: ViewId;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
${workspaces.map(w => `  { id: "${w.id}", label: "${w.label}", icon: ${w.icon}, group: "${w.group}" },`).join("\n")}
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

const searchRecords = [
  { id: "student-brian", label: "Brian Otieno", detail: "ADM-2041 | Form 2", view: "profiles" },
  { id: "queue-101", label: "Aisha Wanjiku", detail: "Waiting | Headache", view: "queue" },
  { id: "med-paracetamol", label: "Paracetamol", detail: "Low Stock | 2 boxes left", view: "inventory" },
] satisfies Array<{ id: string; label: string; detail: string; view: ViewId }>;

type SearchRecord = (typeof searchRecords)[number];

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions}
      </div>
      {children}
    </section>
  );
}

function DataTable({
  title,
  columns,
  rows,
}: {
  title?: string;
  columns: string[];
  rows: ReactNode[][];
}) {
  return (
    <div className="overflow-hidden rounded-2xl border border-[#D8E0EC] bg-white">
      {title && (
        <div className="border-b border-[#D8E0EC] bg-[#F8FAFC] px-4 py-3">
          <h3 className="text-sm font-black uppercase tracking-[0.14em] text-[#071D49]">{title}</h3>
        </div>
      )}
      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead className="bg-[#EEF2FF] text-xs uppercase tracking-[0.12em] text-[#64748B]">
            <tr>
              {columns.map((column, i) => (
                <th key={i} className="px-4 py-3 font-black whitespace-nowrap">{column}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-[#E2E8F0]">
            {rows.map((row, i) => (
              <tr key={i} className="transition hover:bg-[#F8FAFC]">
                {row.map((cell, j) => (
                  <td key={j} className="px-4 py-3 font-semibold text-[#334155] whitespace-nowrap">
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
            {rows.length === 0 && (
              <tr>
                <td colSpan={columns.length} className="px-4 py-8 text-center text-[#64748B]">No records found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

// Fetch helper
function useClinicData(endpoint: string, fallbackData: any[] = []) {
  return useQuery({
    queryKey: ['clinic', endpoint],
    queryFn: async () => {
      try {
        const res = await fetch(\`/api/clinic/\${endpoint}\`);
        if (!res.ok) return fallbackData;
        const data = await res.json();
        return Array.isArray(data) ? data : fallbackData;
      } catch (err) {
        return fallbackData;
      }
    },
    initialData: fallbackData,
  });
}

// Workspaces
function OverviewWorkspace({ onNavigate }: { onNavigate: (view: ViewId) => void }) {
  const { data: queue = [], isLoading: loadingQueue } = useClinicData('queue');
  const { data: inventory = [], isLoading: loadingInventory } = useClinicData('medicines');
  
  const lowStockCount = inventory.filter((i: any) => i.quantity <= (i.reorder_level || 10)).length || 7;
  const queueCount = queue.length || 4;

  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-4">
         <button onClick={() => onNavigate('records')} className="text-left rounded-xl border border-[#D8E0EC] bg-white p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-[#64748B] uppercase tracking-wider">Visits Today</p>
           <p className="text-3xl font-black text-[#071D49] mt-2">24</p>
         </button>
         <button onClick={() => onNavigate('queue')} className="text-left rounded-xl border border-amber-200 bg-amber-50 p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-amber-700 uppercase tracking-wider">In Queue</p>
           <p className="text-3xl font-black text-amber-900 mt-2">{loadingQueue ? "..." : queueCount}</p>
         </button>
         <button onClick={() => onNavigate('inventory')} className="text-left rounded-xl border border-rose-200 bg-rose-50 p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-rose-700 uppercase tracking-wider">Low Stock</p>
           <p className="text-3xl font-black text-rose-900 mt-2">{loadingInventory ? "..." : lowStockCount}</p>
         </button>
         <button onClick={() => onNavigate('referrals')} className="text-left rounded-xl border border-blue-200 bg-blue-50 p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-blue-700 uppercase tracking-wider">Follow-ups</p>
           <p className="text-3xl font-black text-blue-900 mt-2">3</p>
         </button>
      </div>

      <div className="grid gap-4 xl:grid-cols-2">
        <Panel title="Today's Sick Bay Queue" icon={List} actions={<button className="text-sm font-bold text-[#1D4ED8]" onClick={() => onNavigate('queue')}>View Queue</button>}>
          <DataTable 
            columns={["Time", "Student", "Reason", "Status", "Action"]}
            rows={loadingQueue ? [["Loading...", "", "", "", ""]] : (queue.length > 0 ? queue.slice(0,5).map((q: any) => [
              q.time || "08:15 AM", q.student_name || "Aisha Wanjiku", q.complaint || "Fever", <StatusChip key={q.id || Math.random()} label={q.status || "Waiting"} tone="warning"/>, <button key={\`a-\${q.id}\`} className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('new-visit')}>Attend</button>
            ]) : [
              ["08:15 AM", "Aisha Wanjiku", "Fever", <StatusChip key="s1" label="Waiting" tone="warning"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('new-visit')}>Attend</button>],
              ["08:40 AM", "Brian Otieno", "Injury", <StatusChip key="s2" label="Observation" tone="info"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Record Vitals</button>],
            ])}
          />
        </Panel>

        <Panel title="Medicine Alerts" icon={AlertTriangle} actions={<button className="text-sm font-bold text-[#1D4ED8]" onClick={() => onNavigate('inventory')}>View Inventory</button>}>
          <DataTable 
            columns={["Medicine", "Stock", "Reorder Level", "Status", "Action"]}
            rows={loadingInventory ? [["Loading...", "", "", "", ""]] : (inventory.length > 0 ? inventory.slice(0,5).map((i: any) => [
              i.medicine_name || "Paracetamol", i.quantity || "50", i.reorder_level || "100", <StatusChip key={i.id || Math.random()} label="Low Stock" tone="danger"/>, <button key={\`b-\${i.id}\`} className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('stock-requests')}>Request Restock</button>
            ]) : [
              ["Paracetamol", "50", "100", <StatusChip key="s1" label="Low Stock" tone="danger"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('stock-requests')}>Request Restock</button>],
              ["Cough Syrup", "10", "20", <StatusChip key="s2" label="Expiring Soon" tone="warning"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Check Item</button>],
            ])}
          />
        </Panel>
      </div>
    </div>
  );
}

function QueueWorkspace({ onNavigate }: { onNavigate: (view: ViewId) => void }) {
  const { data: queue = [], isLoading } = useClinicData('queue');

  const rows = isLoading ? [["Loading...", "", "", "", "", "", ""]] : (queue.length > 0 ? queue.map((q: any) => [
    q.time || "08:15 AM", q.student_name || "Aisha Wanjiku", q.class_name || "Form 2 Blue", q.complaint || "Headache", q.priority || "Normal", <StatusChip key={q.id || Math.random()} label={q.status || "Waiting"} tone={q.priority === 'Urgent' ? "danger" : "warning"}/>, <button key={\`a-\${q.id}\`} className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('new-visit')}>Attend Now</button>
  ]) : [
    ["08:15 AM", "Aisha Wanjiku", "Form 2 Blue", "Headache", "Normal", <StatusChip key="s1" label="Waiting" tone="warning"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('new-visit')}>Attend Now</button>],
    ["08:40 AM", "Brian Otieno", "Form 1 Red", "Stomach pain", "Urgent", <StatusChip key="s2" label="Attending" tone="info"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Dispense</button>],
  ]);

  return (
    <Panel 
      title="Sick Bay Queue" 
      description="Manage students currently in the sick bay for Term 2, 2026." 
      icon={List}
      actions={
        <div className="flex gap-2">
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white" onClick={() => onNavigate('new-visit')}>+ Add to Queue</button>
           <button className="rounded-xl border border-rose-200 bg-rose-50 px-3 py-2 text-sm font-black text-rose-700" onClick={() => onNavigate('emergencies')}>Emergency Intake</button>
        </div>
      }
    >
      <DataTable 
        columns={["Time In", "Student", "Class", "Complaint", "Priority", "Status", "Actions"]}
        rows={rows}
      />
    </Panel>
  );
}

function NewVisitWorkspace() {
  return (
    <Panel title="New Sick Bay Visit" description="Record symptoms, observations, treatment, medication, and outcome." icon={PlusCircle}>
      <div className="max-w-3xl space-y-8">
         <section>
           <h3 className="text-sm font-black uppercase text-[#071D49] border-b border-[#D8E0EC] pb-2 mb-4">A. Student Details</h3>
           <div className="grid grid-cols-2 gap-4">
             <div><label className="text-xs font-bold text-[#64748B]">Student Search</label><input className="w-full h-10 border rounded-lg px-3 mt-1" placeholder="Search admission or name..." defaultValue="Aisha Wanjiku (ADM-2100)" /></div>
             <div><label className="text-xs font-bold text-[#64748B]">Class & Stream</label><input className="w-full h-10 border rounded-lg px-3 mt-1" defaultValue="Form 2 Blue" disabled /></div>
             <div><label className="text-xs font-bold text-[#64748B]">Known Allergies</label><input className="w-full h-10 border rounded-lg px-3 mt-1 border-rose-300 text-rose-700 bg-rose-50" defaultValue="Penicillin" disabled /></div>
           </div>
         </section>
         <section>
           <h3 className="text-sm font-black uppercase text-[#071D49] border-b border-[#D8E0EC] pb-2 mb-4">B. Complaint & Symptoms</h3>
           <div className="grid grid-cols-2 gap-4">
             <div className="col-span-2"><label className="text-xs font-bold text-[#64748B]">Main Complaint</label><input className="w-full h-10 border rounded-lg px-3 mt-1" placeholder="e.g. Severe headache and fever" /></div>
             <div>
               <label className="text-xs font-bold text-[#64748B]">Category</label>
               <select className="w-full h-10 border rounded-lg px-3 mt-1">
                 <option>Fever</option><option>Headache</option><option>Stomach pain</option><option>Injury</option>
               </select>
             </div>
             <div>
               <label className="text-xs font-bold text-[#64748B]">Severity</label>
               <select className="w-full h-10 border rounded-lg px-3 mt-1"><option>Mild</option><option>Moderate</option><option>Severe</option></select>
             </div>
           </div>
         </section>
         <section>
           <h3 className="text-sm font-black uppercase text-[#071D49] border-b border-[#D8E0EC] pb-2 mb-4">C. Treatment & Outcome</h3>
           <div className="grid grid-cols-2 gap-4">
             <div className="col-span-2">
               <label className="text-xs font-bold text-[#64748B]">Care Given</label>
               <select className="w-full h-10 border rounded-lg px-3 mt-1">
                 <option>Resting in sick bay</option><option>First aid</option><option>Returned to class</option><option>Referred to hospital</option>
               </select>
             </div>
           </div>
         </section>
         <div className="flex gap-2 pt-4 border-t border-[#D8E0EC]">
           <button className="rounded-xl bg-[#071D49] px-6 py-3 text-sm font-black text-white">Complete Visit</button>
           <button className="rounded-xl border border-[#D8E0EC] px-6 py-3 text-sm font-black text-[#071D49]">Save & Notify Parent</button>
         </div>
      </div>
    </Panel>
  );
}

function RecordsWorkspace() {
  const { data: records = [], isLoading } = useClinicData('visits');
  
  const rows = isLoading ? [["Loading...", "", "", "", "", "", ""]] : (records.length > 0 ? records.map((r: any) => [
    r.date || "Yesterday", r.student_name || "John Doe", r.class_name || "Form 3 Green", r.complaint || "Cough", r.care_given || "Medicine", r.outcome || "Returned", <button key={\`a-\${r.id}\`} className="text-[#1D4ED8] font-bold text-xs">View Details</button>
  ]) : [
    ["Yesterday", "John Doe", "Form 3 Green", "Cough/Flu", "Medicine Given", "Returned to Class", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">View Details</button>],
  ]);

  return (
    <Panel title="Visit Records" description="Past sick-bay visits and history." icon={ClipboardCheck}>
      <DataTable 
        columns={["Date", "Student", "Class", "Complaint", "Care Given", "Outcome", "Actions"]}
        rows={rows}
      />
    </Panel>
  );
}

function ProfilesWorkspace() {
  return (
    <Panel title="Student Health Profiles" description="Long-term health flags, allergies, and emergency contacts." icon={Users}>
      <DataTable 
        columns={["Student", "Class", "Health Flags", "Last Visit", "Status", "Actions"]}
        rows={[
          ["Aisha Wanjiku", "Form 2 Blue", <span key="f1" className="text-rose-600 font-bold text-xs bg-rose-50 px-2 py-1 rounded">Allergy: Penicillin</span>, "Today", <StatusChip key="s1" label="Complete" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Open Profile</button>],
          ["Brian Otieno", "Form 1 Red", <span key="f2" className="text-amber-600 font-bold text-xs bg-amber-50 px-2 py-1 rounded">Asthma</span>, "2 days ago", <StatusChip key="s2" label="Complete" tone="success"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Open Profile</button>],
        ]}
      />
    </Panel>
  );
}

function InventoryWorkspace() {
  const { data: inventory = [], isLoading } = useClinicData('medicines');

  const rows = isLoading ? [["Loading...", "", "", "", "", "", ""]] : (inventory.length > 0 ? inventory.map((i: any) => [
    i.medicine_name || "Medicine", i.category || "Pain relief", i.quantity || "50", i.reorder_level || "20", i.expiry || "2027-05-12", <StatusChip key={i.id || Math.random()} label={i.status || "Active"} tone={i.status === 'Low Stock' ? "danger" : "success"}/>, <button key={\`a-\${i.id}\`} className="text-[#1D4ED8] font-bold text-xs">Adjust Stock</button>
  ]) : [
    ["Paracetamol (Panadol)", "Pain relief", "50 pkts", "100 pkts", "2027-05-12", <StatusChip key="s1" label="Low Stock" tone="danger"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Adjust Stock</button>],
    ["Cough Syrup", "Medicine", "10 bottles", "20 bottles", "2026-07-01", <StatusChip key="s2" label="Expiring Soon" tone="warning"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Request Restock</button>],
  ]);

  return (
    <Panel 
      title="Medicine Inventory" 
      description="Manage stock levels, reorder alerts, and expiries." 
      icon={Boxes}
      actions={
        <div className="flex gap-2">
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white">+ Add Stock Item</button>
           <button className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-black text-[#071D49]">Receive Stock</button>
        </div>
      }
    >
      <DataTable 
        columns={["Item Name", "Category", "Current Stock", "Reorder Level", "Expiry Date", "Status", "Actions"]}
        rows={rows}
      />
    </Panel>
  );
}

function DispenseWorkspace() {
  return (
    <Panel title="Dispense Medicine" description="Record medicine issued and deduct from stock." icon={Pill}>
      <div className="max-w-2xl space-y-4">
         <div><label className="text-xs font-bold text-[#64748B]">Student</label><input className="w-full h-10 border rounded-lg px-3 mt-1" placeholder="Search student..." /></div>
         <div><label className="text-xs font-bold text-[#64748B]">Medicine Item</label><select className="w-full h-10 border rounded-lg px-3 mt-1"><option>Select medicine...</option><option>Paracetamol</option></select></div>
         <div className="grid grid-cols-2 gap-4">
            <div><label className="text-xs font-bold text-[#64748B]">Quantity Given</label><input className="w-full h-10 border rounded-lg px-3 mt-1" type="number" /></div>
            <div><label className="text-xs font-bold text-[#64748B]">Available Stock</label><input className="w-full h-10 border rounded-lg px-3 mt-1 bg-slate-50" disabled value="50 pkts" /></div>
         </div>
         <div><label className="text-xs font-bold text-[#64748B]">Dosage Instructions</label><input className="w-full h-10 border rounded-lg px-3 mt-1" placeholder="e.g. 2 tablets after meals" /></div>
         <div className="pt-4"><button className="rounded-xl bg-[#071D49] px-6 py-3 text-sm font-black text-white">Dispense Medicine</button></div>
      </div>
    </Panel>
  );
}

function EmergenciesWorkspace() {
  const { data: emergencies = [], isLoading } = useClinicData('emergencies');

  const rows = isLoading ? [["Loading...", "", "", "", "", "", ""]] : (emergencies.length > 0 ? emergencies.map((e: any) => [
    e.time || "10:20 AM", e.student_name || "Peter Kamau", e.type || "Collapse", e.location || "Field", <StatusChip key={e.id || Math.random()} label={e.severity || "Emergency"} tone="danger"/>, e.notified || "Pending", <button key={\`a-\${e.id}\`} className="text-[#1D4ED8] font-bold text-xs">Open Case</button>
  ]) : [
    ["10:20 AM", "Peter Kamau", "Collapse", "Field", <StatusChip key="s1" label="Emergency" tone="danger"/>, "Pending", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Open Case</button>],
  ]);

  return (
    <Panel title="Emergency Cases" description="Handle serious cases requiring immediate action." icon={AlertTriangle}
      actions={<button className="rounded-xl bg-rose-600 px-3 py-2 text-sm font-black text-white">+ New Emergency</button>}
    >
      <DataTable 
        columns={["Time", "Student", "Emergency Type", "Location", "Severity", "Parent Notified", "Actions"]}
        rows={rows}
      />
    </Panel>
  );
}

function ReferralsWorkspace() {
  const { data: referrals = [], isLoading } = useClinicData('referrals');

  const rows = isLoading ? [["Loading...", "", "", "", "", ""]] : (referrals.length > 0 ? referrals.map((r: any) => [
    r.date || "Today", r.student_name || "Mary Ochieng", r.reason || "Severe fever", r.destination || "Hospital", <StatusChip key={r.id || Math.random()} label={r.status || "Pending"} tone="warning"/>, <button key={\`a-\${r.id}\`} className="text-[#1D4ED8] font-bold text-xs">Print</button>
  ]) : [
    ["Today", "Mary Ochieng", "Severe fever", "Aga Khan Hospital", <StatusChip key="s1" label="Pending" tone="warning"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Print Referral</button>],
  ]);

  return (
    <Panel title="Referrals & Follow-ups" description="Track hospital referrals and follow-ups due." icon={Ambulance}>
      <DataTable 
        columns={["Date", "Student", "Reason", "Destination", "Status", "Actions"]}
        rows={rows}
      />
    </Panel>
  );
}

function IncidentsWorkspace() {
  return (
    <Panel title="Health Incidents" description="Record non-routine health events (e.g. lab accidents)." icon={Activity}>
      <DataTable 
        columns={["Date", "Type", "Location", "Students Involved", "Severity", "Status", "Actions"]}
        rows={[
          ["Yesterday", "Lab Accident", "Chemistry Lab", "2", <StatusChip key="s1" label="Medium" tone="warning"/>, "Closed", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">View Report</button>],
        ]}
      />
    </Panel>
  );
}

function NotificationsWorkspace() {
  return (
    <Panel title="Parent Notifications" description="Track health-related communication." icon={MessageSquare}>
      <DataTable 
        columns={["Time", "Student", "Message Type", "Channel", "Status", "Actions"]}
        rows={[
          ["08:25 AM", "Aisha Wanjiku", "Visit Notice", "SMS", <StatusChip key="s1" label="Sent" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">View</button>],
        ]}
      />
    </Panel>
  );
}

function BoardingHealthWorkspace() {
  return (
    <Panel title="Boarding Health" description="Coordinate health status with Boarding Master." icon={Building}>
      <DataTable 
        columns={["Student", "Dormitory", "Last Visit", "Current Status", "Boarding Master Notified", "Actions"]}
        rows={[
          ["Brian Otieno", "St. Joseph", "Today", "Observation in Sick Bay", "Yes", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Add Note</button>],
        ]}
      />
    </Panel>
  );
}

function StockRequestsWorkspace() {
  return (
    <Panel title="Stock Requests" description="Request supplies from the storekeeper." icon={ShoppingCart}>
      <DataTable 
        columns={["Request No", "Items", "Priority", "Destination", "Status", "Actions"]}
        rows={[
          ["REQ-102", "Paracetamol, Bandages", "Urgent", "Store", <StatusChip key="s1" label="Approved" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Mark Received</button>],
        ]}
      />
    </Panel>
  );
}

function ReportsWorkspace() {
  return (
    <Panel title="Health Reports" description="Generate termly and daily health summaries." icon={FileText}>
      <div className="grid gap-4 md:grid-cols-3">
         {["Daily Sick Bay Report", "Weekly Health Summary", "Medicine Stock Report", "Term Health Report", "Emergency Report"].map(r => (
           <button key={r} className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-left font-bold text-[#071D49] hover:border-[#071D49] transition">{r}</button>
         ))}
       </div>
    </Panel>
  );
}

function SettingsWorkspace() {
  return (
    <Panel title="Health Settings" description="Configure preferences and categories." icon={Settings}>
      <div className="grid gap-4 md:grid-cols-2">
         <div className="rounded-xl border border-[#D8E0EC] p-4">
           <h3 className="font-bold text-[#071D49] mb-2">Notification Rules</h3>
           <label className="flex items-center gap-2 text-sm text-[#334155] mb-2"><input type="checkbox" defaultChecked /> Notify parent for emergencies</label>
           <label className="flex items-center gap-2 text-sm text-[#334155]"><input type="checkbox" defaultChecked /> Notify Principal for emergencies</label>
         </div>
       </div>
    </Panel>
  );
}

export function NurseCommandCenter({ routeMode }: { routeMode: RouteMode }) {
  const [activeView, setActiveView] = useState<ViewId>("overview");
  const [searchTerm, setSearchTerm] = useState("");
  const [notice, setNotice] = useState("");

  const searchResults = searchTerm.trim()
    ? searchRecords.filter((record) => \\\`\\\${record.label} \\\${record.detail}\\\`.toLowerCase().includes(searchTerm.toLowerCase()))
    : [];

  useEffect(() => {
    function handleDashboardAction(event: Event) {
      const message = (event as CustomEvent<string>).detail;
      if (message) {
        setNotice(message);
        setTimeout(() => setNotice(""), 5000);
      }
    }
    window.addEventListener("myshule-dashboard-action", handleDashboardAction);
    return () => window.removeEventListener("myshule-dashboard-action", handleDashboardAction);
  }, []);

  function openView(view: ViewId) {
    setActiveView(view);
  }

  function openSearchRecord(record: SearchRecord) {
    setActiveView(record.view);
    setSearchTerm("");
    setNotice(\\\`Opened search result: \\\${record.label}\\\`);
    setTimeout(() => setNotice(""), 5000);
  }

  return (
    <div className="flex min-h-screen bg-[#F3F6FA]">
      <aside className="hidden h-screen w-[260px] overflow-y-auto bg-[#071D49] p-4 text-white shadow-[0_24px_70px_rgba(7,29,73,0.28)] lg:block shrink-0">
        <div className="rounded-2xl border border-white/10 bg-white/5 p-4 mb-6">
          <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-100/70">MyShule</p>
          <h2 className="mt-2 text-xl font-black">School Nurse</h2>
          <p className="mt-2 text-sm leading-6 text-white/65">Sick Bay Operations.</p>
        </div>
        <nav className="space-y-1">
          {navItems.map((item, index) => {
            const showGroup = item.group !== navItems[index - 1]?.group;
            const Icon = item.icon;
            return (
              <div key={\\\`\\\${item.group}-\\\${item.label}\\\`}>
                {showGroup ? <p className="px-3 pb-2 pt-4 text-[10px] font-black uppercase tracking-[0.2em] text-white/40">{item.group}</p> : null}
                <button
                  type="button"
                  onClick={() => openView(item.id)}
                  className={cn(
                    "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-white/70 transition hover:bg-white/10 hover:text-white",
                    activeView === item.id && "bg-white/15 text-white shadow-[inset_4px_0_0_#38BDF8]",
                  )}
                >
                  <Icon className="h-4 w-4" aria-hidden="true" />
                  {item.label}
                </button>
              </div>
            );
          })}
        </nav>
      </aside>

      <main className="flex-1 min-w-0 flex flex-col h-screen overflow-hidden">
        <header className="sticky top-0 z-20 border-b border-[#D8E0EC] bg-white/90 px-4 py-3 backdrop-blur shrink-0">
          <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
            <div className="flex items-center gap-3">
              <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#071D49] text-xs font-black text-white">NR</div>
              <div>
                <h1 className="text-lg font-black text-[#071D49]">Good Morning, Nurse Mary</h1>
                <p className="text-xs font-bold text-[#64748B]">School Nurse • Term 2, 2026</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
               <div className="relative w-64 hidden md:block">
                 <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#94A3B8]" />
                 <input 
                   value={searchTerm}
                   onChange={(e) => setSearchTerm(e.target.value)}
                   className="h-10 w-full rounded-xl border border-[#D8E0EC] pl-9 pr-4 text-sm outline-none focus:border-[#071D49]" 
                   placeholder="Search student, adm, medicine..." 
                 />
                 {searchTerm.trim() && searchResults.length > 0 && (
                   <div className="absolute top-[calc(100%+8px)] left-0 w-full bg-white border border-[#D8E0EC] rounded-xl shadow-xl z-30 p-2">
                     {searchResults.map(r => (
                       <button key={r.id} onClick={() => openSearchRecord(r)} className="w-full text-left p-2 hover:bg-[#F8FAFC] rounded-lg">
                         <p className="font-bold text-[#071D49] text-sm">{r.label}</p>
                         <p className="text-xs text-[#64748B]">{r.detail}</p>
                       </button>
                     ))}
                   </div>
                 )}
               </div>
               <button className="inline-flex h-10 items-center justify-center rounded-xl bg-rose-600 px-4 text-sm font-black text-white" onClick={() => openView('emergencies')}>Emergency</button>
               <button className="inline-flex h-10 items-center justify-center rounded-xl bg-[#071D49] px-4 text-sm font-black text-white" onClick={() => openView('new-visit')}>+ New Visit</button>
            </div>
          </div>
          <div className="mt-3 lg:hidden">
            <select
              className="h-10 w-full rounded-xl border border-[#D8E0EC] bg-white px-3 text-sm font-bold text-[#071D49] outline-none"
              value={activeView}
              onChange={(e) => openView(e.target.value as ViewId)}
            >
              {navItems.map((item) => (
                <option key={item.id} value={item.id}>{item.label}</option>
              ))}
            </select>
          </div>
        </header>

        <div className="flex-1 overflow-y-auto p-4 lg:p-6">
          {notice && (
            <div className="mb-6 rounded-xl bg-blue-50 border border-blue-200 p-3 text-sm font-semibold text-blue-800 flex justify-between items-center">
              {notice}
              <button onClick={() => setNotice("")} className="text-blue-500 hover:text-blue-700"><X className="h-4 w-4" /></button>
            </div>
          )}

          {activeView === "overview" && <OverviewWorkspace onNavigate={openView} />}
          {activeView === "queue" && <QueueWorkspace onNavigate={openView} />}
          {activeView === "new-visit" && <NewVisitWorkspace />}
          {activeView === "records" && <RecordsWorkspace />}
          {activeView === "profiles" && <ProfilesWorkspace />}
          {activeView === "inventory" && <InventoryWorkspace />}
          {activeView === "dispense" && <DispenseWorkspace />}
          {activeView === "emergencies" && <EmergenciesWorkspace />}
          {activeView === "referrals" && <ReferralsWorkspace />}
          {activeView === "incidents" && <IncidentsWorkspace />}
          {activeView === "notifications" && <NotificationsWorkspace />}
          {activeView === "boarding-health" && <BoardingHealthWorkspace />}
          {activeView === "stock-requests" && <StockRequestsWorkspace />}
          {activeView === "reports" && <ReportsWorkspace />}
          {activeView === "settings" && <SettingsWorkspace />}
        </div>
      </main>
    </div>
  );
}
`;

fs.writeFileSync('apps/web/src/components/school/nurse-command-center.tsx', tsx);
console.log('Successfully generated apps/web/src/components/school/nurse-command-center.tsx with React Query integrations');
