const fs = require('fs');

const workspaces = [
  { id: "overview", label: "Overview", icon: "LayoutDashboard", group: "Command Center", desc: "Live operational picture of boarding life today." },
  { id: "register", label: "Boarder Register", icon: "Users", group: "Boarders", desc: "Master list of all learners in boarding." },
  { id: "dorms", label: "Dormitories & Rooms", icon: "Building", group: "Facilities", desc: "Manage hostels, dormitories, rooms, and capacity." },
  { id: "beds", label: "Bed Allocation", icon: "BedDouble", group: "Facilities", desc: "Assign, change, transfer, and release beds." },
  { id: "roll-call", label: "Daily Roll Call", icon: "ClipboardList", group: "Daily Operations", desc: "Confirm that every boarder is accounted for." },
  { id: "leave", label: "Leave / Exeat Requests", icon: "DoorOpen", group: "Daily Operations", desc: "Manage students allowed to leave boarding temporarily." },
  { id: "late-returns", label: "Late Returns & Absences", icon: "Clock", group: "Daily Operations", desc: "Track students who return late from leave or miss roll call." },
  { id: "duty", label: "Duty Roster", icon: "Calendar", group: "Daily Operations", desc: "Manage boarding duty staff, dorm captains, and prefects." },
  { id: "incidents", label: "Dorm Incidents", icon: "ShieldAlert", group: "Welfare & Discipline", desc: "Log boarding-related incidents in hostels or dormitories." },
  { id: "welfare", label: "Health & Welfare", icon: "HeartPulse", group: "Welfare & Discipline", desc: "Track boarding welfare concerns and sick bay coordination." },
  { id: "meals", label: "Meals & Dining", icon: "Utensils", group: "Welfare & Discipline", desc: "Tracks boarding meal attendance and special diets." },
  { id: "inspections", label: "Dorm Inspections", icon: "CheckSquare", group: "Maintenance & Stores", desc: "Cleanliness checks, room inspections, and hygiene." },
  { id: "maintenance", label: "Maintenance Requests", icon: "Wrench", group: "Maintenance & Stores", desc: "Report broken beds, doors, windows, lights, etc." },
  { id: "inventory", label: "Boarding Inventory", icon: "Package", group: "Maintenance & Stores", desc: "Tracks boarding-related items issued to dorms." },
  { id: "visitors", label: "Visitors & Gate Passes", icon: "UserPlus", group: "Communication", desc: "Coordinates parent/guardian boarding visits and student pickups." },
  { id: "communication", label: "Parent Communication", icon: "MessageSquare", group: "Communication", desc: "Communicate with parents about boarding matters." },
  { id: "approvals", label: "Approvals", icon: "CheckCircle", group: "Management", desc: "Boarding approvals in one clean workspace." },
  { id: "reports", label: "Reports & Downloads", icon: "FileText", group: "Management", desc: "Generates boarding reports for daily operations and audits." },
  { id: "settings", label: "Boarding Settings", icon: "Settings", group: "Management", desc: "Controls boarding-specific rules and notification rules." },
];

const tsx = `// GENERATED BY scaffold_boarding_master.js
"use client";

import { useState, useEffect, type ReactNode } from "react";
import {
  AlertTriangle,
  BedDouble,
  Bell,
  Building,
  Calendar,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ClipboardList,
  Clock,
  DoorOpen,
  FileText,
  HeartPulse,
  LayoutDashboard,
  MessageSquare,
  Package,
  Search,
  Settings,
  ShieldAlert,
  UserPlus,
  Users,
  Utensils,
  Wrench,
  X,
  type LucideIcon,
} from "lucide-react";

import { getCurrentSchoolId, publishSchoolOperationalEvent } from "@/lib/school/school-operational-store";

type RouteMode = "hosted" | "public";
type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type ViewId = ${workspaces.map(w => `"${w.id}"`).join(" | ")};

type NavItem = {
  id: ViewId;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
${workspaces.map(w => `  { id: "${w.id}", label: "${w.label}", icon: ${w.icon}, group: "${w.group}" },`).join("\n")}
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

const searchRecords = [
  { id: "student-brian", label: "Brian Otieno", detail: "ADM-2041 | St. Joseph B12", view: "register" },
  { id: "incident-101", label: "Dorm Noise Incident", detail: "Ref #101 | St. Joseph Dorm", view: "incidents" },
] satisfies Array<{ id: string; label: string; detail: string; view: ViewId }>;

type SearchRecord = (typeof searchRecords)[number];

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function ProgressBar({ value, tone = "info" }: { value: number; tone?: Tone }) {
  return (
    <div className="h-2 rounded-full bg-[#E2E8F0] overflow-hidden mt-2">
      <div className={cn("h-full rounded-full transition-all duration-500", toneClasses[tone].dot)} style={{ width: \\\`\\\${Math.max(0, Math.min(100, value))}%\\\` }} />
    </div>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions}
      </div>
      {children}
    </section>
  );
}

function DataTable({
  title,
  columns,
  rows,
}: {
  title?: string;
  columns: string[];
  rows: ReactNode[][];
}) {
  return (
    <div className="overflow-hidden rounded-2xl border border-[#D8E0EC] bg-white">
      {title && (
        <div className="border-b border-[#D8E0EC] bg-[#F8FAFC] px-4 py-3">
          <h3 className="text-sm font-black uppercase tracking-[0.14em] text-[#071D49]">{title}</h3>
        </div>
      )}
      <div className="overflow-x-auto">
        <table className="w-full text-left text-sm">
          <thead className="bg-[#EEF2FF] text-xs uppercase tracking-[0.12em] text-[#64748B]">
            <tr>
              {columns.map((column, i) => (
                <th key={i} className="px-4 py-3 font-black whitespace-nowrap">{column}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-[#E2E8F0]">
            {rows.map((row, i) => (
              <tr key={i} className="transition hover:bg-[#F8FAFC]">
                {row.map((cell, j) => (
                  <td key={j} className="px-4 py-3 font-semibold text-[#334155] whitespace-nowrap">
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
            {rows.length === 0 && (
              <tr>
                <td colSpan={columns.length} className="px-4 py-8 text-center text-[#64748B]">No records found.</td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function EmptyState({ message, actionText, onAction }: { message: string, actionText: string, onAction: () => void }) {
  return (
    <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-[#D8E0EC] bg-[#F8FAFC] p-12 text-center">
      <AlertTriangle className="h-12 w-12 text-[#94A3B8] mb-4" />
      <p className="text-[#071D49] font-bold mb-4">{message}</p>
      <button onClick={onAction} className="rounded-xl bg-[#071D49] px-4 py-2 text-sm font-black text-white">{actionText}</button>
    </div>
  );
}

// Workspaces Implementations

function OverviewWorkspace({ onNavigate }: { onNavigate: (view: ViewId) => void }) {
  return (
    <div className="space-y-6">
      <div className="grid gap-4 md:grid-cols-4">
         <button onClick={() => onNavigate('register')} className="text-left rounded-xl border border-[#D8E0EC] bg-white p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-[#64748B] uppercase tracking-wider">Total Boarders</p>
           <p className="text-3xl font-black text-[#071D49] mt-2">1,240</p>
         </button>
         <button onClick={() => onNavigate('roll-call')} className="text-left rounded-xl border border-[#D8E0EC] bg-white p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-[#64748B] uppercase tracking-wider">Present Tonight</p>
           <p className="text-3xl font-black text-[#071D49] mt-2">1,190</p>
         </button>
         <button onClick={() => onNavigate('roll-call')} className="text-left rounded-xl border border-rose-200 bg-rose-50 p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-rose-700 uppercase tracking-wider">Missing Roll Call</p>
           <p className="text-3xl font-black text-rose-900 mt-2">3</p>
         </button>
         <button onClick={() => onNavigate('leave')} className="text-left rounded-xl border border-blue-200 bg-blue-50 p-4 shadow-sm hover:shadow-md transition">
           <p className="text-xs font-black text-blue-700 uppercase tracking-wider">Approved Leave-Outs</p>
           <p className="text-3xl font-black text-blue-900 mt-2">45</p>
         </button>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Panel title="Tonight's Roll Call" icon={ClipboardList}>
          <DataTable 
            columns={["Student", "ADM", "Dorm", "Room", "Bed", "Status", "Action"]}
            rows={[
              ["Brian Otieno", "2451", "St. Joseph", "1A", "B12", <StatusChip key="s1" label="Not Marked" tone="danger"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('roll-call')}>Mark Now</button>],
              ["John Doe", "2211", "St. Paul", "2B", "C10", <StatusChip key="s2" label="On Leave" tone="info"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">View</button>],
            ]}
          />
        </Panel>

        <Panel title="Urgent Follow-ups" icon={AlertTriangle}>
          <DataTable 
            columns={["Concern", "Student", "Details", "Action"]}
            rows={[
              ["Missing from Roll Call", "Brian Otieno", "St. Joseph 1A", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Escalate</button>],
              ["Unresolved Repair", "St. Paul Dorm", "Broken Window", <button key="a2" className="text-[#1D4ED8] font-bold text-xs">View</button>],
            ]}
          />
        </Panel>
      </div>
      
      <Panel title="Dorm Status" icon={Building}>
        <DataTable 
          columns={["Dormitory", "Capacity", "Occupied", "Available", "Roll Call %", "Action"]}
          rows={[
            ["St. Joseph", "400", "390", "10", "98%", <button key="a1" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('dorms')}>Open Dorm</button>],
            ["St. Paul", "450", "445", "5", "100%", <button key="a2" className="text-[#1D4ED8] font-bold text-xs" onClick={() => onNavigate('dorms')}>Open Dorm</button>],
          ]}
        />
      </Panel>
    </div>
  );
}

function RegisterWorkspace() {
  return (
    <Panel 
      title="Boarder Register" 
      description="Master list of all learners in boarding." 
      icon={Users}
      actions={
        <div className="flex gap-2">
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white">Add Boarder</button>
           <button className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-black text-[#071D49]">Import</button>
        </div>
      }
    >
      <DataTable 
        columns={["Student", "ADM", "Class", "Dorm", "Room", "Bed", "Status", "Actions"]}
        rows={[
          ["Brian Otieno", "2451", "Form 2", "St. Joseph", "1A", "B12", <StatusChip key="s1" label="Active" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">View Profile</button>],
        ]}
      />
    </Panel>
  );
}

function DormsWorkspace() {
  return (
    <Panel title="Dormitories & Rooms" description="Manage physical boarding structure and capacity." icon={Building}>
      <DataTable 
        columns={["Dormitory", "Type", "Capacity", "Occupied", "Available", "Warden", "Status", "Actions"]}
        rows={[
          ["St. Joseph", "Boys Dormitory", "400", "390", "10", "Mr. Kamau", <StatusChip key="s1" label="Active" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">View Rooms</button>],
        ]}
      />
    </Panel>
  );
}

function BedsWorkspace() {
  return (
    <Panel title="Bed Allocation" description="Assign, change, transfer, and release beds." icon={BedDouble}>
      <div className="grid grid-cols-2 gap-4">
        <div>
           <h3 className="text-sm font-black uppercase text-[#071D49] mb-4">Students Needing Beds</h3>
           <DataTable 
             columns={["Student", "ADM", "Preference", "Action"]}
             rows={[
               ["John Mark", "2600", "Boys Dorm", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Allocate</button>],
             ]}
           />
        </div>
        <div>
           <h3 className="text-sm font-black uppercase text-[#071D49] mb-4">Available Beds</h3>
           <DataTable 
             columns={["Dorm", "Room", "Bed No.", "Action"]}
             rows={[
               ["St. Joseph", "1A", "B13", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Assign Bed</button>],
             ]}
           />
        </div>
      </div>
    </Panel>
  );
}

function RollCallWorkspace() {
  return (
    <Panel title="Daily Roll Call" description="Confirm that every boarder is accounted for." icon={ClipboardList}>
      <div className="mb-4 flex gap-2">
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white">Start Roll Call</button>
           <button className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm font-black text-[#071D49]">Print Missing List</button>
      </div>
      <DataTable 
        columns={["Student", "ADM", "Dorm", "Room", "Bed", "Status", "Actions"]}
        rows={[
          ["Brian Otieno", "2451", "St. Joseph", "1A", "B12", <StatusChip key="s1" label="Present" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Edit Status</button>],
          ["John Doe", "2211", "St. Paul", "2B", "C10", <StatusChip key="s2" label="Not Marked" tone="danger"/>, <button key="a2" className="text-[#1D4ED8] font-bold text-xs">Mark Now</button>],
        ]}
      />
    </Panel>
  );
}

function LeaveWorkspace() {
  return (
    <Panel title="Leave / Exeat Requests" description="Manage students allowed to leave boarding temporarily." icon={DoorOpen}>
      <div className="mb-4 flex gap-2">
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white">Create Leave Request</button>
      </div>
      <DataTable 
        columns={["Student", "Leave Type", "Expected Return", "Parent", "Status", "Actions"]}
        rows={[
          ["Brian Otieno", "Medical Leave", "2026-06-15", "Mr. Otieno", <StatusChip key="s1" label="Approved" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Check Out</button>],
        ]}
      />
    </Panel>
  );
}

function LateReturnsWorkspace() {
  return (
    <Panel title="Late Returns & Absences" description="Track students who return late from leave or miss roll call." icon={Clock}>
      <DataTable 
        columns={["Student", "Dorm", "Expected Time", "Actual Time", "Delay", "Status", "Actions"]}
        rows={[
          ["Sarah K", "Girls Wing A", "18:00", "20:00", "2 hrs", <StatusChip key="s1" label="Unresolved" tone="danger"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Add Explanation</button>],
        ]}
      />
    </Panel>
  );
}

function DutyWorkspace() {
  return (
    <Panel title="Duty Roster" description="Manage boarding duty staff, dorm captains, and prefects." icon={Calendar}>
      <DataTable 
        columns={["Date", "Dormitory", "Staff on Duty", "Prefect/Captain", "Status", "Actions"]}
        rows={[
          ["Today", "St. Joseph", "Mr. Kamau", "Brian O.", <StatusChip key="s1" label="Active" tone="info"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Add Report</button>],
        ]}
      />
    </Panel>
  );
}

function IncidentsWorkspace() {
  return (
    <Panel title="Dorm Incidents" description="Log boarding-related incidents in hostels or dormitories." icon={ShieldAlert}>
       <div className="mb-4 flex gap-2">
           <button className="rounded-xl bg-rose-50 text-rose-700 border border-rose-200 px-3 py-2 text-sm font-black">Log Incident</button>
       </div>
       <DataTable 
        columns={["Ref", "Student(s)", "Dorm", "Type", "Severity", "Status", "Actions"]}
        rows={[
          ["#1042", "Peter Otieno", "St. Joseph", "Noise", <StatusChip key="s1" label="Medium" tone="warning"/>, "Open", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Escalate</button>],
        ]}
      />
    </Panel>
  );
}

function WelfareWorkspace() {
  return (
    <Panel title="Health & Welfare" description="Track boarding welfare concerns and sick bay coordination." icon={HeartPulse}>
       <DataTable 
        columns={["Student", "Dorm", "Concern Type", "Last Note", "Referred To", "Status", "Actions"]}
        rows={[
          ["John Doe", "St. Paul", "Sick bay follow-up", "Headache reported", "Nurse", <StatusChip key="s1" label="Referred" tone="info"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Add Note</button>],
        ]}
      />
    </Panel>
  );
}

function MealsWorkspace() {
  return (
    <Panel title="Meals & Dining" description="Tracks boarding meal attendance and special diets." icon={Utensils}>
       <DataTable 
        columns={["Meal", "Date", "Expected", "Present", "On Leave", "Issues", "Actions"]}
        rows={[
          ["Breakfast", "Today", "1,240", "1,190", "45", "0", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">View Issue</button>],
        ]}
      />
    </Panel>
  );
}

function InspectionsWorkspace() {
  return (
    <Panel title="Dorm Inspections" description="Cleanliness checks, room inspections, and hygiene." icon={CheckSquare}>
       <div className="mb-4 flex gap-2">
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white">Start Inspection</button>
       </div>
       <DataTable 
        columns={["Date", "Dorm", "Room", "Inspector", "Score", "Issues", "Status", "Actions"]}
        rows={[
          ["Today", "St. Joseph", "1A", "Mr. Kamau", "85%", "1", "Completed", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Create Repair</button>],
        ]}
      />
    </Panel>
  );
}

function MaintenanceWorkspace() {
  return (
    <Panel title="Maintenance Requests" description="Report broken beds, doors, windows, lights, etc." icon={Wrench}>
       <div className="mb-4 flex gap-2">
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white">Create Repair Request</button>
       </div>
       <DataTable 
        columns={["Ref", "Dorm", "Room", "Issue", "Priority", "Assigned To", "Status", "Actions"]}
        rows={[
          ["REP-120", "St. Paul", "2B", "Broken Window", <StatusChip key="p1" label="Urgent" tone="danger"/>, "Maintenance Team", "In Progress", <button key="a1" className="text-[#1D4ED8] font-bold text-xs">View</button>],
        ]}
      />
    </Panel>
  );
}

function InventoryWorkspace() {
  return (
    <Panel title="Boarding Inventory" description="Tracks boarding-related items issued to dorms." icon={Package}>
       <div className="mb-4 flex gap-2">
           <button className="rounded-xl bg-[#071D49] px-3 py-2 text-sm font-black text-white">Request Items</button>
       </div>
       <DataTable 
        columns={["Request Ref", "Item", "Qty", "Dorm", "Reason", "Status", "Actions"]}
        rows={[
          ["INV-450", "Mattress", "5", "St. Joseph", "Replacement", <StatusChip key="s1" label="Approved" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Confirm Receipt</button>],
        ]}
      />
    </Panel>
  );
}

function VisitorsWorkspace() {
  return (
    <Panel title="Visitors & Gate Passes" description="Coordinates parent/guardian boarding visits and student pickups." icon={UserPlus}>
       <DataTable 
        columns={["Pass No.", "Student", "Guardian", "Purpose", "Valid From", "Status", "Actions"]}
        rows={[
          ["GP-012", "Brian Otieno", "Mr. Otieno", "Medical Pickup", "Today 14:00", <StatusChip key="s1" label="Active" tone="info"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Record Checkout</button>],
        ]}
      />
    </Panel>
  );
}

function CommunicationWorkspace() {
  return (
    <Panel title="Parent Communication" description="Communicate with parents about boarding matters." icon={MessageSquare}>
       <DataTable 
        columns={["Date", "Student", "Parent", "Channel", "Subject", "Status", "Actions"]}
        rows={[
          ["Today", "Brian Otieno", "Mr. Otieno", "SMS", "Leave Approved", <StatusChip key="s1" label="Delivered" tone="success"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">View Message</button>],
        ]}
      />
    </Panel>
  );
}

function ApprovalsWorkspace() {
  return (
    <Panel title="Approvals" description="Boarding approvals in one clean workspace." icon={CheckCircle}>
       <DataTable 
        columns={["Request", "Student/Dorm", "Type", "Required Approver", "Status", "Actions"]}
        rows={[
          ["Leave Request", "Sarah K", "Overnight Leave", "Deputy Principal", <StatusChip key="s1" label="Pending" tone="warning"/>, <button key="a1" className="text-[#1D4ED8] font-bold text-xs">Escalate</button>],
        ]}
      />
    </Panel>
  );
}

function ReportsWorkspace() {
  return (
    <Panel title="Reports & Downloads" description="Generates boarding reports for daily operations and audits." icon={FileText}>
       <div className="grid gap-4 md:grid-cols-3">
         {["Daily roll call report", "Missing students report", "Leave-out report", "Late return trend", "Dorm repairs report"].map(r => (
           <button key={r} className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-left font-bold text-[#071D49] hover:border-[#071D49] transition">{r}</button>
         ))}
       </div>
    </Panel>
  );
}

function SettingsWorkspace() {
  return (
    <Panel title="Boarding Settings" description="Controls boarding-specific rules and notification rules." icon={Settings}>
       <div className="grid gap-4 md:grid-cols-2">
         <div className="rounded-xl border border-[#D8E0EC] p-4">
           <h3 className="font-bold text-[#071D49] mb-2">Notification Rules</h3>
           <label className="flex items-center gap-2 text-sm text-[#334155] mb-2"><input type="checkbox" defaultChecked /> Notify parent for late return</label>
           <label className="flex items-center gap-2 text-sm text-[#334155]"><input type="checkbox" defaultChecked /> Notify Deputy for missing roll call</label>
         </div>
       </div>
    </Panel>
  );
}

// Simple Layout Components

export function BoardingMasterCommandCenter({ routeMode }: { routeMode: RouteMode }) {
  const [activeView, setActiveView] = useState<ViewId>("overview");
  const [searchTerm, setSearchTerm] = useState("");
  const [notice, setNotice] = useState("");

  const searchResults = searchTerm.trim()
    ? searchRecords.filter((record) => \\\`\\\${record.label} \\\${record.detail}\\\`.toLowerCase().includes(searchTerm.toLowerCase()))
    : [];

  useEffect(() => {
    function handleDashboardAction(event: Event) {
      const message = (event as CustomEvent<string>).detail;
      if (message) {
        setNotice(message);
        setTimeout(() => setNotice(""), 5000);
      }
    }
    window.addEventListener("myshule-dashboard-action", handleDashboardAction);
    return () => window.removeEventListener("myshule-dashboard-action", handleDashboardAction);
  }, []);

  function openView(view: ViewId) {
    setActiveView(view);
  }

  function openSearchRecord(record: SearchRecord) {
    setActiveView(record.view);
    setSearchTerm("");
    setNotice(\\\`Opened search result: \\\${record.label}\\\`);
    setTimeout(() => setNotice(""), 5000);
  }

  return (
    <div className="flex min-h-screen bg-[#F3F6FA]">
      {/* Sidebar */}
      <aside className="hidden h-screen w-[260px] overflow-y-auto bg-[#071D49] p-4 text-white shadow-[0_24px_70px_rgba(7,29,73,0.28)] lg:block shrink-0">
        <div className="rounded-2xl border border-white/10 bg-white/5 p-4 mb-6">
          <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-100/70">MyShule</p>
          <h2 className="mt-2 text-xl font-black">Boarding Master</h2>
          <p className="mt-2 text-sm leading-6 text-white/65">All Dormitories oversight.</p>
        </div>
        <nav className="space-y-1" aria-label="Boarding master navigation">
          {navItems.map((item, index) => {
            const showGroup = item.group !== navItems[index - 1]?.group;
            const Icon = item.icon;
            return (
              <div key={\\\`\\\${item.group}-\\\${item.label}\\\`}>
                {showGroup ? <p className="px-3 pb-2 pt-4 text-[10px] font-black uppercase tracking-[0.2em] text-white/40">{item.group}</p> : null}
                <button
                  type="button"
                  onClick={() => openView(item.id)}
                  className={cn(
                    "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-white/70 transition hover:bg-white/10 hover:text-white",
                    activeView === item.id && "bg-white/15 text-white shadow-[inset_4px_0_0_#38BDF8]",
                  )}
                >
                  <Icon className="h-4 w-4" aria-hidden="true" />
                  {item.label}
                </button>
              </div>
            );
          })}
        </nav>
      </aside>

      {/* Main Area */}
      <main className="flex-1 min-w-0 flex flex-col h-screen overflow-hidden">
        {/* Topbar */}
        <header className="sticky top-0 z-20 border-b border-[#D8E0EC] bg-white/90 px-4 py-3 backdrop-blur shrink-0">
          <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
            <div className="flex items-center gap-3">
              <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#071D49] text-xs font-black text-white">BM</div>
              <div>
                <h1 className="text-lg font-black text-[#071D49]">Good Evening, Mr. Otieno</h1>
                <p className="text-xs font-bold text-[#64748B]">Boarding Master • Term 2, 2026 • Week 6 • All Dormitories</p>
              </div>
            </div>
            <div className="flex items-center gap-3">
               <div className="relative w-64 hidden md:block">
                 <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#94A3B8]" />
                 <input 
                   value={searchTerm}
                   onChange={(e) => setSearchTerm(e.target.value)}
                   className="h-10 w-full rounded-xl border border-[#D8E0EC] pl-9 pr-4 text-sm outline-none focus:border-[#071D49]" 
                   placeholder="Search student, adm, dorm, room..." 
                 />
                 {searchTerm.trim() && searchResults.length > 0 && (
                   <div className="absolute top-[calc(100%+8px)] left-0 w-full bg-white border border-[#D8E0EC] rounded-xl shadow-xl z-30 p-2">
                     {searchResults.map(r => (
                       <button key={r.id} onClick={() => openSearchRecord(r)} className="w-full text-left p-2 hover:bg-[#F8FAFC] rounded-lg">
                         <p className="font-bold text-[#071D49] text-sm">{r.label}</p>
                         <p className="text-xs text-[#64748B]">{r.detail}</p>
                       </button>
                     ))}
                   </div>
                 )}
               </div>
               <StatusChip label="Kisumu Boys" tone="info" />
               <button className="inline-flex h-10 items-center justify-center rounded-xl bg-[#071D49] px-4 text-sm font-black text-white">Start Roll Call</button>
            </div>
          </div>
          {/* Mobile Nav Selector */}
          <div className="mt-3 lg:hidden">
            <select
              className="h-10 w-full rounded-xl border border-[#D8E0EC] bg-white px-3 text-sm font-bold text-[#071D49] outline-none"
              value={activeView}
              onChange={(e) => openView(e.target.value as ViewId)}
            >
              {navItems.map((item) => (
                <option key={item.id} value={item.id}>{item.label}</option>
              ))}
            </select>
          </div>
        </header>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-4 lg:p-6">
          {notice && (
            <div className="mb-6 rounded-xl bg-blue-50 border border-blue-200 p-3 text-sm font-semibold text-blue-800 flex justify-between items-center">
              {notice}
              <button onClick={() => setNotice("")} className="text-blue-500 hover:text-blue-700"><X className="h-4 w-4" /></button>
            </div>
          )}

          {activeView === "overview" && <OverviewWorkspace onNavigate={openView} />}
          {activeView === "register" && <RegisterWorkspace />}
          {activeView === "dorms" && <DormsWorkspace />}
          {activeView === "beds" && <BedsWorkspace />}
          {activeView === "roll-call" && <RollCallWorkspace />}
          {activeView === "leave" && <LeaveWorkspace />}
          {activeView === "late-returns" && <LateReturnsWorkspace />}
          {activeView === "duty" && <DutyWorkspace />}
          {activeView === "incidents" && <IncidentsWorkspace />}
          {activeView === "welfare" && <WelfareWorkspace />}
          {activeView === "meals" && <MealsWorkspace />}
          {activeView === "inspections" && <InspectionsWorkspace />}
          {activeView === "maintenance" && <MaintenanceWorkspace />}
          {activeView === "inventory" && <InventoryWorkspace />}
          {activeView === "visitors" && <VisitorsWorkspace />}
          {activeView === "communication" && <CommunicationWorkspace />}
          {activeView === "approvals" && <ApprovalsWorkspace />}
          {activeView === "reports" && <ReportsWorkspace />}
          {activeView === "settings" && <SettingsWorkspace />}
        </div>
      </main>
    </div>
  );
}
`;

fs.writeFileSync('apps/web/src/components/school/boarding-master-command-center.tsx', tsx);
console.log('Successfully generated apps/web/src/components/school/boarding-master-command-center.tsx');
