const fs = require('fs');

const workspaces = [
  { id: "home", label: "Overview", icon: "Home", group: "Overview", desc: "This is the Class Teacher’s command center. It shows the class condition today." },
  { id: "register", label: "My Class Register", icon: "Users", group: "Class Operations", desc: "Shows all learners officially assigned to the class/stream." },
  { id: "attendance", label: "Attendance", icon: "ClipboardCheck", group: "Class Operations", desc: "Daily class roll call. This is one of the most important Class Teacher tasks." },
  { id: "progress", label: "Academic Progress", icon: "GraduationCap", group: "Academics", desc: "Class Teacher monitors overall academic performance of the assigned class." },
  { id: "comments", label: "Report Card Comments", icon: "FileSignature", group: "Academics", desc: "Class Teacher adds final comments before report cards are approved/published." },
  { id: "discipline", label: "Discipline & Behaviour", icon: "ShieldAlert", group: "Student Welfare", desc: "Class Teacher sees class-level behaviour issues and records minor incidents." },
  { id: "welfare", label: "Welfare & Counselling", icon: "HeartPulse", group: "Student Welfare", desc: "Class Teacher identifies learners who may need extra support and refers them safely." },
  { id: "health", label: "Health Notes", icon: "Stethoscope", group: "Student Welfare", desc: "Shows safe learner health alerts and nurse-related class follow-ups." },
  { id: "fees", label: "Fees Follow-up", icon: "Banknote", group: "Administration", desc: "Class Teacher can see basic fee status for follow-up." },
  { id: "communication", label: "Parent Communication", icon: "MessageCircle", group: "Communication", desc: "Send and track parent/guardian communication for the class." },
  { id: "meetings", label: "Meetings & Appointments", icon: "Calendar", group: "Communication", desc: "Track parent meetings and learner follow-ups." },
  { id: "homework", label: "Homework & Class Tasks", icon: "BookOpenCheck", group: "Planning", desc: "Class Teacher can view class-wide homework/task load and create class notices or tasks." },
  { id: "timetable", label: "Timetable", icon: "CalendarDays", group: "Planning", desc: "Class Teacher views the class timetable and daily schedule." },
  { id: "documents", label: "Documents & Letters", icon: "FolderOpen", group: "Resources", desc: "Generate class-related printable documents." },
  { id: "requests", label: "Requests & Approvals", icon: "CheckSquare", group: "Resources", desc: "Class Teacher creates requests that need action from other roles." },
  { id: "reports", label: "Reports & Downloads", icon: "FileText", group: "Resources", desc: "Generate class-level reports for daily, weekly, termly, and end-term use." },
  { id: "notifications", label: "Notifications", icon: "Bell", group: "System", desc: "Shows all tasks, alerts, replies, approvals, and system messages relevant to the Class Teacher." },
  { id: "settings", label: "Settings", icon: "Settings", group: "System", desc: "Small class-level preferences." },
];

let tsx = `// GENERATED BY scaffold_class_teacher.js
"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import {
  AlertTriangle,
  Bell,
  BookOpenCheck,
  Calendar,
  CalendarDays,
  CheckSquare,
  ChevronDown,
  ClipboardCheck,
  FileSignature,
  FileText,
  FolderOpen,
  GraduationCap,
  HeartPulse,
  Home,
  MessageCircle,
  MoreHorizontal,
  Search,
  Settings,
  ShieldAlert,
  Stethoscope,
  Banknote,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

import {
  getCurrentSchoolId,
  publishSchoolOperationalEvent,
} from "@/lib/school/school-operational-store";
import { openPrintDocument } from "@/lib/dashboard/export";

type ClassTeacherRouteMode = "hosted" | "public";
type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type TeacherView = ${workspaces.map(w => `"${w.id}"`).join(" | ")};

type NavItem = {
  id: TeacherView;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
${workspaces.map(w => `  { id: "${w.id}", label: "${w.label}", icon: ${w.icon}, group: "${w.group}" },`).join("\n")}
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

const classTeacherSearchRecords = [
  { id: "student-brian", label: "Brian Otieno", detail: "ADM-2041 | absent today | parent follow-up", view: "register" },
  { id: "guardian-wanjiku", label: "Mrs. Wanjiku", detail: "Guardian message about homework completion", view: "communication" },
] satisfies Array<{ id: string; label: string; detail: string; view: TeacherView }>;

type ClassTeacherSearchRecord = (typeof classTeacherSearchRecords)[number];

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions}
      </div>
      {children}
    </section>
  );
}

// Sub-components for specific workspaces
function OverviewWorkspace() {
  return (
    <Panel title="Overview" description="This is the Class Teacher’s command center. It shows the class condition today." icon={Home}>
      <div className="grid gap-4 md:grid-cols-4">
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 font-bold text-[#071D49]">Total Learners: 46</div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 font-bold text-[#071D49]">Present Today: 43</div>
        <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 font-bold text-rose-700">Absent Today: 3</div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 font-bold text-[#071D49]">Fee Arrears: 7</div>
      </div>
    </Panel>
  );
}

function SimpleWorkspace({
  title,
  description,
  icon,
}: {
  title: string;
  description: string;
  icon: LucideIcon;
}) {
  return (
    <Panel title={title} description={description} icon={icon}>
      <div className="flex flex-col items-center justify-center py-12 text-center">
        <AlertTriangle className="h-12 w-12 text-[#64748B]/30 mb-4" />
        <p className="text-lg font-semibold text-[#071D49]">Workspace Content Pending</p>
        <p className="mt-2 text-sm text-[#64748B]">This module is being connected to the new MyShule architecture.</p>
      </div>
    </Panel>
  );
}

function LearnerProfileDrawer({
  learnerId,
  onClose,
}: {
  learnerId: string | null;
  onClose: () => void;
}) {
  if (!learnerId) return null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end bg-[#071D49]/20 backdrop-blur-sm">
      <div className="w-full max-w-lg bg-white h-full shadow-2xl flex flex-col border-l border-[#D8E0EC] overflow-y-auto">
        <header className="sticky top-0 bg-white/95 backdrop-blur z-10 border-b border-[#D8E0EC] p-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-12 w-12 rounded-full bg-[#071D49] text-white flex items-center justify-center font-black">
              {learnerId.substring(0,2).toUpperCase()}
            </div>
            <div>
              <h2 className="text-lg font-black text-[#071D49]">Learner Profile</h2>
              <p className="text-xs font-semibold text-[#64748B]">{learnerId}</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-[#F3F6FA] rounded-full transition text-[#64748B]">
            <X className="h-5 w-5" />
          </button>
        </header>

        <div className="p-4 space-y-6">
          <section className="space-y-3">
             <h3 className="text-xs font-black uppercase tracking-widest text-[#64748B]">Quick Actions</h3>
             <div className="flex flex-wrap gap-2">
               <button className="rounded-full bg-[#071D49] px-3 py-1.5 text-xs font-black text-white">Message Parent</button>
               <button className="rounded-full border border-[#D8E0EC] px-3 py-1.5 text-xs font-black text-[#071D49]">Schedule Meeting</button>
               <button className="rounded-full border border-[#D8E0EC] px-3 py-1.5 text-xs font-black text-[#071D49]">Add Class Note</button>
             </div>
          </section>

          <section>
            <h3 className="text-xs font-black uppercase tracking-widest text-[#64748B] mb-3">Overview</h3>
            <div className="grid grid-cols-2 gap-3">
              <div className="rounded-xl bg-[#F8FAFC] border border-[#D8E0EC] p-3">
                <span className="block text-xs text-[#64748B] mb-1">Attendance</span>
                <span className="block font-black text-[#071D49]">92%</span>
              </div>
              <div className="rounded-xl bg-[#F8FAFC] border border-[#D8E0EC] p-3">
                <span className="block text-xs text-[#64748B] mb-1">Fee Status</span>
                <span className="block font-black text-rose-600">Arrears</span>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}

export function ClassTeacherCommandCenter({ routeMode }: { routeMode: ClassTeacherRouteMode }) {
  const [activeView, setActiveView] = useState<TeacherView>("home");
  const [searchTerm, setSearchTerm] = useState("");
  const [notice, setNotice] = useState("Ready for Form 2 Blue daily follow-up.");
  const [selectedLearner, setSelectedLearner] = useState<string | null>(null);

  const searchResults = searchTerm.trim()
    ? classTeacherSearchRecords.filter((record) => \`\${record.label} \${record.detail}\`.toLowerCase().includes(searchTerm.toLowerCase()))
    : [];

  function openView(view: TeacherView) {
    setActiveView(view);
    setNotice(\`Workspace changed.\`);
  }

  function openSearchRecord(record: ClassTeacherSearchRecord) {
    setActiveView(record.view);
    setSearchTerm("");
  }

  return (
    <div className="flex min-h-screen bg-[#F3F6FA]">
      <Sidebar activeView={activeView} onViewChange={openView} />
      <main className="flex-1 min-w-0 flex flex-col">
        <Topbar
          searchTerm={searchTerm}
          searchResults={searchResults}
          onSearchTermChange={setSearchTerm}
          onSearchResult={openSearchRecord}
          onQuickView={openView}
        />
        <div className="flex-1 overflow-y-auto p-4 lg:p-6 space-y-6">
          {notice && (
            <div className="rounded-xl bg-blue-50 border border-blue-200 p-3 text-sm font-semibold text-blue-800 flex justify-between items-center">
              {notice}
              <button onClick={() => setNotice("")} className="text-blue-500 hover:text-blue-700">
                <X className="h-4 w-4" />
              </button>
            </div>
          )}

          {activeView === "home" && <OverviewWorkspace />}
          {activeView === "register" && (
             <Panel title="My Class Register" description="Shows all learners officially assigned to the class." icon={Users} actions={
               <button onClick={() => setSelectedLearner("Brian Otieno")} className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Open Sample Learner Profile</button>
             }>
                <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-center">
                   <p className="text-sm font-semibold text-[#64748B]">Click the button above to test the Learner Profile Drawer.</p>
                </div>
             </Panel>
          )}
${workspaces.filter(w => !["home", "register"].includes(w.id)).map(w => `          {activeView === "${w.id}" && <SimpleWorkspace title="${w.label}" description="${w.desc}" icon={${w.icon}} />}`).join("\n")}
        </div>
      </main>

      <LearnerProfileDrawer learnerId={selectedLearner} onClose={() => setSelectedLearner(null)} />
    </div>
  );
}

// Include required layout components below
function Sidebar({
  activeView,
  onViewChange,
}: {
  activeView: TeacherView;
  onViewChange: (view: TeacherView) => void;
}) {
  return (
    <aside className="hidden h-screen w-[260px] overflow-y-auto bg-[#071D49] p-4 text-white shadow-[0_24px_70px_rgba(7,29,73,0.28)] lg:block shrink-0">
      <div className="rounded-2xl border border-white/10 bg-white/5 p-4 mb-6">
        <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-100/70">MyShule</p>
        <h2 className="mt-2 text-xl font-black">Class Teacher</h2>
        <p className="mt-2 text-sm leading-6 text-white/65">Form 2 Blue daily operations.</p>
      </div>
      <nav className="space-y-1" aria-label="Class teacher navigation">
        {navItems.map((item, index) => {
          const showGroup = item.group !== navItems[index - 1]?.group;
          const Icon = item.icon;

          return (
            <div key={\`\${item.group}-\${item.label}\`}>
              {showGroup ? <p className="px-3 pb-2 pt-4 text-[10px] font-black uppercase tracking-[0.2em] text-white/40">{item.group}</p> : null}
              <button
                type="button"
                onClick={() => onViewChange(item.id)}
                className={cn(
                  "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-white/70 transition hover:bg-white/10 hover:text-white",
                  activeView === item.id && "bg-white/15 text-white shadow-[inset_4px_0_0_#38BDF8]",
                )}
              >
                <Icon className="h-4 w-4" aria-hidden="true" />
                {item.label}
              </button>
            </div>
          );
        })}
      </nav>
    </aside>
  );
}

function Topbar({
  searchTerm,
  searchResults,
  onSearchTermChange,
  onSearchResult,
  onQuickView,
}: {
  searchTerm: string;
  searchResults: typeof classTeacherSearchRecords;
  onSearchTermChange: (value: string) => void;
  onSearchResult: (record: ClassTeacherSearchRecord) => void;
  onQuickView: (view: TeacherView) => void;
}) {
  return (
    <header className="sticky top-0 z-20 border-b border-[#D8E0EC] bg-white/90 px-4 py-3 backdrop-blur">
      <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
        <div className="flex items-center gap-3">
          <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#071D49] text-xs font-black text-white">CT</div>
          <h1 className="text-lg font-black text-[#071D49]">Class Teacher Workspace</h1>
        </div>
        <div className="flex items-center gap-3">
          <StatusChip label="Term 2" tone="info" />
          <button
            type="button"
            className="inline-flex min-h-10 items-center justify-center rounded-xl bg-[#071D49] px-4 text-sm font-black text-white"
          >
            Mark Attendance
          </button>
        </div>
      </div>
    </header>
  );
}
`;

fs.writeFileSync('apps/web/src/components/school/class-teacher-command-center.tsx', tsx);
console.log('Successfully regenerated class-teacher-command-center.tsx');
