
const fs = require('fs');
fs.writeFileSync('scaffold_librarian.js', `const fs = require('fs');

const workspaces = [
  { id: "overview", label: "Overview", icon: "Home", group: "Dashboard", desc: "Manage books, loans, returns, overdue items, stock status, and borrower activity." },
  { id: "issue", label: "Issue Books", icon: "BookUp", group: "Circulation", desc: "Issue books to students, staff, classes, streams, departments, or teachers." },
  { id: "return", label: "Return Books", icon: "BookDown", group: "Circulation", desc: "Receive returned books, update condition, clear loans, and calculate overdue fines." },
  { id: "catalogue", label: "Book Catalogue", icon: "Library", group: "Inventory", desc: "View, search, filter, edit, and manage all library books and copies." },
  { id: "add_books", label: "Add / Accession Books", icon: "BookPlus", group: "Inventory", desc: "Register new book titles, add copies, generate accession numbers, and print barcodes." },
  { id: "loans", label: "Loans & Overdues", icon: "Clock", group: "Monitoring", desc: "Monitor issued books, due dates, overdue borrowers, reminders, and escalation status." },
  { id: "lost_damaged", label: "Lost / Damaged Books", icon: "HeartCrack", group: "Monitoring", desc: "Record lost and damaged books, assign charges, update book status, and track recovery." },
  { id: "fines", label: "Fines & Payments", icon: "Banknote", group: "Monitoring", desc: "Manage library fines, replacement charges, waivers, and payment follow-up." },
  { id: "borrowers", label: "Students & Borrowers", icon: "Users", group: "People", desc: "View borrower profiles, active loans, overdue history, fines, and borrowing eligibility." },
  { id: "class_textbooks", label: "Class Textbook Distribution", icon: "Layers", group: "People", desc: "Distribute textbooks, readers, and subject resources to classes and teachers." },
  { id: "reservations", label: "Reservations", icon: "Bookmark", group: "Operations", desc: "Manage book reservations, waiting lists, availability alerts, and reservation expiry." },
  { id: "stocktake", label: "Library Stocktake", icon: "ScanBarcode", group: "Operations", desc: "Scan, count, reconcile, and report library stock by shelf, category, or whole library." },
  { id: "departments", label: "Departments & Subject Resources", icon: "Briefcase", group: "Operations", desc: "Manage resources assigned to subjects, departments, teachers, and learning areas." },
  { id: "visits", label: "Library Visits & Reading Logs", icon: "Footprints", group: "Analytics", desc: "Record student library visits, reading sessions, and reading program participation." },
  { id: "requests", label: "Requests & Approvals", icon: "CheckSquare", group: "System", desc: "Handle book requests, stock purchase requests, write-off approvals, and waivers." },
  { id: "reports", label: "Reports & Downloads", icon: "FileText", group: "System", desc: "Generate library reports for management, classes, departments, audits, and parents." },
  { id: "notices", label: "Notices & Communication", icon: "MessageCircle", group: "System", desc: "Send library notices, overdue reminders, fine alerts, and lost book notices." },
  { id: "settings", label: "Library Settings", icon: "Settings", group: "System", desc: "Configure library rules, borrowing limits, due dates, fines, and notification templates." }
];

let tsx = \`// GENERATED BY scaffold_librarian.js
"use client";

import { useState, type FormEvent, type ReactNode } from "react";
import {
  AlertTriangle,
  Banknote,
  Bell,
  BookDown,
  Bookmark,
  BookOpen,
  BookPlus,
  BookUp,
  Briefcase,
  Calendar,
  CheckCircle2,
  CheckSquare,
  ChevronDown,
  Clock,
  Download,
  FileText,
  Filter,
  Footprints,
  HeartCrack,
  Home,
  Layers,
  Library,
  MessageCircle,
  MoreHorizontal,
  Plus,
  Printer,
  ScanBarcode,
  Search,
  Settings,
  Users,
  X,
  XCircle,
  type LucideIcon,
} from "lucide-react";

import {
  getCurrentSchoolId,
  publishSchoolOperationalEvent,
} from "@/lib/school/school-operational-store";

type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type LibrarianView = \${workspaces.map(w => \`"\${w.id}"\`).join(" | ")};

type NavItem = {
  id: LibrarianView;
  label: string;
  icon: LucideIcon;
  group: string;
};

const navItems: NavItem[] = [
\${workspaces.map(w => \`  { id: "\${w.id}", label: "\${w.label}", icon: \${w.icon}, group: "\${w.group}" },\`).join("\n")}
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold whitespace-nowrap", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full shrink-0", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions && <div className="shrink-0">{actions}</div>}
      </div>
      {children}
    </section>
  );
}

// ----------------------------------------------------------------------
// WORKSPACE COMPONENTS
// ----------------------------------------------------------------------

function OverviewWorkspace({ onNavigate }: { onNavigate: (v: LibrarianView) => void }) {
  return (
    <Panel title="Library Overview" description="Manage books, loans, returns, overdue items, stock status, and borrower activity for the current term." icon={Home}>
      <div className="grid gap-4 md:grid-cols-4 lg:grid-cols-6 mb-6">
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("catalogue")}>
          <div className="text-sm font-semibold text-[#64748B]">Total Books</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">12,450</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("catalogue")}>
          <div className="text-sm font-semibold text-[#64748B]">Available</div>
          <div className="mt-1 text-2xl font-black text-emerald-600">11,200</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("loans")}>
          <div className="text-sm font-semibold text-[#64748B]">Issued Out</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">1,150</div>
        </div>
        <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 cursor-pointer hover:border-rose-300 transition" onClick={() => onNavigate("loans")}>
          <div className="text-sm font-semibold text-rose-700">Overdue Books</div>
          <div className="mt-1 text-2xl font-black text-rose-700">84</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("lost_damaged")}>
          <div className="text-sm font-semibold text-[#64748B]">Lost This Year</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">16</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition" onClick={() => onNavigate("fines")}>
          <div className="text-sm font-semibold text-[#64748B]">Fines Pending</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">KES 4,500</div>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          <div className="rounded-xl border border-[#D8E0EC] overflow-hidden">
            <div className="bg-[#F8FAFC] px-4 py-3 border-b border-[#D8E0EC] flex justify-between items-center">
              <h3 className="font-bold text-[#071D49]">Today’s Library Queue</h3>
              <button className="text-sm text-blue-600 font-semibold hover:underline">View All</button>
            </div>
            <div className="p-4">
              <table className="w-full text-sm text-left">
                <thead>
                  <tr className="text-[#64748B] border-b border-[#D8E0EC]">
                    <th className="pb-2 font-semibold">Borrower</th>
                    <th className="pb-2 font-semibold">Class</th>
                    <th className="pb-2 font-semibold">Book</th>
                    <th className="pb-2 font-semibold">Status</th>
                    <th className="pb-2 font-semibold text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#D8E0EC]">
                  <tr>
                    <td className="py-3 font-medium text-[#071D49]">Amina Wanjiku</td>
                    <td className="py-3 text-[#64748B]">Form 2 East</td>
                    <td className="py-3 text-[#071D49]">Blossoms of the Savannah</td>
                    <td className="py-3"><StatusChip label="Due Today" tone="warning" /></td>
                    <td className="py-3 text-right">
                      <button className="text-blue-600 hover:underline font-semibold" onClick={() => onNavigate("return")}>Receive</button>
                    </td>
                  </tr>
                  <tr>
                    <td className="py-3 font-medium text-[#071D49]">Brian Otieno</td>
                    <td className="py-3 text-[#64748B]">Form 3 Blue</td>
                    <td className="py-3 text-[#071D49]">A Doll's House</td>
                    <td className="py-3"><StatusChip label="Overdue" tone="danger" /></td>
                    <td className="py-3 text-right">
                      <button className="text-blue-600 hover:underline font-semibold" onClick={() => onNavigate("loans")}>Remind</button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          
          <div className="rounded-xl border border-[#D8E0EC] overflow-hidden">
            <div className="bg-[#F8FAFC] px-4 py-3 border-b border-[#D8E0EC]">
              <h3 className="font-bold text-[#071D49]">Recent Activity</h3>
            </div>
            <div className="p-4 space-y-4 text-sm">
              <div className="flex gap-3">
                <div className="w-2 h-2 rounded-full bg-emerald-500 mt-1.5 shrink-0"></div>
                <div><span className="font-semibold">Book Issued:</span> <em>Memories We Lost</em> issued to John Doe (Form 1 West).</div>
              </div>
              <div className="flex gap-3">
                <div className="w-2 h-2 rounded-full bg-blue-500 mt-1.5 shrink-0"></div>
                <div><span className="font-semibold">Book Returned:</span> <em>KCSE Revision Chemistry</em> by Mary Njeri.</div>
              </div>
              <div className="flex gap-3">
                <div className="w-2 h-2 rounded-full bg-rose-500 mt-1.5 shrink-0"></div>
                <div><span className="font-semibold">Marked Lost:</span> <em>Secondary Math Bk 2</em> reported lost by Kevin Ochieng.</div>
              </div>
            </div>
          </div>
        </div>

        <div className="space-y-6">
          <div className="rounded-xl border border-rose-200 bg-rose-50 overflow-hidden">
            <div className="px-4 py-3 border-b border-rose-200 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-rose-600" />
              <h3 className="font-bold text-rose-900">Urgent Alerts</h3>
            </div>
            <div className="p-4 space-y-3 text-sm text-rose-800">
              <div className="flex justify-between items-start">
                <span><strong>84 books</strong> are currently overdue.</span>
                <button className="text-rose-900 underline font-semibold text-xs" onClick={() => onNavigate("loans")}>View</button>
              </div>
              <div className="flex justify-between items-start">
                <span><strong>5 students</strong> have more than 2 overdue books.</span>
                <button className="text-rose-900 underline font-semibold text-xs" onClick={() => onNavigate("borrowers")}>View</button>
              </div>
              <div className="flex justify-between items-start">
                <span><strong>2 classes</strong> have not returned termly readers.</span>
                <button className="text-rose-900 underline font-semibold text-xs" onClick={() => onNavigate("class_textbooks")}>Notify</button>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-center">
            <ScanBarcode className="h-10 w-10 text-[#071D49] mx-auto mb-2 opacity-80" />
            <p className="text-sm font-bold text-[#071D49] mb-4">Quick Issue / Return</p>
            <div className="flex flex-col gap-2">
              <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white" onClick={() => onNavigate("issue")}>Open Issue Desk</button>
              <button className="rounded-lg border border-[#071D49] px-4 py-2 text-sm font-black text-[#071D49]" onClick={() => onNavigate("return")}>Open Return Desk</button>
            </div>
          </div>
        </div>
      </div>
    </Panel>
  );
}

function IssueBooksWorkspace() {
  const [basket, setBasket] = useState<{title: string, barcode: string}[]>([]);
  const [barcodeInput, setBarcodeInput] = useState("");
  const [successMsg, setSuccessMsg] = useState("");

  const handleScan = (e: React.FormEvent) => {
    e.preventDefault();
    if (!barcodeInput) return;
    setBasket([...basket, { title: "Sample Book Scanned", barcode: barcodeInput }]);
    setBarcodeInput("");
  };

  const handleIssue = () => {
    if (basket.length === 0) return;
    setSuccessMsg(\\`\\${basket.length} books issued to Brian Otieno. Due date: 26 June 2026.\\`);
    setBasket([]);
  };

  return (
    <Panel title="Issue Books" description="Fast book issuing using barcode scan or manual search." icon={BookUp}>
      {successMsg && (
        <div className="mb-4 rounded-xl bg-emerald-50 border border-emerald-200 p-4 text-sm font-bold text-emerald-800 flex justify-between">
          <div className="flex items-center gap-2"><CheckCircle2 className="w-5 h-5" /> {successMsg}</div>
          <button className="underline">Print Issue Slip</button>
        </div>
      )}
      
      <div className="grid lg:grid-cols-2 gap-6">
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-bold text-[#071D49] mb-1">1. Select Borrower</label>
            <div className="relative">
              <Search className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" />
              <input type="text" placeholder="Search student by name, admission number, class..." className="w-full rounded-xl border border-[#D8E0EC] py-2 pl-9 pr-3 text-sm focus:border-[#071D49] focus:outline-none focus:ring-1 focus:ring-[#071D49]" />
            </div>
            {/* Mock selected borrower */}
            <div className="mt-2 rounded-xl border border-blue-200 bg-blue-50 p-3 flex justify-between items-center">
              <div>
                <div className="font-bold text-blue-900">Brian Otieno</div>
                <div className="text-xs text-blue-700">ADM-2041 • Form 3 Blue • <span className="font-bold">Clear Status</span></div>
              </div>
              <button className="text-blue-500 hover:bg-blue-100 p-1 rounded"><X className="w-4 h-4" /></button>
            </div>
          </div>

          <div>
            <label className="block text-sm font-bold text-[#071D49] mb-1">2. Scan or Search Book</label>
            <form onSubmit={handleScan} className="relative">
              <ScanBarcode className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" />
              <input autoFocus type="text" value={barcodeInput} onChange={e => setBarcodeInput(e.target.value)} placeholder="Scan barcode or search title, ISBN..." className="w-full rounded-xl border border-[#D8E0EC] py-2 pl-9 pr-3 text-sm focus:border-[#071D49] focus:outline-none focus:ring-1 focus:ring-[#071D49]" />
            </form>
          </div>
        </div>

        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] flex flex-col">
          <div className="px-4 py-3 border-b border-[#D8E0EC] font-bold text-[#071D49] flex justify-between">
            <span>Issue Basket ({basket.length})</span>
            {basket.length > 0 && <button className="text-xs text-rose-600 hover:underline" onClick={() => setBasket([])}>Clear</button>}
          </div>
          <div className="p-4 flex-1 overflow-auto min-h-[200px]">
            {basket.length === 0 ? (
              <div className="text-center text-[#64748B] text-sm py-8">Scan a book to add to basket</div>
            ) : (
              <ul className="space-y-2">
                {basket.map((item, idx) => (
                  <li key={idx} className="flex justify-between items-center bg-white p-2 border border-[#D8E0EC] rounded-lg text-sm">
                    <div>
                      <div className="font-semibold text-[#071D49]">{item.title}</div>
                      <div className="text-xs text-[#64748B]">Barcode: {item.barcode}</div>
                    </div>
                    <button className="text-rose-500"><XCircle className="w-4 h-4" /></button>
                  </li>
                ))}
              </ul>
            )}
          </div>
          <div className="p-4 border-t border-[#D8E0EC] bg-white rounded-b-xl">
            <button 
              disabled={basket.length === 0}
              onClick={handleIssue}
              className="w-full rounded-xl bg-[#071D49] py-3 text-sm font-black text-white disabled:opacity-50"
            >
              Issue {basket.length} Books
            </button>
          </div>
        </div>
      </div>
    </Panel>
  );
}

function ReturnBooksWorkspace() {
  const [barcodeInput, setBarcodeInput] = useState("");
  const [returned, setReturned] = useState<{title: string, borrower: string, fine: string} | null>(null);

  const handleScan = (e: React.FormEvent) => {
    e.preventDefault();
    if (!barcodeInput) return;
    setReturned({ title: "The River and the Source", borrower: "Amina Wanjiku", fine: "None" });
    setBarcodeInput("");
  };

  return (
    <Panel title="Return Books" description="Receive returned books, update condition, and clear loans." icon={BookDown}>
      <div className="max-w-2xl mx-auto">
        <form onSubmit={handleScan} className="mb-6 relative">
          <ScanBarcode className="absolute left-4 top-3.5 h-5 w-5 text-[#64748B]" />
          <input autoFocus type="text" value={barcodeInput} onChange={e => setBarcodeInput(e.target.value)} placeholder="Scan book barcode to return..." className="w-full rounded-2xl border-2 border-[#D8E0EC] py-3 pl-12 pr-4 text-base focus:border-[#071D49] focus:outline-none" />
          <button type="submit" className="absolute right-2 top-2 rounded-lg bg-[#071D49] px-4 py-1.5 text-sm font-black text-white">Return</button>
        </form>

        {returned && (
          <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 text-center animate-in fade-in slide-in-from-bottom-4">
            <CheckCircle2 className="h-12 w-12 text-emerald-500 mx-auto mb-4" />
            <h3 className="text-xl font-black text-emerald-900 mb-1">Book Returned Successfully</h3>
            <p className="text-emerald-700 font-medium mb-4">{returned.title} returned by {returned.borrower}.</p>
            <div className="flex justify-center gap-3">
              <button className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-black text-white" onClick={() => setReturned(null)}>Scan Next Book</button>
              <button className="rounded-lg border border-emerald-300 px-4 py-2 text-sm font-black text-emerald-800">Print Return Slip</button>
            </div>
          </div>
        )}
      </div>
    </Panel>
  );
}

function BookCatalogueWorkspace() {
  return (
    <Panel title="Book Catalogue" description="View, search, filter, edit, and manage all library books and copies." icon={Library} actions={
      <button className="flex items-center gap-2 rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">
        <Plus className="h-4 w-4" /> Add Book
      </button>
    }>
      <div className="flex flex-col sm:flex-row gap-3 mb-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" />
          <input type="text" placeholder="Search title, author, ISBN, barcode..." className="w-full rounded-xl border border-[#D8E0EC] py-2 pl-9 pr-3 text-sm focus:border-[#071D49] focus:outline-none focus:ring-1 focus:ring-[#071D49]" />
        </div>
        <button className="flex items-center gap-2 rounded-xl border border-[#D8E0EC] bg-white px-4 py-2 text-sm font-bold text-[#071D49]">
          <Filter className="h-4 w-4" /> Filters
        </button>
      </div>
      
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Author</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">ISBN</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Subject</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Total</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Available</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { title: "Blossoms of the Savannah", author: "H.R. Ole Kulet", isbn: "978-9966-06-6", subject: "Literature", total: 45, available: 12 },
              { title: "Secondary Math Form 2", author: "KICD", isbn: "978-9966-22-1", subject: "Mathematics", total: 120, available: 105 },
              { title: "A Doll's House", author: "Henrik Ibsen", isbn: "978-0140-44-1", subject: "Literature", total: 50, available: 2 },
            ].map((b, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{b.title}</td>
                <td className="px-4 py-3 text-[#64748B]">{b.author}</td>
                <td className="px-4 py-3 text-[#64748B]">{b.isbn}</td>
                <td className="px-4 py-3 text-[#64748B]">{b.subject}</td>
                <td className="px-4 py-3 font-medium">{b.total}</td>
                <td className="px-4 py-3 font-medium text-emerald-600">{b.available}</td>
                <td className="px-4 py-3 text-right">
                  <button className="p-1 text-[#64748B] hover:bg-[#D8E0EC] rounded"><MoreHorizontal className="w-4 h-4" /></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}


function AddBooksWorkspace() {
  return (
    <Panel title="Add / Accession Books" description="Register new book titles, add copies, generate accession numbers, and print barcodes." icon={BookPlus}>
      <div className="grid lg:grid-cols-3 gap-6">
        <div className="lg:col-span-2 space-y-6">
          <div className="rounded-xl border border-[#D8E0EC] bg-white p-5">
            <h3 className="font-bold text-[#071D49] mb-4">Book Details</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="col-span-2">
                <label className="block text-sm font-bold text-[#071D49] mb-1">Title *</label>
                <input type="text" className="w-full rounded-xl border border-[#D8E0EC] py-2 px-3 text-sm focus:border-[#071D49] focus:outline-none focus:ring-1 focus:ring-[#071D49]" placeholder="e.g., The River and the Source" />
              </div>
              <div>
                <label className="block text-sm font-bold text-[#071D49] mb-1">Author *</label>
                <input type="text" className="w-full rounded-xl border border-[#D8E0EC] py-2 px-3 text-sm focus:border-[#071D49] focus:outline-none" placeholder="e.g., Margaret Ogola" />
              </div>
              <div>
                <label className="block text-sm font-bold text-[#071D49] mb-1">ISBN</label>
                <input type="text" className="w-full rounded-xl border border-[#D8E0EC] py-2 px-3 text-sm focus:border-[#071D49] focus:outline-none" placeholder="e.g., 978-9966-..." />
              </div>
              <div>
                <label className="block text-sm font-bold text-[#071D49] mb-1">Category *</label>
                <select className="w-full rounded-xl border border-[#D8E0EC] py-2 px-3 text-sm focus:border-[#071D49] focus:outline-none bg-white">
                  <option>Literature</option>
                  <option>Mathematics</option>
                  <option>Science</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-bold text-[#071D49] mb-1">Class Level</label>
                <select className="w-full rounded-xl border border-[#D8E0EC] py-2 px-3 text-sm focus:border-[#071D49] focus:outline-none bg-white">
                  <option>All Classes</option>
                  <option>Form 1</option>
                  <option>Form 2</option>
                </select>
              </div>
            </div>
          </div>

          <div className="rounded-xl border border-[#D8E0EC] bg-white p-5">
            <h3 className="font-bold text-[#071D49] mb-4">Copy Details</h3>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-bold text-[#071D49] mb-1">Number of Copies *</label>
                <input type="number" min="1" defaultValue="1" className="w-full rounded-xl border border-[#D8E0EC] py-2 px-3 text-sm focus:border-[#071D49] focus:outline-none" />
              </div>
              <div>
                <label className="block text-sm font-bold text-[#071D49] mb-1">Shelf Location *</label>
                <input type="text" className="w-full rounded-xl border border-[#D8E0EC] py-2 px-3 text-sm focus:border-[#071D49] focus:outline-none" placeholder="e.g., Shelf A2" />
              </div>
              <div>
                <label className="block text-sm font-bold text-[#071D49] mb-1">Accession Mode</label>
                <select className="w-full rounded-xl border border-[#D8E0EC] py-2 px-3 text-sm focus:border-[#071D49] focus:outline-none bg-white">
                  <option>Auto-generate</option>
                  <option>Manual Entry</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-bold text-[#071D49] mb-1">Acquisition Source</label>
                <select className="w-full rounded-xl border border-[#D8E0EC] py-2 px-3 text-sm focus:border-[#071D49] focus:outline-none bg-white">
                  <option>Purchase</option>
                  <option>Donation</option>
                  <option>Government Supply</option>
                </select>
              </div>
            </div>
          </div>
          
          <div className="flex gap-3">
            <button className="rounded-xl bg-[#071D49] px-6 py-2.5 text-sm font-black text-white">Save & Add Copies</button>
            <button className="rounded-xl border border-[#D8E0EC] bg-white px-6 py-2.5 text-sm font-bold text-[#071D49]">Save & Print Barcodes</button>
          </div>
        </div>

        <div className="space-y-6">
          <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-5">
            <h3 className="font-bold text-[#071D49] mb-2">Bulk Import</h3>
            <p className="text-sm text-[#64748B] mb-4">Got a lot of books to add? Use our CSV template.</p>
            <div className="space-y-3 flex flex-col">
              <button className="flex justify-center items-center gap-2 rounded-lg bg-white border border-[#D8E0EC] px-4 py-2 text-sm font-bold text-[#071D49]">
                <Download className="w-4 h-4" /> Download Template
              </button>
              <button className="flex justify-center items-center gap-2 rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">
                Upload CSV
              </button>
            </div>
          </div>
        </div>
      </div>
    </Panel>
  );
}

function LoansOverduesWorkspace() {
  return (
    <Panel title="Loans & Overdues" description="Monitor issued books, due dates, overdue borrowers, reminders, and escalation status." icon={Clock} actions={
      <div className="flex gap-2">
        <button className="rounded-lg border border-[#D8E0EC] bg-white px-4 py-2 text-sm font-bold text-[#071D49]">Export</button>
        <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Send SMS Reminders</button>
      </div>
    }>
      <div className="flex gap-4 mb-4 border-b border-[#D8E0EC]">
        <button className="pb-2 text-sm font-black text-[#071D49] border-b-2 border-[#071D49]">Overdue</button>
        <button className="pb-2 text-sm font-bold text-[#64748B]">Due Today</button>
        <button className="pb-2 text-sm font-bold text-[#64748B]">All Active Loans</button>
        <button className="pb-2 text-sm font-bold text-[#64748B]">Reminder History</button>
      </div>

      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]"><input type="checkbox" className="rounded" /></th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Borrower</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Class/Dept</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Book Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Due Date</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Overdue</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Reminder</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { borrower: "Brian Otieno", class: "Form 3 Blue", title: "A Doll's House", due: "01 Jun 2026", overdue: "10 days", status: "Sent (2)" },
              { borrower: "Mercy Kipkorir", class: "Form 1 East", title: "Certificate Agriculture Form 1", due: "05 Jun 2026", overdue: "6 days", status: "Pending" },
              { borrower: "Mr. Omondi", class: "Science Dept", title: "Advanced Chemistry", due: "20 May 2026", overdue: "22 days", status: "Escalated" },
            ].map((l, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3"><input type="checkbox" className="rounded" /></td>
                <td className="px-4 py-3 font-semibold text-[#071D49]">{l.borrower}</td>
                <td className="px-4 py-3 text-[#64748B]">{l.class}</td>
                <td className="px-4 py-3 text-[#071D49]">{l.title}</td>
                <td className="px-4 py-3 text-rose-600 font-medium">{l.due}</td>
                <td className="px-4 py-3 font-bold text-rose-600">{l.overdue}</td>
                <td className="px-4 py-3"><StatusChip label={l.status} tone={l.status === 'Pending' ? 'neutral' : l.status === 'Escalated' ? 'danger' : 'success'} /></td>
                <td className="px-4 py-3 text-right">
                  <button className="text-blue-600 hover:underline font-semibold mr-3">Remind</button>
                  <button className="p-1 text-[#64748B] hover:bg-[#D8E0EC] rounded"><MoreHorizontal className="w-4 h-4" /></button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function LostDamagedWorkspace() {
  return (
    <Panel title="Lost / Damaged Books" description="Record lost and damaged books, assign charges, and track replacement." icon={HeartCrack} actions={
      <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Record Lost Book</button>
    }>
      <div className="grid gap-4 md:grid-cols-4 mb-6">
        <div className="rounded-xl border border-rose-200 bg-rose-50 p-4">
          <div className="text-sm font-semibold text-rose-700">Lost This Term</div>
          <div className="mt-1 text-2xl font-black text-rose-700">16</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <div className="text-sm font-semibold text-[#64748B]">Damaged This Term</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">24</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <div className="text-sm font-semibold text-[#64748B]">Awaiting Replacement</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">10</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <div className="text-sm font-semibold text-[#64748B]">Written Off</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">5</div>
        </div>
      </div>
      
      <div className="flex gap-4 mb-4 border-b border-[#D8E0EC]">
        <button className="pb-2 text-sm font-black text-[#071D49] border-b-2 border-[#071D49]">Lost Books</button>
        <button className="pb-2 text-sm font-bold text-[#64748B]">Damaged Books</button>
        <button className="pb-2 text-sm font-bold text-[#64748B]">Repair Queue</button>
        <button className="pb-2 text-sm font-bold text-[#64748B]">Written Off</button>
      </div>

      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Book Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Borrower</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Date Reported</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Cost</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Fine Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { title: "Secondary Math Bk 2", borrower: "Kevin Ochieng (Form 2)", date: "09 Jun 2026", cost: "KES 850", status: "Sent to Accounts" },
              { title: "Blossoms of the Savannah", borrower: "Library Inventory", date: "02 Jun 2026", cost: "KES 600", status: "N/A" },
            ].map((b, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{b.title}</td>
                <td className="px-4 py-3 text-[#64748B]">{b.borrower}</td>
                <td className="px-4 py-3 text-[#64748B]">{b.date}</td>
                <td className="px-4 py-3 font-medium">{b.cost}</td>
                <td className="px-4 py-3"><StatusChip label={b.status} tone={b.status === 'N/A' ? 'neutral' : 'info'} /></td>
                <td className="px-4 py-3 text-right">
                  <button className="text-blue-600 hover:underline font-semibold">View</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function FinesPaymentsWorkspace() {
  return (
    <Panel title="Fines & Payments" description="Track library fines, replacement charges, waivers, and payment status." icon={Banknote} actions={
      <div className="flex gap-2">
        <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Create Fine</button>
      </div>
    }>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Student/Staff</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Class/Dept</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Fine Type</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Amount</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { borrower: "Brian Otieno", class: "Form 3 Blue", type: "Overdue", amount: "KES 200", status: "Pending" },
              { borrower: "Kevin Ochieng", class: "Form 2 East", type: "Lost Book", amount: "KES 850", status: "Sent to Accounts" },
              { borrower: "Joy Kendi", class: "Form 1 West", type: "Damage Repair", amount: "KES 300", status: "Paid" },
            ].map((f, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{f.borrower}</td>
                <td className="px-4 py-3 text-[#64748B]">{f.class}</td>
                <td className="px-4 py-3 text-[#64748B]">{f.type}</td>
                <td className="px-4 py-3 font-medium text-rose-600">{f.amount}</td>
                <td className="px-4 py-3"><StatusChip label={f.status} tone={f.status === 'Pending' ? 'warning' : f.status === 'Paid' ? 'success' : 'info'} /></td>
                <td className="px-4 py-3 text-right">
                  <button className="text-blue-600 hover:underline font-semibold mr-3">View</button>
                  {f.status === "Pending" && <button className="text-[#071D49] hover:underline font-semibold">Send to Accounts</button>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function StudentsBorrowersWorkspace() {
  return (
    <Panel title="Students & Borrowers" description="View borrower profiles, active loans, and restrictions." icon={Users}>
      <div className="flex flex-col sm:flex-row gap-3 mb-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" />
          <input type="text" placeholder="Search student by name, admission no, class..." className="w-full rounded-xl border border-[#D8E0EC] py-2 pl-9 pr-3 text-sm focus:border-[#071D49] focus:outline-none" />
        </div>
        <select className="rounded-xl border border-[#D8E0EC] bg-white px-4 py-2 text-sm font-bold text-[#071D49]">
          <option>All Borrowers</option>
          <option>Students</option>
          <option>Staff</option>
          <option>Has Overdue</option>
          <option>Restricted</option>
        </select>
      </div>
      
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Borrower</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Adm/Staff No.</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Class/Dept</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Active Loans</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { name: "Amina Wanjiku", adm: "ADM-2104", class: "Form 2 East", loans: 2, status: "Active" },
              { name: "Brian Otieno", adm: "ADM-2041", class: "Form 3 Blue", loans: 3, status: "Has Overdue" },
              { name: "Kevin Ochieng", adm: "ADM-2210", class: "Form 2 East", loans: 0, status: "Restricted" },
            ].map((s, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{s.name}</td>
                <td className="px-4 py-3 text-[#64748B]">{s.adm}</td>
                <td className="px-4 py-3 text-[#64748B]">{s.class}</td>
                <td className="px-4 py-3 font-medium">{s.loans}</td>
                <td className="px-4 py-3"><StatusChip label={s.status} tone={s.status === 'Active' ? 'success' : s.status === 'Restricted' ? 'danger' : 'warning'} /></td>
                <td className="px-4 py-3 text-right">
                  <button className="text-blue-600 hover:underline font-semibold">View Profile</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function ClassTextbookWorkspace() {
  return (
    <Panel title="Class Textbook Distribution" description="Distribute textbooks, readers, and subject resources to classes and teachers." icon={Layers} actions={
      <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Issue to Class</button>
    }>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Class/Stream</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Subject</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Book Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Issued</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Teacher Responsible</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {[
              { class: "Form 1 East", subject: "English", title: "Memories We Lost", issued: 45, teacher: "Mr. Kamau", status: "Issued" },
              { class: "Form 2 Blue", subject: "Math", title: "Secondary Math Bk 2", issued: 50, teacher: "Ms. Omondi", status: "Return Pending" },
            ].map((c, i) => (
              <tr key={i} className="hover:bg-[#F8FAFC]">
                <td className="px-4 py-3 font-semibold text-[#071D49]">{c.class}</td>
                <td className="px-4 py-3 text-[#64748B]">{c.subject}</td>
                <td className="px-4 py-3 text-[#071D49]">{c.title}</td>
                <td className="px-4 py-3 font-medium">{c.issued}</td>
                <td className="px-4 py-3 text-[#64748B]">{c.teacher}</td>
                <td className="px-4 py-3"><StatusChip label={c.status} tone={c.status === 'Issued' ? 'success' : 'warning'} /></td>
                <td className="px-4 py-3 text-right">
                  <button className="text-blue-600 hover:underline font-semibold mr-3">Receive</button>
                  <button className="text-blue-600 hover:underline font-semibold">View</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function LibraryStocktakeWorkspace() {
  return (
    <Panel title="Library Stocktake" description="Scan, count, reconcile, and report library stock by shelf, category, or whole library." icon={ScanBarcode} actions={
      <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Start Stocktake</button>
    }>
      <div className="flex flex-col items-center justify-center py-16 text-center bg-[#F8FAFC] rounded-xl border border-dashed border-[#D8E0EC]">
        <ScanBarcode className="h-12 w-12 text-[#64748B]/30 mb-4" />
        <p className="text-lg font-bold text-[#071D49]">No Active Stocktake</p>
        <p className="mt-2 text-sm text-[#64748B] max-w-md">Start a new stocktake to audit books on shelves, record missing items, and generate a reconciliation report.</p>
        <div className="mt-6 flex gap-3">
          <button className="rounded-lg border border-[#D8E0EC] bg-white px-4 py-2 text-sm font-bold text-[#071D49]">View Previous Stocktakes</button>
        </div>
      </div>
    </Panel>
  );
}

function SettingsWorkspace() {
  return (
    <Panel title="Library Settings" description="Configure library rules, borrowing limits, due dates, fines, and notification templates." icon={Settings}>
      <div className="grid lg:grid-cols-2 gap-6">
        <div className="space-y-6">
          <div className="rounded-xl border border-[#D8E0EC] p-5 bg-white">
            <h3 className="font-bold text-[#071D49] mb-4">Borrowing Rules</h3>
            <div className="space-y-4">
              <div className="flex justify-between items-center border-b border-[#D8E0EC] pb-3">
                <span className="text-sm font-semibold text-[#071D49]">Max books per student</span>
                <input type="number" defaultValue="3" className="w-20 rounded-lg border border-[#D8E0EC] py-1 px-2 text-center text-sm" />
              </div>
              <div className="flex justify-between items-center border-b border-[#D8E0EC] pb-3">
                <span className="text-sm font-semibold text-[#071D49]">Max books per staff</span>
                <input type="number" defaultValue="10" className="w-20 rounded-lg border border-[#D8E0EC] py-1 px-2 text-center text-sm" />
              </div>
              <div className="flex justify-between items-center border-b border-[#D8E0EC] pb-3">
                <span className="text-sm font-semibold text-[#071D49]">Default loan duration (days)</span>
                <input type="number" defaultValue="14" className="w-20 rounded-lg border border-[#D8E0EC] py-1 px-2 text-center text-sm" />
              </div>
            </div>
            <button className="mt-4 rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white w-full">Save Rules</button>
          </div>
        </div>
        
        <div className="space-y-6">
          <div className="rounded-xl border border-[#D8E0EC] p-5 bg-white">
            <h3 className="font-bold text-[#071D49] mb-4">Fine Rules</h3>
            <div className="space-y-4">
              <div className="flex justify-between items-center border-b border-[#D8E0EC] pb-3">
                <span className="text-sm font-semibold text-[#071D49]">Enable overdue fines</span>
                <input type="checkbox" defaultChecked className="rounded" />
              </div>
              <div className="flex justify-between items-center border-b border-[#D8E0EC] pb-3">
                <span className="text-sm font-semibold text-[#071D49]">Fine per day (KES)</span>
                <input type="number" defaultValue="20" className="w-20 rounded-lg border border-[#D8E0EC] py-1 px-2 text-center text-sm" />
              </div>
            </div>
            <button className="mt-4 rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white w-full">Save Fine Settings</button>
          </div>
        </div>
      </div>
    </Panel>
  );
}

// Minimal placeholder for the remaining 14 workspaces to maintain the structure
function SimpleWorkspace({ title, description, icon: Icon }: { title: string; description: string; icon: LucideIcon }) {
  return (
    <Panel title={title} description={description} icon={Icon}>
      <div className="flex flex-col items-center justify-center py-16 text-center bg-[#F8FAFC] rounded-xl border border-dashed border-[#D8E0EC]">
        <Icon className="h-12 w-12 text-[#64748B]/30 mb-4" />
        <p className="text-lg font-bold text-[#071D49]">{title} Workspace</p>
        <p className="mt-2 text-sm text-[#64748B] max-w-sm">{description}</p>
        <div className="mt-6 flex gap-3">
          <button className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white">Main Action</button>
          <button className="rounded-lg border border-[#D8E0EC] bg-white px-4 py-2 text-sm font-bold text-[#071D49]">Export</button>
        </div>
      </div>
    </Panel>
  );
}

export default function LibrarianCommandCenter() {
  const [activeView, setActiveView] = useState<LibrarianView>("overview");

  return (
    <div className="flex min-h-screen bg-[#F3F6FA] font-sans">
      <Sidebar activeView={activeView} onViewChange={setActiveView} />
      <main className="flex-1 min-w-0 flex flex-col h-screen">
        <Topbar activeView={activeView} />
        <div className="flex-1 overflow-y-auto p-4 lg:p-6 space-y-6">
          
          {activeView === "overview" && <OverviewWorkspace onNavigate={setActiveView} />}
          {activeView === "issue" && <IssueBooksWorkspace />}
          {activeView === "return" && <ReturnBooksWorkspace />}
          {activeView === "catalogue" && <BookCatalogueWorkspace />}
          {activeView === "add_books" && <AddBooksWorkspace />}
          {activeView === "loans" && <LoansOverduesWorkspace />}
          {activeView === "lost_damaged" && <LostDamagedWorkspace />}
          {activeView === "fines" && <FinesPaymentsWorkspace />}
          {activeView === "borrowers" && <StudentsBorrowersWorkspace />}
          {activeView === "class_textbooks" && <ClassTextbookWorkspace />}
          {activeView === "stocktake" && <LibraryStocktakeWorkspace />}
          {activeView === "settings" && <SettingsWorkspace />}
          {/* Dynamically render the rest with SimpleWorkspace */}
          {!["overview", "issue", "return", "catalogue", "add_books", "loans", "lost_damaged", "fines", "borrowers", "class_textbooks", "stocktake", "settings"].includes(activeView) && (

            <SimpleWorkspace 
              title={navItems.find(i => i.id === activeView)?.label || ""} 
              description={navItems.find(i => i.id === activeView)?.desc || ""} 
              icon={navItems.find(i => i.id === activeView)?.icon || AlertTriangle} 
            />
          )}
        </div>
      </main>
    </div>
  );
}

function Sidebar({ activeView, onViewChange }: { activeView: LibrarianView; onViewChange: (view: LibrarianView) => void }) {
  return (
    <aside className="hidden h-screen w-[260px] overflow-y-auto bg-[#071D49] p-4 text-white shadow-[0_24px_70px_rgba(7,29,73,0.28)] lg:block shrink-0">
      <div className="rounded-2xl border border-white/10 bg-white/5 p-4 mb-6">
        <p className="text-xs font-black uppercase tracking-[0.22em] text-cyan-100/70">MyShule</p>
        <h2 className="mt-2 text-xl font-black">Librarian</h2>
        <p className="mt-2 text-sm leading-6 text-white/65">Main Library Operations</p>
      </div>
      <nav className="space-y-1" aria-label="Librarian navigation">
        {navItems.map((item, index) => {
          const showGroup = item.group !== navItems[index - 1]?.group;
          const Icon = item.icon;
          return (
            <div key={\\`\\${item.group}-\\${item.label}\\`}>
              {showGroup ? <p className="px-3 pb-2 pt-4 text-[10px] font-black uppercase tracking-[0.2em] text-white/40">{item.group}</p> : null}
              <button
                type="button"
                onClick={() => onViewChange(item.id)}
                className={cn(
                  "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-white/70 transition hover:bg-white/10 hover:text-white",
                  activeView === item.id && "bg-white/15 text-white shadow-[inset_4px_0_0_#38BDF8]"
                )}
              >
                <Icon className="h-4 w-4 shrink-0" aria-hidden="true" />
                <span className="truncate">{item.label}</span>
              </button>
            </div>
          );
        })}
      </nav>
    </aside>
  );
}

function Topbar({ activeView }: { activeView: LibrarianView }) {
  const label = navItems.find(i => i.id === activeView)?.label || "Dashboard";
  return (
    <header className="sticky top-0 z-20 border-b border-[#D8E0EC] bg-white/90 px-4 py-3 backdrop-blur shrink-0">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-3">
          <div className="grid h-10 w-10 place-items-center rounded-xl bg-[#071D49] text-xs font-black text-white shrink-0">LB</div>
          <h1 className="text-lg font-black text-[#071D49] truncate">{label}</h1>
        </div>
        <div className="flex items-center gap-3 shrink-0">
          <StatusChip label="Term 2 (2026)" tone="info" />
          <button className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#D8E0EC] hover:bg-[#F8FAFC] transition text-[#071D49]">
            <Search className="h-4 w-4" />
          </button>
          <button className="flex h-10 w-10 items-center justify-center rounded-xl border border-[#D8E0EC] hover:bg-[#F8FAFC] transition text-[#071D49] relative">
            <Bell className="h-4 w-4" />
            <span className="absolute top-2 right-2 h-2 w-2 rounded-full bg-rose-500"></span>
          </button>
          <div className="relative group">
            <button className="flex h-10 items-center justify-center rounded-xl bg-[#071D49] px-4 text-sm font-black text-white gap-2">
              Quick Action <ChevronDown className="h-4 w-4" />
            </button>
            <div className="absolute right-0 mt-2 w-48 rounded-xl border border-[#D8E0EC] bg-white p-2 shadow-xl opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all">
              <button className="w-full text-left px-3 py-2 text-sm font-semibold text-[#071D49] hover:bg-[#F8FAFC] rounded-lg">Scan Book</button>
              <button className="w-full text-left px-3 py-2 text-sm font-semibold text-[#071D49] hover:bg-[#F8FAFC] rounded-lg">Issue Book</button>
              <button className="w-full text-left px-3 py-2 text-sm font-semibold text-[#071D49] hover:bg-[#F8FAFC] rounded-lg">Return Book</button>
              <div className="h-px bg-[#D8E0EC] my-1"></div>
              <button className="w-full text-left px-3 py-2 text-sm font-semibold text-rose-600 hover:bg-rose-50 rounded-lg">Record Lost Book</button>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
}
\`;

const dir = 'apps/web/src/components/school';
if (!fs.existsSync(dir)){
    fs.mkdirSync(dir, { recursive: true });
}

fs.writeFileSync('apps/web/src/components/school/librarian-command-center.tsx', tsx);
console.log('Successfully generated librarian-command-center.tsx');
`);
