// GENERATED BY scaffold_system_monitor.js
"use client";

import { useState, type ReactNode } from "react";
import {
  Activity,
  AlertTriangle,
  Building2,
  Database,
  FileText,
  FileWarning,
  Gauge,
  GitMerge,
  HardDrive,
  LayoutDashboard,
  MoreHorizontal,
  Network,
  RefreshCwOff,
  Search,
  Send,
  ServerCog,
  Settings,
  ShieldAlert,
  Siren,
  Wrench,
  Search as ListMagnifyingGlass,
  type LucideIcon,
} from "lucide-react";

import { MyShuleBrand, MyShuleMark } from "@/components/brand/myshule-brand";
import { ApprovalInbox } from "@/components/shared/approval-inbox";
import { MobileWorkspaceNavigation } from "@/components/shared/mobile-workspace-navigation";
import { NotificationBell } from "@/components/shared/notification-bell";
import { TaskQueue } from "@/components/shared/task-queue";
import { WorkflowToast } from "@/components/shared/workflow-toast";
import { requestDashboardApi } from "@/lib/dashboard/api-client";
import { downloadCsvFile, downloadTextFile, openPrintDocument } from "@/lib/dashboard/export";
import {
  getCurrentSchoolId,
  publishSchoolOperationalEvent,
} from "@/lib/school/school-operational-store";

type RouteMode = "hosted" | "public";
type Tone = "success" | "info" | "warning" | "danger" | "neutral";
type ViewId = "overview" | "tenant-health" | "uptime-services" | "error-logs" | "background-jobs" | "offline-sync" | "performance-analytics" | "support-diagnostics" | "integrations" | "notifications" | "database-backups" | "storage-files" | "security-events" | "audit-explorer" | "release-monitor" | "incident-center" | "reports" | "settings";
type MonitorToastType = "success" | "error" | "info";
type MonitorAction = (payload: { title: string; message?: string; type?: MonitorToastType }) => void;

type NavItem = {
  id: ViewId;
  label: string;
  icon: LucideIcon;
  group: string;
  desc: string;
};

const navItems: NavItem[] = [
  { id: "overview", label: "Overview", icon: LayoutDashboard, group: "Platform Health", desc: "System Health Overview" },
  { id: "tenant-health", label: "Tenant Health", icon: Building2, group: "Platform Health", desc: "Track technical health for each school" },
  { id: "uptime-services", label: "Uptime & Services", icon: Activity, group: "Platform Health", desc: "Track whether MyShule services are alive" },
  { id: "error-logs", label: "Error Logs", icon: FileWarning, group: "Diagnostics", desc: "Search and diagnose platform errors" },
  { id: "background-jobs", label: "Background Jobs", icon: ServerCog, group: "Diagnostics", desc: "Monitor and control asynchronous work" },
  { id: "offline-sync", label: "Offline Sync", icon: RefreshCwOff, group: "Diagnostics", desc: "Track actions saved on devices" },
  { id: "performance-analytics", label: "Performance Analytics", icon: Gauge, group: "Diagnostics", desc: "Monitor speed and usage quality" },
  { id: "support-diagnostics", label: "Support Diagnostics", icon: Wrench, group: "Diagnostics", desc: "Troubleshoot school issues safely" },
  { id: "integrations", label: "Integrations Health", icon: Network, group: "Infrastructure", desc: "Monitor third-party services" },
  { id: "notifications", label: "Notifications Delivery", icon: Send, group: "Infrastructure", desc: "Monitor SMS, email, and in-app notifications" },
  { id: "database-backups", label: "Database & Backups", icon: Database, group: "Infrastructure", desc: "Monitor database health and backups" },
  { id: "storage-files", label: "Storage & Files", icon: HardDrive, group: "Infrastructure", desc: "Monitor file uploads and generated PDFs" },
  { id: "security-events", label: "Security Events", icon: ShieldAlert, group: "Security & Ops", desc: "Monitor suspicious platform activity" },
  { id: "audit-explorer", label: "Audit Explorer", icon: ListMagnifyingGlass, group: "Security & Ops", desc: "Search audit logs for sensitive actions" },
  { id: "release-monitor", label: "Release & Version", icon: GitMerge, group: "Security & Ops", desc: "Track deployed versions and user clients" },
  { id: "incident-center", label: "Incident Center", icon: Siren, group: "Security & Ops", desc: "Create and resolve technical incidents" },
  { id: "reports", label: "Reports", icon: FileText, group: "Management", desc: "Generate platform health reports" },
  { id: "settings", label: "Monitor Settings", icon: Settings, group: "Management", desc: "Manage preferences and alert thresholds" },
];

const toneClasses: Record<Tone, { card: string; chip: string; dot: string; text: string }> = {
  success: {
    card: "border-emerald-200 bg-emerald-50 text-emerald-900",
    chip: "border-emerald-200 bg-emerald-50 text-emerald-700",
    dot: "bg-emerald-500",
    text: "text-emerald-700",
  },
  info: {
    card: "border-blue-200 bg-blue-50 text-blue-950",
    chip: "border-blue-200 bg-blue-50 text-blue-700",
    dot: "bg-blue-500",
    text: "text-blue-700",
  },
  warning: {
    card: "border-amber-200 bg-amber-50 text-amber-950",
    chip: "border-amber-200 bg-amber-50 text-amber-700",
    dot: "bg-amber-500",
    text: "text-amber-700",
  },
  danger: {
    card: "border-rose-200 bg-rose-50 text-rose-950",
    chip: "border-rose-200 bg-rose-50 text-rose-700",
    dot: "bg-rose-500",
    text: "text-rose-700",
  },
  neutral: {
    card: "border-slate-200 bg-white text-[#071D49]",
    chip: "border-slate-200 bg-slate-50 text-slate-700",
    dot: "bg-slate-400",
    text: "text-slate-600",
  },
};

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function StatusChip({ label, tone = "neutral" }: { label: string; tone?: Tone }) {
  return (
    <span className={cn("inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs font-bold whitespace-nowrap", toneClasses[tone].chip)}>
      <span className={cn("h-2 w-2 rounded-full shrink-0", toneClasses[tone].dot)} />
      {label}
    </span>
  );
}

const tenantHealthRows = [
  ["Mangu High", "8 Active", "Healthy", "Healthy", "Normal"],
  ["Kisumu Boys", "12 Active", "Degraded", "Failing", "High"],
];

const serviceRows = [
  ["Frontend Web App", "Operational", "1 min ago", "45ms", "99.99%"],
  ["Backend API", "Operational", "1 min ago", "120ms", "99.95%"],
  ["SMS Service", "Degraded", "2 mins ago", "850ms", "98.50%"],
];

function exportPlatformHealthSnapshot(onAction: MonitorAction) {
  downloadCsvFile({
    filename: "myshule-platform-health-snapshot.csv",
    headers: ["Metric", "Value", "Status"],
    rows: [
      ["Platform Status", "Healthy", "Operational"],
      ["Active Schools", "42", "Tracked"],
      ["Schools With Issues", "2", "Needs attention"],
      ["Failed Jobs", "14", "Retry queue open"],
    ],
  });
  onAction({ title: "Health snapshot exported", message: "Downloaded a CSV snapshot of the current System Monitor health cards.", type: "success" });
}

function exportTenantHealthSnapshot(onAction: MonitorAction) {
  downloadCsvFile({
    filename: "myshule-tenant-health-snapshot.csv",
    headers: ["School", "Modules", "Queue Status", "Sync Status", "Severity"],
    rows: tenantHealthRows,
  });
  onAction({ title: "Tenant snapshot exported", message: "Downloaded tenant-scoped health rows from the visible monitor table.", type: "success" });
}

function downloadOperationalLog(title: string, lines: string[], onAction: MonitorAction) {
  downloadTextFile({
    filename: `${title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "system-monitor"}-log.txt`,
    content: [`MyShule System Monitor`, title, `Generated: ${new Date().toISOString()}`, "", ...lines].join("\n"),
  });
  onAction({ title, message: "Downloaded the visible diagnostic details for operator review.", type: "success" });
}

function openOperationalReport(reportTitle: string, rows: Array<[string, string]>, onAction: MonitorAction) {
  openPrintDocument({
    eyebrow: "MyShule System Monitor",
    title: reportTitle,
    subtitle: `Generated from visible monitor state on ${new Date().toLocaleString()}`,
    rows: rows.map(([label, value]) => ({ label, value })),
    footer: "This report contains operational metadata only and must not include private tenant records.",
  });
  onAction({ title: "Report preview opened", message: `${reportTitle} is open for print or PDF download.`, type: "success" });
}

function recordMonitorAction(
  action: string,
  detail: {
    module: string;
    entityId?: string;
    body: string;
    severity?: "info" | "warning" | "critical" | "success";
    payload?: Record<string, unknown>;
    notify?: boolean;
  },
) {
  publishSchoolOperationalEvent({
    schoolId: getCurrentSchoolId(),
    type: `system_monitor.${action.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "") || "action"}`,
    module: detail.module,
    actorRole: "system-monitor",
    entityId: detail.entityId ?? action,
    title: action,
    body: detail.body,
    severity: detail.severity ?? "info",
    payload: detail.payload,
    notifications: detail.notify
      ? [
          {
            audienceRoles: ["Super Admin", "System Monitor"],
            title: action,
            body: detail.body,
            severity: detail.severity ?? "info",
            relatedModule: detail.module,
            relatedRecordId: detail.entityId,
            requiresAction: detail.severity === "critical" || detail.severity === "warning",
          },
        ]
      : undefined,
  });
}

async function runMonitorEndpointCheck(
  label: string,
  endpoint: string,
  onAction: MonitorAction,
  options?: { module?: string; entityId?: string },
) {
  const startedAt = performance.now();

  try {
    await requestDashboardApi(endpoint, { method: "GET" });
    const durationMs = Math.round(performance.now() - startedAt);
    recordMonitorAction(`${label} health check`, {
      module: options?.module ?? "system-monitor",
      entityId: options?.entityId ?? endpoint,
      body: `${label} responded from ${endpoint} in ${durationMs}ms.`,
      severity: "success",
      payload: { endpoint, durationMs, checkedAt: new Date().toISOString() },
    });
    onAction({ title: `${label} check passed`, message: `${endpoint} responded in ${durationMs}ms.`, type: "success" });
  } catch (error) {
    const message = error instanceof Error ? error.message : `${label} check failed.`;
    recordMonitorAction(`${label} health check failed`, {
      module: options?.module ?? "system-monitor",
      entityId: options?.entityId ?? endpoint,
      body: message,
      severity: "critical",
      payload: { endpoint, checkedAt: new Date().toISOString(), error: message },
      notify: true,
    });
    onAction({ title: `${label} check failed`, message, type: "error" });
  }
}

function Panel({
  title,
  description,
  icon: Icon,
  children,
  actions,
}: {
  title: string;
  description?: string;
  icon?: LucideIcon;
  children: ReactNode;
  actions?: ReactNode;
}) {
  return (
    <section className="rounded-2xl border border-[#D8E0EC] bg-white p-5 shadow-[0_18px_50px_rgba(7,29,73,0.08)]">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-3">
          {Icon ? (
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#EEF5FF] text-[#1D4ED8]">
              <Icon className="h-5 w-5" aria-hidden="true" />
            </span>
          ) : null}
          <div>
            <h2 className="text-xl font-black tracking-[-0.01em] text-[#071D49]">{title}</h2>
            {description ? <p className="mt-1 text-sm leading-6 text-[#64748B]">{description}</p> : null}
          </div>
        </div>
        {actions && <div className="shrink-0">{actions}</div>}
      </div>
      {children}
    </section>
  );
}

// ----------------------------------------------------------------------
// WORKSPACE COMPONENTS
// ----------------------------------------------------------------------

function OverviewWorkspace({ onNavigate, onAction }: { onNavigate: (v: ViewId) => void; onAction: MonitorAction }) {
  return (
    <Panel title="System Health Overview" description="Monitor uptime, tenant status, queues, sync, integrations, and incidents across MyShule." icon={LayoutDashboard} actions={
      <div className="flex gap-2">
        <button type="button" className="rounded-lg border border-[#D8E0EC] px-4 py-2 text-sm font-bold text-[#071D49]" onClick={() => exportPlatformHealthSnapshot(onAction)}>Export Health Snapshot</button>
        <button type="button" className="flex items-center gap-2 rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white" onClick={() => onNavigate("incident-center")}>
          Open Incident Center
        </button>
      </div>
    }>
      <div className="grid gap-4 md:grid-cols-4 lg:grid-cols-4 mb-6">
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 cursor-pointer hover:border-emerald-300 transition">
          <div className="text-sm font-semibold text-emerald-700">Platform Status</div>
          <div className="mt-1 text-2xl font-black text-emerald-700">Healthy</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 cursor-pointer hover:border-blue-300 transition">
          <div className="text-sm font-semibold text-[#64748B]">Active Schools</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">42</div>
        </div>
        <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 cursor-pointer hover:border-rose-300 transition" onClick={() => onNavigate("tenant-health")}>
          <div className="text-sm font-semibold text-rose-700">Schools With Issues</div>
          <div className="mt-1 text-2xl font-black text-rose-700">2</div>
        </div>
        <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 cursor-pointer hover:border-amber-300 transition" onClick={() => onNavigate("background-jobs")}>
          <div className="text-sm font-semibold text-amber-700">Failed Jobs</div>
          <div className="mt-1 text-2xl font-black text-amber-700">14</div>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
          <div className="rounded-xl border border-[#D8E0EC] overflow-hidden">
            <div className="bg-[#F8FAFC] px-4 py-3 border-b border-[#D8E0EC] flex justify-between items-center">
              <h3 className="font-bold text-[#071D49]">Schools Requiring Attention</h3>
              <button type="button" className="text-xs font-bold text-blue-600 hover:underline" onClick={() => onNavigate("tenant-health")}>View All</button>
            </div>
            <div className="p-4 overflow-x-auto">
              <table className="w-full text-sm text-left whitespace-nowrap">
                <thead>
                  <tr className="text-[#64748B] border-b border-[#D8E0EC]">
                    <th className="pb-2 font-semibold">School</th>
                    <th className="pb-2 font-semibold">Status</th>
                    <th className="pb-2 font-semibold">Issue Type</th>
                    <th className="pb-2 font-semibold">Severity</th>
                    <th className="pb-2 font-semibold text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-[#D8E0EC]">
                  <tr>
                    <td className="py-3 font-medium text-[#071D49]">Kisumu Boys</td>
                    <td className="py-3"><StatusChip label="Degraded" tone="warning" /></td>
                    <td className="py-3 text-[#64748B]">Sync Failures</td>
                    <td className="py-3"><StatusChip label="High" tone="danger" /></td>
                    <td className="py-3 text-right">
                      <button type="button" className="text-blue-600 hover:underline font-semibold text-xs" onClick={() => onNavigate("tenant-health")}>View Health</button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div className="space-y-6">
          <div className="rounded-xl border border-[#D8E0EC] overflow-hidden">
            <div className="px-4 py-3 border-b border-[#D8E0EC] flex items-center gap-2 bg-[#F8FAFC]">
              <AlertTriangle className="h-5 w-5 text-amber-500" />
              <h3 className="font-bold text-[#071D49]">Active Incidents</h3>
            </div>
            <div className="p-4 space-y-3 text-sm">
              <div className="flex justify-between items-start">
                <span className="text-[#071D49]"><strong>M-Pesa Callbacks Delayed</strong></span>
                <button type="button" className="text-blue-600 underline font-semibold text-xs" onClick={() => onNavigate("incident-center")}>Review</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Panel>
  );
}

function TenantHealthWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Tenant Health" description="Track technical health for each school while preserving tenant isolation." icon={Building2} actions={
      <div className="flex gap-2">
        <button type="button" className="rounded-lg border border-[#D8E0EC] px-4 py-2 text-sm font-bold text-[#071D49]" onClick={() => exportTenantHealthSnapshot(onAction)}>Export Tenant Snapshot</button>
      </div>
    }>
      <div className="flex flex-col sm:flex-row gap-3 mb-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" />
          <input type="text" placeholder="Search School Name..." className="w-full rounded-xl border border-[#D8E0EC] py-2 pl-9 pr-3 text-sm focus:border-[#071D49] focus:outline-none focus:ring-1 focus:ring-[#071D49]" />
        </div>
        <select className="rounded-xl border border-[#D8E0EC] px-3 py-2 text-sm text-[#071D49] outline-none">
          <option>All Statuses</option>
          <option>Healthy</option>
          <option>Warning</option>
          <option>Critical</option>
        </select>
      </div>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">School</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Modules</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Queue Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Sync Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Severity</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 font-semibold text-[#071D49]">Mangu High</td>
              <td className="px-4 py-3 text-[#64748B]">8 Active</td>
              <td className="px-4 py-3"><StatusChip label="Healthy" tone="success" /></td>
              <td className="px-4 py-3"><StatusChip label="Healthy" tone="success" /></td>
              <td className="px-4 py-3"><StatusChip label="Normal" tone="neutral" /></td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => openOperationalReport("Mangu High tenant health", [["School", "Mangu High"], ["Modules", "8 Active"], ["Queue Status", "Healthy"], ["Sync Status", "Healthy"], ["Severity", "Normal"]], onAction)}>View Details</button>
                <button type="button" aria-label="Download Mangu High health details" className="p-1 text-[#64748B] hover:bg-[#D8E0EC] rounded" onClick={() => downloadOperationalLog("Mangu High tenant health", ["School: Mangu High", "Modules: 8 Active", "Queue: Healthy", "Sync: Healthy", "Severity: Normal"], onAction)}><MoreHorizontal className="w-4 h-4" /></button>
              </td>
            </tr>
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 font-semibold text-[#071D49]">Kisumu Boys</td>
              <td className="px-4 py-3 text-[#64748B]">12 Active</td>
              <td className="px-4 py-3"><StatusChip label="Degraded" tone="warning" /></td>
              <td className="px-4 py-3"><StatusChip label="Failing" tone="danger" /></td>
              <td className="px-4 py-3"><StatusChip label="High" tone="danger" /></td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => openOperationalReport("Kisumu Boys tenant health", [["School", "Kisumu Boys"], ["Modules", "12 Active"], ["Queue Status", "Degraded"], ["Sync Status", "Failing"], ["Severity", "High"]], onAction)}>View Details</button>
                <button type="button" aria-label="Download Kisumu Boys health details" className="p-1 text-[#64748B] hover:bg-[#D8E0EC] rounded" onClick={() => downloadOperationalLog("Kisumu Boys tenant health", ["School: Kisumu Boys", "Modules: 12 Active", "Queue: Degraded", "Sync: Failing", "Severity: High"], onAction)}><MoreHorizontal className="w-4 h-4" /></button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function UptimeServicesWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Uptime & Services" description="Track whether MyShule services are alive." icon={Activity} actions={
      <div className="flex gap-2">
        <button type="button" className="rounded-lg border border-[#D8E0EC] px-4 py-2 text-sm font-bold text-[#071D49]" onClick={() => {
          downloadCsvFile({ filename: "myshule-service-health-check.csv", headers: ["Service", "Status", "Last Check", "Response Time", "Uptime 7d"], rows: serviceRows });
          onAction({ title: "Health check snapshot created", message: "Downloaded current service status for the operator health-check run.", type: "success" });
        }}>Run Health Check</button>
      </div>
    }>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Service</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Last Check</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Response Time</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Uptime 7d</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 font-semibold text-[#071D49]">Frontend Web App</td>
              <td className="px-4 py-3"><StatusChip label="Operational" tone="success" /></td>
              <td className="px-4 py-3 text-[#64748B]">1 min ago</td>
              <td className="px-4 py-3 text-[#64748B]">45ms</td>
              <td className="px-4 py-3 text-[#64748B]">99.99%</td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => void runMonitorEndpointCheck("Frontend Web App", "/health/ready", onAction, { module: "frontend" })}>Ping Now</button>
              </td>
            </tr>
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 font-semibold text-[#071D49]">Backend API</td>
              <td className="px-4 py-3"><StatusChip label="Operational" tone="success" /></td>
              <td className="px-4 py-3 text-[#64748B]">1 min ago</td>
              <td className="px-4 py-3 text-[#64748B]">120ms</td>
              <td className="px-4 py-3 text-[#64748B]">99.95%</td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => void runMonitorEndpointCheck("Backend API", "/observability/health", onAction, { module: "backend-api" })}>Ping Now</button>
              </td>
            </tr>
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 font-semibold text-[#071D49]">SMS Service</td>
              <td className="px-4 py-3"><StatusChip label="Degraded" tone="warning" /></td>
              <td className="px-4 py-3 text-[#64748B]">2 mins ago</td>
              <td className="px-4 py-3 text-[#64748B]">850ms</td>
              <td className="px-4 py-3 text-[#64748B]">98.50%</td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => downloadOperationalLog("SMS Service degraded sample", ["Service: SMS Service", "Status: Degraded", "Last check: 2 mins ago", "Response time: 850ms", "Uptime 7d: 98.50%"], onAction)}>View Logs</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function ErrorLogsWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Error Logs" description="Search and diagnose platform errors across tenants, modules, users, and services." icon={FileWarning}>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Time</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Severity</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">School</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Module</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Error Message</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 text-[#64748B]">10:45 AM</td>
              <td className="px-4 py-3"><StatusChip label="Error" tone="danger" /></td>
              <td className="px-4 py-3 font-semibold text-[#071D49]">Kisumu Boys</td>
              <td className="px-4 py-3 text-[#64748B]">Attendance</td>
              <td className="px-4 py-3 text-[#071D49] truncate max-w-[200px]">Failed to sync offline record...</td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => downloadOperationalLog("Attendance sync stack trace", ["Time: 10:45 AM", "School: Kisumu Boys", "Module: Attendance", "Error: Failed to sync offline record", "Trace ID: sync-attendance-1045"], onAction)}>View Stack Trace</button>
                <button type="button" className="text-emerald-600 hover:underline font-semibold text-xs" onClick={() => {
                  recordMonitorAction("Attendance sync incident resolution review", {
                    module: "offline-sync",
                    entityId: "sync-attendance-1045",
                    body: "Attendance sync incident marked for operator resolution review before closure.",
                    severity: "warning",
                    notify: true,
                  });
                  onAction({ title: "Resolution review recorded", message: "The attendance sync incident now has an audit record and remains visible until operator closure.", type: "info" });
                }}>Mark Resolved</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function BackgroundJobsWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Background Jobs" description="Monitor and control asynchronous work." icon={ServerCog} actions={
      <div className="flex gap-2">
        <button type="button" className="rounded-lg border border-[#D8E0EC] px-4 py-2 text-sm font-bold text-[#071D49]" onClick={() => {
          recordMonitorAction("Retry failed background jobs", {
            module: "background-jobs",
            entityId: "failed-jobs-batch",
            body: "Failed background jobs were queued for retry with tenant context preserved.",
            severity: "warning",
            notify: true,
            payload: { queue: "all-failed", requestedAt: new Date().toISOString() },
          });
          onAction({ title: "Retry batch recorded", message: "Failed jobs were recorded for retry and tenant-safe follow-up.", type: "info" });
        }}>Retry Failed</button>
      </div>
    }>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Job ID</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Queue</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">School</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Attempts</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 text-[#64748B]">#98214</td>
              <td className="px-4 py-3 font-semibold text-[#071D49]">PDF Generation</td>
              <td className="px-4 py-3 text-[#071D49]">Alliance High</td>
              <td className="px-4 py-3"><StatusChip label="Failed" tone="danger" /></td>
              <td className="px-4 py-3 text-[#64748B]">3</td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => {
                  recordMonitorAction("Retry background job", {
                    module: "background-jobs",
                    entityId: "98214",
                    body: "Job #98214 was recorded for PDF generation retry for Alliance High.",
                    severity: "warning",
                    notify: true,
                    payload: { jobId: "98214", queue: "PDF Generation", school: "Alliance High" },
                  });
                  onAction({ title: "Job retry recorded", message: "Job #98214 now has a retry audit record for Alliance High.", type: "info" });
                }}>Retry Job</button>
                <button type="button" aria-label="Download job 98214 details" className="p-1 text-[#64748B] hover:bg-[#D8E0EC] rounded" onClick={() => downloadOperationalLog("Job 98214 retry details", ["Job ID: #98214", "Queue: PDF Generation", "School: Alliance High", "Status: Failed", "Attempts: 3"], onAction)}><MoreHorizontal className="w-4 h-4" /></button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function OfflineSyncWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Offline Sync Monitor" description="Track actions saved on devices and confirm they reached the server safely." icon={RefreshCwOff}>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">School</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Module</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Role</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Action Type</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 font-semibold text-[#071D49]">Kisumu Boys</td>
              <td className="px-4 py-3 text-[#64748B]">Attendance</td>
              <td className="px-4 py-3 text-[#64748B]">Teacher</td>
              <td className="px-4 py-3 text-[#071D49]">Submit Register</td>
              <td className="px-4 py-3"><StatusChip label="Conflict" tone="warning" /></td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => openOperationalReport("Offline sync conflict", [["School", "Kisumu Boys"], ["Module", "Attendance"], ["Role", "Teacher"], ["Action", "Submit Register"], ["Status", "Conflict"]], onAction)}>Resolve Conflict</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function IntegrationsWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Integrations Health" description="Monitor third-party services." icon={Network}>
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <div className="rounded-xl border border-[#D8E0EC] p-4 text-center">
          <h3 className="font-bold text-[#071D49]">M-Pesa</h3>
          <div className="mt-2"><StatusChip label="Operational" tone="success" /></div>
          <button type="button" className="mt-4 text-xs font-bold text-blue-600 border border-blue-200 px-3 py-1 rounded" onClick={() => void runMonitorEndpointCheck("M-Pesa integration", "/observability/health", onAction, { module: "mpesa" })}>Test Connection</button>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] p-4 text-center">
          <h3 className="font-bold text-[#071D49]">SMS Gateway</h3>
          <div className="mt-2"><StatusChip label="Degraded" tone="warning" /></div>
          <button type="button" className="mt-4 text-xs font-bold text-blue-600 border border-blue-200 px-3 py-1 rounded" onClick={() => downloadOperationalLog("SMS gateway integration logs", ["Provider: SMS Gateway", "Status: Degraded", "Action: Review provider latency and failed delivery queue"], onAction)}>View Logs</button>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] p-4 text-center">
          <h3 className="font-bold text-[#071D49]">Email Provider</h3>
          <div className="mt-2"><StatusChip label="Operational" tone="success" /></div>
          <button type="button" className="mt-4 text-xs font-bold text-blue-600 border border-blue-200 px-3 py-1 rounded" onClick={() => void runMonitorEndpointCheck("Email provider", "/observability/health", onAction, { module: "email-provider" })}>Test Connection</button>
        </div>
      </div>
    </Panel>
  );
}

function NotificationsWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Notifications Delivery" description="Monitor SMS, email, and in-app notifications." icon={Send}>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">School</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Channel</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Template</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Sent At</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 font-semibold text-[#071D49]">Alliance High</td>
              <td className="px-4 py-3 text-[#64748B]">SMS</td>
              <td className="px-4 py-3 text-[#64748B]">Fee Reminder</td>
              <td className="px-4 py-3"><StatusChip label="Failed" tone="danger" /></td>
              <td className="px-4 py-3 text-[#64748B]">10:00 AM</td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => {
                  recordMonitorAction("Retry notification delivery", {
                    module: "notifications",
                    entityId: "alliance-high-fee-reminder",
                    body: "Fee Reminder SMS retry was recorded for Alliance High only.",
                    severity: "warning",
                    notify: true,
                    payload: { school: "Alliance High", channel: "SMS", template: "Fee Reminder" },
                  });
                  onAction({ title: "Delivery retry recorded", message: "Fee Reminder SMS retry now has a tenant-scoped operational record.", type: "info" });
                }}>Retry Delivery</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function DatabaseBackupsWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Database & Backups" description="Monitor database health, migrations, backups, and restore readiness." icon={Database}>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Type</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Started At</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Size</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Verified</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 font-semibold text-[#071D49]">Daily Full Backup</td>
              <td className="px-4 py-3"><StatusChip label="Completed" tone="success" /></td>
              <td className="px-4 py-3 text-[#64748B]">02:00 AM</td>
              <td className="px-4 py-3 text-[#64748B]">12.4 GB</td>
              <td className="px-4 py-3 text-[#64748B]">Yes</td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => openOperationalReport("Daily full backup details", [["Type", "Daily Full Backup"], ["Status", "Completed"], ["Started At", "02:00 AM"], ["Size", "12.4 GB"], ["Verified", "Yes"]], onAction)}>View Details</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function StorageFilesWorkspace() {
  return (
    <Panel title="Storage & Files" description="Monitor file uploads, generated PDFs, and storage quotas." icon={HardDrive}>
      <div className="grid gap-4 md:grid-cols-4 lg:grid-cols-4 mb-6">
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-center">
          <div className="text-sm font-semibold text-[#64748B]">Total Storage</div>
          <div className="mt-1 text-xl font-black text-[#071D49]">850 GB</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-center">
          <div className="text-sm font-semibold text-[#64748B]">Failed PDF Generation</div>
          <div className="mt-1 text-xl font-black text-rose-600">8</div>
        </div>
      </div>
    </Panel>
  );
}

function SecurityEventsWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Security Events" description="Monitor suspicious platform activity." icon={ShieldAlert}>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Time</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Severity</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">User</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Event Type</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 text-[#64748B]">Yesterday</td>
              <td className="px-4 py-3"><StatusChip label="Critical" tone="danger" /></td>
              <td className="px-4 py-3 font-semibold text-[#071D49]">john.doe@example.com</td>
              <td className="px-4 py-3 text-[#071D49]">Cross-tenant Access Blocked</td>
              <td className="px-4 py-3"><StatusChip label="Blocked" tone="neutral" /></td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => openOperationalReport("Security event details", [["Time", "Yesterday"], ["Severity", "Critical"], ["User", "john.doe@example.com"], ["Event Type", "Cross-tenant Access Blocked"], ["Status", "Blocked"]], onAction)}>View Details</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function AuditExplorerWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Audit Explorer" description="Search audit logs for sensitive platform actions." icon={ListMagnifyingGlass}>
       <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Time</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Actor</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Action</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Resource</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 text-[#64748B]">10:00 AM</td>
              <td className="px-4 py-3 font-semibold text-[#071D49]">Super Admin</td>
              <td className="px-4 py-3 text-[#071D49]">Invited System Monitor</td>
              <td className="px-4 py-3 text-[#64748B]">User: john.doe</td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => openOperationalReport("Audit event details", [["Time", "10:00 AM"], ["Actor", "Super Admin"], ["Action", "Invited System Monitor"], ["Resource", "User: john.doe"]], onAction)}>View Details</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function ReleaseMonitorWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Release & Version Monitor" description="Detect old frontend versions, stale browser caches, and release-related errors." icon={GitMerge}>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">School</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">User Role</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Client Version</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Update Required</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 font-semibold text-[#071D49]">Nairobi Primary</td>
              <td className="px-4 py-3 text-[#64748B]">Teacher</td>
              <td className="px-4 py-3 text-[#071D49]">v1.2.4 (Outdated)</td>
              <td className="px-4 py-3"><StatusChip label="Yes" tone="danger" /></td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => {
                  recordMonitorAction("Force client revalidation", {
                    module: "release-monitor",
                    entityId: "nairobi-primary-teacher-v1.2.4",
                    body: "Teacher client v1.2.4 for Nairobi Primary was recorded for cache revalidation.",
                    severity: "warning",
                    payload: { school: "Nairobi Primary", role: "Teacher", clientVersion: "v1.2.4" },
                  });
                  onAction({ title: "Revalidation recorded", message: "Client revalidation has an audit record for Nairobi Primary.", type: "info" });
                }}>Force Revalidation</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function PerformanceAnalyticsWorkspace() {
  return (
    <Panel title="Performance Analytics" description="Monitor speed and usage quality." icon={Gauge}>
       <div className="grid gap-4 md:grid-cols-3 mb-6">
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-center">
          <div className="text-sm font-semibold text-[#64748B]">Average API Time</div>
          <div className="mt-1 text-xl font-black text-[#071D49]">150ms</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-center">
          <div className="text-sm font-semibold text-[#64748B]">Slowest Module</div>
          <div className="mt-1 text-xl font-black text-amber-600">Report Cards</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-center">
          <div className="text-sm font-semibold text-[#64748B]">Queue Delay</div>
          <div className="mt-1 text-xl font-black text-[#071D49]">4s</div>
        </div>
      </div>
    </Panel>
  );
}

function SupportDiagnosticsWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Support Diagnostics" description="Safely diagnose school issues using technical traces, not private school records." icon={Wrench}>
      <div className="flex flex-col sm:flex-row gap-3 mb-4">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-2.5 h-4 w-4 text-[#64748B]" />
          <input type="text" placeholder="Search by school, request ID, job ID, phone ending..." className="w-full rounded-xl border border-[#D8E0EC] py-2 pl-9 pr-3 text-sm focus:border-[#071D49] focus:outline-none focus:ring-1 focus:ring-[#071D49]" />
        </div>
      </div>
      <div className="grid gap-4 md:grid-cols-4">
        {["User Session Check", "Module Health Check", "Request Trace Lookup", "Sync Lookup"].map(tool => (
          <button key={tool} type="button" className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-left font-bold text-[#071D49] hover:border-[#071D49] transition" onClick={() => openOperationalReport(tool, [["Tool", tool], ["Scope", "Technical metadata only"], ["Tenant private records", "Not included"], ["Next step", "Enter a school, request ID, job ID, or trace key in the search box"]], onAction)}>{tool}</button>
        ))}
      </div>
    </Panel>
  );
}

function IncidentCenterWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Incident Center" description="Create, track, update, and resolve technical incidents." icon={Siren} actions={
      <button type="button" className="rounded-lg bg-rose-600 px-4 py-2 text-sm font-black text-white" onClick={() => {
        recordMonitorAction("Create technical incident", {
          module: "incident-center",
          entityId: "incident-draft",
          body: "Technical incident draft created for operator triage with tenant-safe diagnostics required before publishing.",
          severity: "warning",
          notify: true,
        });
        onAction({ title: "Incident draft recorded", message: "The incident draft now has an operational record for triage.", type: "info" });
      }}>Create Incident</button>
    }>
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Incident ID</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Severity</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            <tr className="hover:bg-[#F8FAFC]">
              <td className="px-4 py-3 text-[#64748B]">INC-402</td>
              <td className="px-4 py-3 font-semibold text-[#071D49]">M-Pesa Callbacks Delayed</td>
              <td className="px-4 py-3"><StatusChip label="High" tone="danger" /></td>
              <td className="px-4 py-3"><StatusChip label="Investigating" tone="warning" /></td>
              <td className="px-4 py-3 text-right">
                <button type="button" className="text-blue-600 hover:underline font-semibold text-xs mr-3" onClick={() => openOperationalReport("Incident INC-402", [["Incident ID", "INC-402"], ["Title", "M-Pesa Callbacks Delayed"], ["Severity", "High"], ["Status", "Investigating"]], onAction)}>View</button>
                <button type="button" className="text-emerald-600 hover:underline font-semibold text-xs" onClick={() => {
                  recordMonitorAction("Incident resolution review", {
                    module: "incident-center",
                    entityId: "INC-402",
                    body: "INC-402 marked for resolution review; callback replay evidence is required before final closure.",
                    severity: "warning",
                    notify: true,
                  });
                  onAction({ title: "Resolution review recorded", message: "INC-402 remains tracked until callback replay evidence is attached.", type: "info" });
                }}>Resolve</button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </Panel>
  );
}

function ReportsWorkspace({ onAction }: { onAction: MonitorAction }) {
  return (
    <Panel title="Reports" description="Generate platform health and technical operation reports." icon={FileText}>
       <div className="grid gap-4 md:grid-cols-3">
        {["Daily Platform Health Report", "Weekly Tenant Health Report", "Failed Jobs Report", "Release Adoption Report", "Backup Health Report"].map(r => (
          <button key={r} type="button" className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4 text-left font-bold text-[#071D49] hover:border-[#071D49] transition" onClick={() => openOperationalReport(r, [["Report", r], ["Source", "System Monitor visible operational state"], ["Tenant data", "Aggregated operational metadata only"], ["Generated by", "System Monitor"]], onAction)}>{r}</button>
        ))}
      </div>
    </Panel>
  );
}

function SettingsWorkspace() {
  return (
    <Panel title="Monitor Settings" description="Manage System Monitor’s own preferences and alert thresholds, not global school settings." icon={Settings}>
      <div className="grid gap-4 md:grid-cols-2">
        <div className="rounded-xl border border-[#D8E0EC] p-4">
          <h3 className="font-bold text-[#071D49] mb-4">My Notification Preferences</h3>
          <div className="space-y-3 text-sm text-[#64748B]">
            <div className="flex justify-between items-center"><span className="font-semibold text-[#071D49]">Receive critical alerts</span> <input type="checkbox" defaultChecked className="rounded text-blue-600" /></div>
            <div className="flex justify-between items-center"><span className="font-semibold text-[#071D49]">Receive daily health summary</span> <input type="checkbox" defaultChecked className="rounded text-blue-600" /></div>
          </div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] p-4">
          <h3 className="font-bold text-[#071D49] mb-4">Alert Thresholds</h3>
          <div className="space-y-3 text-sm text-[#64748B]">
            <div className="flex justify-between items-center"><span className="font-semibold text-[#071D49]">Failed jobs alert threshold</span> <input type="number" defaultValue={10} className="w-16 rounded border border-[#D8E0EC] px-2 py-1 text-right" /></div>
            <div className="flex justify-between items-center"><span className="font-semibold text-[#071D49]">Error spike threshold</span> <input type="number" defaultValue={50} className="w-16 rounded border border-[#D8E0EC] px-2 py-1 text-right" /></div>
          </div>
        </div>
      </div>
    </Panel>
  );
}

export function SystemMonitorDashboard({ routeMode }: { routeMode: RouteMode }) {
  const [activeView, setActiveView] = useState<ViewId>("overview");
  const [toasts, setToasts] = useState<Array<{ id: string; title: string; message?: string; type?: MonitorToastType }>>([]);

  const pushMonitorToast: MonitorAction = ({ title, message, type = "info" }) => {
    setToasts((current) => [
      ...current.slice(-3),
      {
        id: `${Date.now()}-${Math.random().toString(16).slice(2)}`,
        title,
        message,
        type,
      },
    ]);
  };

  const removeToast = (id: string) => {
    setToasts((current) => current.filter((toast) => toast.id !== id));
  };

  return (
    <div className="flex min-h-dvh bg-[#F3F6FA] font-sans">
      <aside className="hidden h-dvh w-[260px] shrink-0 overflow-y-auto bg-[#071D49] p-4 text-white shadow-[0_24px_70px_rgba(7,29,73,0.28)] lg:block">
        <div className="rounded-2xl border border-white/10 bg-white/5 p-4 mb-6">
          <MyShuleBrand markSize={38} nameClassName="text-base" />
          <h2 className="mt-2 text-xl font-black">System Monitor</h2>
          <p className="mt-2 text-sm leading-6 text-white/65">Platform Health & Ops</p>
        </div>
        <nav className="space-y-1" aria-label="System Monitor navigation">
          {navItems.map((item, index) => {
            const showGroup = item.group !== navItems[index - 1]?.group;
            const Icon = item.icon;
            return (
              <div key={`${item.group}-${item.label}`}>
                {showGroup ? <p className="px-3 pb-2 pt-4 text-[10px] font-black uppercase tracking-[0.2em] text-white/40">{item.group}</p> : null}
                <button
                  type="button"
                  onClick={() => setActiveView(item.id)}
                  className={cn(
                    "flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold text-white/70 transition hover:bg-white/10 hover:text-white",
                    activeView === item.id && "bg-white/15 text-white shadow-[inset_4px_0_0_#38BDF8]"
                  )}
                >
                  <Icon className="h-4 w-4 shrink-0" aria-hidden="true" />
                  <span className="truncate">{item.label}</span>
                </button>
              </div>
            );
          })}
        </nav>
      </aside>
      <main className="flex h-dvh min-w-0 flex-1 flex-col">
        <header className="sticky top-0 z-20 border-b border-[#D8E0EC] bg-white/90 px-4 py-3 backdrop-blur shrink-0">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-center gap-3">
              <MyShuleMark size={40} />
              <h1 className="text-lg font-black text-[#071D49] truncate">{navItems.find(i => i.id === activeView)?.label || "Dashboard"}</h1>
              <span className="rounded-full border border-[#D8E0EC] bg-[#F8FAFC] px-2.5 py-1 text-xs font-bold uppercase tracking-[0.12em] text-[#64748B]">{routeMode}</span>
            </div>
            <div className="flex w-full flex-wrap items-center gap-2 sm:w-auto sm:justify-end">
              <StatusChip label="Global Platform" tone="info" />
              <button type="button" aria-label="Open System Monitor search" className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#071D49] text-white" onClick={() => pushMonitorToast({ title: "Search ready", message: "Use each workspace search box to inspect tenant-safe operational metadata.", type: "info" })}>
                <Search className="h-4 w-4" />
              </button>
              <TaskQueue />
              <ApprovalInbox currentUserId="superadmin" />
              <NotificationBell />
            </div>
          </div>
          <div className="mt-3 lg:hidden">
            <MobileWorkspaceNavigation
              label="System monitor workspace"
              items={navItems}
              value={activeView}
              onValueChange={(value) => setActiveView(value as ViewId)}
              testId="system-monitor-mobile-workspace-nav"
            />
          </div>
        </header>
        <div className="flex-1 overflow-y-auto p-4 lg:p-6 space-y-6">
          {activeView === "overview" && <OverviewWorkspace onNavigate={setActiveView} onAction={pushMonitorToast} />}
          {activeView === "tenant-health" && <TenantHealthWorkspace onAction={pushMonitorToast} />}
          {activeView === "uptime-services" && <UptimeServicesWorkspace onAction={pushMonitorToast} />}
          {activeView === "error-logs" && <ErrorLogsWorkspace onAction={pushMonitorToast} />}
          {activeView === "background-jobs" && <BackgroundJobsWorkspace onAction={pushMonitorToast} />}
          {activeView === "offline-sync" && <OfflineSyncWorkspace onAction={pushMonitorToast} />}
          {activeView === "performance-analytics" && <PerformanceAnalyticsWorkspace />}
          {activeView === "support-diagnostics" && <SupportDiagnosticsWorkspace onAction={pushMonitorToast} />}
          {activeView === "integrations" && <IntegrationsWorkspace onAction={pushMonitorToast} />}
          {activeView === "notifications" && <NotificationsWorkspace onAction={pushMonitorToast} />}
          {activeView === "database-backups" && <DatabaseBackupsWorkspace onAction={pushMonitorToast} />}
          {activeView === "storage-files" && <StorageFilesWorkspace />}
          {activeView === "security-events" && <SecurityEventsWorkspace onAction={pushMonitorToast} />}
          {activeView === "audit-explorer" && <AuditExplorerWorkspace onAction={pushMonitorToast} />}
          {activeView === "release-monitor" && <ReleaseMonitorWorkspace onAction={pushMonitorToast} />}
          {activeView === "incident-center" && <IncidentCenterWorkspace onAction={pushMonitorToast} />}
          {activeView === "reports" && <ReportsWorkspace onAction={pushMonitorToast} />}
          {activeView === "settings" && <SettingsWorkspace />}
        </div>
      </main>
      <div className="fixed bottom-4 right-4 z-50 flex max-w-[calc(100vw-2rem)] flex-col items-end">
        {toasts.map((toast) => (
          <WorkflowToast key={toast.id} {...toast} onClose={removeToast} />
        ))}
      </div>
    </div>
  );
}
