import { createHash } from 'node:crypto';
import type { ReportArtifact } from '../../../common/reports/report-artifact';
import type { AnalyticsPrintReport } from './analytics-report-contract';

/** RFC 4180 escaping plus spreadsheet formula neutralization, including leading whitespace. */
export function analyticsCsvCell(value:string):string {
  const safe=/^\s*[=+@\-\t\r]/.test(value)?`'${value}`:value;
  return `"${safe.replaceAll('"','""')}"`;
}
export function createAnalyticsReportCsv(report:AnalyticsPrintReport):ReportArtifact {
  const rows:string[][]=[['School',report.school_name],['Report',report.title],['Document',report.document_number],['Exam',report.exam],
    ['Period',report.period],['Scope',report.scope],['Generated at (UTC)',report.generated_at],['Generated by',report.generated_by],
    ...report.filters.map(f=>[f.label,f.value]),[]];
  for(const section of report.sections)rows.push([section.title],[section.note??''],section.headers,...section.rows,[]);
  rows.push(['Methodology'],...report.notes.map(n=>[n]));
  const content=Buffer.from('\uFEFF'+rows.map(r=>r.map(analyticsCsvCell).join(',')).join('\r\n'),'utf8');
  return {filename:`${report.document_number.toLowerCase()}.csv`,contentType:'text/csv; charset=utf-8',content,byteLength:content.length,
    checksumSha256:createHash('sha256').update(content).digest('hex'),generatedAt:report.generated_at,rowCount:report.sections.reduce((n,s)=>n+s.rows.length,0)};
}
