"use client";

import { useState } from "react";
import { FileText, Download, Printer } from "lucide-react";
import { toast } from "sonner";
import { Panel, StatusChip, Tone } from "./shared";
import { useSchoolQuery } from "@/lib/data/school-hooks";
import { generateStoreReport } from "./api-client";
import { Modal } from "@/components/ui/modal";

type StoreReport = {
  id: string;
  title: string;
  type: string;
  period: string;
  generated_by: string;
  generated_date: string;
  status: string;
};

type ReportsData = {
  metrics: {
    total_reports: number;
    generated_this_month: number;
  };
  report_types: string[];
  reports: StoreReport[];
};

export function ReportsWorkspace() {
  const { data, isLoading, refetch } = useSchoolQuery<ReportsData>('/admin-command/storekeeper/reports');
  const [generating, setGenerating] = useState(false);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedReportType, setSelectedReportType] = useState("");
  const [period, setPeriod] = useState("");

  const reports = data?.reports || [];
  const reportTypes = data?.report_types || [
    "Stock Movement Report",
    "Stock Valuation Report",
    "Low Stock Report",
    "Stocktake Report",
    "Damaged/Lost Items Report",
    "Issue Summary Report",
    "Supplier Summary Report",
  ];

  const getStatusTone = (status: string): Tone => {
    if (status === "Ready") return "success";
    if (status === "Generating") return "info";
    if (status === "Failed") return "danger";
    return "neutral";
  };

  const handleGenerateClick = () => {
    setSelectedReportType(data?.report_types?.[0] || reportTypes[0] || "Stock Movement Report");
    setPeriod("");
    setIsModalOpen(true);
  };

  const handleConfirmGenerate = async () => {
    if (!period.trim()) {
      toast.error("Please enter a period.");
      return;
    }
    setGenerating(true);
    try {
      await generateStoreReport({ type: selectedReportType, period });
      toast.success("Report is being generated. It will appear below when ready.");
      setIsModalOpen(false);
      refetch();
    } catch {
      toast.error("Failed to generate report.");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <Panel
      title="Store Reports"
      description="Generate and download store inventory reports."
      icon={FileText}
      actions={
        <button
          disabled={generating}
          onClick={handleGenerateClick}
          className="inline-flex items-center gap-2 rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white hover:bg-blue-900 transition disabled:opacity-50"
        >
          <FileText className="h-4 w-4" /> {generating ? "Generating..." : "Generate Report"}
        </button>
      }
    >
      {/* Metrics */}
      <div className="grid gap-4 md:grid-cols-2 mb-6">
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <div className="text-sm font-semibold text-[#64748B]">Total Reports</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">{isLoading ? "..." : data?.metrics?.total_reports || 0}</div>
        </div>
        <div className="rounded-xl border border-[#D8E0EC] bg-[#F8FAFC] p-4">
          <div className="text-sm font-semibold text-[#64748B]">Generated This Month</div>
          <div className="mt-1 text-2xl font-black text-[#071D49]">{isLoading ? "..." : data?.metrics?.generated_this_month || 0}</div>
        </div>
      </div>

      {/* Reports Table */}
      <div className="overflow-x-auto rounded-xl border border-[#D8E0EC]">
        <table className="w-full text-sm text-left whitespace-nowrap">
          <thead className="bg-[#F8FAFC] text-[#071D49]">
            <tr>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Report Title</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Type</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Period</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Generated By</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Date</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC]">Status</th>
              <th className="px-4 py-3 font-bold border-b border-[#D8E0EC] text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[#D8E0EC]">
            {isLoading ? (
              <tr><td colSpan={7} className="px-4 py-8 text-center text-[#64748B]">Loading reports...</td></tr>
            ) : reports.length === 0 ? (
              <tr><td colSpan={7} className="px-4 py-8 text-center text-[#64748B]">No reports generated yet. Click &quot;Generate Report&quot; to create a stock movement, valuation, or stocktake report.</td></tr>
            ) : (
              reports.map((report) => (
                <tr key={report.id} className="hover:bg-[#F8FAFC]">
                  <td className="px-4 py-3 font-semibold text-[#071D49]">{report.title}</td>
                  <td className="px-4 py-3 text-[#64748B]">{report.type}</td>
                  <td className="px-4 py-3 text-[#64748B]">{report.period}</td>
                  <td className="px-4 py-3 text-[#64748B]">{report.generated_by}</td>
                  <td className="px-4 py-3 text-[#64748B]">{report.generated_date}</td>
                  <td className="px-4 py-3"><StatusChip label={report.status} tone={getStatusTone(report.status)} /></td>
                  <td className="px-4 py-3 text-right">
                    {report.status === "Ready" ? (
                      <div className="inline-flex gap-2">
                        <button className="inline-flex items-center gap-1 text-blue-600 hover:underline font-semibold text-xs">
                          <Download className="h-3 w-3" /> Download
                        </button>
                        <button className="inline-flex items-center gap-1 text-[#64748B] hover:underline font-semibold text-xs">
                          <Printer className="h-3 w-3" /> Print
                        </button>
                      </div>
                    ) : report.status === "Generating" ? (
                      <span className="text-xs text-blue-600">Processing...</span>
                    ) : (
                      <span className="text-xs text-rose-600">Failed</span>
                    )}
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      <Modal
        open={isModalOpen}
        title="Generate Store Report"
        description="Select a report type and specify the period for which to generate the report."
        onClose={() => setIsModalOpen(false)}
        footer={
          <div className="flex gap-2 justify-end">
            <button
              onClick={() => setIsModalOpen(false)}
              className="rounded-lg border border-[#D8E0EC] px-4 py-2 text-sm font-semibold text-[#64748B] hover:bg-[#F8FAFC] transition"
            >
              Cancel
            </button>
            <button
              onClick={handleConfirmGenerate}
              disabled={generating || !period.trim()}
              className="rounded-lg bg-[#071D49] px-4 py-2 text-sm font-black text-white hover:bg-blue-900 transition disabled:opacity-50"
            >
              {generating ? "Generating..." : "Generate"}
            </button>
          </div>
        }
      >
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-semibold text-[#071D49] mb-1">
              Report Type
            </label>
            <select
              value={selectedReportType}
              onChange={(e) => setSelectedReportType(e.target.value)}
              className="w-full rounded-lg border border-[#D8E0EC] p-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-[#071D49]"
            >
              {reportTypes.map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label className="block text-sm font-semibold text-[#071D49] mb-1">
              Period (e.g. 'Term 2 2026', 'June 2026', 'Q2 2026')
            </label>
            <input
              type="text"
              placeholder="Enter period..."
              value={period}
              onChange={(e) => setPeriod(e.target.value)}
              className="w-full rounded-lg border border-[#D8E0EC] p-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#071D49]"
            />
          </div>
        </div>
      </Modal>
    </Panel>
  );
}
