'use client';

import React from 'react';

interface PayrollSummaryTemplateProps {
  payrollMonth: string;
  dateGenerated: string;
  generatedBy: string;
  records: Array<{
    staffName: string;
    role: string;
    basicSalary: number;
    allowances: number;
    deductions: number;
    netPay: number;
  }>;
}

export default function PayrollSummaryTemplate({
  payrollMonth,
  dateGenerated,
  generatedBy,
  records,
}: PayrollSummaryTemplateProps) {
  
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES' }).format(amount);
  };

  const totalBasic = records.reduce((sum, r) => sum + r.basicSalary, 0);
  const totalAllowances = records.reduce((sum, r) => sum + r.allowances, 0);
  const totalDeductions = records.reduce((sum, r) => sum + r.deductions, 0);
  const totalNet = records.reduce((sum, r) => sum + r.netPay, 0);

  return (
    <div className="flex flex-col gap-6 text-sm">
      <section className="flex justify-between items-end border-b border-gray-800 pb-2">
        <div>
          <h3 className="font-bold text-base uppercase">Payroll Summary - {payrollMonth}</h3>
        </div>
        <div className="text-right text-xs">
          <p><strong>Generated On:</strong> {dateGenerated}</p>
          <p><strong>Generated By:</strong> {generatedBy}</p>
        </div>
      </section>

      <section>
        <table className="w-full border-collapse border border-gray-800 text-[11px] text-left">
          <thead className="bg-gray-100">
            <tr>
              <th className="border border-gray-800 p-2">Staff Name</th>
              <th className="border border-gray-800 p-2">Role</th>
              <th className="border border-gray-800 p-2 text-right">Basic Salary</th>
              <th className="border border-gray-800 p-2 text-right">Allowances</th>
              <th className="border border-gray-800 p-2 text-right">Deductions</th>
              <th className="border border-gray-800 p-2 text-right">Net Pay</th>
            </tr>
          </thead>
          <tbody>
            {records.map((rec, idx) => (
              <tr key={idx}>
                <td className="border border-gray-800 p-2 font-medium">{rec.staffName}</td>
                <td className="border border-gray-800 p-2">{rec.role}</td>
                <td className="border border-gray-800 p-2 text-right">{formatCurrency(rec.basicSalary)}</td>
                <td className="border border-gray-800 p-2 text-right">{formatCurrency(rec.allowances)}</td>
                <td className="border border-gray-800 p-2 text-right text-red-600">{formatCurrency(rec.deductions)}</td>
                <td className="border border-gray-800 p-2 text-right font-bold">{formatCurrency(rec.netPay)}</td>
              </tr>
            ))}
            <tr className="bg-gray-200 font-bold">
              <td className="border border-gray-800 p-2 text-right" colSpan={2}>TOTALS</td>
              <td className="border border-gray-800 p-2 text-right">{formatCurrency(totalBasic)}</td>
              <td className="border border-gray-800 p-2 text-right">{formatCurrency(totalAllowances)}</td>
              <td className="border border-gray-800 p-2 text-right text-red-600">{formatCurrency(totalDeductions)}</td>
              <td className="border border-gray-800 p-2 text-right">{formatCurrency(totalNet)}</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section className="grid grid-cols-2 gap-12 mt-12 px-8">
        <div className="flex flex-col items-center">
          <div className="w-full border-b border-gray-800 mb-2"></div>
          <p className="font-bold">Prepared By (HR/Accountant)</p>
        </div>
        <div className="flex flex-col items-center">
          <div className="w-full border-b border-gray-800 mb-2"></div>
          <p className="font-bold">Approved By (Principal)</p>
        </div>
      </section>
    </div>
  );
}
