const roleHomePaths: Record<string, string> = {
  superadmin: "/superadmin/dashboard",
  platform_owner: "/superadmin/dashboard",
  principal: "/school/principal",
  "deputy-principal": "/school/deputy-principal",
  secretary: "/school/secretary",
  owner: "/school/principal",
  admin: "/school/admin",
  member: "/school/admin",
  staff: "/school/admin",
  school_admin: "/school/admin",
  "school-admin": "/school/admin",
  school_owner: "/school/principal",
  "school-owner": "/school/principal",
  tenant_owner: "/school/principal",
  bursar: "/school/bursar",
  accountant: "/school/accountant",
  teacher: "/school/teacher",
  dean: "/school/dean-academics",
  dean_academics: "/school/dean-academics",
  "dean-academics": "/school/dean-academics",
  "dean-of-academics": "/school/dean-academics",
  academic_dean: "/school/dean-academics",
  "academic-dean": "/school/dean-academics",
  exam_manager: "/school/exams-manager",
  "exam-manager": "/school/exams-manager",
  exams_manager: "/school/exams-manager",
  "exams-manager": "/school/exams-manager",
  exam_officer: "/school/exams-manager",
  "exam-officer": "/school/exams-manager",
  exams_officer: "/school/exams-manager",
  "exams-officer": "/school/exams-manager",
  examination_officer: "/school/exams-manager",
  "examination-officer": "/school/exams-manager",
  hod: "/school/hod",
  hos: "/school/hos",
  head_of_subject: "/school/hos",
  "head-of-subject": "/school/hos",
  head_of_department: "/school/hod",
  "head-of-department": "/school/hod",
  department_head: "/school/hod",
  "department-head": "/school/hod",
  class_teacher: "/school/class-teacher",
  "class-teacher": "/school/class-teacher",
  grade_master: "/school/grade-master",
  form_master: "/school/grade-master",
  "grade-master": "/school/grade-master",
  "form-master": "/school/grade-master",
  "grade-form-master": "/school/grade-master",
  storekeeper: "/school/storekeeper",
  librarian: "/school/librarian",
  nurse: "/school/nurse",
  "clinic-staff": "/school/nurse",
  boarding_master: "/school/boarding-master",
  "boarding-master": "/school/boarding-master",
  security_officer: "/school/security-officer",
  "security-officer": "/school/security-officer",
  transport_manager: "/school/transport-manager",
  "transport-manager": "/school/transport-manager",
  lab_technician: "/school/laboratory-technician",
  laboratory_technician: "/school/laboratory-technician",
  "lab-technician": "/school/laboratory-technician",
  "laboratory-technician": "/school/laboratory-technician",
  school_counsellor: "/school/guidance-counselling",
  "school-counsellor": "/school/guidance-counselling",
  counsellor: "/school/guidance-counselling",
  counselor: "/school/guidance-counselling",
  guidance_counselling: "/school/guidance-counselling",
  "guidance-counselling": "/school/guidance-counselling",
  discipline_master: "/school/discipline-master",
  "discipline-master": "/school/discipline-master",
  dean_of_students: "/school/discipline-master",
  "dean-of-students": "/school/discipline-master",
  admissions: "/school/admissions",
  registrar: "/school/admissions",
  admissions_officer: "/school/admissions",
  "admissions-officer": "/school/admissions",
  student: "/school/student",
  ict_manager: "/school/ict-manager",
  "ict-manager": "/school/ict-manager",
  ict: "/school/ict-manager",
  computer_lab_manager: "/school/ict-manager",
  "computer-lab-manager": "/school/ict-manager",
  "computer-lab-user": "/school/ict-manager",
  "ict-computer-lab-user": "/school/ict-manager",
  parent: "/portal/dashboard",
};

export function getRoleHomePath(role: string | null | undefined) {
  if (!role) {
    return "/school/principal";
  }

  return roleHomePaths[role] ?? "/school/principal";
}
