import fs from "node:fs";
import path from "node:path";

function readSource(file: string) {
  return fs.readFileSync(path.join(process.cwd(), file), "utf8");
}

describe("academic leadership command center shell contract", () => {
  it("renders the Dean of Academics shell through live academic workspace modules", () => {
    const source = readSource("src/components/school/dean-academics-command-center.tsx");

    expect(source).toMatch(/from "\.\/dean-academics\/overview-workspace"/);
    expect(source).toMatch(/from "\.\/dean-academics\/curriculum-coverage-workspace"/);
    expect(source).toMatch(/from "\.\/dean-academics\/department-performance-workspace"/);
    expect(source).toMatch(/from "\.\/dean-academics\/teacher-workload-workspace"/);
    expect(source).toMatch(/from "\.\/dean-academics\/lesson-plans-workspace"/);
    expect(source).toMatch(/from "\.\/dean-academics\/lesson-logs-workspace"/);
    expect(source).toMatch(/from "\.\/dean-academics\/assessments-workspace"/);
    expect(source).toMatch(/from "\.\/dean-academics\/academic-interventions-workspace"/);
    expect(source).toMatch(/from "\.\/dean-academics\/reports-workspace"/);
    expect(source).toMatch(/function normalizeDeanView/);
    expect(source).toMatch(/data-testid="role-operational-command-center"/);
    expect(source).not.toMatch(/deanSearchRecords|Term 2 CAT 1|Class 7B|Pending reviews", "14|Integrity alerts", "6|Report batches", "4/);
  });

  it("renders the HOD shell through live department workspace modules", () => {
    const source = readSource("src/components/school/hod-command-center.tsx");

    expect(source).toMatch(/from "\.\/hod\/overview-workspace"/);
    expect(source).toMatch(/from "\.\/hod\/department-teachers-workspace"/);
    expect(source).toMatch(/from "\.\/hod\/subject-allocation-workspace"/);
    expect(source).toMatch(/from "\.\/hod\/coverage-review-workspace"/);
    expect(source).toMatch(/from "\.\/hod\/lesson-plans-workspace"/);
    expect(source).toMatch(/from "\.\/hod\/marks-moderation-workspace"/);
    expect(source).toMatch(/from "\.\/hod\/resource-requests-workspace"/);
    expect(source).toMatch(/from "\.\/hod\/reports-workspace"/);
    expect(source).toMatch(/function normalizeHodView/);
    expect(source).toMatch(/data-testid="role-operational-command-center"/);
    expect(source).not.toMatch(/GENERATED BY scaffold_hod|SimpleWorkspace|Mathematics Department|Good evening, Mr\. Otieno|3 Missing|Marksheets Pending/);
  });

  it("keeps HOD subject allocation human-operated instead of asking for raw IDs", () => {
    const source = readSource("src/components/school/hod/subject-allocation-workspace.tsx");

    expect(source).toMatch(/subject-allocation\/options/);
    expect(source).toMatch(/<select name="subject_id"/);
    expect(source).toMatch(/<select name="class_section_id"/);
    expect(source).toMatch(/<select name="academic_term_id"/);
    expect(source).not.toMatch(/Subject ID|Class Section ID|Academic Term ID|Staff member ID/);
  });
});
