export type ModuleRegistrySeedItem = {
  code: string;
  name: string;
  description: string;
  category?: string;
  route_segment?: string | null;
  permission_scopes?: readonly string[];
  feature_flags?: Record<string, unknown>;
  status?: 'active' | 'inactive';
  base_price_cents?: number;
  per_student_price_cents?: number;
  billing_metadata?: Record<string, unknown>;
};

export const MODULE_REGISTRY_SEED = [
  {
    code: 'students',
    name: 'Student Management',
    description: 'Student records, profiles, guardians, and lifecycle.',
    category: 'core',
    route_segment: 'students',
    permission_scopes: ['students:read', 'students:write'],
    billing_metadata: { pricing_unit: 'student' },
  },
  {
    code: 'admissions',
    name: 'Admissions',
    description: 'Student onboarding, document verification, transfers, and registration.',
    category: 'administration',
    route_segment: 'admissions',
    permission_scopes: ['admissions:read', 'admissions:write'],
    billing_metadata: { pricing_unit: 'student' },
  },
  {
    code: 'academics',
    name: 'Academic Structure',
    description: 'CBE, CBC, 8-4-4, international levels, classes, streams, subjects, and assignments.',
    category: 'academics',
    route_segment: 'academics',
    permission_scopes: ['academics:read', 'academics:write', 'academics:assign-teachers'],
    billing_metadata: { pricing_unit: 'student' },
  },
  {
    code: 'finance',
    name: 'Fee Management',
    description: 'Fee structures, invoices, payments, arrears, collections, and financial oversight.',
    category: 'finance',
    route_segment: 'finance',
    permission_scopes: ['finance:read', 'finance:write', 'payments:create'],
    billing_metadata: { pricing_unit: 'student', plan_family: 'core_finance' },
  },
  {
    code: 'exams',
    name: 'Exams and Results',
    description: 'Assessments, marks, reports, academic analytics, CBT hooks, and result publishing.',
    category: 'academics',
    route_segment: 'exams',
    permission_scopes: ['exams:read', 'exams:write', 'exams:enter-marks', 'exams:review', 'exams:approve'],
    billing_metadata: { pricing_unit: 'student' },
  },
  {
    code: 'discipline',
    name: 'Discipline',
    description: 'Incidents, actions, escalation, counselling, welfare, and behavior analytics.',
    category: 'student_welfare',
    route_segment: 'discipline',
    permission_scopes: ['discipline:read', 'discipline:write', 'discipline:manage', 'discipline:reports'],
    billing_metadata: { pricing_unit: 'student' },
  },
  {
    code: 'timetable',
    name: 'Timetable',
    description: 'Published timetables, lesson coverage, room planning, and schedule conflicts.',
    category: 'academics',
    route_segment: 'timetable',
    permission_scopes: ['timetable:read', 'timetable:write'],
    billing_metadata: { pricing_unit: 'school' },
  },
  {
    code: 'lab_management',
    name: 'Laboratory Management',
    description: 'Labs, sessions, mandatory attendance, equipment, chemicals, and safety controls.',
    category: 'academics',
    route_segment: 'labs',
    permission_scopes: ['labs:read', 'labs:write', 'labs:attendance', 'labs:inventory', 'labs:approve-disposal'],
    billing_metadata: { pricing_unit: 'student', premium: true },
  },
  {
    code: 'teacher_biometric_attendance',
    name: 'Teacher Attendance',
    description: 'Biometric teacher scans, attendance logs, offline device sync, and punctuality reports.',
    category: 'staff',
    route_segment: 'teacher-attendance',
    permission_scopes: ['teacher_attendance:read', 'teacher_attendance:devices', 'teacher_attendance:override', 'teacher_attendance:reports'],
    billing_metadata: { pricing_unit: 'device', premium: true },
  },
  {
    code: 'parent_portal',
    name: 'Parent Portal',
    description: 'Parent and student self-service portals, payments, messages, and child summaries.',
    category: 'portal',
    route_segment: 'portal',
    permission_scopes: ['portal:read_own_children', 'portal:message_school'],
    billing_metadata: { pricing_unit: 'student' },
  },
  {
    code: 'inventory',
    name: 'Store and Inventory',
    description: 'Stock, procurement, issuing, transfers, assets, valuation, and reconciliation.',
    category: 'operations',
    route_segment: 'inventory',
    permission_scopes: ['inventory:read', 'inventory:write', 'procurement:read', 'procurement:write'],
    billing_metadata: { pricing_unit: 'school' },
  },
  {
    code: 'library',
    name: 'Library',
    description: 'Catalog, lending, returns, fines, reservations, and library reports.',
    category: 'academics',
    route_segment: 'library',
    permission_scopes: ['library:read', 'library:write'],
    billing_metadata: { pricing_unit: 'school' },
  },
  {
    code: 'transport',
    name: 'Transport',
    description: 'Routes, vehicles, learner manifests, trip operations, and route alerts.',
    category: 'operations',
    route_segment: 'transport',
    permission_scopes: ['transport:read', 'transport:write'],
    billing_metadata: { pricing_unit: 'vehicle', premium: true },
  },
  {
    code: 'communication_sms',
    name: 'Communication and SMS',
    description: 'SMS wallet, announcements, reminders, delivery logs, and parent engagement analytics.',
    category: 'communication',
    route_segment: 'communication',
    permission_scopes: ['school_sms:read', 'school_sms:send', 'school_sms:purchase'],
    billing_metadata: { pricing_unit: 'message' },
  },
  {
    code: 'reports',
    name: 'Reports',
    description: 'PDF, CSV, Excel, scheduled, graphical, and operational reports.',
    category: 'analytics',
    route_segment: 'reports',
    permission_scopes: ['reports:read'],
    billing_metadata: { pricing_unit: 'school' },
  },
  {
    code: 'staff',
    name: 'Staff and HR',
    description: 'Staff profiles, contracts, leave, documents, duty ownership, and payroll summaries.',
    category: 'staff',
    route_segment: 'staff',
    permission_scopes: ['hr:read', 'hr:write'],
    billing_metadata: { pricing_unit: 'staff' },
  },
  {
    code: 'admin_command_centers',
    name: 'Administrative Leadership',
    description: 'Principal, deputy principal, and secretary command centers.',
    category: 'leadership',
    route_segment: 'leadership',
    permission_scopes: ['principal:read', 'deputy:read', 'secretary:read'],
    billing_metadata: { pricing_unit: 'school' },
  },
  {
    code: 'principal_dashboard',
    name: 'Principal Executive Dashboard',
    description: 'Module-aware executive KPIs, alerts, analytics, trends, and reports for the Principal.',
    category: 'leadership',
    route_segment: 'dashboard',
    permission_scopes: ['principal:read'],
    billing_metadata: { pricing_unit: 'school', included_with: 'admin_command_centers' },
  },
  {
    code: 'clinic_health',
    name: 'Clinic and Health',
    description: 'Clinic visits, medicine inventory, dispensing, health analytics, and parent medical history.',
    category: 'health',
    route_segment: 'clinic',
    permission_scopes: ['clinic:read', 'clinic:write', 'clinic:inventory', 'clinic:dispense', 'clinic:reports'],
    billing_metadata: { pricing_unit: 'student', premium: true },
  },
  {
    code: 'procurement',
    name: 'Procurement',
    description: 'Purchase requests, supplier tracking, approvals, invoice attachment, and budget linkage.',
    category: 'operations',
    route_segment: 'procurement',
    permission_scopes: ['procurement:read', 'procurement:write'],
    billing_metadata: { pricing_unit: 'school' },
  },
  {
    code: 'hostel',
    name: 'Hostel',
    description: 'Hostel occupancy, dormitory issues, boarding incidents, and meal consumption analytics.',
    category: 'boarding',
    route_segment: 'hostel',
    permission_scopes: ['hostel:read', 'hostel:write'],
    billing_metadata: { pricing_unit: 'boarder', premium: true },
  },
  {
    code: 'boarding',
    name: 'Boarding Management',
    description: 'Boarding houses, meal analytics, dormitory oversight, and boarding student operations.',
    category: 'boarding',
    route_segment: 'boarding',
    permission_scopes: ['boarding:read', 'boarding:write'],
    billing_metadata: { pricing_unit: 'boarder', premium: true },
  },
  {
    code: 'cbt_exams',
    name: 'CBT Exams',
    description: 'Computer-based tests, online exam delivery, grading, and invigilation analytics.',
    category: 'academics',
    route_segment: 'cbt',
    permission_scopes: ['exams:read', 'exams:write', 'exams:approve'],
    billing_metadata: { pricing_unit: 'student', premium: true },
  },
  {
    code: 'lms',
    name: 'eLearning and LMS',
    description: 'Digital learning content, assignments, learner activity, and online class resources.',
    category: 'academics',
    route_segment: 'lms',
    permission_scopes: ['lms:read', 'lms:write'],
    billing_metadata: { pricing_unit: 'student', premium: true },
  },
  {
    code: 'ai_insights',
    name: 'AI Insights',
    description: 'Auditable smart alerts, forecasts, anomalies, and executive recommendations.',
    category: 'analytics',
    route_segment: 'ai-insights',
    permission_scopes: ['principal:read', 'reports:read'],
    billing_metadata: { pricing_unit: 'school', premium: true },
  },
  {
    code: 'visitor_management',
    name: 'Visitor Management',
    description: 'Gate visitors, appointments, check-ins, emergency logs, and school security reports.',
    category: 'operations',
    route_segment: 'visitors',
    permission_scopes: ['visitors:read', 'visitors:write'],
    billing_metadata: { pricing_unit: 'school' },
  },
  {
    code: 'asset_tracking',
    name: 'Asset Tracking',
    description: 'School assets, assignments, repairs, depreciation, and utilization reporting.',
    category: 'operations',
    route_segment: 'assets',
    permission_scopes: ['inventory:read', 'inventory:write'],
    billing_metadata: { pricing_unit: 'asset', premium: true },
  },
  {
    code: 'iot',
    name: 'IoT and Smart Campus',
    description: 'Device registry, telemetry ingestion, smart campus alerts, and command dispatch.',
    category: 'operations',
    route_segment: 'iot',
    permission_scopes: ['iot:read', 'iot:write'],
    billing_metadata: { pricing_unit: 'device', premium: true },
  },
] as const satisfies readonly ModuleRegistrySeedItem[];

export type ModuleCode = (typeof MODULE_REGISTRY_SEED)[number]['code'];

export const DEFAULT_ONBOARDING_MODULE_CODES: ModuleCode[] = [
  'students',
  'admissions',
  'academics',
  'finance',
  'exams',
  'discipline',
  'communication_sms',
  'reports',
  'staff',
  'timetable',
  'admin_command_centers',
  'principal_dashboard',
];
